Repository pingcap/docs-cn, pull requests merged in 2019-10, with the labels that each got.

#1912 *: fix spelling errors
  dev/key-features.md
  v1.0/overview.md
  v2.0/overview.md
  v2.1-legacy/features.md
  v2.1/key-features.md
  v3.0/key-features.md
Labels: align-N/A, contribution

#1908 reference: fix the default capacity of txn-local-latches
  dev/reference/configuration/tidb-server/configuration-file.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
Labels: pending-aligning

#1897 add script for running markdownlint locally
  .circleci/config.yml
  .gitignore
  CONTRIBUTING.md
  scripts/markdownlint
Labels: aligned-with-docs

#1889 reference/best-practices: add Haproxy Best Practice
  dev/TOC.md
  dev/reference/best-practices/haproxy.md
  media/haproxy.jpg
  v2.1/TOC.md
  v2.1/reference/best-practices/haproxy.md
  v3.0/TOC.md
  v3.0/reference/best-practices/haproxy.md
Labels: best-practices, pending-aligning

#1902 release, TOC: add release notes for 3.0.4
  dev/TOC.md
  dev/releases/3.0.4.md
  dev/releases/rn.md
  v3.0/TOC.md
  v3.0/releases/3.0.4.md
  v3.0/releases/rn.md
Labels: aligned-in-docs

#1906 dev, v3.0, v2.1: add more items in loader config template
  dev/reference/tools/loader.md
  v2.1/reference/tools/loader.md
  v3.0/reference/tools/loader.md
Labels: aligning, dev, v2.1, v3.0

#1920 reference/best-practices: update HAProxy doc
  dev/reference/best-practices/haproxy.md
  v2.1/reference/best-practices/haproxy.md
  v3.0/reference/best-practices/haproxy.md
Labels: pending-aligning

#1884 dev/reference/best-practices: add java best practice doc
  dev/TOC.md
  dev/reference/best-practices/using-tidb-in-java.md
  media/java-practice-1.png
  media/java-practice-2.png
  v2.1/TOC.md
  v2.1/reference/best-practices/using-tidb-in-java.md
  v3.0/TOC.md
  v3.0/reference/best-practices/using-tidb-in-java.md
Labels: best-practices, pending-aligning

#1851 Add description of GLOBAL level of tidb_txn_mode variable
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
Labels: aligned-in-docs, dev, v3.0

#1919 how-to/deploy: increase the usage precautions for labels
  v3.0/how-to/deploy/geographic-redundancy/location-awareness.md
  v3.0/how-to/deploy/orchestrated/ansible.md
Labels: pending-aligning

#1910 tidb-in-kubernetes: make deploy doc clearer on aliyun
  dev/tidb-in-kubernetes/deploy/alibaba-cloud.md
  v3.0/tidb-in-kubernetes/deploy/alibaba-cloud.md
Labels: aligning, dev, tidb-in-k8s, v3.0

#1909 config: add document for items which will be removed
  dev/reference/configuration/pd-server/configuration-file.md
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/reference/configuration/tikv-server/configuration-file.md
  v3.0/reference/configuration/pd-server/configuration-file.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
  v3.0/reference/configuration/tikv-server/configuration-file.md
Labels: aligned-in-docs

#1914 how-to/get-started: update Docker Compose command
  dev/how-to/get-started/deploy-tidb-from-docker-compose.md
  v3.0/how-to/get-started/deploy-tidb-from-docker-compose.md
Labels: align-N/A, contribution

#1932 releases: fix a typo
  dev/releases/3.0.4.md
  v3.0/releases/3.0.4.md
Labels: aligned-with-docs, dev, v3.0

#1930 tidb-in-kubernetes: fix internal link format
  dev/tidb-in-kubernetes/upgrade/tidb-cluster.md
  v3.0/tidb-in-kubernetes/upgrade/tidb-cluster.md
Labels: align-N/A, dev, tidb-in-k8s, v3.0

#1933 releases: update format
  dev/releases/3.0.4.md
  v3.0/releases/3.0.4.md
Labels: aligned-with-docs, dev, v3.0

#1841 toc, faq: add tidb-binlog FAQ
  dev/TOC.md
  dev/faq/tidb-binlog.md
  v2.1/TOC.md
  v2.1/faq/tidb-binlog.md
  v3.0/TOC.md
  v3.0/faq/tidb-binlog.md
Labels: LGT2, dev, pending-aligning, v2.1, v3.0

#1934 tidb-in-kubernetes/deploy: update the Note formats
  dev/tidb-in-kubernetes/deploy/aws-eks.md
  dev/tidb-in-kubernetes/deploy/gcp-gke.md
  v3.0/tidb-in-kubernetes/deploy/aws-eks.md
  v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
Labels: align-N/A, dev, v3.0

#1894 how-to/scale: update pd-ctl command
  dev/how-to/scale/horizontally.md
  v2.1/how-to/scale/horizontally.md
  v3.0/how-to/scale/horizontally.md
Labels: aligned-in-docs, v3.0

#1741 reference: update TiKV metrics docs
  dev/reference/key-monitoring-metrics/overview-dashboard.md
  v3.0/reference/key-monitoring-metrics/overview-dashboard.md
Labels: aligned-in-docs, dev, v3.0

#1861 v3.0, dev/tidb-in-kubernetes: notes about "cluster-id mismatch"
  dev/tidb-in-kubernetes/troubleshoot.md
  v3.0/tidb-in-kubernetes/troubleshoot.md
Labels: dev, pending-aligning, tidb-in-k8s, v3.0

#1823 reference: add tidb best practices under high concurrency
  dev/TOC.md
  dev/reference/best-practices/high-concurrency.md
  media/best-practices/QPS1.png
  media/best-practices/QPS2.png
  media/best-practices/QPS3.png
  media/best-practices/QPS4.png
  media/best-practices/QPS5.png
  media/best-practices/QPS6.png
  media/best-practices/QPS7.png
  media/best-practices/QPS8.png
  media/best-practices/table-Region-range.png
  media/best-practices/tidb-data-overview.png
  media/best-practices/tikv-Region-split.png
  v3.0/TOC.md
  v3.0/reference/best-practices/high-concurrency.md
Labels: best-practices, dev, pending-aligning, v3.0

#1856 dev: Add a description to the development deployment environment configuration
  dev/how-to/deploy/hardware-recommendations.md
  v2.1/how-to/deploy/hardware-recommendations.md
  v3.0/how-to/deploy/hardware-recommendations.md
Labels: aligned-in-docs, dev, v2.1, v3.0

#1935 tools: update config for reparo
  dev/reference/tools/tidb-binlog/reparo.md
  v2.1/reference/tools/tidb-binlog/reparo.md
  v3.0/reference/tools/tidb-binlog/reparo.md
Labels: dev, pending-aligning, v2.1, v3.0

#1931 *: add schema related errors FAQ and description of `tidb_max_delta_schema_count`
  dev/faq/tidb.md
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  v2.1/faq/tidb.md
  v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/faq/tidb.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
Labels: aligned-in-docs, aligning

#1937 *: fix typos
  dev/reference/sql/constraints.md
  dev/tidb-in-kubernetes/troubleshoot.md
  v2.1/reference/sql/constraints.md
  v3.0/reference/sql/constraints.md
  v3.0/tidb-in-kubernetes/troubleshoot.md
Labels: align-N/A, dev, v2.1, v3.0

#1924 references: update DM FAQ for 4GB binlog
  dev/faq/data-migration.md
  v2.1/faq/data-migration.md
  v3.0/faq/data-migration.md
Labels: pending-aligning

#1942 toc: refine the sequence of sql statements
  dev/TOC.md
  v2.1/TOC.md
  v3.0/TOC.md
Labels: aligned-with-docs

#1944 faq: refine the language of "Information schema is changed" section
  dev/faq/tidb.md
  v2.1/faq/tidb.md
  v3.0/faq/tidb.md
Labels: aligned-in-docs

#1939 reference: add documentation for statement summary
  dev/TOC.md
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  dev/reference/mysql-compatibility.md
  dev/reference/performance/statement-summary.md
  v3.0/TOC.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/reference/mysql-compatibility.md
  v3.0/reference/performance/statement-summary.md
Labels: LGT1, aligned-in-docs, dev, v3.0

#1925 reference, faq: update TiDB parameters, delete command option file
  dev/faq/tidb.md
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/reference/configuration/tidb-server/configuration.md
  dev/reference/configuration/tidb-server/server-command-option.md
  v2.1/faq/tidb.md
  v2.1/reference/configuration/tidb-server/configuration-file.md
  v2.1/reference/configuration/tidb-server/configuration.md
  v2.1/reference/configuration/tidb-server/server-command-option.md
  v3.0/faq/tidb.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
  v3.0/reference/configuration/tidb-server/configuration.md
  v3.0/reference/configuration/tidb-server/server-command-option.md
Labels: pending-aligning

#1855 tidb-in-kubernetes/get-started: Create deploy-tidb-from-kubernetes-kind.md
  dev/TOC.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
  v3.0/TOC.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
Labels: dev, pending-aligning, tidb-in-k8s, v3.0

#1885 reference/tools: refine the language of DM error system document
  dev/reference/tools/data-migration/error-system.md
  v3.0/reference/tools/data-migration/error-system.md
Labels: dev, pending-aligning, v3.0

#1938 reference: fix a typo
  dev/reference/tispark.md
  v3.0/reference/tispark.md
Labels: align-N/A

#1907 reference/mysql-compatibility: update MySQL compat
  dev/reference/mysql-compatibility.md
  v3.0/reference/mysql-compatibility.md
Labels: aligned-with-docs

#1850 reference/garbage-collection: Add a table to explain GC's configurations about mode and concurrency
  dev/reference/garbage-collection/configuration.md
  v3.0/reference/garbage-collection/configuration.md
Labels: aligned-in-docs, dev, v3.0

#1946 reference: concentrate binlog documents
  dev/TOC.md
  dev/how-to/deploy/orchestrated/ansible.md
  dev/how-to/get-started/tidb-binlog.md
  dev/how-to/maintain/backup-and-restore.md
  dev/how-to/upgrade/from-previous-version.md
  dev/how-to/upgrade/to-tidb-2.1.md
  dev/reference/tools/download.md
  dev/reference/tools/tidb-binlog/deploy.md
  dev/reference/tools/tidb-binlog/faq.md
  dev/reference/tools/tidb-binlog/maintain.md
  dev/reference/tools/tidb-binlog/monitor.md
  dev/reference/tools/tidb-binlog/overview.md
  dev/reference/tools/tidb-binlog/upgrade.md
  dev/tidb-in-kubernetes/maintain/backup-and-restore.md
  v2.1/TOC.md
  v2.1/how-to/deploy/orchestrated/ansible.md
  v2.1/how-to/get-started/tidb-binlog.md
  v2.1/how-to/maintain/backup-and-restore.md
  v2.1/how-to/upgrade/from-previous-version.md
  v2.1/how-to/upgrade/to-tidb-2.1.md
  v2.1/reference/tools/download.md
  v2.1/reference/tools/tidb-binlog/deploy.md
  v2.1/reference/tools/tidb-binlog/faq.md
  v2.1/reference/tools/tidb-binlog/maintain.md
  v2.1/reference/tools/tidb-binlog/monitor.md
  v2.1/reference/tools/tidb-binlog/overview.md
  v2.1/reference/tools/tidb-binlog/upgrade.md
  v3.0/TOC.md
  v3.0/how-to/deploy/orchestrated/ansible.md
  v3.0/how-to/get-started/tidb-binlog.md
  v3.0/how-to/maintain/backup-and-restore.md
  v3.0/how-to/upgrade/from-previous-version.md
  v3.0/how-to/upgrade/to-tidb-2.1.md
  v3.0/reference/tools/download.md
  v3.0/reference/tools/tidb-binlog/deploy.md
  v3.0/reference/tools/tidb-binlog/faq.md
  v3.0/reference/tools/tidb-binlog/maintain.md
  v3.0/reference/tools/tidb-binlog/monitor.md
  v3.0/reference/tools/tidb-binlog/overview.md
  v3.0/reference/tools/tidb-binlog/upgrade.md
  v3.0/tidb-in-kubernetes/maintain/backup-and-restore.md
Labels: LGT1, pending-aligning, refactor

#1952 *: add Grafana monitoring best practices
  dev/TOC.md
  dev/reference/best-practices/grafana-monitor.md
  media/best-practices/add-avg-function-check-trend.jpg
  media/best-practices/add-avg-function.jpeg
  media/best-practices/add-instance-dimension.jpeg
  media/best-practices/axes-scale-linear.jpg
  media/best-practices/default-axes-scale.jpg
  media/best-practices/default-y-min.jpeg
  media/best-practices/edit-expression-check-dimensions.jpg
  media/best-practices/graph-tooltip-shared-crosshair.jpeg
  media/best-practices/graph-tooltip-shared-tooltip.jpg
  media/best-practices/graph-tooltip.jpeg
  media/best-practices/manually-input-check-metric.jpeg
  media/best-practices/metric-board-edit-entry.png
  media/best-practices/metric-board-expression.jpeg
  media/best-practices/prometheus-api-interface.jpg
  media/best-practices/y-min-auto.jpg
  v2.1/TOC.md
  v2.1/reference/best-practices/grafana-monitor.md
  v3.0/TOC.md
  v3.0/reference/best-practices/grafana-monitor.md
Labels: best-practices, pending-aligning

#1953 reference/best-practices: refine Grafana wording
  dev/reference/best-practices/grafana-monitor.md
  v2.1/reference/best-practices/grafana-monitor.md
  v3.0/reference/best-practices/grafana-monitor.md
Labels: align-N/A

#1943 tidb-in-kubernetes: update default cluster requirements doc
  dev/tidb-in-kubernetes/deploy/general-kubernetes.md
  v3.0/tidb-in-kubernetes/deploy/general-kubernetes.md
Labels: aligned-with-docs

#1945 tidb-in-kubernetes: update tcp_syncookies's value
  dev/tidb-in-kubernetes/deploy/prerequisites.md
  v3.0/tidb-in-kubernetes/deploy/prerequisites.md
Labels: aligned-in-docs, dev, tidb-in-k8s, v3.0

#1949 how-to: refine language
  dev/how-to/deploy/data-migration-with-binary.md
  dev/how-to/get-started/data-migration.md
  dev/reference/tools/tidb-binlog/maintain.md
  v2.1/how-to/deploy/data-migration-with-binary.md
  v2.1/how-to/get-started/data-migration.md
  v2.1/reference/tools/tidb-binlog/maintain.md
  v3.0/how-to/deploy/data-migration-with-binary.md
  v3.0/how-to/get-started/data-migration.md
  v3.0/reference/tools/tidb-binlog/maintain.md
Labels: aligned-in-docs

#1956 tidb-in-kubernetes/get-started: fix a grep error on macOS
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
Labels: aligned-with-docs, dev, v3.0

#1941 reference/transactions: update pessimistic doc to v3.0
  dev/reference/transactions/transaction-pessimistic.md
  v3.0/reference/transactions/transaction-pessimistic.md
Labels: aligned-in-docs

#1951 *: reorganize docs to keep 2.1 and 3.0 consistent
  _index.md
  v2.1/_index.md
  v2.1/how-to/deploy/hardware-recommendations.md
  v2.1/how-to/deploy/orchestrated/ansible.md
  v2.1/how-to/get-started/deploy-tidb-from-docker-compose.md
  v2.1/overview.md
Labels: aligned-with-docs, refactor

#1960 how-to/maintain: fix code block format
  v3.0/how-to/maintain/backup-and-restore.md
Labels: align-N/A

#1959 *: add maintaining tidb binlog in k8s docs
  dev/TOC.md
  dev/tidb-in-kubernetes/maintain/backup-and-restore.md
  dev/tidb-in-kubernetes/maintain/tidb-binlog.md
  dev/tidb-in-kubernetes/reference/configuration/tidb-drainer.md
  v3.0/TOC.md
  v3.0/tidb-in-kubernetes/maintain/backup-and-restore.md
  v3.0/tidb-in-kubernetes/maintain/tidb-binlog.md
  v3.0/tidb-in-kubernetes/reference/configuration/tidb-drainer.md
Labels: aligned-with-docs, dev, tidb-in-k8s, v3.0

#1890 tidb-in-kubernetes: add one faq item
  dev/tidb-in-kubernetes/faq.md
  dev/tidb-in-kubernetes/tidb-operator-overview.md
  v3.0/tidb-in-kubernetes/faq.md
  v3.0/tidb-in-kubernetes/tidb-operator-overview.md
Labels: dev, pending-aligning, tidb-in-k8s, v3.0

#1969 reference/security: fix format in user account management doc
  dev/reference/security/user-account-management.md
  v2.1/reference/security/user-account-management.md
  v3.0/reference/security/user-account-management.md
Labels: align-N/A

#1965 how-to/monitor: update manual deploy monitor
  dev/how-to/monitor/monitor-a-cluster.md
  v3.0/how-to/monitor/monitor-a-cluster.md
Labels: master, pending-aligning, v3.0

#1970 tidb-in-kubernets: refine kubernetes and tidb deployment docs
  dev/tidb-in-kubernetes/deploy/general-kubernetes.md
  dev/tidb-in-kubernetes/tidb-operator-overview.md
  v3.0/tidb-in-kubernetes/deploy/general-kubernetes.md
  v3.0/tidb-in-kubernetes/tidb-operator-overview.md
Labels: pending-aligning, tidb-in-k8s

#1882 reference: update pd-ctl flags
  dev/reference/tools/pd-control.md
  v2.1/reference/tools/pd-control.md
  v3.0/reference/tools/pd-control.md
Labels: dev, pending-aligning, v2.1, v3.0

#1968 reference/tools: update binlogctl doc to add "-show-offline-nodes"
  dev/reference/tools/tidb-binlog/maintain.md
  v2.1/reference/tools/tidb-binlog/maintain.md
  v3.0/reference/tools/tidb-binlog/maintain.md
Labels: pending-aligning

#1958 how-to/scale: add a note in with-ansible document
  dev/how-to/scale/with-ansible.md
  v2.1/how-to/scale/with-ansible.md
  v3.0/how-to/scale/with-ansible.md
Labels: pending-aligning

#1982 releases: add TiDB 3.0.5 Release Notes
  dev/releases/3.0.5.md
  dev/releases/rn.md
  v3.0/releases/3.0.5.md
  v3.0/releases/rn.md
Labels: aligned-in-docs

#1983 toc: add 3.0.5 Release Notes
  dev/TOC.md
  v3.0/TOC.md
Labels: aligned-with-docs

#1971 tidb-in-kubernetes: update key and namespace name and improve tidb-operator customization
  dev/tidb-in-kubernetes/deploy/aws-eks.md
  v3.0/tidb-in-kubernetes/deploy/aws-eks.md
Labels: dev, pending-aligning, tidb-in-k8s, v3.0

#1986 tools: add one syncer check description
  dev/reference/tools/syncer.md
  v2.1/reference/tools/syncer.md
  v3.0/reference/tools/syncer.md
Labels: LGT1, pending-aligning

#1777 tidb-in-kubernetes: add permitHost document
  dev/tidb-in-kubernetes/initialize-cluster.md
  v3.0/tidb-in-kubernetes/initialize-cluster.md
Labels: contribution, pending-aligning, tidb-in-k8s

#1988 Update disk formatting document
  dev/how-to/deploy/orchestrated/ansible.md
  v2.1/how-to/deploy/orchestrated/ansible.md
  v3.0/how-to/deploy/orchestrated/ansible.md
Labels: dev, pending-aligning, v2.1, v3.0

#1973 tidb-in-kubernetes: update for the case where pod pending due to ha policy
  dev/tidb-in-kubernetes/troubleshoot.md
  v3.0/tidb-in-kubernetes/troubleshoot.md
Labels: dev, pending-aligning, tidb-in-k8s, v3.0

#1989 best-practices: add rewriting suggestion for insert on duplicate key update
  dev/reference/best-practices/java-app.md
  v2.1/reference/best-practices/java-app.md
  v3.0/reference/best-practices/java-app.md
Labels: best-practices, pending-aligning

#1940 tidb-in-kubernetes: update offline pump doc
  dev/tidb-in-kubernetes/maintain/backup-and-restore.md
  v3.0/tidb-in-kubernetes/maintain/backup-and-restore.md
Labels: aligned-in-docs, tidb-in-k8s

#1828 dev: remove transaction kv count limit
  dev/faq/tidb.md
  dev/reference/transactions/transaction-model.md
  dev/tidb-in-kubernetes/reference/configuration/tidb-cluster.md
  v3.0/tidb-in-kubernetes/reference/configuration/tidb-cluster.md
Labels: pending-aligning

#1961 tools: refine config file for DM
  dev/TOC.md
  dev/how-to/deploy/data-migration-with-ansible.md
  dev/how-to/deploy/data-migration-with-binary.md
  dev/reference/tools/data-migration/configure/dm-master-configuration-file.md
  dev/reference/tools/data-migration/configure/dm-worker-configuration-file-full.md
  dev/reference/tools/data-migration/configure/dm-worker-configuration-file.md
  dev/reference/tools/data-migration/configure/overview.md
  dev/reference/tools/data-migration/configure/task-configuration-file-full.md
  dev/reference/tools/data-migration/configure/task-configuration-file.md
  dev/reference/tools/data-migration/relay-log.md
  v2.1/TOC.md
  v2.1/how-to/deploy/data-migration-with-ansible.md
  v2.1/how-to/deploy/data-migration-with-binary.md
  v2.1/reference/tools/data-migration/configure/dm-master-configuration-file.md
  v2.1/reference/tools/data-migration/configure/dm-worker-configuration-file-full.md
  v2.1/reference/tools/data-migration/configure/dm-worker-configuration-file.md
  v2.1/reference/tools/data-migration/configure/overview.md
  v2.1/reference/tools/data-migration/configure/task-configuration-file-full.md
  v2.1/reference/tools/data-migration/configure/task-configuration-file.md
  v2.1/reference/tools/data-migration/relay-log.md
  v3.0/TOC.md
  v3.0/how-to/deploy/data-migration-with-ansible.md
  v3.0/how-to/deploy/data-migration-with-binary.md
  v3.0/reference/tools/data-migration/configure/dm-master-configuration-file.md
  v3.0/reference/tools/data-migration/configure/dm-worker-configuration-file-full.md
  v3.0/reference/tools/data-migration/configure/dm-worker-configuration-file.md
  v3.0/reference/tools/data-migration/configure/overview.md
  v3.0/reference/tools/data-migration/configure/task-configuration-file-full.md
  v3.0/reference/tools/data-migration/configure/task-configuration-file.md
  v3.0/reference/tools/data-migration/relay-log.md
Labels: pending-aligning

#1995 references: add DM v1.0.2 release notes
  dev/TOC.md
  dev/reference/tools/data-migration/releases/1.0.2.md
  v2.1/TOC.md
  v2.1/reference/tools/data-migration/releases/1.0.2.md
  v3.0/TOC.md
  v3.0/reference/tools/data-migration/releases/1.0.2.md
Labels: aligning, dev, v2.1, v3.0

#1978 reference: add max open files explanation on lightning
  dev/reference/tools/tidb-lightning/deployment.md
  v2.1/reference/tools/tidb-lightning/deployment.md
  v3.0/reference/tools/tidb-lightning/deployment.md
Labels: pending-aligning

#1975 reference: refine DM TOC
  dev/TOC.md
  v2.1/TOC.md
  v3.0/TOC.md
Labels: pending-aligning

#1974 reference: fix skip-grant-table mistake in user-account-management
  dev/reference/security/user-account-management.md
  v2.1/reference/security/user-account-management.md
  v3.0/reference/security/user-account-management.md
Labels: LGT1, LGT2, pending-aligning

#1996 media: update tidb-operator-overview image
  dev/tidb-in-kubernetes/tidb-operator-overview.md
  media/tidb-operator-overview.png
  v3.0/tidb-in-kubernetes/tidb-operator-overview.md
Labels: aligned-in-docs

#1999 deploy: update an ansible command
  dev/how-to/deploy/orchestrated/ansible.md
  v2.1/how-to/deploy/orchestrated/ansible.md
  v3.0/how-to/deploy/orchestrated/ansible.md
Labels: pending-aligning

#1992 *: optimize anchor text of 68 links for SEO
  dev/benchmark/how-to-run-sysbench.md
  dev/faq/tidb.md
  dev/how-to/get-started/tispark.md
  dev/how-to/maintain/backup-and-restore.md
  dev/how-to/migrate/from-mysql.md
  dev/reference/configuration/pd-server/configuration-file.md
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  dev/reference/configuration/tikv-server/configuration-file.md
  dev/reference/sql/language-structure/comment-syntax.md
  dev/reference/tispark.md
  dev/tidb-in-kubernetes/deploy/prerequisites.md
  dev/tidb-in-kubernetes/deploy/tidb-operator.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-gke.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
  dev/tidb-in-kubernetes/reference/configuration/tidb-cluster.md
  v2.1/benchmark/how-to-run-sysbench.md
  v2.1/faq/tidb.md
  v2.1/how-to/maintain/backup-and-restore.md
  v2.1/how-to/migrate/from-mysql.md
  v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v2.1/reference/sql/functions-and-operators/operators.md
  v2.1/reference/sql/language-structure/comment-syntax.md
  v2.1/reference/tispark.md
  v2.1/tispark/tispark-user-guide_v1.x.md
  v3.0/benchmark/how-to-run-sysbench.md
  v3.0/faq/tidb.md
  v3.0/how-to/get-started/tispark.md
  v3.0/how-to/maintain/backup-and-restore.md
  v3.0/how-to/migrate/from-mysql.md
  v3.0/reference/configuration/pd-server/configuration-file.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/reference/configuration/tikv-server/configuration-file.md
  v3.0/reference/sql/language-structure/comment-syntax.md
  v3.0/reference/tispark.md
  v3.0/tidb-in-kubernetes/deploy/prerequisites.md
  v3.0/tidb-in-kubernetes/deploy/tidb-operator.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-gke.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
  v3.0/tidb-in-kubernetes/reference/configuration/tidb-cluster.md
Labels: align-N/A, dev, v2.1, v3.0

#1966 statistics: add more description for `update_time`
  dev/reference/performance/statistics.md
  v2.1/reference/performance/statistics.md
  v3.0/reference/performance/statistics.md
Labels: LGT1, dev, pending-aligning, v2.1, v3.0

#1994 tools: update descriptions for query-status of DM
  dev/how-to/get-started/data-migration.md
  dev/how-to/migrate/from-aurora.md
  dev/reference/tools/data-migration/deploy.md
  dev/reference/tools/data-migration/from-aurora.md
  dev/reference/tools/data-migration/query-status.md
  v2.1/how-to/get-started/data-migration.md
  v2.1/how-to/migrate/from-aurora.md
  v2.1/reference/tools/data-migration/deploy.md
  v2.1/reference/tools/data-migration/from-aurora.md
  v2.1/reference/tools/data-migration/query-status.md
  v3.0/how-to/get-started/data-migration.md
  v3.0/how-to/migrate/from-aurora.md
  v3.0/reference/tools/data-migration/deploy.md
  v3.0/reference/tools/data-migration/from-aurora.md
  v3.0/reference/tools/data-migration/query-status.md
Labels: pending-aligning
