Repository pingcap/docs-cn, pull requests merged in 2019-04, with the labels that each got.

#1197 tools: add doc for tidb-ctl base64decode
  tools/tidb-controller.md
Labels: LGT2

#1225 sql: update set variables
  sql/tidb-specific.md
  sql/variable.md
Labels: LGT1

#1227 sql: update EXPLAIN related document
  sql/mysql-compatibility.md
  sql/understanding-the-query-execution-plan.md
Labels: LGT1

#1240 toc, sql: move optimizer hints to separate file
  TOC.md
  sql/optimizer-hints.md
  sql/tidb-specific.md
Labels: DITA Refactoring

#1244 toc, op-guide: spit configuration by component
  op-guide/configuration.md
  op-guide/pd-configuration.md
  op-guide/tikv-configuration.md
Labels: DITA Refactoring

#1241 sql, TOC: split information schema from system database and improve
  TOC.md
  sql/information-schema.md
  sql/system-database.md
Labels: DITA Refactoring

#1248 op-guide: reorganize and update migration overview
  op-guide/migration-overview.md
Labels: DITA Refactoring

#1253 *: move overview and features
  QUICKSTART.md
  key-features.md
  overview.md
Labels: DITA Refactoring

#1242 TOC: covert docs-cn to DITA TOC
  TOC.md
Labels: DITA Refactoring

#1262 sql, TOC: update doc title
  TOC.md
  sql/system-database.md
Labels: LGT1

#1281 *: rename how-to get started
  TOC.md
  dev/how-to/get-started/explore-sql.md
  dev/how-to/get-started/local-cluster/install-from-docker-compose.md
  dev/how-to/get-started/read-historical-data.md
Labels: Refactor

#1259 sql: update content structure and wording
  sql/privilege.md
  sql/user-account-management.md
Labels: LGT2

#1264 tools, toc: reorganize TiDB Binlog documents
  TOC.md
  tools/binlog/binlog-slave-client.md
  tools/binlog/deploy.md
  tools/binlog/monitor.md
  tools/binlog/operation.md
  tools/binlog/overview.md
  tools/binlog/reparo.md
  tools/binlog/tidb-binlog-kafka.md
  tools/binlog/tidb-binlog-local.md
  tools/binlog/upgrade.md
Labels: Refactor
