Repository pingcap/docs-cn, pull requests merged in 2019-11, with the labels that each got.

#1990 reference: add PD scheduling best practice
  dev/TOC.md
  dev/glossary.md
  dev/reference/best-practices/pd-scheduling.md
  v2.1/TOC.md
  v2.1/glossary.md
  v2.1/reference/best-practices/pd-scheduling.md
  v3.0/TOC.md
  v3.0/glossary.md
  v3.0/reference/best-practices/pd-scheduling.md
Labels: best-practices

#1950 tools: refactor faq and troubleshooting for DM
  dev/TOC.md
  dev/faq/data-migration.md
  dev/how-to/troubleshoot/data-migration.md
  dev/reference/tools/data-migration/faq.md
  dev/reference/tools/data-migration/troubleshoot/dm.md
  dev/reference/tools/data-migration/troubleshoot/error-handling.md
  dev/reference/tools/data-migration/troubleshoot/error-system.md
  v2.1/TOC.md
  v2.1/faq/data-migration.md
  v2.1/how-to/troubleshoot/data-migration.md
  v2.1/reference/tools/data-migration/faq.md
  v2.1/reference/tools/data-migration/troubleshoot/dm.md
  v2.1/reference/tools/data-migration/troubleshoot/error-handling.md
  v2.1/reference/tools/data-migration/troubleshoot/error-system.md
  v3.0/TOC.md
  v3.0/faq/data-migration.md
  v3.0/how-to/troubleshoot/data-migration.md
  v3.0/reference/tools/data-migration/faq.md
  v3.0/reference/tools/data-migration/troubleshoot/dm.md
  v3.0/reference/tools/data-migration/troubleshoot/error-handling.md
  v3.0/reference/tools/data-migration/troubleshoot/error-system.md
Labels: pending-aligning, refactor

#1979 reference/performance: update optimizer hints for master
  dev/reference/performance/optimizer-hints.md
Labels: LGT2, aligning, markdownlint checked, master, v4.0

#2004 *: fix 20 broken links
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/reference/supported-clients.md
  dev/reference/tools/data-migration/configure/task-configuration-file.md
  dev/releases/21rc5.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
  v2.1/reference/configuration/tidb-server/configuration-file.md
  v2.1/reference/supported-clients.md
  v2.1/reference/tools/data-migration/configure/task-configuration-file.md
  v2.1/releases/21rc5.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
  v3.0/reference/supported-clients.md
  v3.0/reference/tools/data-migration/configure/task-configuration-file.md
  v3.0/releases/21rc5.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
Labels: aligned-in-docs, dev, seo, v2.1, v3.0

#2005 reference/best-practices: update PD term references
  dev/reference/best-practices/pd-scheduling.md
  v2.1/reference/best-practices/pd-scheduling.md
  v3.0/reference/best-practices/pd-scheduling.md
Labels: best-practices

#1948 tools: add quick started for lightning
  dev/TOC.md
  dev/how-to/get-started/tidb-lightning.md
  v2.1/TOC.md
  v2.1/how-to/get-started/tidb-lightning.md
  v3.0/TOC.md
  v3.0/how-to/get-started/tidb-lightning.md
Labels: pending-aligning, queeny-test-suggested

#1998 reference: update DM upgrade doc, add v1.0.2 / v1.0.1
  dev/TOC.md
  dev/reference/tools/data-migration/dm-upgrade.md
  v2.1/TOC.md
  v2.1/reference/tools/data-migration/dm-upgrade.md
  v3.0/TOC.md
  v3.0/reference/tools/data-migration/dm-upgrade.md
Labels: pending-aligning

#1997 tidb-in-kubernetes: add irq balance description in deployment prerequisites doc
  dev/tidb-in-kubernetes/deploy/prerequisites.md
  v3.0/tidb-in-kubernetes/deploy/prerequisites.md
Labels: tidb-in-k8s

#2007 reference/configuration: fix-feature-introduce-version
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
Labels: pending-aligning

#2013 releases: add 2.1.18 release notes
  dev/TOC.md
  dev/releases/2.1.18.md
  dev/releases/rn.md
  v2.1/TOC.md
  v2.1/releases/2.1.18.md
  v2.1/releases/rn.md
  v3.0/TOC.md
  v3.0/releases/2.1.18.md
  v3.0/releases/rn.md
Labels: aligned-in-docs

#2014 how-to, tidb-in-kubernetes: clarify language and fix a typo
  dev/how-to/deploy/orchestrated/ansible.md
  dev/tidb-in-kubernetes/troubleshoot.md
  v3.0/tidb-in-kubernetes/troubleshoot.md
Labels: aligned-in-docs

#1915 how-to/deploy: update a file name for TiDB Binlog
  dev/reference/tools/tidb-binlog/deploy.md
  v3.0/reference/tools/tidb-binlog/deploy.md
Labels: aligned-in-docs, dev, v3.0

#2002 reference/tools: add solution for argument-list too long error for DM 1.0.2
  dev/reference/tools/data-migration/troubleshoot/error-handling.md
  v2.1/reference/tools/data-migration/troubleshoot/error-handling.md
  v3.0/reference/tools/data-migration/troubleshoot/error-handling.md
Labels: pending-aligning

#1967 data-migration: refine language for dm-worker connection switch doc
  dev/reference/tools/data-migration/overview.md
  dev/reference/tools/data-migration/usage-scenarios/master-slave-switch.md
  v2.1/reference/tools/data-migration/overview.md
  v2.1/reference/tools/data-migration/usage-scenarios/master-slave-switch.md
  v3.0/reference/tools/data-migration/overview.md
  v3.0/reference/tools/data-migration/usage-scenarios/master-slave-switch.md
Labels: aligned-in-docs, dev, v2.1, v3.0

#1955 benchmark: update add-index-with-load doc
  dev/TOC.md
  dev/benchmark/add-index-with-load.md
  v3.0/TOC.md
  v3.0/benchmark/add-index-with-load.md
Labels: aligned-in-docs

#2022 tools: fix link for dm's config
  dev/reference/tools/data-migration/configure/task-configuration-file.md
  v2.1/reference/tools/data-migration/configure/task-configuration-file.md
  v3.0/reference/tools/data-migration/configure/task-configuration-file.md
Labels: pending-aligning

#2021 resources: update pingcap documentation style guide to v1.1
  resources/pingcap-style-guide-zh-v1.0.pdf
  resources/pingcap-style-guide-zh-v1.1.pdf
Labels: align-N/A

#2026 *: fix 11 broken links
  dev/releases/2.1.18.md
  dev/tidb-in-kubernetes/deploy/alibaba-cloud.md
  dev/tidb-in-kubernetes/deploy/aws-eks.md
  dev/tidb-in-kubernetes/deploy/gcp-gke.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
  v2.1/releases/2.1.18.md
  v3.0/releases/2.1.18.md
  v3.0/tidb-in-kubernetes/deploy/alibaba-cloud.md
  v3.0/tidb-in-kubernetes/deploy/aws-eks.md
  v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
Labels: aligned-with-docs, dev, seo, v2.1, v3.0

#2024 faq: update one faq item about ddl
  dev/faq/tidb.md
  v2.1/faq/tidb.md
  v3.0/faq/tidb.md
Labels: align-N/A, dev, v2.1, v3.0

#1549 dev, v2.1, v3.0: update sysbench config
  dev/benchmark/how-to-run-sysbench.md
  dev/benchmark/sysbench-v4.md
  v2.1/benchmark/how-to-run-sysbench.md
  v3.0/benchmark/how-to-run-sysbench.md
  v3.0/benchmark/sysbench-v4.md
  v3.1/benchmark/how-to-run-sysbench.md
  v3.1/benchmark/sysbench-v4.md
Labels: contribution, pending-aligning

#2028 generate v3.1 PDF
  scripts/generate_pdf.sh
  scripts/merge_by_toc.py
Labels: aligned-with-docs, website

#2025 best-practices: fix mistake in java best practices
  dev/reference/best-practices/java-app.md
  v2.1/reference/best-practices/java-app.md
  v3.0/reference/best-practices/java-app.md
  v3.1/reference/best-practices/java-app.md
Labels: pending-aligning

#2030 .github: update version description in PR template
  .github/pull_request_template.md
Labels: aligned-in-docs

#2031 v3.1/reference: update optimizer hints
  v3.1/reference/performance/optimizer-hints.md
Labels: pending-aligning

#2000 toc, reference: delete `show create user` usage from v2.1
  v2.1/TOC.md
  v2.1/reference/sql/statements/alter-user.md
  v2.1/reference/sql/statements/create-user.md
  v2.1/reference/sql/statements/drop-user.md
  v2.1/reference/sql/statements/set-password.md
  v2.1/reference/sql/statements/show-create-user.md
  v2.1/reference/sql/statements/show-grants.md
Labels: pending-aligning, v2.1

#1972 reference: remove duplicate tidb binlog alerting rules content
  dev/reference/alert-rules.md
  dev/reference/tidb-binlog/monitor.md
  v2.1/reference/alert-rules.md
  v2.1/reference/tidb-binlog/monitor.md
  v3.0/reference/alert-rules.md
  v3.0/reference/tidb-binlog/monitor.md
  v3.1/reference/alert-rules.md
  v3.1/reference/tidb-binlog/monitor.md
Labels: pending-aligning

#1991 reference: update docs to reflect changes in `tidb/config/config.go`
  dev/reference/configuration/tidb-server/configuration-file.md
Labels: dev, master, pending-aligning

#2038 *: update offline deployment
  dev/how-to/deploy/orchestrated/offline-ansible.md
  v2.1/how-to/deploy/orchestrated/offline-ansible.md
  v3.0/how-to/deploy/orchestrated/offline-ansible.md
  v3.1/how-to/deploy/orchestrated/offline-ansible.md
Labels: master, pending-aligning, v2.1, v3.0

#2036 tools: add sql-mode config for sync-diff-inspector
  dev/reference/tools/sync-diff-inspector/overview.md
  v2.1/reference/tools/sync-diff-inspector/overview.md
  v3.0/reference/tools/sync-diff-inspector/overview.md
  v3.1/reference/tools/sync-diff-inspector/overview.md
Labels: pending-aligning

#2035 tidb-in-kubernetes: make local pv provisioning procedure clearer
  dev/tidb-in-kubernetes/reference/configuration/storage-class.md
  v3.0/tidb-in-kubernetes/reference/configuration/storage-class.md
  v3.1/tidb-in-kubernetes/reference/configuration/storage-class.md
Labels: dev, pending-aligning, tidb-in-k8s, v3.0, v3.1

#1984 tidb-in-kubernetes: update helm content in aws deployment doc
  dev/tidb-in-kubernetes/deploy/aws-eks.md
  v3.0/tidb-in-kubernetes/deploy/aws-eks.md
  v3.1/tidb-in-kubernetes/deploy/aws-eks.md
Labels: pending-aligning, tidb-in-k8s

#2040 tidb-in-kubernetes: add customizing logging and update organization
  dev/tidb-in-kubernetes/deploy/gcp-gke.md
  v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
  v3.1/tidb-in-kubernetes/deploy/gcp-gke.md
Labels: aligned-with-docs, tidb-in-k8s

#2042 tidb-in-kubernetes: delete all content about DinD
  dev/TOC.md
  dev/overview.md
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/tidb-in-kubernetes/deploy/tidb-operator.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
  dev/tidb-in-kubernetes/tidb-operator-overview.md
  v2.1/reference/configuration/tidb-server/configuration-file.md
  v3.0/TOC.md
  v3.0/overview.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
  v3.0/tidb-in-kubernetes/deploy/tidb-operator.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
  v3.0/tidb-in-kubernetes/tidb-operator-overview.md
  v3.1/TOC.md
  v3.1/overview.md
  v3.1/reference/configuration/tidb-server/configuration-file.md
  v3.1/tidb-in-kubernetes/deploy/tidb-operator.md
  v3.1/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
  v3.1/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
  v3.1/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
  v3.1/tidb-in-kubernetes/tidb-operator-overview.md
Labels: aligned-in-docs, tidb-in-k8s

#2041 tidb-in-kubernetes: improve gke deploy doc for multiple k8s clusters management
  dev/tidb-in-kubernetes/deploy/gcp-gke.md
  v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
  v3.1/tidb-in-kubernetes/deploy/gcp-gke.md
Labels: dev, pending-aligning, tidb-in-k8s, v3.0, v3.1

#2044 data-migration: add reference in dm overview
  dev/reference/tools/data-migration/overview.md
  v2.1/reference/tools/data-migration/overview.md
  v3.0/reference/tools/data-migration/overview.md
  v3.1/reference/tools/data-migration/overview.md
Labels: align-N/A

#2037 tools: add trouble shooting for binlog
  dev/TOC.md
  dev/reference/tidb-binlog/troubleshoot/binlog.md
  dev/reference/tidb-binlog/troubleshoot/error-handling.md
  v2.1/TOC.md
  v2.1/reference/tidb-binlog/troubleshoot/binlog.md
  v2.1/reference/tidb-binlog/troubleshoot/error-handling.md
  v3.0/TOC.md
  v3.0/reference/tidb-binlog/troubleshoot/binlog.md
  v3.0/reference/tidb-binlog/troubleshoot/error-handling.md
  v3.1/TOC.md
  v3.1/reference/tidb-binlog/troubleshoot/binlog.md
  v3.1/reference/tidb-binlog/troubleshoot/error-handling.md
Labels: pending-aligning

#2006 tools/tidb-binlog: update faq
  dev/reference/tidb-binlog/deploy.md
  dev/reference/tidb-binlog/faq.md
  dev/reference/tidb-binlog/maintain.md
  v2.1/reference/tidb-binlog/deploy.md
  v2.1/reference/tidb-binlog/faq.md
  v2.1/reference/tidb-binlog/maintain.md
  v3.0/reference/tidb-binlog/deploy.md
  v3.0/reference/tidb-binlog/faq.md
  v3.0/reference/tidb-binlog/maintain.md
  v3.1/reference/tidb-binlog/deploy.md
  v3.1/reference/tidb-binlog/faq.md
  v3.1/reference/tidb-binlog/maintain.md
Labels: align-N/A, dev, v2.1, v3.0, v3.1

#2051 reference/sql: refine doc of expressions for pushdown
  dev/reference/sql/functions-and-operators/expressions-pushed-down.md
  v3.0/reference/sql/functions-and-operators/expressions-pushed-down.md
  v3.1/reference/sql/functions-and-operators/expressions-pushed-down.md
Labels: DNM, align-N/A, dev

#2052 reference: add version info for the MEM column
  v3.0/reference/system-databases/information-schema.md
Labels: pending-aligning, v3.0

#2043 best-practices: fix typos
  dev/reference/best-practices/high-concurrency.md
  v3.0/reference/best-practices/high-concurrency.md
  v3.1/reference/best-practices/high-concurrency.md
Labels: aligned-in-docs

#2029 circleci: upload v3.1 PDF
  .circleci/config.yml
Labels: aligned-in-docs, website

#2050 tools: update download url
  dev/reference/tools/download.md
Labels: LGT1, pending-aligning

#2019 reference/performance: add follower-read doc
  dev/TOC.md
  dev/reference/performance/follower-read.md
  v3.1/TOC.md
  v3.1/reference/performance/follower-read.md
Labels: contribution, pending-aligning, v3.1

#2056 tools: update download urls
  v2.1/reference/tools/download.md
  v3.0/reference/tools/download.md
  v3.1/reference/tools/download.md
Labels: pending-aligning

#2064 *: update column_name description
  dev/reference/performance/statistics.md
  v2.1/reference/performance/statistics.md
  v3.0/reference/performance/statistics.md
  v3.1/reference/performance/statistics.md
Labels: pending-aligning

#2039 best-practices: add massive region performance improvement doc
  dev/TOC.md
  dev/reference/best-practices/massive-regions.md
  media/best-practices/pd-worker-metrics.png
  media/best-practices/propose-wait-duration.png
  media/best-practices/raft-process.png
  media/best-practices/raft-store-cpu.png
  v2.1/TOC.md
  v2.1/reference/best-practices/massive-regions.md
  v3.0/TOC.md
  v3.0/reference/best-practices/massive-regions.md
  v3.1/TOC.md
  v3.1/reference/best-practices/massive-regions.md
Labels: best-practices, dev, pending-aligning, v2.1, v3.0, v3.1

#2068 best-practices: fix typos in massive region best practices
  dev/reference/best-practices/massive-regions.md
  v2.1/reference/best-practices/massive-regions.md
  v3.0/reference/best-practices/massive-regions.md
  v3.1/reference/best-practices/massive-regions.md
Labels: pending-aligning

#2015 dev, 3.0, 3.1: add GC io limit
  dev/reference/garbage-collection/configuration.md
  v3.0/reference/garbage-collection/configuration.md
  v3.1/reference/garbage-collection/configuration.md
Labels: dev, v3.0, v3.1

#2072 media: update the HAProxy image
  media/haproxy.jpg
Labels: align-N/A, best-practices

#2020 reference/tools: add a BR tool doc
  dev/TOC.md
  dev/how-to/maintain/backup-and-restore/br.md
  dev/how-to/maintain/backup-and-restore/mydumper-loader.md
  media/br-arch.png
  v3.1/TOC.md
  v3.1/how-to/maintain/backup-and-restore/br.md
  v3.1/how-to/maintain/backup-and-restore/mydumper-loader.md
Labels: dev, pending-aligning, v3.1

#2048 how-to/upgrade: update supported versions of TiDB 2.1 and remove inapplicable info
  dev/how-to/upgrade/from-previous-version.md
  dev/how-to/upgrade/rolling-updates-with-ansible.md
  dev/how-to/upgrade/to-tidb-2.1.md
  v2.1/TOC.md
  v2.1/how-to/upgrade/from-previous-version.md
  v2.1/how-to/upgrade/rolling-updates-with-ansible.md
  v2.1/how-to/upgrade/to-tidb-2.1.md
  v3.0/how-to/upgrade/from-previous-version.md
  v3.0/how-to/upgrade/rolling-updates-with-ansible.md
  v3.0/how-to/upgrade/to-tidb-2.1.md
  v3.1/how-to/upgrade/from-previous-version.md
  v3.1/how-to/upgrade/rolling-updates-with-ansible.md
  v3.1/how-to/upgrade/to-tidb-2.1.md
Labels: LGT1, aligned-in-docs

#2069 tools: update dm-ansible's download description
  dev/how-to/deploy/data-migration-with-ansible.md
  v2.1/how-to/deploy/data-migration-with-ansible.md
  v3.0/how-to/deploy/data-migration-with-ansible.md
  v3.1/how-to/deploy/data-migration-with-ansible.md
Labels: pending-aligning

#2060 tools: fix mistake in tikv-ctl usage
  dev/reference/tools/tikv-control.md
  v2.1/reference/tools/tikv-control.md
  v3.0/reference/tools/tikv-control.md
  v3.1/reference/tools/tikv-control.md
Labels: pending-aligning, small

#2062 tools: fix tidb-enterprise-tools description
  dev/reference/tools/download.md
  v2.1/reference/tools/download.md
  v3.0/reference/tools/download.md
  v3.1/reference/tools/download.md
Labels: pending-aligning, small

#2059 reference: delete execution-plan-bind for v2.1
  v2.1/TOC.md
  v2.1/reference/performance/execution-plan-bind.md
Labels: pending-aligning, small

#2054 reference: update pessimistic transaction doc
  dev/reference/transactions/transaction-pessimistic.md
  v3.0/reference/transactions/transaction-pessimistic.md
  v3.1/reference/transactions/transaction-pessimistic.md
Labels: pending-aligning

#2055 tidb-kubernetes: add backup and restore usage docs
  dev/tidb-in-kubernetes/maintain/backup-and-restore/backup-gcs.md
  dev/tidb-in-kubernetes/maintain/backup-and-restore/backup-s3.md
  dev/tidb-in-kubernetes/maintain/backup-and-restore/restore.md
Labels: large, pending-aligning, tidb-in-k8s

#2078 how-to/get-started: add DM encrypt password and update download url
  dev/how-to/get-started/data-migration.md
  v2.1/how-to/get-started/data-migration.md
  v3.0/how-to/get-started/data-migration.md
  v3.1/how-to/get-started/data-migration.md
Labels: pending-aligning, small

#2075 reference/configuration: add a warning sentence
  dev/reference/configuration/tidb-server/configuration-file.md
Labels: dev, pending-aligning, small

#2065 tidb-in-kubernetes: improve content and wording of `deploy-tidb-from-k8s-kind` doc
  dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
  v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
  v3.1/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
Labels: pending-aligning

#2046 how-to/deploy: update supported versions of ansible and remove 2.0 GA info
  dev/how-to/deploy/orchestrated/offline-ansible.md
  v2.1/how-to/deploy/orchestrated/offline-ansible.md
  v3.0/how-to/deploy/orchestrated/offline-ansible.md
  v3.1/how-to/deploy/orchestrated/offline-ansible.md
Labels: aligned-in-docs

#2034 how-to/upgrade: update `from_previous_version` doc
  dev/how-to/upgrade/from-previous-version.md
  v2.1/how-to/upgrade/from-previous-version.md
  v3.0/how-to/upgrade/from-previous-version.md
  v3.1/how-to/upgrade/from-previous-version.md
Labels: aligned-in-docs

#2082 dev, v3.0, v3.1/*: add TiDB 3.0.6 Release Notes
  dev/TOC.md
  dev/releases/3.0.6.md
  dev/releases/rn.md
  v3.0/TOC.md
  v3.0/releases/3.0.6.md
  v3.0/releases/rn.md
  v3.1/TOC.md
  v3.1/releases/3.0.6.md
  v3.1/releases/rn.md
Labels: DNM, aligned-in-docs, dev, v3.0, v3.1

#2086 v3.0, v3.1, dev: add missed PRs in 3.0.6 patch2
  dev/releases/3.0.6.md
  v3.0/releases/3.0.6.md
  v3.1/releases/3.0.6.md
Labels: aligned-in-docs, dev, v3.0, v3.1

#2045 reference: update the transaction-related docs
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  dev/reference/transactions/overview.md
  dev/reference/transactions/transaction-isolation.md
  dev/reference/transactions/transaction-model.md
  v2.1-legacy/sql/mysql-compatibility.md
  v2.1-legacy/sql/transaction-isolation.md
  v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v2.1/reference/transactions/overview.md
  v2.1/reference/transactions/transaction-isolation.md
  v2.1/reference/transactions/transaction-model.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/reference/transactions/overview.md
  v3.0/reference/transactions/transaction-isolation.md
  v3.0/reference/transactions/transaction-model.md
  v3.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.1/reference/transactions/overview.md
  v3.1/reference/transactions/transaction-isolation.md
  v3.1/reference/transactions/transaction-model.md
Labels: DNM, dev, pending-aligning, v2.1, v3.0, v3.1
