Repository pingcap/docs-cn, pull requests merged in 2020-10, with the labels that each got.

#4639 Refine a dashboard image
  media/dashboard/dashboard-metrics-relation-home.png
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/no-need, type/enhancement

#4642 tidb-configuration-file: remove allow-auto-random from config manual
  tidb-configuration-file.md
  troubleshoot-hot-spot-issues.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4641 *: remove expression index out of experimental feature.
  sql-statements/sql-statement-create-index.md
  tidb-configuration-file.md
Labels: size/small, status/LGT2, translation/doing, v5.0

#4649 user-defined-variables: Update SQL keywords to capital
  user-defined-variables.md
Labels: contribution, hacktoberfest-accepted, status/LGT1, translation/no-need

#4647 user-defined-variables: Update SQL keywords to capital
  user-defined-variables.md
Labels: contribution, hacktoberfest-accepted, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/no-need

#4648 stmt reference: update sql_calc_found_rows
  sql-statements/sql-statement-select.md
Labels: size/small, status/LGT1, status/PTAL, translation/from-docs

#4622 docs: add set-operators.md
  TOC.md
  functions-and-operators/set-operators.md
Labels: size/medium, status/LGT2, status/can-merge, translation/doing, v5.0

#4638 Fix typos in troubleshoot-cpu-issues.md
  troubleshoot-cpu-issues.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/done, type/bug-fix

#4603 Fix wording in optimizer-hints.md
  optimizer-hints.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done, type/enhancement

#4576 explain: add index merge
  explain-index-merge.md
  query-execution-plan.md
Labels: follow-up, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#4663 br: change a note format to fix a display issue
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done, type/bug-fix

#4636 add doc for broadcast join
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4644 Delete roadmap.md
  roadmap.md
Labels: contribution, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT1, status/WIP, translation/from-docs

#4646 Add aliases in roadmap.md
  roadmap.md
Labels: contribution, status/LGT1, translation/from-docs

#4667 Add 5 aliases to fix dead links
  information-schema/information-schema-engines.md
  scale-tidb-using-tiup.md
  storage-engine/rocksdb-overview.md
  tiflash/troubleshoot-tiflash.md
  tiup/tiup-mirror.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix, version-specific-changes-required

#4672 Media: Update java-practice-1.png
  best-practices/java-app-best-practices.md
  media/best-practices/java-practice-1.png
  media/java-practice-1.png
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/doing

#4671 Update the default value of quota-backend-bytes
  pd-configuration-file.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4682 Fix TiFlash critical logs
  tiflash/maintain-tiflash.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/done

#4686 Add 2 aliases to fix dead links
  information-schema/information-schema-cluster-config.md
  information-schema/information-schema-processlist.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix, version-specific-changes-required

#4691 ticdc: add more protocol in ticdc sink config
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4692 Fix wording in use-tiflash.md
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/done, type/bug-fix

#4697 ticdc: correct cyclic-sync-ddl usage
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4699 Fix a note display error
  choose-index.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/no-need

#4696 Add conflicts check script and test files
  .circleci/config.yml
  scripts/check-conflicts.py
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, translation/from-docs

#4673 Improve images of three dcs in 2 cities
  media/three-data-centers-in-two-cities-deployment-03.png
  three-data-centers-in-two-cities-deployment.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/from-docs, type/enhancement

#4662 performance tuning: change SQL tuning TOC
  TOC.md
  analyze-slow-queries.md
  blacklist-control-plan.md
  dashboard/dashboard-slow-query.md
  dashboard/dashboard-statement-details.md
  explain-overview.md
  faq/sql-faq.md
  functions-and-operators/expressions-pushed-down.md
  mysql-compatibility.md
  sql-physical-optimization.md
  sql-statements/sql-statement-explain-analyze.md
  sql-statements/sql-statement-explain.md
  sql-tuning-overview.md
  subquery-optimization.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, status/PTAL, status/can-merge, translation/from-docs, version-specific-changes-required

#4708 Fix an image link that causes display failure
  media/three-data-centers-in-two-cities-deployment-03.png
  three-data-centers-in-two-cities-deployment.md
Labels: size/small, status/LGT1, translation/no-need, type/bug-fix

#4712 Update an image about labels
  media/three-data-centers-in-two-cities-deployment-03.png
  three-data-centers-in-two-cities-deployment.md
Labels: size/small, status/LGT1, status/PTAL, translation/no-need

#4711 Fix typo in pd-configuration-file.md
  pd-configuration-file.md
Labels: first-time-contributor, needs-cherry-pick-4.0, status/LGT1, translation/no-need

#4694 faq: add multistatement faq
  faq/tidb-faq.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/from-docs

#4659 docs-cn: modify coprocessor-cache.md
  coprocessor-cache.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, status/can-merge, status/require-change, translation/doing

#4714 prepared plan cache: Enable by default
  dashboard/dashboard-faq.md
  optimizer-hints.md
  sql-prepare-plan-cache.md
  tidb-configuration-file.md
Labels: follow-up, size/medium, status/LGT2, translation/from-docs, v5.0

#4637 tidb-binlog: add decription for initial-commit-ts
  tidb-binlog/tidb-binlog-configuration-file.md
Labels: contribution, needs-cherry-pick-3.0, require-LGT1, size/small, status/LGT1, status/can-merge, status/require-change, translation/doing

#4687 Introduce how to deploy on arm64
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4657 Update quick-start-with-tidb.md
  quick-start-with-tidb.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4721 contributing guide: update translation tasks claim process
  CONTRIBUTING.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/medium, status/LGT2, status/PTAL, translation/doing

#4733 Update operators.md
  functions-and-operators/operators.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-master, size/small, status/LGT1, translation/doing, type/bug-fix

#4690 explain: add aggregation
  explain-aggregation.md
Labels: follow-up, needs-cherry-pick-4.0, size/large, status/LGT1, status/PTAL, translation/from-docs

#4746 Add 9 aliases to fix dead links
  explain-overview.md
  identify-slow-queries.md
  information-schema/information-schema-cluster-load.md
  releases/release-2.1.1.md
  releases/release-3.0.4.md
  sql-statements/sql-statement-drop-sequence.md
  sql-statements/sql-statement-rename-table.md
  tidb-binlog/tidb-binlog-reparo.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#4748 Remove unneccssary escape \ from `--advertise-status-addr`
  command-line-flags-for-tikv-configuration.md
Labels: first-time-contributor, needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing, type/bug-fix

#4745 add tidb_opt_prefer_range_scan variable
  system-variables.md
Labels: first-time-contributor, size/small, status/LGT1, translation/doing

#4754 Fix sync-log description in 4.0
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing

#4755 Dashboard is GA, Diagnostics is Experimental
  dashboard/dashboard-diagnostics-access.md
  dashboard/dashboard-intro.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, translation/done

#4700 explain: add partitions
  explain-partitions.md
  sql-statements/sql-statement-explain.md
Labels: follow-up, needs-cherry-pick-4.0, size/large, status/LGT1, status/PTAL, translation/from-docs

#4751 Update tiflash-configuration.md
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4760 Add documentation about APPROX_PERCENTILE aggregate function
  functions-and-operators/aggregate-group-by-functions.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/done

#4730 releases: add TiDB 4.0.8 release notes
  TOC.md
  releases/release-4.0.8.md
  releases/release-notes.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/from-docs
