Repository pingcap/docs-cn, pull requests merged in 2020-08, with the labels that each got.

#3750 br: add use constraint with CDC and drainer
  br/backup-and-restore-faq.md
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#3830 br: add faq
  br/backup-and-restore-faq.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, status/require-change, translation/doing

#4154 .github: add cherry-pick checklist to pr template
  .github/pull_request_template.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/no-need

#3998 Add warn for tiflash data_dir
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4159 Delete 2 docs that are not in TOC.md
  geo-redundancy-deployment.md
  load-misuse-handling.md
Labels: require-LGT1, status/LGT1, status/can-merge, translation/no-need, type/4.0-cherry-pick

#4075 br: add sql related link
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/done

#4093 release: add TiDB 3.0.17 release notes
  TOC.md
  releases/release-3.0.17.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/from-docs

#4160 Add all releases to TOC
  TOC.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT1, translation/no-need

#3979 lightning: add docs for local backend
  TOC.md
  backup-and-restore-using-dumpling-lightning.md
  backup-and-restore-using-mydumper-lightning.md
  dumpling-overview.md
  ecosystem-tool-user-guide.md
  get-started-with-tidb-lightning.md
  loader-overview.md
  media/tidb-lightning-architecture.png
  migrate-from-mysql-mydumper-files.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/monitor-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-glossary.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-tidb-backend.md
Labels: needs-cherry-pick-4.0, size/large, status/LGT2, status/require-change, translation/doing, version-specific-changes-required

#4169 add a description for configuration item query-feedback-limit
  releases/release-3.0.17.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/done

#4094 tidb-lightning: update docs
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
  tidb-lightning/monitor-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-glossary.md
  troubleshoot-tidb-lightning.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/medium, status/LGT1, status/can-merge, translation/from-docs

#4171 remove word slave in tispark document
  tispark-overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing, type/enhancement

#4066 Add document for tiup-cluster
  maintain-tidb-using-tiup.md
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT1, translation/doing

#4184 [cherry-pick] br: add use constraint with CDC and drainer (#3750)
  br/backup-and-restore-faq.md
  br/backup-and-restore-tool.md
Labels: status/can-merge, type/3.1-cherry-pick

#4170 Update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/require-change, translation/doing

#3418 Update related description in troubleshoot-tiflash
  tiflash/troubleshoot-tiflash.md
Labels: contribution, size/small, status/LGT1, status/PTAL, status/require-change, translation/doing

#4194 Update related description in troubleshoot-tiflash
  tiflash/troubleshoot-tiflash.md
Labels: size/small, status/LGT1, translation/doing

#4186 Update pd-control.md
  pd-control.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4199 add tiup deployment prompt in ticdc docs
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4198 Remove 2 docs that are not in toc
  load-misuse-handling.md
  loader-overview.md
  tidb-lightning/tidb-lightning-misuse-handling.md
  troubleshoot-tidb-lightning.md
Labels: needs-cherry-pick-3.0, size/small, status/LGT1, translation/done, type/enhancement, version-specific-changes-required

#4201 TOC: add 2 entries
  TOC.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, require-LGT1, status/LGT1, status/can-merge, translation/done, type/bug-fix

#4117 Update tiup document
  scale-tidb-using-tiup.md
  tiup/tiup-faq.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4068 lightning: update configure about backslash
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4100 *: add note in character-set-and-collation; modify a tikv config
  character-set-and-collation.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#4024 mysql-compatibility: Improve MySQL Compatibility
  mysql-compatibility.md
  sql-statements/sql-statement-analyze-table.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, status/PTAL, status/can-merge, translation/from-docs

#4213 Update benchmark-sysbench-v4-vs-v3.md
  benchmark/benchmark-sysbench-v4-vs-v3.md
Labels: contribution, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4183 pd: add some missing configuration descriptions
  pd-configuration-file.md
Labels: require-LGT1, size/medium, status/LGT1, status/PTAL, status/can-merge, translation/done, v5.0

#4211 Fix a typo in 2.1.17 release notes
  releases/release-2.1.17.md
Labels: contribution, needs-cherry-pick-2.1, size/small, status/LGT1, translation/no-need

#4177 Update backup-and-restore-tool.md
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done

#4172 Add `interactive_timeout` variable
  system-variables.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4197 Update multi-data-centers-in-one-city-deployment.md
  multi-data-centers-in-one-city-deployment.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4209 update the docs of new feature in cdc v4.0.5
  media/cdc-architecture.png
  ticdc/manage-ticdc.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT1, status/require-change, translation/doing

#4150 add more details
  mysql-compatibility.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing

#4145 Align the description of TiFlash Grafana dashboard with other components
  grafana-pd-dashboard.md
  grafana-tikv-dashboard.md
  tiflash/monitor-tiflash.md
Labels: needs-cherry-pick-4.0, size/large, status/LGT1, status/PTAL, translation/doing

#4193 Update character-set-and-collation.md
  character-set-and-collation.md
Labels: needs-cherry-pick-4.0, special-week, status/LGT1, status/PTAL, translation/from-docs

#4232 Add an alias to fix dead link
  sql-statements/sql-statement-modify-column.md
Labels: require-LGT1, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#4111 faq, sql-statements: update docs
  faq/sql-faq.md
  sql-statements/sql-statement-set-variable.md
Labels: needs-cherry-pick-4.0, status/LGT2, status/PTAL, translation/from-docs, version-specific-changes-required

#3585 benchmark: change a parameter level from global to session
  benchmark/v4.0-performance-benchmarking-with-tpch.md
Labels: contribution, needs-cherry-pick-4.0, status/LGT2, status/PTAL, status/can-merge, translation/doing

#4237 binlog: change binlog slave to binlog consumer
  TOC.md
  ecosystem-tool-user-case.md
  tidb-binlog/binlog-consumer-client.md
  tidb-binlog/tidb-binlog-overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2, translation/from-docs, version-specific-changes-required

#4239 Add auto-scaling doc link in 4.0 experimental feature
  experimental-features-4.0.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/done

#4132 update the usage of tikv-ctl modify-tikv-config
  tikv-control.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4234 ticdc: update the note about a bug
  ticdc/ticdc-open-protocol.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4248 faq, sql-statements: update docs
  faq/tidb-faq.md
  sql-statements/sql-statement-set-variable.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT1, translation/no-need

#4246 correct the content in auto-random.md
  auto-random.md
  system-variables.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT2, status/can-merge, translation/doing

#4255 Update documents fix drop column support features
  sql-statements/sql-statement-drop-column.md
Labels: contribution, size/small, status/LGT1, status/PTAL, v5.0

#4249 Add TLS in TiDB Dashboard documentation
  dashboard/dashboard-ops-reverse-proxy.md
  dashboard/dashboard-ops-security.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4258 Removed spurious backslash from troubleshoot-hot-spot-issues.md
  troubleshoot-hot-spot-issues.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#4230 add doc for tiflash tls config
  enable-tls-between-components.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4233 Add document for tiup cluster clean
  maintain-tidb-using-tiup.md
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4238 Change the way of config offline mirror package
  upgrade-tidb-using-tiup-offline.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4256 fix typo: tidb-scheduling
  tidb-scheduling.md
Labels: contribution, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/no-need

#4265 br: update limitation
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4259 remove duplicate table
  character-set-and-collation.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4272 Add migrate control node in tiup-cluster
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4269 Change the code block format of manage-ticdc.md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/done, type/bug-fix

#4273 Add document for tiup cluster rename
  maintain-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4280 Add what's new in TiDB 4.0 to index
  _index.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#4270 pd: add rule group configuration
  configure-placement-rules.md
  pd-control.md
Labels: require-LGT1, size/medium, status/LGT1, status/PTAL, status/can-merge, translation/doing, v5.0

#4283 Add 3 aliases to fix dead links
  information-schema/information-schema-cluster-systeminfo.md
  quick-start-with-tidb.md
  storage-engine/titan-configuration.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix, version-specific-changes-required

#4282 toc: update the file order of br
  TOC.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#4285 Fix unclear description of PD configuration items
  command-line-flags-for-pd-configuration.md
  pd-configuration-file.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/done, type/enhancement, version-specific-changes-required

#4289 fix typo: hardware-and-software-requirements
  hardware-and-software-requirements.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/LGT1, translation/no-need, type/bug-fix

#4279 Add doc for tiup cluster env init
  production-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4295 Fixed evict-leader-scheduler syntax
  best-practices/pd-scheduling-best-practices.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs, type/bug-fix

#4301 fix an error in `create sequence`
  sql-statements/sql-statement-show-create-sequence.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, translation/doing, type/bug-fix

#4300 Emphasize that statement summary history tables may lose after TiDB rebooting
  statement-summary-tables.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4302 add a config item [security]spilled-file-encryption-method in tidb-configuration-file.md
  tidb-configuration-file.md
Labels: require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing, v5.0

#4276 update pd-ctl doc
  pd-control.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/from-docs, version-specific-changes-required

#4310 Update hardware-and-software-requirement
  hardware-and-software-requirements.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4227 optimizer-hints: add docs for `nth_plan()` hint
  optimizer-hints.md
Labels: contribution, size/small, status/LGT1, status/PTAL, translation/doing, v5.0

#4314 Update check-before-deployment.md
  check-before-deployment.md
Labels: contribution, follow-up, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4326 chore: remove extra indent after copyable snippet code
  check-before-deployment.md
Labels: require-LGT1, status/can-merge, translation/no-need

#4327 remove extra spaces to fix a display error
  check-before-deployment.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix

#4329 mydumper: Improve clarity of mydumper warning
  mydumper-overview.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-docs

#4333 Fix dead links
  information-schema/information-schema-cluster-log.md
  information-schema/information-schema-ddl-jobs.md
  information-schema/information-schema-inspection-rules.md
  information-schema/information-schema-key-column-usage.md
  information-schema/information-schema-schemata.md
  information-schema/information-schema-table-constraints.md
  information-schema/information-schema-tikv-region-status.md
  mysql-schema.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, version-specific-changes-required

#4324 Update DM 2.0 related doc
  ecosystem-tool-user-case.md
  ecosystem-tool-user-guide.md
  migrate-from-aurora-mysql-database.md
  migration-overview.md
  tidb-troubleshooting-map.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#4340 Fix a dead link
  functions-and-operators/string-functions.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix, version-specific-changes-required

#4332 Update tidb-configuration-file.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4346 Clarify wording in BR tool doc
  br/backup-and-restore-tool.md
Labels: size/small, status/LGT1, translation/doing

#4339 Clarify wording in BR tool doc
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, require-LGT1, size/small, status/LGT1, translation/doing

#4311 sql-statements: improve SHOW TABLE REGIONS examples
  sql-statements/sql-statement-show-table-regions.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/require-change, translation/from-docs

#4352 ticdc: update ga related docs
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT1, status/PTAL, translation/doing

#4353 ticdc: add ga version, remove experiment warning
  experimental-features-4.0.md
  ticdc-deployment-topology.md
  ticdc/ticdc-overview.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4294 ticdc: update pulsar sink
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT1, status/require-change, translation/doing

#4355 ticdc: update open protocol
  ticdc/ticdc-open-protocol.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4364 ticdc: fix some unprecise docs
  ticdc/manage-ticdc.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done

#4366 Fix typos in manage-ticdc.md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/no-need, type/bug-fix

#4369 ticdc: revert cdc ga
  experimental-features-4.0.md
  ticdc-deployment-topology.md
  ticdc/ticdc-overview.md
  whats-new-in-tidb-4.0.md
Labels: status/LGT1

#4319 add doc for tiflash encryption-at-rest
  enable-tls-between-components.md
  encryption-at-rest.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4262 Fix a typo in tidb lightning deployment document
  TOC.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, translation/done, type/bug-fix

#4360 Update default value for RocksDB max-subcompactions
  tikv-configuration-file.md
Labels: needs-cherry-pick-3.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/from-docs

#4361 Update default value for RocksDB max-subcompactions
  tikv-configuration-file.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/from-docs

#4376 Correct a description
  tidb-troubleshooting-map.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#4368 cdc: add Apache Pulsar to cdc architecture
  media/cdc-architecture.png
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4384 Update tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-overview.md
Labels: size/small, status/LGT1, translation/doing

#4372 Update tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-overview.md
Labels: contribution, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, size/small, status/LGT1, status/PTAL, status/require-change, translation/doing

#4261 update pd-recover docs
  pd-recover.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/from-docs

#4391 Update tispark-deployment-topology.md
  tispark-deployment-topology.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix
