Repository pingcap/docs-cn, pull requests merged in 2020-01, with the labels that each got.

#2148 reference/tools: refine mydumper doc
  dev/reference/tools/mydumper.md
  v2.1/reference/tools/mydumper.md
  v3.0/reference/tools/mydumper.md
  v3.1/reference/tools/mydumper.md
Labels: aligned-in-docs

#2162 reference: improve usability of certificate-based authentication doc
  dev/reference/security/cert-based-authentication.md
  v3.0/reference/security/cert-based-authentication.md
Labels: aligned-with-docs

#2152 how-to/scale/with-ansible: add a note
  dev/how-to/scale/with-ansible.md
  v3.0/how-to/scale/with-ansible.md
  v3.1/how-to/scale/with-ansible.md
Labels: align-N/A, dev, v3.0, v3.1

#2164 br: unify doc titles
  dev/how-to/maintain/backup-and-restore/br.md
  v3.1/how-to/maintain/backup-and-restore/br.md
Labels: aligned-in-docs, dev, v3.1

#2163 tidb-in-kubernetes: fix the pump affinity error
  dev/tidb-in-kubernetes/maintain/tidb-binlog.md
  v3.0/tidb-in-kubernetes/maintain/tidb-binlog.md
  v3.1/tidb-in-kubernetes/maintain/tidb-binlog.md
Labels: pending-aligning, small, tidb-in-k8s

#2023 tidb-in-kubernetes: update doc for net.ipv4.tcp_keepalive_time config
  dev/tidb-in-kubernetes/troubleshoot.md
  v3.0/tidb-in-kubernetes/troubleshoot.md
  v3.1/tidb-in-kubernetes/troubleshoot.md
Labels: pending-aligning, tidb-in-k8s

#2168 tidb-in-kubernetes: refine the language of k8s troubleshoot doc
  dev/tidb-in-kubernetes/troubleshoot.md
  v3.0/tidb-in-kubernetes/troubleshoot.md
  v3.1/tidb-in-kubernetes/troubleshoot.md
Labels: aligned-in-docs, tidb-in-k8s

#1993 tools/tidb-lightning: update Lightning-related docs
  dev/TOC.md
  dev/reference/tools/tidb-lightning/config.md
  dev/reference/tools/tidb-lightning/deployment.md
  dev/reference/tools/tidb-lightning/monitor.md
  dev/reference/tools/tidb-lightning/overview.md
  dev/reference/tools/tidb-lightning/web.md
  media/lightning-grafana-row-1.png
  media/lightning-grafana-row-2.png
  media/lightning-grafana-row-3.png
  media/lightning-grafana-row-4.png
  media/lightning-grafana-row-5.png
  media/lightning-grafana-row-6.png
  media/lightning-grafana-row-7.png
  media/lightning-web-frontpage.png
  media/lightning-web-queue.png
  media/lightning-web-submit.png
  media/lightning-web-table.png
  v2.1/TOC.md
  v2.1/reference/tools/tidb-lightning/config.md
  v2.1/reference/tools/tidb-lightning/deployment.md
  v2.1/reference/tools/tidb-lightning/monitor.md
  v2.1/reference/tools/tidb-lightning/overview.md
  v2.1/reference/tools/tidb-lightning/web.md
  v3.0/TOC.md
  v3.0/reference/tools/tidb-lightning/config.md
  v3.0/reference/tools/tidb-lightning/deployment.md
  v3.0/reference/tools/tidb-lightning/monitor.md
  v3.0/reference/tools/tidb-lightning/overview.md
  v3.0/reference/tools/tidb-lightning/web.md
  v3.1/TOC.md
  v3.1/reference/tools/tidb-lightning/config.md
  v3.1/reference/tools/tidb-lightning/deployment.md
  v3.1/reference/tools/tidb-lightning/monitor.md
  v3.1/reference/tools/tidb-lightning/overview.md
  v3.1/reference/tools/tidb-lightning/web.md
Labels: DNM, LGT1, aligned-with-docs, dev, large, v2.1, v3.0

#2156 *: add doc to restart tidb components on k8s
  dev/TOC.md
  dev/tidb-in-kubernetes/maintain/restart.md
  v3.0/TOC.md
  v3.0/tidb-in-kubernetes/maintain/restart.md
  v3.1/TOC.md
  v3.1/tidb-in-kubernetes/maintain/restart.md
Labels: medium, pending-aligning, tidb-in-k8s

#2170 reference/tools: add "-tidb-password" cli flag in tidb-lightning config
  dev/reference/tools/tidb-lightning/config.md
  v2.1/reference/tools/tidb-lightning/config.md
  v3.0/reference/tools/tidb-lightning/config.md
  v3.1/reference/tools/tidb-lightning/config.md
Labels: aligned-with-docs, dev, small, v2.1, v3.0, v3.1

#2154 reference/tidb-binlog: improve snapshot timestamp for initialization
  dev/reference/tidb-binlog/deploy.md
  v2.1/reference/tidb-binlog/deploy.md
  v3.0/reference/tidb-binlog/deploy.md
  v3.1/reference/tidb-binlog/deploy.md
Labels: pending-aligning, small

#2174 reference: update supported character sets
  v2.1/reference/mysql-compatibility.md
Labels: align-N/A

#2177 reference: update grafana best practice
  dev/reference/best-practices/grafana-monitor.md
  v2.1/reference/best-practices/grafana-monitor.md
  v3.0/reference/best-practices/grafana-monitor.md
  v3.1/reference/best-practices/grafana-monitor.md
Labels: pending-aligning, small

#2178 CONTRIBUTING: fix a broken link
  CONTRIBUTING.md
Labels: pending-aligning, status/can-merge

#2171 faq/upgrade: fix SQL format
  dev/faq/upgrade.md
  v2.1/faq/upgrade.md
  v3.0/faq/upgrade.md
  v3.1/faq/upgrade.md
Labels: aligned-in-docs, status/can-merge

#2169 benchmark: add lightning import for TPC-C
  dev/benchmark/how-to-run-tpcc.md
  v3.0/benchmark/how-to-run-tpcc.md
  v3.1/benchmark/how-to-run-tpcc.md
Labels: large, pending-aligning, status/can-merge

#2179 dev, v3.1: add 3.1.0-beta.1 release notes
  dev/TOC.md
  dev/releases/3.1.0-beta.1.md
  dev/releases/rn.md
  v3.1/TOC.md
  v3.1/releases/3.1.0-beta.1.md
  v3.1/releases/rn.md
Labels: aligned-in-docs, status/can-merge

#2175 tidb-binlog: introduce how to upgrade binlog
  dev/reference/tidb-binlog/upgrade.md
  v2.1/reference/tidb-binlog/upgrade.md
  v3.0/reference/tidb-binlog/upgrade.md
  v3.1/reference/tidb-binlog/upgrade.md
Labels: pending-aligning, status/can-merge

#2180 reference: update description and format in java app
  v3.0/reference/best-practices/java-app.md
Labels: best-practices, contribution

#2182 best-practice: update the description and format for Java best practice
  dev/reference/best-practices/java-app.md
  v2.1/reference/best-practices/java-app.md
  v3.1/reference/best-practices/java-app.md
Labels: pending-aligning

#2102 *: add glossary for binlog
  dev/TOC.md
  dev/reference/tidb-binlog/glossary.md
  v2.1/TOC.md
  v2.1/reference/tidb-binlog/glossary.md
  v3.0/TOC.md
  v3.0/reference/tidb-binlog/glossary.md
  v3.1/TOC.md
  v3.1/reference/tidb-binlog/glossary.md
Labels: medium, pending-aligning, status/can-merge

#2187 reference/security: add cert-based authentication doc for v3.1
  v3.1/TOC.md
  v3.1/reference/security/cert-based-authentication.md
Labels: v3.1

#2186 releases, TOC: add TiDB 3.0.9 Release Notes
  dev/TOC.md
  dev/releases/3.0.9.md
  dev/releases/rn.md
  v3.0/TOC.md
  v3.0/releases/3.0.9.md
  v3.0/releases/rn.md
  v3.1/TOC.md
  v3.1/releases/3.0.9.md
  v3.1/releases/rn.md
Labels: dev, status/can-merge, v3.0, v3.1

#2189 release: add a note to 3.0.9 release notes
  dev/releases/3.0.9.md
  v3.0/releases/3.0.9.md
  v3.1/releases/3.0.9.md
Labels: aligned-in-docs, dev, v3.0, v3.1

#2128 how-to/deploy: delete enable_slow_query_log
  dev/how-to/deploy/orchestrated/ansible.md
  v3.0/how-to/deploy/orchestrated/ansible.md
  v3.1/how-to/deploy/orchestrated/ansible.md
Labels: pending-aligning, small, status/can-merge

#2183 pull_request_template: create checkboxes to reduce manual effort of typing words
  .github/pull_request_template.md
Labels: pending-aligning

#2195 releases, toc: add 4.0.0-beta release notes
  dev/TOC.md
  dev/releases/4.0.0-beta.md
  dev/releases/rn.md
Labels: DNM until Ansible tag is ready, aligned-in-docs, dev, v4.0

#2185 reference/tidb-binlog: add encrypt_password for tidb-binlog/deploy.md
  dev/reference/tidb-binlog/deploy.md
  v3.0/reference/tidb-binlog/deploy.md
  v3.1/reference/tidb-binlog/deploy.md
Labels: LGT1, pending-aligning, status/can-merge

#2188 tidb-binlog: improve the descriptions in tidb binlog deployment doc
  dev/reference/tidb-binlog/deploy.md
  v2.1/reference/tidb-binlog/deploy.md
  v3.0/reference/tidb-binlog/deploy.md
  v3.1/reference/tidb-binlog/deploy.md
Labels: pending-aligning, status/can-merge

#2196 releases: improve format of 4.0.0-beta release notes
  dev/releases/4.0.0-beta.md
Labels: aligned-with-docs, dev, status/can-merge, v4.0

#2155 tidb-in-kubernetes: fix pv deletion
  dev/tidb-in-kubernetes/reference/configuration/storage-class.md
  v3.0/tidb-in-kubernetes/reference/configuration/storage-class.md
  v3.1/tidb-in-kubernetes/reference/configuration/storage-class.md
Labels: pending-aligning, small

#2201 tools: add a glossary for dm in v2.1
  v2.1/TOC.md
  v2.1/reference/tools/data-migration/glossary.md
Labels: aligned-in-docs, v2.1

#2193 configuration/tidb-server: add a description for `max-server-connections`
  dev/reference/configuration/tidb-server/configuration-file.md
Labels: pending-aligning, small

#2192 reference/sql: correct description about push_down expression alias before v3.0.3
  v3.0/reference/sql/functions-and-operators/expressions-pushed-down.md
Labels: LGT1, pending-aligning, small, status/can-merge
