Repository pingcap/docs-cn, pull requests merged in 2020-12, with the labels that each got.

#4982 Update manage-ticdc.md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4983 dumpling: add system database detail
  dumpling-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4978 Media: Delete tidb-trace-viewer-2.png
  media/tidb-trace-viewer-2.png
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/done

#4960 Remove useless download info for binlogctl
  tidb-binlog/binlog-control.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#4991 Add log.level description
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4946 tiup: use absolute path
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing, type/bug-fix

#4972 Media: Delete two images that involve third-party logos
  media/grafana-screenshot.png
  media/tiup/grafana-login.png
  post-installation-check.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/done

#4996 chore: add script to upload file to s3
  .circleci/config.yml
  scripts/upload.py
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/done

#5002 resources: update a Figma template link
  resources/figma-quick-start-guide.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/no-need

#4977 Deprecate config item `max-memory` and add items `server-memory-quota` and `memory-usage-alarm-ratio`
  configure-memory-usage.md
  system-variables.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT1, status/require-change, translation/doing, version-specific-changes-required

#5017 tidb-control: modify --port to status port
  tidb-control.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-master, size/small, status/LGT1, status/PTAL, translation/doing

#5003 add more comment for mem-quota-query
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing

#5028 statements: put access-key & secret-key in backup example
  sql-statements/sql-statement-backup.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#5026 change note to warning for experimental features
  dashboard/dashboard-diagnostics-access.md
  dynamic-config.md
  information-schema/information-schema-sql-diagnostics.md
  storage-engine/titan-configuration.md
  tidb-configuration-file.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#5036 Fix typos in tikv-overview.md
  tikv-overview.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix

#4912 explain: add subqueries
  explain-subqueries.md
Labels: follow-up, needs-cherry-pick-4.0, require-LGT1, size/large, status/LGT1, status/PTAL, status/can-merge, translation/from-docs

#5042 binlog: add an example for `ignore-txn-commit-ts`
  tidb-binlog/tidb-binlog-configuration-file.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#5010 ticdc: add a description in ticdc-overview.md
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing

#4992 pd-ctl: add scheduler config evict-leader-scheduler
  pd-control.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#5027 update example versions in download-ecosystem-tools.md
  download-ecosystem-tools.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing

#5013 tikv: add server.end-point-slow-log-threshold config
  tikv-configuration-file.md
Labels: first-time-contributor, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/done

#5024 tikv-control: update description
  tikv-control.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#5058 Make the dynamic config of TiKV more clear
  dynamic-config.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#5032 Update upstream-downstream-diff.md
  sync-diff-inspector/upstream-downstream-diff.md
Labels: first-time-contributor, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-master, size/small, status/LGT2, status/PTAL, translation/doing

#5023 Update online environment switch
  production-offline-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing

#5052 update document for adding a float compatibility problem's warning
  data-type-numeric.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#5047 ticdc: add some troubleshoots
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing

#5030 update document to use tiflash in tispark
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5070 media: refine 3 images
  media/deploy-3dc-dr.png
  media/deploy-3dc-optimize.png
  media/deploy-3dc.png
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#5069 sql-statements: use ENBF to render syntax diagrams for BACKUP and RESTORE
  media/sqlgram/BRIETables.png
  media/sqlgram/BackupOption.png
  media/sqlgram/BackupStmt.png
  media/sqlgram/BackupTSO.png
  media/sqlgram/Boolean.png
  media/sqlgram/RestoreOption.png
  media/sqlgram/RestoreStmt.png
  media/sqlgram/ShowBRIEStmt.png
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
  sql-statements/sql-statement-show-backups.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#4979 add documentation for tidb_enable_amend_pessimistic_txn.
  system-variables.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, translation/doing, v5.0

#5049 tidb binlog: add more description in tidb-binlog-deployment-topology.md
  config-templates/simple-file-binlog.yaml
  tidb-binlog-deployment-topology.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/doing

#5073 monitoring: document MetricsTool (Export Grafana Snapshots)
  TOC.md
  _index.md
  exporting-grafana-snapshots.md
  media/metricstool-export.png
  media/metricstool-visualize.png
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/from-docs

#5083 ticdc: fix typos
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done, type/bug-fix

#5078 tiflash: add config item about tiflash io rate limit
  tiflash/tiflash-configuration.md
Labels: size/small, status/LGT1, status/PTAL, translation/done, v5.0

#5035 Add description for tidb_distsql_scan_concurrency
  system-variables.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, translation/doing

#5086 TiFlash config: Add description for delta_index_cache_size
  tiflash/tiflash-configuration.md
Labels: size/small, status/LGT1, status/PTAL, translation/done, v5.0

#5089 Revert "*: remove expression index out of experimental feature."
  sql-statements/sql-statement-create-index.md
  tidb-configuration-file.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing, v5.0

#5093 Add 7 aliases to fix broken links
  functions-and-operators/date-and-time-functions.md
  grafana-tikv-dashboard.md
  sql-statements/sql-statement-rename-index.md
  tidb-binlog/maintain-tidb-binlog-cluster.md
  tidb-binlog/monitor-tidb-binlog-cluster.md
  tidb-binlog/tidb-binlog-overview.md
  transaction-overview.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#5011 Media: Improve five images involving third-party logos
  media/pd-dashboard-cluster.png
  media/syncer-monitor-scheme.png
  media/tidb-binlog-cluster-architecture.png
  media/tidb_binlog_cluster_architecture.png
  media/tikv-dashboard-cluster.png
  media/trace-view.png
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-binlog/tidb-binlog-overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/from-docs, version-specific-changes-required

#5101 Media: Update four images involving third-party logos
  media/cdc-architecture.png
  media/dashboard/dashboard-ops-multiple-pd.png
  media/tiup/grafana-overview.png
  media/view-dashboard.png
Labels: needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#5104 update format and refine punctuation
  system-variables.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/no-need, version-specific-changes-required

#5091 Update pingcap-style-guide-zh.pdf
  resources/pingcap-style-guide-zh.pdf
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/no-need

#5111 Fix a broken link
  best-practices/massive-regions-best-practices.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#5072 media: refine one image
  media/tikv-arch.png
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#5068 TiDB Ansible: clarify in the warning against using Ansible since 4.0
  offline-deployment-using-ansible.md
  online-deployment-using-ansible.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/from-docs

#5120 Standardize the writing of product name "TiDB Binlog"
  command-line-flags-for-tidb-configuration.md
  tidb-binlog-deployment-topology.md
Labels: needs-cherry-pick-4.0, status/LGT2, translation/done, type/bug-fix

#5099 system-variables: disable clustered index by default
  system-variables.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing, v5.0

#5122 tikv: fix wrong description and default value for enable-statistics
  tikv-configuration-file.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#5127 Add a new error code 8129
  error-codes.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#5094 Add TiFlash security configuration
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done, version-specific-changes-required

#5131 Added introduction version description
  configure-memory-usage.md
  system-variables.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4976 releases: add v4.0.9 release notes
  TOC.md
  releases/release-4.0.9.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, status/LGT2, translation/from-docs

#5136 releases: correct the release date
  releases/release-4.0.9.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#5088 encryption-at-rest: describe compatibility change with TiKV <= 4.0.8
  column-pruning.md
  encryption-at-rest.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-4.0, size/medium, status/DNM, status/LGT1, translation/from-docs

#4959 TiCDC: add information about Unified Sorter
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/medium, status/DNM, status/LGT2, translation/done

#4975 system variable: add tidb_enable_rate_limit_action
  system-variables.md
Labels: needs-cherry-pick-4.0, size/small, status/DNM, status/LGT1, translation/done

#5031 *: update FAQ of tools
  br/backup-and-restore-faq.md
  ticdc/troubleshoot-ticdc.md
  tidb-binlog/handle-tidb-binlog-errors.md
  tidb-lightning/tidb-lightning-faq.md
Labels: needs-cherry-pick-4.0, size/small, status/DNM, status/LGT2, translation/done

#4951 Add explanation about two kafka parameters
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, translation/done

#4958 add more details to pipelined lock
  pessimistic-transaction.md
Labels: needs-cherry-pick-4.0, size/small, status/DNM, status/LGT1, translation/done

#5087 Update tools FAQ during oncall week of 12-04 ~ 12-10
  br/backup-and-restore-faq.md
  faq/migration-tidb-faq.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, translation/doing

#5145 fix the default value of tcp-keep-alive
  tidb-configuration-file.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#5133 tikv: rename auto-tuned config
  tikv-configuration-file.md
Labels: size/small, status/LGT1, translation/from-docs, v5.0

#4965 Add desc of new TiFlash storage settings and guidelines for upgrading in v4.0.9
  config-templates/complex-tiflash.yaml
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-4.0, size/large, status/DNM, status/LGT1, translation/done, version-specific-changes-required

#5151 Fix a typo
  tidb-troubleshooting-map.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix

#5123 update tikv-server-config file with bottommost-level-compression
  data-type-numeric.md
  tikv-configuration-file.md
Labels: first-time-contributor, size/small, status/LGT1, translation/doing, v5.0

#5153 pd: add new configurations
  pd-configuration-file.md
  pd-control.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing, v5.0

#5092 update GC for release 5.0
  garbage-collection-configuration.md
  tikv-configuration-file.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing, v5.0

#5166 GC: unify TiKV and TiDB --> TiDB
  garbage-collection-configuration.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/done, version-specific-changes-required

#5106 releases: add tidb 3.0.20 release notes
  TOC.md
  releases/release-3.0.20.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2, translation/from-docs

#5156 errorcode: Add TiFlashServerBusy and TiFlashServerTimeout.
  error-codes.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done

#5159 add variable item `tidb_track_aggregate_memory_usage`
  system-variables.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing, v5.0

#5177 Change attribute value
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing, type/bug-fix

#5163 tikv-configuration-file: add config for compaction guard
  tikv-configuration-file.md
  tune-tikv-memory-performance.md
Labels: status/LGT1, status/PTAL, translation/from-docs, v5.0

#5180 Make bg_task_io_rate_limit setting experimental
  tiflash/tiflash-configuration.md
Labels: size/small, status/LGT1, translation/done, v5.0

#5183 disable gc in compaction filter by default
  garbage-collection-configuration.md
  tikv-configuration-file.md
Labels: size/small, status/LGT1, translation/doing, v5.0

#5132 Add doc for List partition and List columns partition
  partitioned-table.md
Labels: size/medium, status/LGT2, status/require-change, translation/doing, v5.0

#5181 update async commit related configurations
  system-variables.md
  tidb-configuration-file.md
Labels: size/medium, status/LGT1, status/PTAL, translation/doing, v5.0

#5157 Remove all TiDB Ansible related contents from dev
  TOC.md
  best-practices/grafana-monitor-best-practices.md
  dashboard/dashboard-diagnostics-access.md
  dashboard/dashboard-faq.md
  dashboard/dashboard-overview.md
  faq/deploy-and-maintain-faq.md
  faq/migration-tidb-faq.md
  get-started-with-tispark.md
  grafana-overview-dashboard.md
  grafana-pd-dashboard.md
  grafana-tidb-dashboard.md
  grafana-tikv-dashboard.md
  maintain-tidb-using-ansible.md
  maintain-tidb-using-tiup.md
  offline-deployment-using-ansible.md
  online-deployment-using-ansible.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  scale-tidb-using-ansible.md
  scale-tidb-using-tiup.md
  schedule-replicas-by-topology-labels.md
  telemetry.md
  three-data-centers-in-two-cities-deployment.md
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/monitor-tidb-binlog-cluster.md
  tidb-binlog/upgrade-tidb-binlog.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/monitor-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-monitoring-api.md
  tiflash/monitor-tiflash.md
  tikv-control.md
  tispark-overview.md
  tiup/tiup-cluster.md
  troubleshoot-high-disk-io.md
  troubleshoot-tidb-lightning.md
  upgrade-tidb-using-ansible.md
  upgrade-tidb-using-tiup.md
Labels: follow-up, needs-cherry-pick-5.0, size/large, status/LGT2, status/PTAL, translation/doing, v5.0, version-specific-changes-required

#5191 update doc for list partition table
  partitioned-table.md
  system-variables.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing, v5.0

#5186 add log redaction-related contents
  TOC.md
  identify-slow-queries.md
  log-redaction.md
  pd-configuration-file.md
  system-variables.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/medium, status/LGT2, status/PTAL, translation/doing, v5.0, version-specific-changes-required

#5188 pd-configuration: add enable-joint-consensus
  pd-configuration-file.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing, v5.0, version-specific-changes-required

#5158 tidb config: add txn-entry-size-limit
  tidb-configuration-file.md
Labels: follow-up, needs-cherry-pick-5.0, status/DNM, status/LGT1, translation/doing, v5.0

#5202 Update PR template for v5.0
  .github/pull_request_template.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs

#5207 Remove 4.0-specific docs from TOC
  TOC.md
Labels: size/small, status/LGT1, translation/done

#4858 delete mydumper doc in dev and 5.0
  TOC.md
  backup-and-restore-using-dumpling-lightning.md
  backup-and-restore-using-mydumper-lightning.md
  br/backup-and-restore-tool.md
  download-ecosystem-tools.md
  dumpling-overview.md
  mydumper-overview.md
  three-data-centers-in-two-cities-deployment.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-troubleshooting-map.md
Labels: needs-cherry-pick-5.0, size/large, status/LGT2, translation/doing, v5.0, version-specific-changes-required

#5211 Add description related to compaction rate limit
  tikv-configuration-file.md
  tikv-control.md
Labels: needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/from-docs

#5195 clustered indexes: add initial docs
  TOC.md
  clustered-indexes.md
  system-variables.md
Labels: needs-cherry-pick-5.0, status/LGT2, status/PTAL, translation/from-docs, v5.0

#5215 chore: update release-5.0 PDF
  .circleci/config.yml
Labels: status/LGT1, translation/done

#5164 statistics: add docs for version 2
  best-practices/tidb-best-practices.md
  statistics.md
  tidb-best-practices.md
Labels: needs-cherry-pick-5.0, size/medium, status/LGT1, status/require-change, translation/doing, v5.0

#5213 Delete loader/syncer docs in dev/v5.0
  TOC.md
  download-ecosystem-tools.md
  ecosystem-tool-user-guide.md
  faq/migration-tidb-faq.md
  loader-overview.md
  syncer-overview.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-overview.md
Labels: follow-up, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/doing, v5.0, version-specific-changes-required

#5222 Comment out v5.0 version marks
  log-redaction.md
  pd-configuration-file.md
  system-variables.md
  tidb-configuration-file.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, translation/done

#5176 update lightning faq
  ecosystem-tool-user-case.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-faq.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT3, status/PTAL, translation/doing

#5165 Refine the language of benchmark-tidb-using-sysbench.md
  benchmark/benchmark-tidb-using-sysbench.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/no-need, type/bug-fix

#5162 Correct wrong description for a coprocessor config
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs

#5154 mysql-compatibility: update ZERO_DATE docs
  mysql-compatibility.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs
