Repository pingcap/docs-cn, pull requests merged in 2020-05, with the labels that each got.

#2878 TiUP: add several reference documents
  TOC.md
  reference/tools/tiup/bench.md
  reference/tools/tiup/cluster.md
  reference/tools/tiup/manage-component.md
  reference/tools/tiup/mirrors.md
  reference/tools/tiup/overview.md
  reference/tools/tiup/package-component.md
  reference/tools/tiup/playground.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/doing

#2938 how-to/deploy: add cdc deployment through tiup
  how-to/deploy/orchestrated/tiup.md
  how-to/scale/with-tiup.md
  reference/tools/ticdc/deploy.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL

#2950 contributing: add a link to join #sig-docs Slack channel
  CONTRIBUTING.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small

#2940 sql: add docs for rule_generate_column_substitute.
  reference/sql/generated-columns.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#2672 add documentation for tidb_opt_distinct_agg_push_down
  reference/configuration/tidb-server/tidb-specific-variables.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/can-merge, translation/from-docs

#2958 ci: add GitHub action to upload media files
  .github/workflows/media.yml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/no-need

#2802 br: add backup and resotre from s3 with BR
  reference/tools/br/br.md
Labels: follow-up, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#2959 contributing: add link of #sig-docs slack channel with referral
  CONTRIBUTING.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/no-need

#2970 tools: fix typo of binlog's minitor
  reference/tidb-binlog/monitor.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/welcome, type/bug-fix

#2919 how-to/deploy: fix a command in tiup deployment doc
  how-to/deploy/orchestrated/tiup.md
Labels: contribution, size/small, status/can-merge, status/require-change, translation/doing

#2918 tiup: add close swap section and fix a command
  how-to/deploy/orchestrated/tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, status/require-change, translation/doing

#2978 tiup: modify user login description
  how-to/deploy/orchestrated/tiup.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#2907 tiflash: update expression list supported by TiFlash in 4.0
  reference/tiflash/use-tiflash.md
Labels: status/PTAL, status/can-merge, translation/doing

#2906 tiflash: update expression list supported by TiFlash in 3.1
  reference/tiflash/use-tiflash.md
Labels: status/LGT1, status/PTAL, status/can-merge, translation/doing

#2948 reference/performance: reorder tikv tuning log parameters
  reference/performance/tune-tikv.md
Labels: contribution, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, size/small, status/can-merge, translation/doing, type/bug-fix

#2980 reference: enlarge txn-total-size-limit when binlog enabled
  reference/configuration/tidb-server/configuration-file.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/doing

#2990 tiup: refine some expressions in manage-component.md
  TOC.md
  reference/tools/tiup/manage-component.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#2946 sql: fix config name in collation doc
  reference/sql/characterset-and-collation.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/doing, type/bug-fix

#2988 reference/mysql-compatibility: remove limit of add index on generated columns
  reference/mysql-compatibility.md
Labels: status/LGT2, translation/doing, v4.0

#2989 reference/mysql-compatibility: remove limit of add index on generated columns
  reference/mysql-compatibility.md
Labels: size/small, status/LGT2, status/can-merge, translation/doing

#2921 tiflash: update expression list supported by TiFlash in master
  reference/tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, status/can-merge, status/require-change, translation/doing

#2997 tiup: fix two titles in scale/with-tiup.md
  how-to/scale/with-tiup.md
  reference/tools/ticdc/deploy.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/from-docs

#2977 add param value for 'tidb_replica_read'
  reference/performance/follower-read.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#2998 how-to/secure: remove some week cipher suits
  how-to/secure/enable-tls-clients.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#2933 *: fix typo for reload tls
  how-to/secure/enable-tls-clients.md
  reference/sql/statements/alter-instance.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/done, type/bug-fix

#2904 reference/tools: add warning for deprecated loader
  reference/tools/loader.md
  reference/tools/tidb-lightning/tidb-backend.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2, translation/doing

#2993 tiup: refine expressions in playground.md
  reference/tools/tiup/playground.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/doing

#2986 reference: add a description in the mysql-compatibility doc
  reference/mysql-compatibility.md
Labels: contribution, needs-cherry-pick-3.1, status/can-merge, translation/welcome

#2976 tiup: fix typo in bench.md and cluster.md
  reference/tools/tiup/bench.md
  reference/tools/tiup/cluster.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done

#3016 releases: add 3.0.14 release notes
  TOC.md
  releases/3.0.14.md
  releases/rn.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/done

#2994 reference/configuration: update configure file reference for distinct-agg-push-down
  reference/configuration/tidb-server/configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3011 sql: introduce invisible index
  reference/mysql-compatibility.md
  reference/sql/statements/add-index.md
  reference/sql/statements/alter-index.md
  reference/sql/statements/alter-table.md
  reference/sql/statements/create-index.md
  reference/sql/statements/create-table.md
  reference/sql/statements/drop-index.md
  reference/sql/statements/rename-index.md
  reference/sql/statements/show-indexes.md
  reference/system-databases/information-schema.md
Labels: size/large, status/LGT2, translation/doing

#3024 cdc: update address and advertise address
  reference/tools/ticdc/deploy.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3023 add explaination about `last_plan_from_cache`
  reference/configuration/tidb-server/tidb-specific-variables.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, status/require-change, translation/doing

#3029 tiup: add -p flag on deploy incluster.md
  reference/tools/tiup/cluster.md
Labels: needs-cherry-pick-4.0, translation/done

#3032 TiUP: improve expressions in mirrors.md and package-component.md
  reference/tools/tiup/mirrors.md
  reference/tools/tiup/package-component.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/done, type/bug-fix

#3015 reference/tools: update lightning, syncer docs
  reference/tools/syncer.md
  reference/tools/tidb-lightning/deployment.md
  reference/tools/tidb-lightning/overview.md
  reference/tools/tidb-lightning/tidb-backend.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/doing

#3037 how-to/monitor: change the image format for better doc maintenance
  how-to/monitor/key-visualizer.md
Labels: needs-cherry-pick-4.0, size/small, translation/doing

#3039 reference/performance: reorder tikv tuning log parameters #2948
  reference/performance/tune-tikv.md
Labels: size/small, translation/doing

#3040 releases: add a note to tidb 3.0.14 release notes
  releases/3.0.14.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/done

#2494 reference/titan: add titan docs
  TOC.md
  media/titan/titan-1.png
  media/titan/titan-2.png
  media/titan/titan-3.png
  media/titan/titan-4.png
  media/titan/titan-5.png
  media/titan/titan-6.png
  media/titan/titan-7.png
  reference/titan/configuration.md
  reference/titan/overview.md
Labels: needs-cherry-pick-4.0, size/large, status/can-merge, translation/doing

#2746 tools: update use limit for sync-diff-inspector
  reference/tools/sync-diff-inspector/overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#2955 how-to/troubleshoot: add TiDB diagnose map
  TOC.md
  how-to/troubleshoot/diagnose-map.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/large, translation/done

#3014 reference: add explanation for prepare-plan-cache-capacity type
  reference/configuration/tidb-server/configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, status/can-merge, translation/doing, type/enhancement

#3059 reference/sql: create index in json strings
  reference/sql/data-types/json.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/doing

#3056 reference: refine expressions in characterset-and-collation.md
  reference/sql/characterset-and-collation.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/done

#3026 reference/performance: add doc for rule max-min-eliminate
  TOC.md
  reference/performance/max-min-eliminate.md
  reference/performance/sql-optimizer-overview.md
Labels: needs-cherry-pick-4.0, status/can-merge, status/require-change, translation/doing

#3021 releases: add tidb release notes in 4.0.0-rc.1
  releases/4.0.0-rc.1.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/done

#2853 reference/sql: update data types
  TOC.md
  reference/sql/data-types/date-and-time.md
  reference/sql/data-types/json.md
  reference/sql/data-types/numeric.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/from-docs

#3046 doc: add auto_id_cache table option explanation
  reference/mysql-compatibility.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, status/require-change, translation/welcome

#3068 toc: add `alter-instance` in toc
  TOC.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/can-merge, translation/done

#3070 Update tiup.md change capactiy to capacity.
  how-to/deploy/orchestrated/tiup.md
Labels: follow-up, status/can-merge, translation/doing

#2644 reference/performance: elaborate more on optimizer hints
  reference/performance/optimizer-hints.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/PTAL, status/can-merge, translation/doing

#3065 br: remove confusing concurrency
  reference/tools/br/br.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge

#2939 releases: add deprecated note in title
  releases/3.0.10.md
  releases/3.0.11.md
  releases/3.0.12.md
  releases/3.0.9.md
  releases/3.1.0-beta.2.md
  releases/3.1.0-rc.md
  releases/4.0.0-rc.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/done

#3088 how-to/deploy: fix a typo
  how-to/deploy/orchestrated/tiup.md
Labels: contribution, size/small, status/can-merge, translation/doing, type/bug-fix

#2975 reference: fix split region doc mistake
  reference/sql/statements/split-region.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, status/require-change, translation/doing

#3087 reference: fix some mistakes about transaction isolation
  follower-read.md
  transaction-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, translation/doing

#2762 reference: add new option for tidb_replica_read
  follower-read.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/PTAL, translation/from-docs

#2857 reference: add documents about Coprocessor cache
  TOC.md
  coprocessor-cache.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/large, translation/doing, v4.0

#3109 reference/performance: fix an anchor
  coprocessor-cache.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing, type/bug-fix

#3104 tools/br: add explanation for copying SSTs file
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/from-docs

#3115 how-to/deploy: fix typos
  production-deployment-using-tiup.md
Labels: contribution, size/small, translation/doing

#3113 how-to/deploy: fix typos
  production-deployment-using-tiup.md
Labels: contribution, size/small, status/can-merge, translation/doing

#2848 execution-plan-bind: update document for sql bind
  execution-plan-binding.md
Labels: needs-cherry-pick-4.0, status/can-merge, status/require-change, translation/doing, type/enhancement

#2985 br: add incremental recover/backup.
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/PTAL, status/can-merge, translation/doing

#3119 Update hardware-and-software-requirements.md
  hardware-and-software-requirements.md
Labels: contribution, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3103 TiFlash: Add some notes about hint on table alias name
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2, status/PTAL, translation/doing

#3125 Update hardware-and-software-requirements.md
  hardware-and-software-requirements.md
Labels: status/can-merge, translation/doing

#3114 README.md: remove outdated file path description
  README.md
  media/contribution-map.png
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/done

#3117 releases: add 4.0.0-rc.2 release notes
  TOC.md
  releases/release-4.0.0-rc.2.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, translation/done

#3133 releases: fix typos in 4.0.0-rc.2
  releases/release-4.0.0-rc.2.md
Labels: needs-cherry-pick-4.0, translation/done, type/bug-fix

#3135 releases: fix an unclear note in 4.0.0-rc.2
  releases/release-4.0.0-rc.2.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done

#3149 perf-tuning：adjust the structure of the `SQL tuning` section
  TOC.md
  agg-distinct-optimization.md
  blacklist-control-plan.md
  column-pruning.md
  control-execution-plan.md
  correlated-subquery-optimization.md
  index-choose.md
  partition-pruning.md
  predicate-push-down.md
  query-execution-plan.md
  sql-logical-optimization.md
  sql-optimization-concepts.md
  sql-physical-optimization.md
  sql-tuning-overview.md
  statistics-intro.md
  subquery-optimization.md
  topn-limit-push-down.md
  wrong-index-solution.md
Labels: special-week, status/LGT2, translation/welcome

#3161 TOC: add database tools section
  TOC.md
  faq/licensing-faq.md
Labels: special-week, translation/doing

#3153 Update command line flags for pd configruation
  command-line-flags-for-pd-configuration.md
Labels: special-week, translation/done

#3194 Remove tiflash section in old TOC (commented out) to prevent lint error
  TOC.md
Labels: special-week, status/PTAL, translation/welcome

#3164 Remove upgrade-tiflash.md
  tiflash/upgrade-tiflash.md
Labels: special-week, status/PTAL, status/require-change, translation/done, translation/welcome

#3175 sql-statements: update "admin" related statements
  media/sqlgram/AdminStmt.png
  sql-statements/sql-statement-admin.md
Labels: special-week, status/PTAL, translation/welcome

#3167 add tiflash faq
  faq/tidb-faq.md
  tiflash/tiflash-faq.md
Labels: special-week, status/PTAL, translation/welcome

#3176 Add lightning faq
  troubleshoot-tidb-lightning.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3213 .github: add three github action workflows
  .github/workflows/add-docs-sig-issue.yml
  .github/workflows/add-docs-sig-pr.yml
  .github/workflows/translation-welcome.yml
Labels: special-week, status/PTAL, translation/doing, translation/welcome

#3229 .github: update workflow to auto assign project
  .github/workflows/add-docs-sig-issue.yml
  .github/workflows/add-docs-sig-pr.yml
  .github/workflows/assign-to-project.yml
  .github/workflows/translation-welcome.yml
Labels: special-week, status/PTAL, translation/welcome

#3178 update tikv configuration about pessimistic transaction
  tikv-configuration-file.md
Labels: special-week, status/PTAL, translation/welcome

#3203 Add TiFlash performance tuning to TOC
  TOC.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3157 tuning: add tune-operating-system
  TOC.md
  tune-operating-system.md
Labels: special-week, status/LGT3, status/can-merge, translation/welcome

#3230 resources: update the Figma link
  resources/figma-quick-start-guide.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/can-merge, translation/no-need

#3205 add doc about tiflash command line flags
  tiflash/tiflash-command-line-flags.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3215 split to DDL DML DQL DCL sections
  basic-sql-operations.md
Labels: contribution, special-week, status/PTAL, translation/welcome

#3155 Update command line flags for tikv configruation
  command-line-flags-for-tikv-configuration.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3163 update mysql-compatibility.md & add auto-increment.md
  auto-increment.md
  auto-random.md
  mysql-compatibility.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3190 perf-tuning: Add document for column prune
  column-pruning.md
Labels: special-week, status/LGT2, status/PTAL, status/can-merge, translation/welcome

#3235 *: Update documents and sqlgrams with "alter" prefixed statements
  media/sqlgram/AlterDatabaseStmt.png
  media/sqlgram/AlterInstanceStmt.png
  media/sqlgram/AlterTableSpec.png
  media/sqlgram/AlterTableStmt.png
  media/sqlgram/AlterUserStmt.png
  media/sqlgram/AuthOption.png
  media/sqlgram/ColumnDef.png
  media/sqlgram/ColumnPosition.png
  media/sqlgram/Constraint.png
  media/sqlgram/ConstraintElem.png
  media/sqlgram/ConstraintKeywordOpt.png
  media/sqlgram/DatabaseOption.png
  media/sqlgram/IndexInvisible.png
  media/sqlgram/IndexKeyTypeOpt.png
  media/sqlgram/IndexNameAndTypeOpt.png
  media/sqlgram/IndexOption.png
  media/sqlgram/IndexOptionList.png
  media/sqlgram/IndexPartSpecification.png
  media/sqlgram/IndexPartSpecificationList.png
  media/sqlgram/IndexTypeName.png
  media/sqlgram/InstanceOption.png
  media/sqlgram/KeyOrIndex.png
  media/sqlgram/UserSpec.png
  media/sqlgram/UserSpecList.png
  media/sqlgram/Username.png
  resources/figma-quick-start-guide.md
  sql-statements/sql-statement-add-column.md
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-alter-database.md
  sql-statements/sql-statement-alter-index.md
  sql-statements/sql-statement-alter-instance.md
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-alter-user.md
Labels: follow-up, special-week, status/PTAL, status/can-merge, translation/welcome, v5.0

#3140 transaction-isolation-levels.md: update txn isolation
  transaction-isolation-levels.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3160 Update error-codes.md
  error-codes.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3159 Update tidb-specific-system-variables.md
  tidb-specific-system-variables.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3158 reference: Optimize documents about GC
  TOC.md
  garbage-collection-configuration.md
  garbage-collection-overview.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3209 add troubleshooting-writeconflict
  media/troubleshooting-write-conflict-kv-backoff-ops.png
  media/troubleshooting-write-conflict-kv-retry-duration.png
  media/troubleshooting-write-conflict-lock-resolve-ops.png
  troubleshoot-write-conflicts.md
Labels: special-week, status/LGT2, translation/welcome

#3146 reference: update constraints.md
  constraints.md
Labels: special-week, status/LGT1, status/can-merge, translation/welcome

#3236 update literal-values.md
  literal-values.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3201 perf-tuning: Update the doc of query-execution-plan
  index-merge.md
  query-execution-plan.md
Labels: special-week, status/LGT2, status/PTAL, status/can-merge, translation/welcome

#3238 Update configfile pd
  pd-configuration-file.md
Labels: special-week, status/PTAL, translation/welcome

#3305 reference: update the pd-ctl docs
  pd-control.md
Labels: special-week, status/PTAL, translation/welcome

#3181 perf-tuning: add document for predicate push down
  predicate-push-down.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3258 toc: remove /tidb-index.md
  TOC.md
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-create-index.md
  tidb-index.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3214 perf-tuning: add docs for DISTINCT optimizations
  agg-distinct-optimization.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3300 *: update some statements
  media/sqlgram/ColumnName.png
  media/sqlgram/CreateDatabaseStmt.png
  media/sqlgram/CreateIndexStmtUnique.png.bak
  media/sqlgram/DBName.png
  media/sqlgram/DatabaseOptionList.png
  media/sqlgram/DatabaseOptionListOpt.png
  media/sqlgram/DeallocateStmt.png
  media/sqlgram/DeallocateSym.png
  media/sqlgram/DropTableStmt.png
  media/sqlgram/Identifier.png
  media/sqlgram/IfNotExists.png
  media/sqlgram/IndexTypeOpt.png
  media/sqlgram/RestrictOrCascadeOpt.png
  media/sqlgram/TableNameList.png
  media/sqlgram/TableOrTables.png
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-change-column.md
  sql-statements/sql-statement-create-database.md
  sql-statements/sql-statement-drop-column.md
  sql-statements/sql-statement-drop-table.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3165 update transaction overview
  transaction-overview.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3260 update generate ssl doc
  enable-tls-between-components.md
  generate-self-signed-certificates.md
Labels: special-week, status/PTAL, translation/doing

#3187 perf-tuning: add introduction for prepare plan cache
  TOC.md
  sql-optimization-concepts.md
  sql-prepare-plan-cache.md
Labels: special-week, status/LGT1, status/can-merge, status/require-change, translation/welcome

#3255 Fix sql-statement: use, update, truncate, trace
  media/sqlgram/AssignmentList.png
  media/sqlgram/OptTable.png
  media/sqlgram/PriorityOpt.png
  media/sqlgram/TableName.png
  media/sqlgram/TableRef.png
  media/sqlgram/TableRefs.png
  media/sqlgram/TraceStmt.png
  media/sqlgram/TraceableStmt.png
  media/sqlgram/TruncateTableStmt.png
  media/sqlgram/UpdateStmt.png
  media/sqlgram/UseStmt.png
  media/sqlgram/WhereClauseOptional.png
  sql-statements/sql-statement-trace.md
  sql-statements/sql-statement-update.md
  sql-statements/sql-statement-use.md
Labels: special-week, status/LGT2, status/LGT3, status/PTAL, translation/welcome

#3202 update document of privilege management
  privilege-management.md
Labels: contribution, special-week, status/LGT2, status/LGT3, status/require-change, translation/welcome

#3173 perf-tuning: add index-choose.md
  index-choose.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3197 Add documentations for TiUP
  TOC.md
  tiup/tiup-cluster.md
  tiup/tiup-component-management.md
  tiup/tiup-documentation-guide.md
  tiup/tiup-faq.md
  tiup/tiup-overview.md
  tiup/tiup-package.md
  tiup/tiup-terminology-and-concepts.md
  tiup/tiup-troubleshooting-guide.md
Labels: special-week, status/PTAL, translation/welcome

#3148 update the tidb configuration document
  command-line-flags-for-tidb-configuration.md
  tidb-configuration-file.md
  tiup/tiup-troubleshooting-guide.md
Labels: special-week, status/LGT2, status/can-merge, status/require-change, translation/welcome

#3306 add shutdown statement
  media/sqlgram/ShutdownStmt.png
  sql-statements/sql-statement-shutdown.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3145 reference: update statement summary tables
  statement-summary-tables.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3195 Add Grafana monitoring content and update images
  grafana-overview-dashboard.md
  media/grafana_monitor_overview.png
  media/grafana_monitored_groups.png
  media/overview.png
  tidb-monitoring-framework.md
Labels: special-week, status/LGT2, status/LGT3, status/PTAL, status/can-merge, status/require-change, translation/welcome

#3302 perf-tuning: add doc for wrong index solution page
  wrong-index-solution.md
Labels: special-week, status/LGT2, status/LGT3, status/can-merge, status/require-change, translation/welcome

#3198 Add docs for rocksdb
  TOC.md
  media/tikv-rocksdb.png
  rocksdb/rocksdb-overview.md
Labels: special-week, status/PTAL, status/require-change, translation/welcome

#3298 update several sql statements
  media/sqlgram/CharsetKw.png
  media/sqlgram/CharsetName.png
  media/sqlgram/CharsetNameOrDefault.png
  media/sqlgram/DBName.png
  media/sqlgram/FieldsOrColumns.png
  media/sqlgram/SetNamesStmt.png
  media/sqlgram/ShowColumnsFilterable.png
  media/sqlgram/ShowCreateSequenceStmt.png
  media/sqlgram/ShowDatabaseNameOpt.png
  media/sqlgram/ShowLikeOrWhereOpt.png
  media/sqlgram/ShowStmt.png
  media/sqlgram/ShowTableAliasOpt.png
  media/sqlgram/StringName.png
  media/sqlgram/VariableAssignment.png
  media/sqlgram/VariableAssignmentList.png
  sql-statements/sql-statement-set-names.md
  sql-statements/sql-statement-show-columns-from.md
  sql-statements/sql-statement-show-create-sequence.md
Labels: special-week, status/LGT2, translation/welcome

#3308 add show config statement
  sql-statements/sql-statement-show-config.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3296 add & update several sql statements
  TOC.md
  media/sqlgram/ShowBuiltinsStmt.png
  media/sqlgram/ShowEnginesStmt.png
  media/sqlgram/ShowErrorsStmt.png
  sql-statements/sql-statement-show-builtins.md
  sql-statements/sql-statement-show-engines.md
  sql-statements/sql-statement-show-errors.md
Labels: special-week, status/LGT2, status/can-merge, status/require-change, translation/welcome

#3301 *: udpate `begin` and `commit` statements
  media/sqlgram/BeginTransactionStmt.png
  media/sqlgram/CompletionTypeWithinTransaction.png
  sql-statements/sql-statement-begin.md
  sql-statements/sql-statement-commit.md
Labels: special-week, status/LGT2, status/LGT3, status/can-merge, translation/welcome

#3223 perf-tuning: update docs for statistics
  TOC.md
  media/statistics-1.png
  sql-physical-optimization.md
  statistics-intro.md
  statistics.md
Labels: special-week, status/LGT3, status/can-merge, translation/welcome

#3257 Update tispark doc
  tispark-overview.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3312 update some syntax diagram
  media/sqlgram/AlterTableDropIndexSpec.png
  media/sqlgram/AlterTableDropIndexStmt.png
  media/sqlgram/FlashbackTableStmt.png
  media/sqlgram/FlashbackToNewName.png
  media/sqlgram/IfExists.png
  media/sqlgram/IgnoreOptional.png
  media/sqlgram/Int64Num.png
  media/sqlgram/NUM.png
  media/sqlgram/PartitionNameListOpt.png
  media/sqlgram/RecoverTableStmt.png
  media/sqlgram/RenameTableStmt.png
  media/sqlgram/RowValue.png
  media/sqlgram/ShowTableRegionStmt.png
  media/sqlgram/SplitOption.png
  media/sqlgram/SplitRegionStmt.png
  media/sqlgram/SplitSyntaxOption.png
  media/sqlgram/TableName.png
  media/sqlgram/TableToTable.png
  media/sqlgram/WhereClause.png
  media/sqlgram/WhereClauseOptional.png
  sql-statements/sql-statement-drop-index.md
  sql-statements/sql-statement-flashback-table.md
  sql-statements/sql-statement-recover-table.md
  sql-statements/sql-statement-show-table-regions.md
  sql-statements/sql-statement-split-region.md
Labels: special-week, status/LGT1, status/PTAL, translation/welcome

#3309 update several statements
  sql-statements/sql-statement-do.md
  sql-statements/sql-statement-set-variable.md
  sql-statements/sql-statement-show-variables.md
Labels: special-week, status/LGT2, status/LGT3, status/can-merge, status/require-change, translation/welcome

#3326 add document of `SHOW PLUGINS`
  sql-statements/sql-statement-show-plugins.md
Labels: special-week, status/LGT1, status/PTAL, translation/welcome

#3316 Add doc about next_row_id and profiles
  TOC.md
  sql-statements/sql-statement-show-profiles.md
  sql-statements/sql-statement-show-table-next-row-id.md
Labels: special-week, status/PTAL, translation/welcome

#3193 update comment-syntax.md
  auto-random.md
  comment-syntax.md
Labels: size/small, special-week, status/can-merge, translation/welcome

#3246 update keywords-and-reserved-words.md
  TOC.md
  keywords.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3189 update document of tidb-ctl
  tidb-control.md
Labels: special-week, status/LGT1, status/PTAL, status/can-merge, translation/welcome, version-split-changes-required

#3179 update the doc of view
  views.md
Labels: special-week, status/LGT1, status/PTAL, status/can-merge, translation/welcome

#3318 update functions-and-operator documents
  functions-and-operators/aggregate-group-by-functions.md
  functions-and-operators/json-functions.md
Labels: special-week, status/LGT1, status/PTAL, status/can-merge, translation/welcome

#3317 update some syntax diagram
  media/sqlgram/FlushOption.png
  media/sqlgram/FlushStmt.png
  media/sqlgram/LogTypeOpt.png
  media/sqlgram/NoWriteToBinLogAliasOpt.png
  media/sqlgram/TableNameListOpt.png
  media/sqlgram/WithReadLockOpt.png
  sql-statements/sql-statement-flush-tables.md
Labels: special-week, status/LGT2, status/PTAL, status/can-merge, translation/welcome

#3321 add syntax diagram for show stats_buckets
  media/sqlgram/SHOW_STATS_BUCKETS.png
  statistics.md
Labels: special-week, status/LGT3, status/can-merge, translation/welcome

#3191 perf-tuning: add docs for subquery optimizations
  correlated-subquery-optimization.md
  subquery-optimization.md
Labels: special-week, status/LGT2, status/LGT3, translation/welcome

#3170 perf-tuning: add docs for some overview pages for sql-tuning
  control-execution-plan.md
  media/sql-optimization.png
  query-execution-plan.md
  sql-logical-optimization.md
  sql-optimization-concepts.md
  sql-physical-optimization.md
  sql-tuning-overview.md
Labels: special-week, status/PTAL, status/can-merge, status/require-change, translation/welcome

#3323 update sql-statement-modify-column.md
  sql-statements/sql-statement-modify-column.md
Labels: special-week, status/LGT1, status/PTAL, status/can-merge, translation/welcome

#3279 add topology YAML template
  complex-cdc.yaml
  complex-mini.yaml
  complex-multi-instant.yaml
  complex-tidb-binlog.yaml
  complex-tiflash.yaml
  geo-redundancy-deployment.yaml
  simple-cdc.yaml
  simple-mini.yaml
  simple-multi-instant.yaml
  simple-tidb-binlog.yaml
  simple-tiflash.yaml
Labels: special-week, status/PTAL, status/require-change, translation/welcome

#3337 sql-statements:add drop-stats.md
  TOC.md
  sql-statements/sql-statement-drop-stats.md
  statistics.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3331 sql-statements: update create view and drop view
  sql-statements/sql-statement-create-view.md
  sql-statements/sql-statement-drop-table.md
  sql-statements/sql-statement-drop-view.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3184 perf-tuning: add document for partition pruning
  partition-pruning.md
Labels: special-week, status/LGT2, status/can-merge, translation/welcome

#3335 docs: add sql statement for load data
  sql-statements/sql-statement-load-data.md
Labels: special-week, status/LGT2, status/PTAL, status/can-merge, translation/welcome

#3196 Create monitor-deploy.md and tidb-monitoring-api.md
  TOC.md
  deploy-monitoring-services.md
  mysql-compatibility.md
  tidb-monitoring-api.md
Labels: special-week, status/LGT1, status/PTAL, translation/welcome

#3212 Update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: special-week, status/PTAL, status/require-change, translation/welcome

#3310 update several document related to privilege sql statement
  sql-statements/sql-statement-create-user.md
  sql-statements/sql-statement-drop-user.md
  sql-statements/sql-statement-flush-privileges.md
  sql-statements/sql-statement-grant-privileges.md
  sql-statements/sql-statement-revoke-privileges.md
  sql-statements/sql-statement-set-password.md
Labels: special-week, status/LGT1, status/PTAL, translation/welcome

#3171 update optimistic transaction
  optimistic-transaction.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#3304 *: update "change column" and some sqlgram
  media/sqlgram/ColumnName.png
  media/sqlgram/ColumnPosition.png
  media/sqlgram/IndexKeyTypeOpt.png
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-change-column.md
Labels: special-week, status/LGT2, status/PTAL, translation/welcome
