Repository pingcap/docs-cn, pull requests merged in 2020-07, with the labels that each got.

#3688 Add two missing links in TOC.md
  TOC.md
Labels: needs-cherry-pick-4.0, status/can-merge, status/require-change, translation/doing

#3839 tidb-lightning: add an alias
  tidb-lightning/tidb-lightning-overview.md
Labels: size/small, status/PTAL, status/can-merge, translation/no-need

#3838 loader-overview: add an alias
  loader-overview.md
Labels: size/small, status/PTAL, status/can-merge, translation/no-need

#3818 Fix overview wording
  overview.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, status/can-merge, translation/no-need

#3819 add config information
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, status/can-merge, translation/welcome

#3842 zh: Add operator version requirement for telemetry config
  telemetry.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, translation/done

#3832 Update store limit configuration
  configure-store-limit.md
Labels: status/can-merge, translation/doing

#3834 Add store limit guide
  configure-store-limit.md
Labels: translation/doing

#3646 br: add collation restriction
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3770 add SHARD_ROW_ID_BITS
  TOC.md
  best-practices/high-concurrency-best-practices.md
  faq/sql-faq.md
  shard-row-id-bits.md
  sql-statements/sql-statement-create-table.md
Labels: needs-cherry-pick-4.0, size/medium, status/can-merge, status/require-change, translation/doing

#3849 remove duplicate note in garbage-collection-configuration.md (#3807)
  garbage-collection-configuration.md
Labels: type/4.0-cherry-pick

#3767 Add 4.0.2 release note
  TOC.md
  releases/release-4.0.2.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, translation/from-docs

#3845 Fix typo in literal values
  literal-values.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/can-merge, translation/no-need

#3835 Add scripts to verify anchors
  .circleci/config.yml
  auto-random.md
  br/backup-and-restore-faq.md
  br/backup-and-restore-tool.md
  constraints.md
  dashboard/dashboard-faq.md
  dashboard/dashboard-ops-deploy.md
  dashboard/dashboard-ops-reverse-proxy.md
  dashboard/dashboard-ops-security.md
  error-codes.md
  faq/sql-faq.md
  functions-and-operators/aggregate-group-by-functions.md
  garbage-collection-configuration.md
  get-started-with-tidb-lightning.md
  glossary.md
  mysql-compatibility.md
  online-deployment-using-ansible.md
  quick-start-with-tidb.md
  scripts/verify-link-anchors.sh
  scripts/verify-links.sh
  sql-statements/sql-statement-add-column.md
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-commit.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-recover-table.md
  storage-engine/titan-configuration.md
  system-variables.md
  telemetry.md
  ticdc/ticdc-overview.md
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-binlog/handle-tidb-binlog-errors.md
  tidb-binlog/troubleshoot-tidb-binlog.md
  tidb-configuration-file.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-web-interface.md
  tidb-specific-system-variables.md
  tidb-troubleshooting-map.md
  tiflash/troubleshoot-tiflash.md
  tiflash/tune-tiflash-performance.md
  troubleshoot-lock-conflicts.md
  upgrade-tidb-using-ansible.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/doing, type/enhancement

#3856 Add scripts to verify anchors (#3835)
  .circleci/config.yml
  constraints.md
  faq/tidb-faq.md
  glossary.md
  mysql-compatibility.md
  offline-deployment-using-ansible.md
  online-deployment-using-ansible.md
  optimistic-transaction.md
  scripts/verify-link-anchors.sh
  scripts/verify-links.sh
  sql-statements/sql-statement-commit.md
  sql-statements/sql-statement-recover-table.md
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-web-interface.md
  tidb-troubleshooting-map.md
  upgrade-tidb-using-ansible.md
Labels: type/3.0-cherry-pick

#3855 Add scripts to verify anchors (#3835)
  .circleci/config.yml
  auto-random.md
  br/backup-and-restore-faq.md
  br/backup-and-restore-tool.md
  constraints.md
  faq/tidb-faq.md
  glossary.md
  mysql-compatibility.md
  offline-deployment-using-ansible.md
  online-deployment-using-ansible.md
  optimistic-transaction.md
  scripts/verify-link-anchors.sh
  scripts/verify-links.sh
  sql-statements/sql-statement-commit.md
  sql-statements/sql-statement-recover-table.md
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-web-interface.md
  tidb-troubleshooting-map.md
  upgrade-tidb-using-ansible.md
Labels: status/LGT1, type/3.1-cherry-pick

#3857 Add scripts to verify anchors (#3835)
  .circleci/config.yml
  constraints.md
  faq/tidb-faq.md
  glossary.md
  mysql-compatibility.md
  online-deployment-using-ansible.md
  optimistic-transaction.md
  scripts/verify-link-anchors.sh
  scripts/verify-links.sh
  sql-statements/sql-statement-commit.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-web-interface.md
  upgrade-tidb-using-ansible.md
Labels: status/LGT1, status/can-merge, type/2.1-cherry-pick

#3817 Update tune-tikv-memory-performance.md
  tune-tikv-memory-performance.md
  tune-tikv-thread-performance.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, status/can-merge, translation/done

#3745 ticdc: add doc about config
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3577 faq: update mysql8 client fail to connect tidb
  faq/tidb-faq.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/can-merge, translation/done

#3867 Update tidb-limitations.md
  tidb-limitations.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/no-need, type/bug-fix

#3868 Update whats-new-in-tidb-4.0.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#3799 add the docs about rebalance for ticdc
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3877 deploy: add aliases for tiflash deployment
  production-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/done, version-split-changes-required

#3879 dev/dashboard: fix a broken link
  dashboard/dashboard-ops-reverse-proxy.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done

#3847 Add TiDB v3.0.16 release notes
  TOC.md
  releases/release-3.0.16.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2, translation/from-docs

#3881 Fix a broken link
  tikv-control.md
Labels: size/small, status/LGT1, translation/no-need

#3883 Fix a broken link
  tikv-control.md
Labels: size/small, status/LGT1, status/can-merge, translation/no-need

#3823 Reference TiDB Dashboard intro for TiDB Dashboard links
  best-practices/tidb-best-practices.md
  daily-check.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  telemetry.md
  tidb-architecture.md
  tidb-best-practices.md
  tiflash/use-tiflash.md
  tiup/tiup-cluster.md
  tiup/tiup-playground.md
  troubleshoot-hot-spot-issues.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, status/can-merge, translation/doing

#3866 Update tiup-cluster.md
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, status/can-merge, translation/welcome

#3828 Add HAProxy instructions for TiDB Dashboard
  dashboard/dashboard-faq.md
  dashboard/dashboard-ops-deploy.md
  dashboard/dashboard-ops-reverse-proxy.md
  dashboard/dashboard-ops-security.md
Labels: needs-cherry-pick-4.0, size/medium, status/can-merge, translation/welcome

#3833 Add store limit guide
  TOC.md
  configure-store-limit.md
Labels: status/LGT1, status/can-merge, translation/done, type/3.1-cherry-pick

#3891 toc: add store limit to toc
  TOC.md
Labels: status/LGT1, translation/done, type/bug-fix

#3814 tools: add shard table's check by table-rules for diff
  media/shard-table-sync-1.png
  media/shard-table-sync-2.png
  media/shard-table-sync.png
  sync-diff-inspector/shard-diff.md
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/medium, status/LGT1, translation/doing

#3806 lightning: add local backend configuration
  tidb-lightning/tidb-lightning-configuration.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/doing, type/enhancement

#3898 Readme: change 4.0 branch description
  README.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/done

#3893 Update the producation-offline-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3820 Update TOC.md
  TOC.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/welcome

#3905 Add aliases for 3.0 sysbench docs
  benchmark/v3.0-performance-benchmarking-with-sysbench.md
  benchmark/v3.0-performance-benchmarking-with-tpcc.md
Labels: size/small, status/LGT1, status/require-change, translation/from-docs

#3477 comment-syntax: add TiDB-specific comment syntax
  comment-syntax.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/can-merge, translation/doing

#3906 br: update version
  br/backup-and-restore-use-cases.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/doing

#3914 chore: fix unclosed tag
  dumpling-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#3904 toc: remove 3.0 tests from 4.0 toc
  TOC.md
  benchmark/v3.0-performance-benchmarking-with-sysbench.md
  benchmark/v3.0-performance-benchmarking-with-tpcc.md
Labels: size/small, status/LGT1, translation/done, type/enhancement

#3829 Fix typos in 3 DC in 2 cities deployment doc
  three-data-centers-in-two-cities-deployment.md
  tune-operating-system.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, status/can-merge, translation/done, type/bug-fix

#3918 Add missing aliases for binlog docs
  loader-overview.md
  tidb-binlog/get-started-with-tidb-binlog.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix, version-split-changes-required

#3920 Update loader-overview.md
  loader-overview.md
Labels: size/small, status/LGT1, translation/no-need

#3708 Update --proxy-protocol-networks parameter description
  command-line-flags-for-tidb-configuration.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/doing

#3909 ticdc: correct command line for cyclic replication
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/done

#3924 docs: fix typo
  max-min-eliminate.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/LGT1, translation/welcome

#3923 Update identify-slow-queries.md&statement-summary-tables.md
  identify-slow-queries.md
  statement-summary-tables.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/PTAL, status/can-merge, translation/doing

#3930 Update tidb-configuration-file.md
  tidb-configuration-file.md
Labels: status/LGT2, status/PTAL, translation/welcome

#3934 perf-tuning: update anchors in wrong-index-solution
  wrong-index-solution.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/done

#3859 Update tiflash links
  _index.md
  tiflash/tiflash-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, status/can-merge, status/require-change, translation/doing

#3946 Fix a broken link
  query-execution-plan.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, size/small, status/LGT1, translation/no-need

#3916 *: replace black-white-list by table filter
  TOC.md
  br/backup-and-restore-tool.md
  dumpling-overview.md
  table-filter.md
  ticdc/manage-ticdc.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-glossary.md
  tidb-lightning/tidb-lightning-table-filter.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/large, status/LGT1, status/can-merge, translation/from-docs, version-specific-changes-required

#3945 Fix a broken link
  query-execution-plan.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/no-need

#3925 br, sql-statements: document BACKUP, RESTORE and SHOW [BACKUPS|RESTORES]
  TOC.md
  br/backup-and-restore-storages.md
  media/sqlgram/BackupOption.png
  media/sqlgram/BackupStmt.png
  media/sqlgram/BackupTSO.png
  media/sqlgram/RestoreOption.png
  media/sqlgram/RestoreStmt.png
  media/sqlgram/ShowBRIEStmt.png
  media/sqlgram/ShowLikeOrWhereOpt.png
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
  sql-statements/sql-statement-show-backups.md
Labels: needs-cherry-pick-4.0, size/large, status/can-merge, translation/from-docs

#3744 Add description for isolationLevel
  tispark-overview.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3955 tidb-lightning: delete tidb-lightning-table-filter.md
  tidb-lightning/tidb-lightning-table-filter.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT1, translation/no-need

#3927 Update complex-tiflash.yaml
  config-templates/complex-tiflash.yaml
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/done

#3941 add tiflash store limit config version change warning
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/can-merge, translation/doing

#3960 Delete tidb-lightning-table-filter.md
  tidb-lightning/tidb-lightning-table-filter.md
Labels: status/LGT1, status/can-merge, translation/no-need

#3961 update default value description for oom-action
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/doing

#3928 Add encryption-at-rest document
  TOC.md
  encryption-at-rest.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/from-docs

#3882 ticdc: add more faq
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/medium, status/LGT1, status/can-merge, translation/doing

#3788 cdc: remove allow/black list restriction, will add detail usage later
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT2, status/PTAL, translation/no-need

#3970 Optimize description and add missing links
  blacklist-control-plan.md
  troubleshoot-hot-spot-issues.md
Labels: follow-up, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge

#3972 Optimize description and add missing links
  blacklist-control-plan.md
Labels: needs-cherry-pick-3.0, require-LGT1, size/small, status/LGT1, status/can-merge

#3980 tikv-configuration-file: correct the default value of `hibernate_regions`
  tikv-configuration-file.md
Labels: size/small, status/LGT1, translation/doing

#3982 tidb-config: remove useless note
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/doing

#3984 chore: update PDF name
  .circleci/config.yml
Labels: status/LGT1, translation/no-need

#3981 remove a doc that is not in TOC
  TOC.md
  architecture.md
  check-cluster-status-using-sql-statements.md
  faq/sql-faq.md
  faq/tidb-faq.md
  system-tables/system-table-sql-diagnostics.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-lightning/tidb-lightning-misuse-handling.md
  troubleshoot-tidb-lightning.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/doing, version-specific-changes-required

#3969 Add note about default-auth for MySQL 8.0 clients
  connectors-and-apis.md
  security-compatibility-with-mysql.md
  tidb-specific-system-variables.md
  user-account-management.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/from-docs

#3991 Remove 2 broken links
  troubleshoot-cpu-issues.md
Labels: needs-cherry-pick-4.0, size/small, translation/no-need

#3986 Update expression-syntax.md
  expression-syntax.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, version-specific-changes-required

#3974 update dumpling argument list
  dumpling-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#3995 Update pd-control.md
  pd-control.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/done

#4000 Update 'tiup cluster edit-config' documentation
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#3996 fix: text error
  mysql-compatibility.md
Labels: contribution, needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix

#3993 ticdc: refine the docs about the status in cdc
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4007 .github: disable 3 github actions
  .github/workflows/assign-to-project.yml
  .github/workflows/auto-assign.yml
  .github/workflows/auto-label.yml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/from-docs, version-specific-changes-required

#4005 faq: update descriptions about deploying TiDB on cloud
  faq/tidb-faq.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/no-need, type/bug-fix

#4015 Update production-offline-deployment-using-tiup.md link
  production-offline-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/doing

#4017 Update use tiflash for v4.0.3
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/done

#4006 faq: update descriptions about deploying TiDB on cloud
  faq/tidb-faq.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, size/small, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#4014 Add a note for `oom-action`
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#3922 ticdc: correct command line for cyclic replication
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/no-need

#4013 Make terms about production environment consistent
  check-before-deployment.md
  faq/deploy-and-maintain-faq.md
  storage-engine/titan-configuration.md
Labels: needs-cherry-pick-4.0, status/LGT1

#4028 delete github action config files
  .github/assign-by-files.yml
  .github/auto-label.json
  .github/workflows/assign-to-project.yml
  .github/workflows/auto-assign.yml
  .github/workflows/auto-label.yml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#4001 sys_var: merge sys_vars with tidb specific sys_vars
  TOC.md
  agg-distinct-optimization.md
  best-practices/tidb-best-practices.md
  dashboard/dashboard-overview.md
  dashboard/dashboard-slow-query.md
  faq/sql-faq.md
  identify-expensive-queries.md
  partitioned-table.md
  pessimistic-transaction.md
  query-execution-plan.md
  releases/release-2.1.18.md
  sql-mode.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-show-variables.md
  sql-statements/sql-statement-split-region.md
  subquery-optimization.md
  system-variables.md
  telemetry.md
  tidb-best-practices.md
  tidb-configuration-file.md
  tidb-specific-system-variables.md
  tiflash/tune-tiflash-performance.md
  transaction-overview.md
  troubleshoot-lock-conflicts.md
Labels: size/large, status/LGT2, status/PTAL, status/can-merge, translation/from-docs, version-specific-changes-required

#4035 Update optimistic-transaction: remove reference to being "default"
  optimistic-transaction.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#3967 ticdc: update v4.0.3 changes
  enable-tls-between-components.md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4040 tools: update some description about tidb-binlog and sync-diff-inspector
  sync-diff-inspector/sync-diff-inspector-overview.md
  tidb-binlog/tidb-binlog-faq.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, translation/doing

#4045 fix aliases in system-variables.md
  system-variables.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#3978 release: add TiDB 4.0.3 release notes
  TOC.md
  releases/release-4.0.3.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, require-LGT1, status/LGT1, translation/from-docs

#4025 TiDB Lightning: Modify the description of routes label
  tidb-lightning/tidb-lightning-tidb-backend.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4054 Add index-merge.md aliases to query-execution-plan.md
  query-execution-plan.md
Labels: needs-cherry-pick-4.0, require-LGT1, special-week, status/LGT1, translation/done, version-specific-changes-required

#4049 functions-and-operators: Update JSON functions
  functions-and-operators/json-functions.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/can-merge, translation/from-docs

#4050 Add a link in `CREATE INDEX` sql document
  sql-statements/sql-statement-create-index.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4058 Update Dashboard Doc
  pd-configuration-file.md
  telemetry.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/can-merge, translation/doing

#4057 tikv: document backup.num-threads config
  tikv-configuration-file.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4059 sql-statement-explain-analyze: add note for explain analyze with DML
  sql-statements/sql-statement-explain-analyze.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/can-merge, translation/doing

#3697 Remove sync-log=false from how to run sysbench
  benchmark/benchmark-tidb-using-sysbench.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4033 Update troubleshoot-lock-conflicts.md
  credits.md
  troubleshoot-lock-conflicts.md
Labels: needs-cherry-pick-4.0, require-LGT1, translation/done

#4070 Align updates from en to optimizer-hints.md
  optimizer-hints.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#3686 add some details to comment-syntax.md
  comment-syntax.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, translation/doing

#4076 Fix some issues: add alias; fix wrong content
  system-tables/system-table-information-schema.md
  system-tables/system-table-sql-diagnostics.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/done, version-specific-changes-required

#4027 sql-mode: update compatibility
  TOC.md
  mysql-compatibility.md
  sql-mode.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, status/can-merge, translation/from-docs

#3428 Mydumper: add faq about tz
  mydumper-overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, translation/doing

#3420 Unify the calculation of defaultCF - block-cache-size
  tikv-configuration-file.md
Labels: contribution, size/small, status/LGT1, status/can-merge, translation/doing

#4086 Unify the calculation of defaultCF - block-cache-size
  tikv-configuration-file.md
Labels: require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing, type/enhancement

#4087 toc, index: add K8s deployment
  TOC.md
  _index.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/from-docs

#4047 Update FAQs
  faq/deploy-and-maintain-faq.md
  faq/sql-faq.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, status/require-change, translation/from-docs

#4081 Reorganize "Date and Time Types" doc
  data-type-date-and-time.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/done, type/enhancement

#3587 Fix typos in Dashboard documents
  dashboard/dashboard-access.md
  dashboard/dashboard-diagnostics-report.md
  dashboard/dashboard-diagnostics-usage.md
  dashboard/dashboard-faq.md
  dashboard/dashboard-ops-deploy.md
Labels: needs-cherry-pick-4.0, status/LGT2, translation/no-need

#3704 Update tidb-lightning-tidb-backend
  tidb-lightning/tidb-lightning-tidb-backend.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT1, translation/doing

#4106 Fix typos in TiDB back-end doc
  tidb-lightning/tidb-lightning-tidb-backend.md
Labels: size/small, status/LGT1, translation/doing

#3612 best-practices: add best practice for 3 nodes hybrid deployment
  TOC.md
  best-practices/three-nodes-hybrid-deployment.md
  media/best-practices/three-nodes-default-config-qps.png
  media/best-practices/three-nodes-final-config-qps.png
  media/best-practices/three-nodes-gc-impact.png
  media/best-practices/three-nodes-grpc-pool-usage.png
  media/best-practices/three-nodes-scheduler-pool-usage.png
Labels: needs-cherry-pick-4.0, size/large, status/LGT3, status/can-merge, translation/doing

#3652 Change the way of modifying version numbers (tiup)
  faq/high-reliability-faq.md
Labels: contribution, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/doing

#3702 add explaination about `last_plan_from_binding`
  system-variables.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/doing

#4102 Update FAQs
  faq/tidb-faq.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, size/small, status/LGT1, translation/from-docs

#4104 Add IsolationLevel introduction for PD
  configure-placement-rules.md
  pd-configuration-file.md
  pd-control.md
  schedule-replicas-by-topology-labels.md
Labels: contribution, size/large, status/LGT1, translation/done, v5.0

#3470 update document for system-table-information-schema.md
  system-tables/system-table-information-schema.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/doing

#4121 Update backup-and-restore-tool.md
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/from-docs

#4119 sql-statements: improve load data
  sql-statements/sql-statement-load-data.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#3058 reference/configuration: add a guide about how to use dynamic config
  TOC.md
  dynamic-config.md
Labels: needs-cherry-pick-4.0, size/large, status/LGT3, status/can-merge, translation/doing, v4.0

#4129 Update backup-and-restore-tool.md
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/from-docs

#3749 Update the version description in auto random document
  auto-random.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#3965 ticdc: update the doc link of filter rule
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, status/require-change, translation/doing

#3963 tiup: add document of tispark support in tiup cluster
  TOC.md
  config-templates/complex-tispark.yaml
  config-templates/simple-tispark.yaml
  production-deployment-using-tiup.md
  tispark-deployment-topology.md
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, priority/P1, require-LGT1, size/medium, status/LGT1, status/can-merge, status/require-change, translation/doing, type/enhancement

#3434 update doc for split region
  best-practices/high-concurrency-best-practices.md
  sql-statements/sql-statement-split-region.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/doing

#3480 update describe of auto-increment
  mysql-compatibility.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, status/require-change, translation/doing

#3419 clarify an ambiguous sentence in sysbench report
  benchmark/benchmark-tidb-using-sysbench.md
Labels: contribution, size/small, status/LGT1, status/can-merge, translation/doing

#4137 Clarify an ambiguous sentence in sysbench report
  benchmark/benchmark-tidb-using-sysbench.md
Labels: require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4096 Update dumpling-overview.md
  backup-and-restore-using-dumpling-lightning.md
  backup-and-restore-using-mydumper-lightning.md
  dumpling-overview.md
Labels: needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/done

#4120 release: add TiDB 4.0.4 release notes
  TOC.md
  releases/release-4.0.4.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#4135 partitioning: update docs
  partition-pruning.md
  partitioned-table.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/require-change, translation/no-need

#3943 Add experimental-features.md
  TOC.md
  auto-random.md
  experimental-features-4.0.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing
