Repository pingcap/docs-cn, pull requests merged in 2020-06, with the labels that each got.

#3416 update deploy document to v4.0.0
  post-installation-check.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, translation/doing

#3423 Update character-set-and-collation.md
  character-set-and-collation.md
Labels: needs-cherry-pick-4.0, size/small, translation/doing

#3396 Add warning about using tiflash in read write txn
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3411 TiFlash: Add FAQ for TiFlash trouble-shooting when failed to start
  tiflash/troubleshoot-tiflash.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/can-merge, translation/doing

#3417 Update production-deployment-using-tiup.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  quick-start-with-tidb.md
  tiup/tiup-component-management.md
  tiup/tiup-overview.md
  tiup/tiup-package.md
  tiup/tiup-terminology-and-concepts.md
  tiup/tiup-troubleshooting-guide.md
Labels: needs-cherry-pick-4.0, status/can-merge, status/require-change, translation/doing

#3429 add `require SAN` to certificate authentication docs
  certificate-authentication.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3442 BR: fix a title with bracket
  br/backup-and-restore-faq.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3446 toc: add coprocessor cache to toc
  TOC.md
Labels: needs-cherry-pick-4.0, size/small, translation/no-need

#3436 Update mysql-compatibility.md
  mysql-compatibility.md
Labels: status/can-merge, translation/doing

#3448 add descriptions about new params for plan cache
  statement-summary-tables.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/can-merge

#3449 add descriptions about binding source
  execution-plan-binding.md
  sql-statements/sql-statement-show-bindings.md
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge, translation/doing

#3425 update TiUP offline deployment; rename tiup mirrors to tiup mirror
  TOC.md
  maintain-tidb-using-tiup.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  tiflash/deploy-tiflash.md
  tikv-control.md
  tiup/tiup-cluster.md
  tiup/tiup-documentation-guide.md
  tiup/tiup-faq.md
  tiup/tiup-mirror.md
  tiup/tiup-mirrors.md
  tiup/tiup-overview.md
  tiup/tiup-package.md
  tiup/tiup-troubleshooting-guide.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge, translation/doing

#3421 tidb-configuration-file: change the meaning of max-memory back
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/can-merge, translation/doing

#3452 Add v4.0 sysbench and TPC-C benchmark report
  TOC.md
  benchmark/benchmark-sysbench-v4-vs-v3.md
  benchmark/v4.0-performance-benchmarking-with-tpcc.md
  benchmark/v4.0-performance-benchmarking-with-tpch.md
  media/sysbench_v4vsv3_point_select.png
  media/sysbench_v4vsv3_read_write.png
  media/sysbench_v4vsv3_update_index.png
  media/sysbench_v4vsv3_update_non_index.png
  media/tpcc_v4vsv3.png
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3461 Update v4.0-performance-benchmarking-with-tpch.md
  benchmark/v4.0-performance-benchmarking-with-tpch.md
Labels: size/small, status/can-merge, translation/no-need

#3460 tiup: fix wrong aliases of tiup mirror in release-4.0
  tiup/tiup-mirror.md
Labels: status/can-merge, translation/no-need

#3426 Update go version
  pd-control.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, size/small, status/LGT1, status/can-merge, translation/from-docs

#3463 remove invalid tiup cmd
  production-offline-deployment-using-tiup.md
  tiup/tiup-mirror.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/doing

#3462 Fix typos in 4.0 test report
  benchmark/benchmark-sysbench-v4-vs-v3.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done, type/bug-fix

#3431 TiFlash: Add TiFlash edit-config instruction after manually scaled in TiFlash nodes
  scale-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, translation/doing

#3471 Add tiup upgrade 4.0
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/can-merge, translation/doing

#3473 style: format indent
  quick-start-with-tidb.md
Labels: needs-cherry-pick-4.0, translation/doing

#3478 remove code tag from folder level
  TOC.md
Labels: needs-cherry-pick-4.0

#3481 troubleshooting: fix two typos in tidb-troubleshooting-map.md
  tidb-troubleshooting-map.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/no-need

#3450 docs-cn: add SPM feature in sql bindings doc
  TOC.md
  control-execution-plan.md
  sql-plan-management.md
  sql-statements/sql-statement-admin.md
  tidb-specific-system-variables.md
  wrong-index-solution.md
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge, translation/doing

#3476 update deploy document
  TOC.md
  geo-distributed-deployment-topology.md
  hybrid-deployment-topology.md
  minimal-deployment-topology.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  ticdc-deployment-topology.md
  tidb-binlog-deployment-topology.md
  tiflash-deployment-topology.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3492 Remove output sample of `TRACE` because it's too long
  sql-statements/sql-statement-trace.md
Labels: needs-cherry-pick-4.0, translation/welcome

#3496 correct heading levels
  production-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, translation/doing, type/bug-fix

#3495 toc: remove links at folder level
  TOC.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, size/small, translation/no-need

#3501 releases: remove tiup version
  releases/release-3.0.13.md
  releases/release-3.0.14.md
Labels: translation/from-docs, type/bug-fix

#3440 Add more Dashboard docs
  TOC.md
  dashboard/dashboard-access.md
  dashboard/dashboard-cluster-info.md
  dashboard/dashboard-diagnostics-access.md
  dashboard/dashboard-diagnostics-report.md
  dashboard/dashboard-diagnostics-usage.md
  dashboard/dashboard-faq.md
  dashboard/dashboard-intro.md
  dashboard/dashboard-key-visualizer.md
  dashboard/dashboard-log-search.md
  dashboard/dashboard-ops-deploy.md
  dashboard/dashboard-ops-reverse-proxy.md
  dashboard/dashboard-ops-security.md
  dashboard/dashboard-overview.md
  dashboard/dashboard-profiling.md
  dashboard/dashboard-slow-query.md
  dashboard/dashboard-statement-details.md
  dashboard/dashboard-statement-list.md
  media/dashboard/dashboard-intro.gif
  media/dashboard/dashboard-ops-multiple-pd.svg
  media/dashboard/dashboard-overview-monitor.png
  media/dashboard/dashboard-slow-queries-access.png
  media/dashboard/dashboard-slow-queries-detail1.png
  media/dashboard/dashboard-slow-queries-detail2.png
  media/dashboard/dashboard-slow-queries-list1.png
  media/dashboard/dashboard-slow-queries-list2.png
  media/dashboard/dashboard-slow-queries-list3.png
Labels: needs-cherry-pick-4.0, size/large, status/can-merge, translation/doing

#3486 quick start: add an "explore more" section
  quick-start-with-tidb.md
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge, translation/doing

#3508 fix one typo in tune-tiflash-performance.md
  tiflash/tune-tiflash-performance.md
Labels: needs-cherry-pick-4.0, translation/doing

#3491 Update tiflash-configuration.md
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done

#3497 reference: refine the ecosystem tools user guide
  TOC.md
  ecosystem-tool-user-case.md
  ecosystem-tool-user-guide.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#3514 update daily-inspection.md
  daily-inspection.md
Labels: needs-cherry-pick-4.0, translation/done

#3510 releases: add 3.0.15 release notes
  TOC.md
  releases/release-3.0.15.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/done

#3519 reference refine the ecosystem tools user guide
  TOC.md
  ecosystem-tool-user-case.md
  ecosystem-tool-user-guide.md
  export-or-backup-using-dumpling.md
Labels: needs-cherry-pick-2.1, translation/doing, type/3.0-cherry-pick

#3527 zh: improve description for public cloud
  faq/tidb-faq.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/welcome

#3525 releases: add 4.0.0 GA release notes
  TOC.md
  releases/release-4.0-ga.md
  releases/release-notes.md
Labels: needs-cherry-pick-4.0, translation/done

#3535 Update expressions in daily-check.md
  TOC.md
  daily-check.md
  daily-inspection.md
  media/failed-query-panel.png
  media/garbage-collation-panel.png
  media/host-panel.png
  media/instance-status-panel.png
  media/kv-duration-panel.png
  media/overview-panel.png
  media/pd-duration-panel.png
  media/region-panel.png
  media/sql-analysis-panel.png
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done

#3537 add what's new in tidb 4.0
  TOC.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3457 deploy: fix issues in deployment docs
  check-before-deployment.md
  geo-distributed-deployment-topology.md
  hardware-and-software-requirements.md
  hybrid-deployment-topology.md
  post-installation-check.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/no-need

#3515 add doc for sql_select_limit
  system-variables.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3438 Update mysql-compatibility.md
  mysql-compatibility.md
Labels: contribution, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing, type/bug-fix

#3548 Fix typos in what's new in TiDB 4.0
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/no-need, type/bug-fix

#3542 Spread deploy tiflash to dedicated places
  hardware-and-software-requirements.md
  tiflash/deploy-tiflash.md
  tiflash/troubleshoot-tiflash.md
Labels: needs-cherry-pick-4.0, translation/doing

#3552 TiCDC: Update unsupported scenarios in ticdc-overview.md
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-4.0, translation/done

#3532 *: update using TiFlash in toc and index
  TOC.md
  _index.md
  production-deployment-using-tiup.md
  tiflash/maintain-tiflash.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3541 update dumpling backup document
  export-or-backup-using-dumpling.md
Labels: needs-cherry-pick-4.0, translation/doing

#3540 tiup/: add offline update tiup
  TOC.md
  export-or-backup-using-dumpling.md
  quick-start-with-tidb.md
  upgrade-tidb-using-tiup-offline.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3556 Update quick-start-with-tidb.md
  quick-start-with-tidb.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3494 maintain: clear up some expressions
  maintain-tidb-using-tiup.md
  scale-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done

#3459 system-tables: add a description for columns
  system-tables/system-table-information-schema.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/doing

#3568 dashboard: fix pic and typos in dashboard-overview.md
  dashboard/dashboard-overview.md
Labels: needs-cherry-pick-4.0, translation/no-need

#3570 Update maintain-tidb-using-tiup.md
  maintain-tidb-using-tiup.md
Labels: contribution, needs-cherry-pick-4.0, size/small, translation/doing

#3572 dashboard: convert svg to png
  dashboard/dashboard-ops-deploy.md
  media/dashboard/dashboard-ops-multiple-pd.png
  media/dashboard/dashboard-ops-multiple-pd.svg
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3574 Add missing tikv docs to TOC.md
  TOC.md
  storage-engine/rocksdb-overview.md
  storage-engine/titan-configuration.md
  storage-engine/titan-overview.md
Labels: needs-cherry-pick-4.0, status/require-change, translation/doing

#3507 secure: fix secure-related docs
  TOC.md
  _index.md
  certificate-authentication.md
  dashboard/dashboard-ops-security.md
  enable-tls-between-clients-and-servers.md
  enable-tls-between-components.md
  sql-statements/sql-statement-alter-instance.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done, version-split-changes-required

#3575 Add tispark into TOC
  TOC.md
  get-started-with-tispark.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3561 toc, index: add K8s deployment and update links
  TOC.md
  _index.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/no-need

#3588 glossary: add a term "Restore"
  glossary.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/can-merge, translation/welcome

#3602 tikv: update --adverties-status-addr
  command-line-flags-for-tikv-configuration.md
Labels: needs-cherry-pick-4.0, translation/doing

#3606 Update files in system-tables: add 'SQL' identifier in the execution result of SQL statement (#2847)
  system-tables/system-table-cluster-config.md
  system-tables/system-table-cluster-hardware.md
  system-tables/system-table-cluster-info.md
  system-tables/system-table-cluster-load.md
  system-tables/system-table-cluster-log.md
  system-tables/system-table-cluster-systeminfo.md
  system-tables/system-table-information-schema.md
  system-tables/system-table-inspection-result.md
  system-tables/system-table-inspection-summary.md
  system-tables/system-table-metrics-schema.md
  system-tables/system-table-metrics-summary.md
  system-tables/system-table-metrics-tables.md
Labels: contribution, needs-cherry-pick-4.0, translation/doing

#3609 add migrate-from-mysql-mydumper-files.md to TOC
  TOC.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, translation/from-docs

#3581 *: update expressions and add alias
  br/backup-and-restore-faq.md
  br/backup-and-restore-tool.md
  daily-check.md
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/no-need, version-split-changes-required

#3468 system-tables: add some descriptions for columns
  system-tables/system-table-information-schema.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/doing

#3600 releases: add 4.0.1 release notes
  TOC.md
  releases/release-4.0.1.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, translation/done

#3622 Secure: remove out-dated encryption docs
  TOC.md
  enable-encrypt-stored-data.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, translation/from-docs

#3624 add auto label github action
  .github/auto-label.json
  .github/pull_request_template.md
  .github/workflows/auto-label.yml
Labels: needs-cherry-pick-4.0, translation/done

#3630 github action: add PTAL label for release-xxx PRs
  .github/auto-label.json
  .github/workflows/auto-label.yml
Labels: status/PTAL

#3635 update key word
  basic-features.md
  tidb-limitations.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/welcome

#3634 Revert "github action: add PTAL label for release-xxx PRs"
  .github/auto-label.json
  .github/workflows/auto-label.yml
Labels: status/PTAL, status/can-merge

#3637 add auto assign reviewer github action
  .github/assign-by-files.yml
  .github/workflows/auto-assign.yml
Labels: status/PTAL, translation/done

#3639 modify some wrong word
  basic-features.md
Labels: contribution, follow-up

#3599 Update tiflash-configuration.md
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3604 lightning: fix wrong configuration description
  tidb-lightning/tidb-lightning-configuration.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#3640 change a typo
  basic-features.md
  releases/release-2.1.15.md
  releases/release-3.0-ga.md
  releases/release-3.0.1.md
Labels: status/can-merge, translation/no-need

#3601 tikv/cop: add 4.0.0-beta datetime issue fixing explanation
  mysql-compatibility.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3605 Update tidb-lightning-tidb-backend.md
  tidb-lightning/tidb-lightning-tidb-backend.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#3664 update warning for placement rules
  configure-placement-rules.md
Labels: needs-cherry-pick-4.0, translation/done

#3437 Update pd-scheduling-best-practices.md
  best-practices/pd-scheduling-best-practices.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#3518 Add column description for some system tables
  system-tables/system-table-information-schema.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3503 Add column description for system tables
  system-tables/system-table-information-schema.md
Labels: needs-cherry-pick-4.0, translation/doing

#3647 data migration: rename `data-migration-route.md`
  TOC.md
  _index.md
  migration-overview.md
  quick-start-with-tidb.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done, version-split-changes-required

#3672 Update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/doing

#3617 system_tables: add column description for several information_schema tables
  system-tables/system-table-information-schema.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/doing

#3653 *: fix typo
  schedule-replicas-by-topology-labels.md
  three-data-centers-in-two-cities-deployment.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3626 add deprecated warnings for outdated deployment methods
  .markdownlint.yaml
  deploy-test-cluster-using-docker-compose.md
  quick-start-with-tidb.md
  schedule-replicas-by-topology-labels.md
  test-deployment-using-docker.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/doing

#3678 doc: refine tables, tidb_hot_regions and session_variable in information schema
  system-tables/system-table-information-schema.md
Labels: needs-cherry-pick-4.0, translation/doing

#3655 tools: some minor update
  TOC.md
  load-misuse-handling.md
  loader-overview.md
  tidb-binlog/get-started-with-tidb-binlog.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3676 cdc: add software and hardware recommendation
  hardware-and-software-requirements.md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3666 cdc: add cyclic replication doc
  media/cdc-cyclic-replication.png
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/LGT2, status/can-merge, status/require-change, translation/doing

#3703 add explaination about `nested-loop-join-cache-capacity`
  tidb-configuration-file.md
Labels: translation/doing, v5.0

#3707 Fix titan compression type
  tikv-configuration-file.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/can-merge, translation/doing

#3712 sql-statement-admin.md: fix heading levels
  sql-statements/sql-statement-admin.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/from-docs

#3675 Add an "experimental feature" note in dashboard-intro.md
  dashboard/dashboard-intro.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/from-docs

#3741 add tiup master ssh handshake failed faq
  tiup/tiup-faq.md
Labels: contribution, status/can-merge, translation/doing

#3701 add tiup ssh handshake failed faq
  tiup/tiup-faq.md
Labels: contribution, status/can-merge, translation/doing

#3747 Update playground docs
  tiup/tiup-playground.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3723 Add more faqs in TiCDC
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/medium, status/PTAL, status/can-merge, translation/welcome

#3685 tiup: update pd status description
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/doing

#3489 tiup/cluster: add usage for check command
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, translation/doing, type/enhancement

#3752 *: add warnings
  data-type-json.md
  functions-and-operators/json-functions.md
  generated-columns.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, translation/doing

#3771 *: add warnings for user variables
  user-defined-variables.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, translation/doing

#3649 fix auto label action for master
  .github/assign-by-files.yml
  .github/auto-label.json
  .github/workflows/auto-assign.yml
  .github/workflows/auto-label.yml
Labels: translation/done

#3656 br: fix an expression that isn't accurate enough
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#3778 Fix auto assign config
  .github/assign-by-files.yml
Labels: status/PTAL, status/can-merge, translation/done

#3687 update TiFlash doc about expr pushdown when TiDB new collation is enabled
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3780 update tiflash expr pushdown list
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/doing

#3768 Update production-deployment-using-tiup.md
  production-deployment-using-tiup.md
Labels: size/small, status/PTAL, status/can-merge, translation/doing

#3785 tikv-ctl: document for encryption-meta subcommand
  tikv-control.md
Labels: needs-cherry-pick-4.0, status/PTAL, status/can-merge, translation/from-docs

#3789 *: update links from stable to v4.0 and new docs urls
  CONTRIBUTING.md
  README.md
  TOC.md
  _index.md
  architecture.md
  dashboard/dashboard-ops-deploy.md
  download-ecosystem-tools.md
  ecosystem-tool-user-case.md
  ecosystem-tool-user-guide.md
  faq/tidb-faq.md
  migrate-from-aurora-mysql-database.md
  overview.md
  quick-start-with-tidb.md
  syncer-overview.md
  tidb-troubleshooting-map.md
Labels: needs-cherry-pick-4.0, size/small, status/can-merge

#3795 fix: make tag closed
  blacklist-control-plan.md
Labels: needs-cherry-pick-3.1, status/can-merge

#3797 fix: add code to ankle bracket
  blacklist-control-plan.md
Labels: needs-cherry-pick-3.1

#3784 *: fix descriptions and update format
  basic-features.md
  mysql-compatibility.md
  overview.md
  tune-tikv-thread-performance.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, translation/no-need

#3706 br: remove backup and restore principle
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/can-merge, translation/doing

#3804 Update hardware-and-software-requirements.md
  hardware-and-software-requirements.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/done

#3786 remove restriction on `SELECT INTO FILE` in mysql-compatibility.md
  mysql-compatibility.md
Labels: size/small, status/can-merge, translation/welcome

#3792 remove restriction on `SELECT INTO FILE` in mysql-compatibility.md
  mysql-compatibility.md
Labels: size/small, status/can-merge, translation/welcome

#3810 Fix and update wording in overview
  migration-overview.md
  overview.md
Labels: needs-cherry-pick-4.0, translation/doing

#3815 daily.check.md: add aliases
  daily-check.md
Labels: needs-cherry-pick-4.0, translation/no-need, version-split-changes-required

#3812 Add Telemetry Docs
  TOC.md
  dashboard/dashboard-intro.md
  offline-deployment-using-ansible.md
  online-deployment-using-ansible.md
  pd-configuration-file.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  quick-start-with-tidb.md
  telemetry.md
  tidb-configuration-file.md
  tidb-specific-system-variables.md
  tiup/tiup-overview.md
  upgrade-tidb-using-ansible.md
  upgrade-tidb-using-tiup-offline.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, size/large, status/can-merge, translation/done

#3793 Update character-set-and-collation.md
  character-set-and-collation.md
Labels: needs-cherry-pick-4.0, size/small, status/PTAL, status/can-merge, status/require-change, translation/doing

#3824 fix typo in user-defined-variable.md
  user-defined-variables.md
Labels: needs-cherry-pick-4.0, status/can-merge, translation/no-need, type/bug-fix

#3831 Update store limit configuration
  configure-store-limit.md
Labels: translation/doing

#3836 chore: update letter id
  keywords.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/from-docs
