Repository pingcap/docs-cn, pull requests merged in 2020-09, with the labels that each got.

#4192 releases: add TiDB 4.0.5 release notes
  TOC.md
  releases/release-4.0.5.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#4394 mysql compatibility: add references
  mysql-compatibility.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/from-docs, version-specific-changes-required

#4313 sql-statements: add statement reference for ROLES
  TOC.md
  sql-statements/sql-statement-create-role.md
  sql-statements/sql-statement-drop-role.md
  sql-statements/sql-statement-grant-privileges.md
  sql-statements/sql-statement-grant-role.md
  sql-statements/sql-statement-revoke-role.md
  sql-statements/sql-statement-set-default-role.md
  sql-statements/sql-statement-set-role.md
  sql-statements/sql-statement-shutdown.md
  sql-statements/sql-statement-start-transaction.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, status/require-change, translation/from-docs

#4375 sql-statements: improve language and fix links
  sql-statements/sql-statement-create-database.md
  sql-statements/sql-statement-create-role.md
  sql-statements/sql-statement-create-table-like.md
  sql-statements/sql-statement-deallocate.md
  sql-statements/sql-statement-delete.md
  sql-statements/sql-statement-do.md
  sql-statements/sql-statement-drop-database.md
  sql-statements/sql-statement-drop-role.md
  sql-statements/sql-statement-drop-view.md
  sql-statements/sql-statement-execute.md
  sql-statements/sql-statement-flush-privileges.md
  sql-statements/sql-statement-grant-role.md
  sql-statements/sql-statement-insert.md
  sql-statements/sql-statement-prepare.md
  sql-statements/sql-statement-rename-index.md
  sql-statements/sql-statement-rename-table.md
  sql-statements/sql-statement-replace.md
  sql-statements/sql-statement-revoke-privileges.md
  sql-statements/sql-statement-revoke-role.md
  sql-statements/sql-statement-rollback.md
  sql-statements/sql-statement-select.md
  sql-statements/sql-statement-set-default-role.md
  sql-statements/sql-statement-set-names.md
  sql-statements/sql-statement-set-password.md
  sql-statements/sql-statement-set-role.md
  sql-statements/sql-statement-show-character-set.md
  sql-statements/sql-statement-show-collation.md
  sql-statements/sql-statement-show-columns-from.md
  sql-statements/sql-statement-show-create-table.md
  sql-statements/sql-statement-show-databases.md
  sql-statements/sql-statement-show-errors.md
  sql-statements/sql-statement-show-grants.md
  sql-statements/sql-statement-show-indexes.md
  sql-statements/sql-statement-show-plugins.md
  sql-statements/sql-statement-show-privileges.md
  sql-statements/sql-statement-show-table-status.md
  sql-statements/sql-statement-show-tables.md
  sql-statements/sql-statement-show-variables.md
  sql-statements/sql-statement-show-warnings.md
  sql-statements/sql-statement-truncate.md
  sql-statements/sql-statement-update.md
  sql-statements/sql-statement-use.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/no-need

#4407 Wrap all <role> in back ticks
  sql-statements/sql-statement-create-role.md
  sql-statements/sql-statement-drop-role.md
  sql-statements/sql-statement-grant-privileges.md
  sql-statements/sql-statement-grant-role.md
  sql-statements/sql-statement-revoke-role.md
  sql-statements/sql-statement-set-default-role.md
  sql-statements/sql-statement-set-role.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/doing, type/bug-fix

#4411 Revert the inappropriate changes
  sql-statements/sql-statement-start-transaction.md
Labels: size/small, status/LGT1, translation/no-need

#4399 ticdc: command sample fix and add one more faq
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4413 ticdc: fix a typo
  ticdc/ticdc-open-protocol.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/done, type/bug-fix

#4416 Add 4 aliases to fix dead links
  identify-expensive-queries.md
  information-schema/information-schema-statistics.md
  loader-overview.md
  query-execution-plan.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/no-need, type/bug-fix, version-specific-changes-required

#4422 Update tidb-limitations.md
  tidb-limitations.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix

#4374 Update production-offline-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4385 add system variable 'tidb_enable_clustered_index' for v5.0
  system-variables.md
Labels: size/medium, status/LGT2, status/PTAL, translation/doing, v5.0

#4428 tools: update download link for sync-diff-inspector
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT2, status/can-merge

#4432 sql-statements: add docs for `FETCH FIRST` syntax
  media/sqlgram/FetchFirstOpt.png
  media/sqlgram/FirstOrNext.png
  media/sqlgram/RowOrRows.png
  media/sqlgram/SelectStmtLimit.png
  sql-statements/sql-statement-select.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4438 Fix a typo in mydumper-overview.md
  mydumper-overview.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/no-need, type/bug-fix

#4431 Change the returned value of log-binlog from on/off to 1/0
  tidb-binlog/maintain-tidb-binlog-cluster.md
Labels: contribution, size/small, status/LGT2, status/PTAL, translation/doing

#4414 tiflash: add tls config for tiflash proxy
  enable-tls-between-components.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4440 Change the returned value of log-binlog from on/off to 1/0
  tidb-binlog/maintain-tidb-binlog-cluster.md
Labels: require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4442 Fix the incorrect version for allow_auto_random_explicit_insert
  system-variables.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4443 tools: remove unnecessary kafka version binlog
  download-ecosystem-tools.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4308 statement-reference: update docs
  TOC.md
  sql-statements/sql-statement-create-binding.md
  sql-statements/sql-statement-drop-binding.md
  sql-statements/sql-statement-show-bindings.md
  sql-statements/sql-statement-show-stats-healthy.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/from-docs

#4451 dumpling: add unit to -F
  dumpling-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#4331 Change the default value of `feedback-probability`
  statistics.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, status/require-change, translation/doing

#4456 Add 8 aliases to fix dead links
  functions-and-operators/json-functions.md
  get-started-with-tidb-lightning.md
  mysql-compatibility.md
  pd-configuration-file.md
  releases/release-1.1-alpha.md
  releases/release-3.1.0-beta.2.md
  sql-statements/sql-statement-show-databases.md
  ticdc/manage-ticdc.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#4462 Fix a typo
  enable-tls-between-components.md
Labels: needs-cherry-pick-4.0, status/PTAL, translation/no-need

#3791 *: add more doc for slow log
  identify-slow-queries.md
  system-variables.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, status/require-change, translation/doing

#4467 fix a typo
  benchmark/benchmark-tidb-using-tpcc.md
Labels: contribution, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4472 ticdc: cdc is GA since v4.0.6
  experimental-features-4.0.md
  ticdc-deployment-topology.md
  ticdc/ticdc-overview.md
  whats-new-in-tidb-4.0.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4454 br: update br faq
  br/backup-and-restore-faq.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#4453 sql-statements: improve alter index docs
  sql-statements/sql-statement-alter-index.md
  sql-statements/sql-statement-create-index.md
Labels: size/small, status/LGT1, status/PTAL, translation/from-docs, v5.0

#4450 character set: include useful warning
  character-set-and-collation.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs, version-specific-changes-required

#4474 ticdc: update some usage restrictions and configs
  ticdc/manage-ticdc.md
  ticdc/ticdc-open-protocol.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4483 ticdc: update kafka minumum version
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, translation/doing

#4486 mysql-compatibility: update docs
  mysql-compatibility.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1

#4362 faq: update backup and restore
  br/backup-and-restore-tool.md
  faq/deploy-and-maintain-faq.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-docs

#4446 pessimistic trx: cleanup wording
  pessimistic-transaction.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-docs, version-specific-changes-required

#4482 collation: add utf8_unicode_ci/utf8mb4_unicode_ci support
  basic-features.md
  character-set-and-collation.md
Labels: contribution, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-docs, v5.0

#4485 Add a missing item in mysql-compatibility.md
  mysql-compatibility.md
Labels: size/small, status/LGT1, status/PTAL, translation/done, type/bug-fix

#4498 faq: update backup and restore (#4362) #4491
  br/backup-and-restore-tool.md
  faq/tidb-faq.md
Labels: size/small, status/LGT1, status/PTAL, type/3.1-cherry-pick

#4497 Fix a description in character-and-collation.md
  character-set-and-collation.md
Labels: size/small, status/LGT1, status/PTAL, translation/from-docs, type/bug-fix

#4499 cdc: add upgrading section
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4504 functions-and-operators: function STDDEV is supported
  functions-and-operators/aggregate-group-by-functions.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, translation/doing

#4500 Update sql-faq.md
  faq/sql-faq.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs, version-specific-changes-required

#4466 releases: add TiDB 4.0.6 release notes
  TOC.md
  releases/release-4.0.6.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#4519 best-practices: improve wording in pd-scheduling
  best-practices/pd-scheduling-best-practices.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/no-need

#4518 ticdc: add open protocol parser demo link
  ticdc/ticdc-open-protocol.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4502 Update schedule-replicas-by-topology-labels.md
  schedule-replicas-by-topology-labels.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4521 Fix wording for clustered index item
  system-variables.md
Labels: status/LGT1, status/PTAL, translation/done, type/bug-fix

#4520 config: remove useless config in pessimistic-txn
  tidb-configuration-file.md
  tikv-configuration-file.md
Labels: size/small, status/LGT1, translation/doing

#4503 Fix a typo in manage-ticdc-md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/done, type/bug-fix

#4465 Update schedule-replicas-by-topology-labels.md
  schedule-replicas-by-topology-labels.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/done, version-specific-changes-required

#4533 functions-and-operators: function VAR_SAMP()/STDDEV_SAMP() is supported
  functions-and-operators/aggregate-group-by-functions.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4532 improve location-awareness in 3.1
  TOC.md
  location-awareness.md
  schedule-replicas-by-topology-labels.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT1, status/PTAL, translation/done, version-specific-changes-required

#4505 auth: Remove note about MySQL 8.0 auth plugin
  connectors-and-apis.md
  faq/tidb-faq.md
  security-compatibility-with-mysql.md
  user-account-management.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#4541 Fix titan blob-run-mode options
  storage-engine/titan-configuration.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/doing

#4546 Fix titan blob-run-mode options
  storage-engine/titan-configuration.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing

#4539 Fix wrong description
  functions-and-operators/aggregate-group-by-functions.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/done

#4527 Add async commit configuration
  tidb-configuration-file.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing, v5.0

#4390 Document for tiup-cluster local config directory
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT1, translation/doing

#4549 Remove sync-log config in TiKV config template
  tikv-configuration-file.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/from-docs, version-specific-changes-required

#4530 pd: update placement rules
  configure-placement-rules.md
Labels: size/medium, status/LGT1, status/PTAL, translation/doing, v5.0

#4461 sql-statements: readability of commit/rollback
  sql-statements/sql-statement-commit.md
  sql-statements/sql-statement-rollback.md
  sql-statements/sql-statement-start-transaction.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#4559 fix typo in benchmark result
  benchmark/v4.0-performance-benchmarking-with-tpcc.md
Labels: contribution, size/small, status/LGT1, translation/doing, type/bug-fix

#4562 Fix typo in benchmark result
  benchmark/v4.0-performance-benchmarking-with-tpcc.md
Labels: size/small, status/LGT1, translation/done, type/bug-fix

#4558 system_variables: add tidb_union_concurrency
  system-variables.md
Labels: needs-cherry-pick-3.0, size/small, status/LGT1, translation/doing

#4245 update TiDB roadmap.md
  TOC.md
  roadmap.md
Labels: status/LGT2, status/PTAL, status/require-change, translation/done

#4556 Update deploy-tidb-lightning.md
  tidb-lightning/deploy-tidb-lightning.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4568 Add 1 alias to fix dead link
  information-schema/information-schema-tidb-indexes.md
Labels: needs-cherry-pick-4.0, status/LGT1, translation/no-need, type/bug-fix, version-specific-changes-required

#4566 Update pd-configuration-file.md
  pd-configuration-file.md
Labels: contribution, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, size/small, status/LGT1, status/PTAL, translation/doing

#4545 Update optimizer-hints.md
  optimizer-hints.md
Labels: contribution, needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#4555 ticdc: update the docs about create changefeed
  releases/release-4.0.6.md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#4540 br: update docs for gc life time
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT1, status/require-change, translation/doing

#4447 constraints, create table: improve clarity and update out of date info
  constraints.md
  sql-statements/sql-statement-create-table.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#4429 Fix typos in Titan documents
  storage-engine/titan-configuration.md
  storage-engine/titan-overview.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/done, type/bug-fix

#4449 auto-increment: change "continuous" to monotonic
  auto-increment.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-docs, version-specific-changes-required

#4574 Update pd-configuration-file.md
  pd-configuration-file.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing

#4591 tiup: optimize descriptions about config
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/no-need, type/enhancement

#4593 *: update format and wording
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/monitor-tidb-lightning.md
  tiflash/monitor-tiflash.md
  tiflash/tiflash-configuration.md
  tiup/tiup-cluster.md
  tiup/tiup-faq.md
  tiup/tiup-mirror.md
  tiup/tiup-terminology-and-concepts.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/no-need, type/enhancement

#4557 add the `enable-disk-spill-encrypt.md` to descript the usage of the `spilled-file-encryption-method`
  TOC.md
  enable-disk-spill-encrypt.md
Labels: size/medium, status/LGT1, status/PTAL, translation/doing, v5.0

#4595 system-variables: remove the useless memory quota variables
  system-variables.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs, version-specific-changes-required

#4564 releases: add TiDB 3.0.19 release notes
  TOC.md
  releases/release-3.0.19.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#4588 system-variables: update noop functions
  system-variables.md
Labels: size/small, status/LGT2, status/can-merge, translation/from-docs

#4589 Fix typos in three-node deployment best practices
  best-practices/three-nodes-hybrid-deployment.md
Labels: needs-cherry-pick-4.0, status/LGT1, status/PTAL, translation/done, type/bug-fix

#4590 stmt-reference, sysvars: Document dml-batch-size
  sql-statements/sql-statement-load-data.md
  system-variables.md
Labels: size/small, status/LGT1, status/PTAL, translation/from-docs

#4609 sysvars: update tidb_dml_batch_size
  system-variables.md
Labels: size/small, status/LGT1, translation/from-docs

#4608 releases: add missing release note for v4.0.2 #
  releases/release-4.0.2.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, translation/from-docs

#4263 sql-statement: improve consistency, fix small errors
  constraints.md
  sql-statements/sql-statement-alter-database.md
  sql-statements/sql-statement-begin.md
  sql-statements/sql-statement-change-drainer.md
  sql-statements/sql-statement-change-pump.md
  sql-statements/sql-statement-commit.md
  sql-statements/sql-statement-create-sequence.md
  sql-statements/sql-statement-drop-sequence.md
  sql-statements/sql-statement-drop-stats.md
  sql-statements/sql-statement-explain-analyze.md
  sql-statements/sql-statement-flashback-table.md
  sql-statements/sql-statement-flush-tables.md
  sql-statements/sql-statement-kill.md
  sql-statements/sql-statement-load-stats.md
  sql-statements/sql-statement-recover-table.md
  sql-statements/sql-statement-show-analyze-status.md
  sql-statements/sql-statement-show-builtins.md
  sql-statements/sql-statement-show-config.md
  sql-statements/sql-statement-show-create-sequence.md
  sql-statements/sql-statement-show-drainer-status.md
  sql-statements/sql-statement-show-histograms.md
  sql-statements/sql-statement-show-profiles.md
  sql-statements/sql-statement-show-pump-status.md
  sql-statements/sql-statement-show-stats-meta.md
  sql-statements/sql-statement-show-table-next-rowid.md
  sql-statements/sql-statement-shutdown.md
  sql-statements/sql-statement-split-region.md
  sql-statements/sql-statement-use.md
  system-variables.md
Labels: needs-cherry-pick-4.0, size/large, status/LGT1, status/PTAL, translation/from-docs, version-specific-changes-required

#4594 config: add redact-info-log
  tikv-configuration-file.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT2, status/PTAL, translation/done

#3858 TiDB: add a new document about how to analyze slow queries
  TOC.md
  _index.md
  analyze-slow-queries.md
  media/performance-map.png
Labels: needs-cherry-pick-4.0, size/large, status/LGT2, status/require-change, translation/doing

#4613 Update tidb-lightning-checkpoints.md
  tidb-lightning/tidb-lightning-checkpoints.md
Labels: contribution, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/no-need

#4614 Update tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-backends.md
Labels: contribution, needs-cherry-pick-4.0, require-LGT1, status/LGT1, status/can-merge, translation/no-need

#4560 ticdc: add HTTP API for adjusting log level
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4577 transactions: improve clarity of transactions
  optimistic-transaction.md
  pessimistic-transaction.md
  system-variables.md
  transaction-overview.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, status/can-merge, translation/from-docs

#4565 releases: add TiDB 4.0.7 release notes
  TOC.md
  releases/release-4.0.7.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, status/LGT1, translation/from-docs

#4625 Update the warning for sync-log in v4.0.7
  tikv-configuration-file.md
Labels: status/LGT1, translation/from-docs, type/4.0-cherry-pick

#4578 dashboard: add metric relation profile doc
  TOC.md
  dashboard/dashboard-metrics-relation.md
  media/dashboard/dashboard-metrics-relation-example.png
  media/dashboard/dashboard-metrics-relation-home.png
  media/dashboard/dashboard-metrics-relation-node-example.png
  media/dashboard/dashboard-metrics-relation-node-example1.png
  media/dashboard/dashboard-metrics-relation-node-example2.png
  media/dashboard/dashboard-metrics-relation-relation-example1.png
  media/dashboard/dashboard-metrics-relation-relation-example2.png
Labels: needs-cherry-pick-4.0, size/large, status/LGT2, status/require-change, translation/doing

#4621 sql-stmt: improve consistency, fix small errors
  constraints.md
  sql-statements/sql-statement-alter-database.md
  sql-statements/sql-statement-begin.md
  sql-statements/sql-statement-commit.md
  sql-statements/sql-statement-explain-analyze.md
  sql-statements/sql-statement-flush-tables.md
  sql-statements/sql-statement-kill.md
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-load-stats.md
  sql-statements/sql-statement-recover-table.md
  sql-statements/sql-statement-rollback.md
  sql-statements/sql-statement-show-analyze-status.md
  sql-statements/sql-statement-show-character-set.md
  sql-statements/sql-statement-show-collation.md
  sql-statements/sql-statement-show-variables.md
  sql-statements/sql-statement-split-region.md
  sql-statements/sql-statement-use.md
  tidb-specific-system-variables.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT2, translation/from-docs, version-specific-changes-required

#4596 Update multi-data-centers-in-one-city-deployment.md
  multi-data-centers-in-one-city-deployment.md
Labels: size/small, status/LGT2, status/require-change, translation/doing

#4623 Add necessary tip to avoid misunderstanding
  quick-start-with-tidb.md
Labels: contribution, needs-cherry-pick-4.0, size/small, status/LGT1, status/PTAL, translation/doing

#4634 Update a config example in multi-data-centers-in-one-city-deployment.md
  multi-data-centers-in-one-city-deployment.md
Labels: status/LGT1, translation/no-need
