Repository pingcap/docs-cn, pull requests merged in 2020-02, with the labels that each got.

#2199 *: add the description of `alter-primary-key`
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/reference/sql/statements/add-index.md
  dev/reference/sql/statements/create-index.md
  dev/reference/sql/statements/drop-index.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
  v3.0/reference/sql/statements/add-index.md
  v3.0/reference/sql/statements/create-index.md
  v3.0/reference/sql/statements/drop-index.md
  v3.1/reference/configuration/tidb-server/configuration-file.md
  v3.1/reference/sql/statements/add-index.md
  v3.1/reference/sql/statements/create-index.md
  v3.1/reference/sql/statements/drop-index.md
Labels: pending-aligning, small, status/can-merge

#2203 reference: modify stats-lease cycle from 5 to 20
  dev/reference/performance/statistics.md
  v2.1/reference/performance/statistics.md
  v3.0/reference/performance/statistics.md
  v3.1/reference/performance/statistics.md
Labels: pending-aligning, small, status/can-merge

#2202 reference/sql: apply changes in #2192 to v3.1 and dev
  dev/reference/sql/functions-and-operators/expressions-pushed-down.md
  v3.1/reference/sql/functions-and-operators/expressions-pushed-down.md
Labels: aligned-in-docs, status/can-merge

#2190 reference: update Grafana monitoring best practices
  dev/reference/best-practices/grafana-monitor.md
  v2.1/reference/best-practices/grafana-monitor.md
  v3.0/reference/best-practices/grafana-monitor.md
  v3.1/reference/best-practices/grafana-monitor.md
Labels: aligned-in-docs, status/can-merge

#2205 dev: add admin repair table statement.
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/reference/sql/statements/admin.md
Labels: pending-aligning, small, status/can-merge, v4.0

#2207 v3.1: delete inapplicable optimizer hints
  v3.1/reference/performance/optimizer-hints.md
Labels: aligned-with-docs

#2197 reference/sql: update compatibility description of MySQL
  dev/reference/mysql-compatibility.md
  v3.0/reference/mysql-compatibility.md
  v3.1/reference/mysql-compatibility.md
Labels: LGT2, pending-aligning, small, status/can-merge

#2176 tools/tidb-lightning: update TiDB Lightning FAQ and troubleshooting
  dev/faq/tidb-lightning.md
  dev/how-to/troubleshoot/tidb-lightning.md
  dev/reference/tools/tidb-lightning/monitor.md
  v3.0/faq/tidb-lightning.md
  v3.0/how-to/troubleshoot/tidb-lightning.md
  v3.0/reference/tools/tidb-lightning/monitor.md
  v3.1/faq/tidb-lightning.md
  v3.1/how-to/troubleshoot/tidb-lightning.md
  v3.1/reference/tools/tidb-lightning/monitor.md
Labels: aligned-with-docs, dev, medium, status/can-merge, v3.0, v3.1

#2208 dev/2.1/3.0/3.1/4.0: add global variable latency resulted by gvc.
  dev/reference/configuration/tidb-server/mysql-variables.md
  v2.1/reference/configuration/tidb-server/mysql-variables.md
  v3.0/reference/configuration/tidb-server/mysql-variables.md
  v3.1/reference/configuration/tidb-server/mysql-variables.md
Labels: pending-aligning, small, status/can-merge

#2151 v3.1/how-to/maintain/backup-and-restore/br: add recommend configuration
  dev/how-to/maintain/backup-and-restore/br.md
  v3.1/how-to/maintain/backup-and-restore/br.md
Labels: enhancement, pending-aligning, status/can-merge

#2161 reference/sql: add reserved words for window functions
  dev/reference/sql/language-structure/keywords-and-reserved-words.md
  v3.0/reference/sql/language-structure/keywords-and-reserved-words.md
  v3.1/reference/sql/language-structure/keywords-and-reserved-words.md
Labels: dev, pending-aligning, v3.0, v3.1

#2212 reference/sql/statements/admin: remove statement repetition for admin doc
  dev/reference/sql/statements/admin.md
Labels: aligned-in-docs, status/can-merge

#2167 br: add best practice
  dev/TOC.md
  dev/how-to/maintain/backup-and-restore/br-best-practices.md
  dev/how-to/maintain/backup-and-restore/br.md
  media/br/backup-cpu.png
  media/br/backup-diff.png
  media/br/backup-diff2.png
  media/br/backup-errors.png
  media/br/backup-io.png
  media/br/backup-local-deploy.png
  media/br/backup-nfs-deploy.png
  media/br/backup-range-duration.png
  media/br/backup-subtask-duration.png
  media/br/backup-throughput.png
  media/br/checksum-duration.png
  media/br/restore-checksum.png
  media/br/restore-cpu.png
  media/br/restore-download-sst.png
  media/br/restore-errors.png
  media/br/restore-io.png
  media/br/restore-local-deploy.png
  media/br/restore-nfs-deploy.png
  media/br/restore-process-sst.png
  media/br/restore-region.png
  media/br/test-data.png
  media/br/total-data.png
  v3.1/TOC.md
  v3.1/how-to/maintain/backup-and-restore/br-best-practices.md
  v3.1/how-to/maintain/backup-and-restore/br.md
Labels: LGT1, best-practices, enhancement, large, pending-aligning, v3.1

#2211 *: add document for expensive query log
  dev/TOC.md
  dev/faq/tidb.md
  dev/how-to/maintain/identify-abnormal-queries/identify-aborted-queries.md
  dev/how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
  dev/how-to/troubleshoot/cluster-setup.md
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  dev/reference/system-databases/information-schema.md
  v3.0/TOC.md
  v3.0/faq/tidb.md
  v3.0/how-to/maintain/identify-abnormal-queries/identify-aborted-queries.md
  v3.0/how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
  v3.0/how-to/troubleshoot/cluster-setup.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/reference/system-databases/information-schema.md
  v3.1/TOC.md
  v3.1/faq/tidb.md
  v3.1/how-to/maintain/identify-abnormal-queries/identify-aborted-queries.md
  v3.1/how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
  v3.1/how-to/troubleshoot/cluster-setup.md
  v3.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.1/reference/system-databases/information-schema.md
Labels: pending-aligning

#2200 reference/sql: update generate column document
  dev/reference/sql/generated-columns.md
  v3.0/reference/sql/generated-columns.md
  v3.1/reference/sql/generated-columns.md
Labels: LGT2, pending-aligning, small

#2218 *: remove MyDB
  dev/reference/supported-clients.md
  v1.0/sql/connection-and-APIs.md
  v2.0/sql/connection-and-APIs.md
  v2.1-legacy/sql/connection-and-APIs.md
  v2.1/reference/supported-clients.md
  v3.0/reference/supported-clients.md
  v3.1/reference/supported-clients.md
Labels: aligned-in-docs, dev, status/can-merge, v1.0, v2.0, v2.1, v3.0, v3.1

#2219 tidb-in-kubernetes/deploy: required terraform must be 0.12.*
  dev/tidb-in-kubernetes/deploy/alibaba-cloud.md
  v3.0/tidb-in-kubernetes/deploy/alibaba-cloud.md
  v3.1/tidb-in-kubernetes/deploy/alibaba-cloud.md
Labels: aligned-with-docs, dev, v3.0, v3.1

#2232 Fix deadlinks in two files
  README.md
  _index.md
Labels: pending-aligning

#2233 Fix wrong links in 2 files
  README.md
  _index.md
Labels: pending-aligning

#2184 tidb-lightning: document backend and that system DBs are filtered
  dev/TOC.md
  dev/faq/tidb-lightning.md
  dev/reference/tools/tidb-lightning/config.md
  dev/reference/tools/tidb-lightning/deployment.md
  dev/reference/tools/tidb-lightning/overview.md
  dev/reference/tools/tidb-lightning/table-filter.md
  dev/reference/tools/tidb-lightning/tidb-backend.md
  v3.0/TOC.md
  v3.0/faq/tidb-lightning.md
  v3.0/reference/tools/tidb-lightning/config.md
  v3.0/reference/tools/tidb-lightning/deployment.md
  v3.0/reference/tools/tidb-lightning/overview.md
  v3.0/reference/tools/tidb-lightning/table-filter.md
  v3.0/reference/tools/tidb-lightning/tidb-backend.md
  v3.1/TOC.md
  v3.1/faq/tidb-lightning.md
  v3.1/reference/tools/tidb-lightning/config.md
  v3.1/reference/tools/tidb-lightning/deployment.md
  v3.1/reference/tools/tidb-lightning/overview.md
  v3.1/reference/tools/tidb-lightning/table-filter.md
  v3.1/reference/tools/tidb-lightning/tidb-backend.md
Labels: dev, v3.0, v3.1

#2210 tools: add a guide for choosing TiDB Ecosystem Tools
  dev/TOC.md
  dev/reference/tools/use-guide.md
  v2.1/TOC.md
  v2.1/reference/tools/use-guide.md
  v3.0/TOC.md
  v3.0/reference/tools/use-guide.md
  v3.1/TOC.md
  v3.1/reference/tools/use-guide.md
Labels: LGT2, pending-aligning, status/can-merge

#2240 kubernetes: terraform must be >= v0.12
  dev/tidb-in-kubernetes/deploy/aws-eks.md
  v3.0/tidb-in-kubernetes/deploy/aws-eks.md
  v3.1/tidb-in-kubernetes/deploy/aws-eks.md
Labels: aligned-in-docs

#2241 optimizer-hints: move description before the example
  dev/reference/performance/optimizer-hints.md
  v3.1/reference/performance/optimizer-hints.md
Labels: pending-aligning, small, status/can-merge

#2206 dev: add read committed isolation level for transaction chapter
  dev/reference/transactions/transaction-isolation.md
Labels: dev, pending-aligning, small, v4.0

#2204 dev: update sql admin syntax
  dev/reference/sql/statements/admin.md
Labels: LGT1, dev, pending-aligning, small, status/can-merge, v4.0

#2226 reference: remove warning in RBAC doc
  dev/reference/security/role-based-access-control.md
  v3.0/reference/security/role-based-access-control.md
  v3.1/reference/security/role-based-access-control.md
Labels: LGT2, dev, pending-aligning, v3.0, v3.1

#2017 readme, contributing: rewrite and reorganize contribution resources
  CONTRIBUTING.md
  README.md
Labels: large, pending-aligning

#2245 contributing: update version description
  CONTRIBUTING.md
Labels: pending-aligning, small

#1963 *: update slow log doc
  dev/how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
  v3.0/how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
  v3.1/how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
Labels: LGT1, dev, pending-aligning, status/can-merge, v3.0, v3.1

#2214 tidb-lightning: add glossary
  dev/TOC.md
  dev/reference/tools/tidb-lightning/glossary.md
  v2.1/TOC.md
  v2.1/reference/tools/tidb-lightning/glossary.md
  v3.0/TOC.md
  v3.0/reference/tools/tidb-lightning/glossary.md
  v3.1/TOC.md
  v3.1/reference/tools/tidb-lightning/glossary.md
Labels: aligned-with-docs, dev, medium, v2.1, v3.0, v3.1

#2173 reference: update statement summary docs
  dev/reference/performance/statement-summary.md
  v3.0/reference/performance/statement-summary.md
  v3.1/reference/performance/statement-summary.md
Labels: LGT1, dev, large, pending-aligning, v3.0, v3.1, v4.0

#2247 sql: add doc of hex and binary expression support for `LOAD DATA`
  dev/reference/sql/statements/load-data.md
Labels: LGT1, dev, pending-aligning, small, v4.0

#2213 dev/reference: update the error code
  dev/reference/error-codes.md
Labels: dev, pending-aligning, v4.0

#2081 tidb-in-kubernetes: fix tidb cluster initialize command
  dev/tidb-in-kubernetes/initialize-cluster.md
  v3.0/tidb-in-kubernetes/initialize-cluster.md
  v3.1/tidb-in-kubernetes/initialize-cluster.md
Labels: pending-aligning, small, tidb-in-k8s

#2227 how-to/maintain: change br best practices to use cases
  dev/TOC.md
  dev/reference/tools/br/br.md
  dev/reference/tools/br/use-cases.md
  v3.1/TOC.md
  v3.1/reference/tools/br/br.md
  v3.1/reference/tools/br/use-cases.md
Labels: aligned-in-docs, dev, v3.1

#2253 reference/tools: add br aliases
  dev/reference/tools/br/use-cases.md
  v3.1/reference/tools/br/use-cases.md
Labels: align-N/A, dev, v3.1

#2255 dev/reference/best-practices: update optimistic transaction document
  dev/reference/best-practices/optimistic-transaction.md
Labels: dev, pending-aligning, v4.0

#2224 reference/tidb-binlog: add docs about relay log
  dev/TOC.md
  dev/reference/tidb-binlog/deploy.md
  dev/reference/tidb-binlog/monitor.md
  dev/reference/tidb-binlog/overview.md
  dev/reference/tidb-binlog/relay-log.md
  v3.0/TOC.md
  v3.0/reference/tidb-binlog/deploy.md
  v3.0/reference/tidb-binlog/monitor.md
  v3.0/reference/tidb-binlog/overview.md
  v3.0/reference/tidb-binlog/relay-log.md
  v3.1/TOC.md
  v3.1/reference/tidb-binlog/deploy.md
  v3.1/reference/tidb-binlog/overview.md
  v3.1/reference/tidb-binlog/relay-log.md
Labels: LGT1, pending-aligning

#2256 reference/tools: refine format
  dev/reference/tools/br/use-cases.md
  v3.1/reference/tools/br/use-cases.md
Labels: aligned-in-docs, dev, status/can-merge, v3.1

#2237 reference/system-databases: add description for `TIDB_ROW_ID_SHARDING_INFO`
  dev/reference/system-databases/information-schema.md
Labels: dev, pending-aligning, v4.0

#2258 reference/performance: add hint for INL_HASH_JOIN and INL_MERGE_JOIN
  dev/reference/performance/optimizer-hints.md
Labels: LGT1, dev, v4.0

#2198 *: refactor transaction documents
  dev/TOC.md
  dev/glossary.md
  dev/reference/best-practices/optimistic-transaction.md
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  dev/reference/mysql-compatibility.md
  dev/reference/sql/statements/load-data.md
  dev/reference/sql/statements/select.md
  dev/reference/transactions/overview.md
  dev/reference/transactions/transaction-isolation.md
  dev/reference/transactions/transaction-model.md
  dev/reference/transactions/transaction-optimistic.md
  dev/reference/transactions/transaction-pessimistic.md
  media/2pc-in-tidb.png
  media/best-practices/optimistic-transaction-case1.png
  media/best-practices/optimistic-transaction-case2.png
  media/best-practices/optimistic-transaction-table1.png
  media/best-practices/optimistic-transaction-table2.png
  media/optimistic-transaction-metric.png
  v2.1/TOC.md
  v2.1/glossary.md
  v2.1/reference/best-practices/optimistic-transaction.md
  v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v2.1/reference/mysql-compatibility.md
  v2.1/reference/sql/statements/load-data.md
  v2.1/reference/sql/statements/select.md
  v2.1/reference/transactions/overview.md
  v2.1/reference/transactions/transaction-isolation.md
  v2.1/reference/transactions/transaction-model.md
  v2.1/reference/transactions/transaction-optimistic.md
  v3.0/TOC.md
  v3.0/glossary.md
  v3.0/reference/best-practices/optimistic-transaction.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/reference/mysql-compatibility.md
  v3.0/reference/sql/statements/load-data.md
  v3.0/reference/sql/statements/select.md
  v3.0/reference/transactions/overview.md
  v3.0/reference/transactions/transaction-isolation.md
  v3.0/reference/transactions/transaction-model.md
  v3.0/reference/transactions/transaction-optimistic.md
  v3.0/reference/transactions/transaction-pessimistic.md
  v3.1/TOC.md
  v3.1/glossary.md
  v3.1/reference/best-practices/optimistic-transaction.md
  v3.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.1/reference/mysql-compatibility.md
  v3.1/reference/sql/statements/load-data.md
  v3.1/reference/sql/statements/select.md
  v3.1/reference/transactions/overview.md
  v3.1/reference/transactions/transaction-isolation.md
  v3.1/reference/transactions/transaction-model.md
  v3.1/reference/transactions/transaction-optimistic.md
  v3.1/reference/transactions/transaction-pessimistic.md
Labels: LGT1, dev, large, pending-aligning, refactor, v2.1, v3.0, v3.1

#2257 releases: add 3.0.10 release notes
  dev/TOC.md
  dev/releases/3.0.10.md
  dev/releases/rn.md
  v3.0/TOC.md
  v3.0/releases/3.0.10.md
  v3.0/releases/rn.md
  v3.1/TOC.md
  v3.1/releases/3.0.10.md
  v3.1/releases/rn.md
Labels: aligned-in-docs

#2251 dev: add documentation for index merge
  dev/reference/performance/index-merge.md
Labels: dev, pending-aligning, status/can-merge, v4.0

#2262 *: clarify unsupported behavior in generated column
  dev/reference/sql/generated-columns.md
  v2.1/reference/sql/generated-columns.md
  v3.0/reference/sql/generated-columns.md
  v3.1/reference/sql/generated-columns.md
Labels: dev, pending-aligning, status/can-merge, v2.1, v3.0, v3.1, v4.0

#2254 reference/security: add missing semicolon
  dev/reference/security/cert-based-authentication.md
  v3.0/reference/security/cert-based-authentication.md
  v3.1/reference/security/cert-based-authentication.md
Labels: pending-aligning, small

#2134 reference: add compatibility issue for STRING type
  dev/reference/mysql-compatibility.md
  v3.0/reference/mysql-compatibility.md
  v3.1/reference/mysql-compatibility.md
Labels: pending-aligning, small

#2250 reference/performance: update docs for plan bind
  dev/reference/performance/execution-plan-bind.md
Labels: dev, pending-aligning, status/can-merge, v4.0

#2249 reference/performance: update docs for statistics
  dev/reference/performance/statistics.md
  v3.0/reference/performance/statistics.md
  v3.1/reference/performance/statistics.md
Labels: dev, status/can-merge, v3.0, v3.1, v4.0

#2111 reference: update v2.1 auto-retry description
  v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
Labels: aligned-in-docs, status/can-merge, v2.1

#2119 data-migration: refine the description of dm relay log doc
  dev/reference/tools/data-migration/relay-log.md
  v2.1/reference/tools/data-migration/relay-log.md
  v3.0/reference/tools/data-migration/relay-log.md
  v3.1/reference/tools/data-migration/relay-log.md
Labels: aligned-in-docs, status/can-merge

#2263 reference: improve documents about pessimistic transaction
  dev/reference/configuration/tidb-server/configuration-file.md
  dev/reference/configuration/tidb-server/mysql-variables.md
  dev/reference/configuration/tidb-server/tidb-specific-variables.md
  dev/reference/configuration/tikv-server/configuration-file.md
  dev/reference/transactions/transaction-pessimistic.md
  v3.0/reference/configuration/tidb-server/configuration-file.md
  v3.0/reference/configuration/tidb-server/mysql-variables.md
  v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.0/reference/configuration/tikv-server/configuration-file.md
  v3.0/reference/transactions/transaction-pessimistic.md
  v3.1/reference/configuration/tidb-server/configuration-file.md
  v3.1/reference/configuration/tidb-server/mysql-variables.md
  v3.1/reference/configuration/tidb-server/tidb-specific-variables.md
  v3.1/reference/configuration/tikv-server/configuration-file.md
  v3.1/reference/transactions/transaction-pessimistic.md
Labels: dev, large, pending-aligning, status/can-merge, v3.0, v3.1, v4.0

#2266 .circleci: disable deadlink check
  .circleci/config.yml
Labels: DNM, aligned-in-docs

#2275 readme: make some minor edits to test cherry-pick
  README.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1

#2279 .github: update pr template
  .github/pull_request_template.md
Labels: aligned-in-docs, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1

#2284 scripts: update verify links to fit current layout
  scripts/markdown-link-check.tpl
  scripts/verify-links.sh
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1

#2259 *: add config variable enable-slow-log
  how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
  reference/configuration/tidb-server/configuration-file.md
Labels: dev, pending-aligning, status/can-merge, v4.0

#2209 reference: add user documentation for auto_random feature
  TOC.md
  reference/best-practices/high-concurrency.md
  reference/configuration/tidb-server/configuration-file.md
  reference/sql/attributes/auto-random.md
  reference/sql/language-structure/comment-syntax.md
  reference/sql/language-structure/keywords-and-reserved-words.md
  reference/sql/statements/create-table.md
Labels: LGT1, dev, needs-cherry-pick-3.1, pending-aligning, status/can-merge, v3.1, v4.0

#2289 reference/performance: correct replica selection policy of follower read
  reference/performance/follower-read.md
Labels: LGT1, needs-cherry-pick-3.1, pending-aligning, status/can-merge, v3.1, v4.0

#2291 reference: add user documentation for auto_random feature (#2209)
  TOC.md
  reference/best-practices/high-concurrency.md
  reference/configuration/tidb-server/configuration-file.md
  reference/sql/attributes/auto-random.md
  reference/sql/language-structure/comment-syntax.md
  reference/sql/language-structure/keywords-and-reserved-words.md
  reference/sql/statements/create-table.md
Labels: status/can-merge, type/3.1 cherry-pick

#2292 scripts/verify-links: update link check error messages
  scripts/verify-links.sh
Labels: aligned-in-docs, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1

#2296 tools: remove latest in download document
  reference/tools/download.md
Labels: aligned-in-docs, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1

#2301 tools: remove latest in download document
  reference/tools/download.md
Labels: type/2.1 cherry-pick

#2302 tools: remove latest in download document
  reference/tools/download.md
Labels: type/3.0 cherry-pick

#2308 tools: minor update for drainer's relay log
  reference/tidb-binlog/relay-log.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, pending-aligning

#2305 tools: remove `latest` replacement suggestion
  reference/tools/download.md
Labels: aligned-in-docs

#2297 dev, v4.0: add enable-chunk-rpc doc
  reference/configuration/tidb-server/configuration-file.md
Labels: dev, pending-aligning, status/can-merge, v4.0

#2282 dev, v4.0: add sequence doc
  media/sqlgram/CreateSequenceOptionListOpt.png
  media/sqlgram/CreateSequenceStmt.png
  media/sqlgram/DropSequenceStmt.png
  media/sqlgram/OptTemporary.png
  media/sqlgram/SequenceOption.png
  media/sqlgram/ShowStmt.png
  reference/sql/statements/create-sequence.md
  reference/sql/statements/drop-sequence.md
  reference/sql/statements/show-create-sequence.md
Labels: dev, pending-aligning, v4.0

#2316 how-to/get-started: change tispark-sample-data download address
  how-to/get-started/tispark.md
Labels: aligned-with-docs, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, small

#2307 reference/performance: update raft parameter name
  reference/performance/tune-tikv.md
Labels: aligned-with-docs, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/can-merge

#2322 how-to/get-started: change tispark-sample-data download address for v2.1
  how-to/get-started/tispark.md
Labels: aligned-with-docs, small, type/2.1 cherry-pick

#2315 reference/transaction: fix typo
  reference/transactions/transaction-pessimistic.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, pending-aligning, small, status/can-merge

#2298 tidb-in-kubernetes: add specific Helm version
  tidb-in-kubernetes/reference/tools/in-kubernetes.md
Labels: aligned-with-docs, needs-cherry-pick-3.0, needs-cherry-pick-3.1, small, status/can-merge

#2236 tidb-in-kubernetes: update backup & restore usage docs
  TOC.md
  reference/tools/user-guide.md
  tidb-in-kubernetes/maintain/backup-and-restore/backup-gcs.md
  tidb-in-kubernetes/maintain/backup-and-restore/backup-s3.md
  tidb-in-kubernetes/maintain/backup-and-restore/charts.md
  tidb-in-kubernetes/maintain/backup-and-restore/restore-gcs.md
  tidb-in-kubernetes/maintain/backup-and-restore/restore-s3.md
  tidb-in-kubernetes/maintain/backup-and-restore/restore.md
  tidb-in-kubernetes/reference/configuration/storage-class.md
  tidb-in-kubernetes/tidb-operator-overview.md
Labels: large, needs-cherry-pick-3.0, needs-cherry-pick-3.1, pending-aligning, status/can-merge, tidb-in-k8s

#2252 dev/v3.1: move optimizer hints to proper section
  reference/performance/optimizer-hints.md
Labels: dev, needs-cherry-pick-3.1, pending-aligning, refactor, status/can-merge, v3.1, v4.0

#2260 reference/configuration: add configuration for reserver space
  reference/configuration/tikv-server/configuration-file.md
Labels: dev, pending-aligning, small, v4.0

#2333 sql/attributes: refine the language of auto random doc
  reference/sql/attributes/auto-random.md
Labels: aligned-in-docs, dev, needs-cherry-pick-3.1, status/can-merge, v3.1, v4.0

#2311 reference/performance: update replica selection policy of follower read
  reference/performance/follower-read.md
Labels: aligned-in-docs, dev, needs-cherry-pick-3.1, status/can-merge, v3.1, v4.0

#2336 releases: add TiDB 4.0.0-beta.1 Release Notes
  TOC.md
  releases/4.0.0-beta.1.md
  releases/rn.md
Labels: aligned-in-docs, dev, v4.0
