Repository pingcap/docs-cn, pull requests merged in 2021-11, with the labels that each got.

#7346 Lightning: add character set conversion configuration instructions
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, v5.3

#7342 Fix a mistaken link
  system-variables.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/sql-infra, needs-cherry-pick-release-5.2

#7362 sql-mode.md: fix a typo
  sql-mode.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7363 system-variables: update permitted ranges
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/S, sig/sql-infra

#7322 tidb-configuration-file: add unit for log.max-size
  tidb-configuration-file.md
Labels: type/enhancement, status/LGT1, contribution, translation/doing, status/can-merge, require-LGT1, size/XS, sig/sql-infra

#7378 make some correction for tidb_opt_insubq_to_join_and_agg
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7364 Add two session variables' descriptions related to TSO Scalability feature
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, sig/scheduling, v5.3

#7394 chore: stop building temporary
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1

#7351 system-variables: add `tidb_enable_pseudo_for_outdated_stats`
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/planner, v5.3

#7379 update functions supported by TiFlash
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/bigdata, v5.3

#7356 planner: update the document about Plan-Cache
  sql-prepare-plan-cache.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/planner, v5.3

#7401 Deleted region-split-size and batch-size in tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, sig/migrate, v5.3, needs-cherry-pick-release-5.3

#7396 change the default value of prepared-plan-cache.capacity from 100 to …
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/XS, type/compatibility-or-feature-change, v5.3

#7400 Update Prometheus version in deploy-monitoring-services.md
  deploy-monitoring-services.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/tiup, v5.3

#7187 add dashboard user doc
  TOC.md
  dashboard/dashboard-access.md
  dashboard/dashboard-ops-security.md
  dashboard/dashboard-user.md
  media/dashboard/dashboard-user-insufficient-privileges.png
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, sig/diagnosis, v5.3

#7380 sql-plan-replayer: add sql-plan-replayer doc
  TOC.md
  sql-plan-replayer.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/L, sig/planner, v5.3

#7402 Add the docs for temporary tables
  TOC.md
  br/backup-and-restore-tool.md
  mysql-compatibility.md
  sql-statements/sql-statement-create-table-like.md
  sql-statements/sql-statement-create-table.md
  sql-statements/sql-statement-drop-table.md
  system-variables.md
  temporary-table.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XL, sig/sql-infra, v5.3

#7388 Corrected default values of checksum and analyze in Lightning.
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/S, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7412 Update pessimistic-transaction.md
  media/sqlgram/SelectLockOpt.png
  pessimistic-transaction.md
  sql-statements/sql-statement-select.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/transaction, v5.3

#7419 chore: update pr template for v5.3
  .github/pull_request_template.md
  README.md
Labels: status/LGT1, translation/done, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7404 br: update doc for encrypt
  br/use-br-command-line-tool.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, sig/migrate, v5.3

#7376 ticdc: add usage for eventually consistent replication
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, sig/migrate, v5.3

#7406 Update some default configs of PD
  best-practices/pd-scheduling-best-practices.md
  pd-configuration-file.md
  pd-control.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/transaction, v5.3

#7410 Add auth_socket support
  security-compatibility-with-mysql.md
Labels: status/LGT2, translation/from-docs, status/can-merge, area/security, v5.3

#7391 statistics: add the updates of the new grammar
  sql-statements/sql-statement-analyze-table.md
  statistics.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, sig/planner, v5.3

#7375 add attributes user docs
  TOC.md
  table-attributes.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/scheduling, v5.3

#7407 *:change the reserve space description
  tikv-configuration-file.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, size/XS, sig/engine, v5.3

#7339 Update version info about default enabled Placement Rules
  configure-placement-rules.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, sig/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7365 basic features: add feature matrix
  basic-features.md
Labels: status/LGT2, translation/from-docs, status/can-merge, area/general, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7432 revise the order of system variables into alphabetical order
  system-variables.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, requires-version-specific-changes, require-LGT1, needs-cherry-pick-release-5.0, size/M, sig/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7405 Added precheck in Lightning parallel import
  TOC.md
  media/parallel-import-shard-tables.png
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-prechecks.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, sig/migrate, v5.3, needs-cherry-pick-release-5.3

#7428 br: update doc for encrypt-br
  br/use-br-command-line-tool.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, v5.3

#7389 Update continuous-profiling & dashboard-profiling.md
  TOC.md
  dashboard/continuous-profiling.md
  dashboard/dashboard-profiling.md
  experimental-features.md
  media/dashboard/dashboard-conprof-access.png
  media/dashboard/dashboard-conprof-download.png
  media/dashboard/dashboard-conprof-history.png
  media/dashboard/dashboard-conprof-single.png
  media/dashboard/dashboard-conprof-start.png
  media/dashboard/dashboard-conprof-stop.png
  tiup/tiup-cluster-topology-reference.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, v5.3

#7354 Add description of TiCDC alert rules
  TOC.md
  alert-rules.md
  ticdc/ticdc-alert-rules.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, needs-cherry-pick-release-5.0, size/L, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7381 Add documents for online unsafe recover
  TOC.md
  experimental-features.md
  online-unsafe-recovery.md
  pd-control.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, first-time-contributor, size/L, sig/engine, v5.3

#5561 Add sql optimization-related docs to toc
  TOC.md
  blocklist-control-plan.md
  explain-aggregation.md
  explain-index-merge.md
  explain-indexes.md
  explain-joins.md
  explain-mpp.md
  explain-overview.md
  explain-partitions.md
  explain-subqueries.md
  explain-views.md
  whats-new-in-tidb-4.0.md
Labels: status/LGT2, type/refactor, translation/from-docs, status/can-merge, status/PTAL, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, sig/planner, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7429 Remove store limit scene
  pd-control.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, sig/scheduling, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, v5.3

#7336 Remove cyclic replication feature
  experimental-features.md
  media/cdc-cyclic-replication.png
  releases/release-5.0.0.md
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/L, sig/migrate, v5.3

#7461 revise the format of store related command
  pd-control.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/scheduling

#7439 Correct a minor error
  tidb-configuration-file.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7467 chore: add link check ci
  .github/workflows/ci.yaml
  .github/workflows/link-check.yaml
Labels: status/LGT1, translation/done, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7450 add SASL config item for ticdc
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7479 *: add TiDB release timeline
  TOC.md
  _index.md
  releases/release-5.2.2.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, area/general, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7486 Update the value of txn-local-latches from enable to enabled
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/XS, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, ONCALL

#7485 fix a typo in the SQL example for troubleshoot-write-conflicts.md
  troubleshoot-write-conflicts.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, sig/transaction, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, ONCALL

#7497 revise description of TSO variables
  system-variables.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, sig/scheduling, v5.3

#7247 Update the description of pessimistic transaction
  best-practices/tidb-best-practices.md
  mysql-compatibility.md
  optimistic-transaction.md
  pessimistic-transaction.md
  releases/release-3.0-ga.md
  releases/release-3.0.0-rc.2.md
  sql-statements/sql-statement-begin.md
  sql-statements/sql-statement-commit.md
  system-variables.md
  transaction-overview.md
  troubleshoot-lock-conflicts.md
  whats-new-in-tidb-4.0.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, sig/transaction

#7500 refine TiCDC alter rules
  ticdc/ticdc-alert-rules.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, needs-cherry-pick-release-5.0, size/M, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7481 Update dashboard-profiling.md
  dashboard/dashboard-profiling.md
  media/dashboard/dashboard-profiling-access.png
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, sig/diagnosis, v5.3

#7430 tidb-lightning: max-error and duplicate-resolution
  TOC.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/XL, sig/migrate, v5.3

#7510 update sync-diff-inspector: update settings docs
  media/shard-table-sync-1.png
  sync-diff-inspector/route-diff.md
  sync-diff-inspector/shard-diff.md
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, sig/migrate, v5.3

#7444 Add docs for placement rules in SQL
  TOC.md
  configure-placement-rules.md
  information-schema/information-schema-placement-rules.md
  information-schema/information-schema.md
  placement-rules-in-sql.md
  schedule-replicas-by-topology-labels.md
  sql-statements/sql-statement-alter-placement-policy.md
  sql-statements/sql-statement-create-placement-policy.md
  sql-statements/sql-statement-drop-database.md
  sql-statements/sql-statement-drop-placement-policy.md
  sql-statements/sql-statement-show-create-placement-policy.md
  sql-statements/sql-statement-show-placement-for.md
  sql-statements/sql-statement-show-placement-labels.md
  sql-statements/sql-statement-show-placement.md
  system-variables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, status/PTAL, size/XXL, sig/sql-infra, v5.3

#7512 Update wording in placement rules in sql
  placement-rules-in-sql.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, sig/sql-infra, v5.3

#7499 Update continuous profiling.md
  dashboard/continuous-profiling.md
  dashboard/dashboard-profiling.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, v5.3

#7460 system variables: add `tidb_log_file_max_days`
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, sig/sql-infra, v5.3

#7511 Optimize description to caching conditions
  sql-prepare-plan-cache.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, sig/planner, v5.3

#7509 add note info for Online Unsafe Recovery
  TOC.md
  experimental-features.md
  online-unsafe-recovery.md
  pd-control.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, sig/engine, v5.3

#7517 Revert "tidb-lightning: max-error and duplicate-resolution"
  TOC.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, sig/migrate, v5.3

#7359 statistics: Add a note about the solution of a potential OOM issue
  statistics.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, ONCALL

#7518 Add some warnings about the use of the Tombstone API
  scale-tidb-using-tiup.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, sig/scheduling, ONCALL

#7519 Add a warning for unsafe recover
  tikv-control.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, sig/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, ONCALL

#7431 Fix typos in temporary table docs
  br/backup-and-restore-tool.md
  sql-plan-replayer.md
  temporary-table.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, sig/sql-infra

#7528 br: Add the tag of experimental-feature into encrypt-br
  br/use-br-command-line-tool.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, sig/migrate, v5.3

#7529 Change file name to temporary tables
  TOC.md
  mysql-compatibility.md
  system-variables.md
  temporary-tables.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/S, sig/sql-infra, v5.3

#7197 Update tidb-lightning-faq.md from OnCALL
  tidb-lightning/tidb-lightning-faq.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, ONCALL

#6789 cdc: modify descriptions related to Unified Sorter and data_dir
  ticdc/deploy-ticdc.md
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/docs, sig/migrate, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2

#7478 ticdc: update max-batch-size
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2

#7238 system-variables: correct the description of tidb_allow_fallback_to_tikv
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7417 sequence: remove the `order` keyword of sequence
  sql-statements/sql-statement-create-sequence.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7555 add a default value change description for 5.0 version
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, sig/migrate

#7504 improve csv separator notes
  dumpling-overview.md
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7041 ticdc: add description about gc-ttl
  media/ticdc-state-transfer.png
  ticdc/deploy-ticdc.md
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, sig/docs, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7562 fix the declaration about `INNODB_TEMP_TABLE_INFO`
  temporary-tables.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/sql-infra, v5.3, needs-cherry-pick-release-5.3

#7579 add version information
  TOC.md
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7581 chore: list as the first child in TOC
  TOC.md
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XXL, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7198 Update migrate-from-csv-using-tidb-lightning.md
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7585 change the download link for sync-diff-inspector
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/migrate, ONCALL

#7466 Update description to tidb_scatter_region
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7338 Docs: revise the status information of a TiKV store
  faq/deploy-and-maintain-faq.md
  tidb-scheduling.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, sig/scheduling

#7606 remove stale configuration `raftstore.raft-reject-transfer-leader-duration`
  dynamic-config.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/XS, type/compatibility-or-feature-change, v5.3, needs-cherry-pick-release-5.3

#7608 update the download link for sync-diff-inspector
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS

#7541 ticdc: GA TiCDC open API
  ticdc/ticdc-open-api.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, sig/migrate, v5.3, needs-cherry-pick-release-5.3

#7204 optimization config desc
  ticdc/manage-ticdc.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7549 Add description for --log-file parameter
  tidb-lightning/tidb-lightning-configuration.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7540 Add v5.3 TPCH report
  TOC.md
  benchmark/v5.3-performance-benchmarking-with-tpch.md
  media/tidb-v5.2-tpch-100-vs-gp-spark.png
  media/tidb-v5.3-tpch-100-vs-gp-spark.png
Labels: status/LGT2, translation/done, status/can-merge, size/S, v5.3, needs-cherry-pick-release-5.3

#7542 Add aliases to v5.2 TPCH report
  benchmark/v5.2-performance-benchmarking-with-tpch.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS

#7377 Add warning about data_lock_waits table won't record optimistic transaction blocked by pessimistic transaction
  information-schema/information-schema-data-lock-waits.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/XS, sig/transaction, needs-cherry-pick-release-5.3

#7597 ticdc: update java example link
  ticdc/ticdc-open-protocol.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate

#7561 Bump versions for tiup related content for 5.3.0
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/tiup, v5.3, needs-cherry-pick-release-5.3

#7604 sync-diff-inspector: add annontation for option configuration items
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/migrate, v5.3, needs-cherry-pick-release-5.3

#7361 Update dumpling-overview.md
  dumpling-overview.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7398 Update transaction types panel name
  grafana-tidb-dashboard.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/transaction, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7498 update ticdc recommended disk size
  hardware-and-software-requirements.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7188 Correct "cronyd" to "chronyd" and add a description
  check-before-deployment.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT2, needs-cherry-pick-release-5.0, size/XS, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7427 Update transaction-overview.md
  transaction-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/XS, sig/transaction, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7443 Optimize the description of disabling swap
  check-before-deployment.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7347 update max-backups desc
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7660 sync-diff-inspector: update docker link
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, ONCALL

#7521 Bump version for v5.3.0 - ecosystem tools
  download-ecosystem-tools.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-dm-import.md
  tiup/tiup-component-dm.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, v5.3, needs-cherry-pick-release-5.3

#7664 update plan replayer doc
  sql-plan-replayer.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, sig/planner, v5.3, needs-cherry-pick-release-5.3

#7666 chore: update generate pdf scripts
  scripts/merge_by_toc.py
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7397 Add-a-sub-title-for-tiup-cluster-scale-in
  scale-tidb-using-tiup.md
  tiup/tiup-component-cluster-scale-in.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7675 ticdc open protocol: fix a typo
  ticdc/ticdc-open-protocol.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, sig/migrate

#7627 Fix the user docs of table attributes
  table-attributes.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, sig/scheduling, v5.3, needs-cherry-pick-release-5.3

#7605 fix the expression about creating sql user when enabling sem
  dashboard/dashboard-user.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/diagnosis, v5.3, needs-cherry-pick-release-5.3

#7683 update `sort-dir` supported version
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7693 Add the TPC-H result graphics
  media/tidb-v5-tpch-100-vs-gp-spark.png
  media/tidb-v5.2-tpch-100-vs-gp-spark.png
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS

#7409 update some alert rules
  alert-rules.md
  tidb-troubleshooting-map.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, sig/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7701 Optimize wording for tidb-computing
  tidb-computing.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7686 tidb: warn limitations of placement rules dict syntax
  placement-rules-in-sql.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/S, sig/sql-infra, v5.3, needs-cherry-pick-release-5.3

#7710 lightning: fix lightning distribute import config
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7694 add v530 benchmark documents
  TOC.md
  benchmark/benchmark-sysbench-v5.3.0-vs-v5.2.2.md
  benchmark/v5.3-performance-benchmarking-with-tpcc.md
  media/sysbench_v522vsv530_point_select.png
  media/sysbench_v522vsv530_read_write.png
  media/sysbench_v522vsv530_update_index.png
  media/sysbench_v522vsv530_update_non_index.png
  media/tpcc_v522_vs_v530.png
Labels: status/LGT2, translation/doing, status/can-merge, status/PTAL, size/XL, v5.3, needs-cherry-pick-release-5.3

#7685 change-tiup-related-content
  quick-start-with-tidb.md
  tiup/tiup-playground.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, sig/tiup, v5.3, needs-cherry-pick-release-5.3

#7717 Add a missing note to v4.0.9 release notes
  releases/release-4.0.9.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7449 Update basic-features.md for v5.3
  basic-features.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, v5.3, needs-cherry-pick-release-5.3

#7369 add v5.3 release notes
  TOC.md
  _index.md
  pd-control.md
  pd-recover.md
  releases/release-5.3.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, v5.3, needs-cherry-pick-release-5.3

#7593 update experimental features for v5.3
  experimental-features.md
Labels: status/LGT2, translation/done, translation/doing, status/can-merge, size/S, v5.3, needs-cherry-pick-release-5.3

#7628 Add doc for raftstore asynchronous write io
  tikv-configuration-file.md
  tune-tikv-thread-performance.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, sig/engine, v5.3, needs-cherry-pick-release-5.3

#7730 Fix typos in tidb 5.3.0 release notes
  releases/release-5.3.0.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/M, v5.3, needs-cherry-pick-release-5.3

#7733 add links for some config items to release notes 5.3.0
  releases/release-5.3.0.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, v5.3, needs-cherry-pick-release-5.3

#7724 fix a note rendering error
  quick-start-with-tidb.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7731 Delete a duplicated line in the example in explain-indexes.md
  explain-indexes.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7692 Fix error on conversion between date and time types
  data-type-date-and-time.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7659 alert-rules.md: Updated alter rule's promql expression.
  alert-rules.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, sig/diagnosis, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7572 Update tiup-component-cluster-scale-in.md
  tiup/tiup-component-cluster-scale-in.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7551 chore: update dispatch in release-5.3
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S

#7759 Fix rendering failures caused by wrong format
  .github/workflows/dispatch.yml
  releases/release-5.3.0.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/S, v5.3, needs-cherry-pick-release-5.3
