Repository pingcap/docs-cn, pull requests merged in 2021-06, with the labels that each got.

#6371 Enhance TiDB login descriptions
  dashboard/dashboard-access.md
  post-installation-check.md
Labels: needs-cherry-pick-release-5.0, size/XS, status/LGT2, status/can-merge, translation/doing

#6382 Fix a typo in system-variables.md
  system-variables.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6386 Fix typo: tispark-overview.md
  tispark-overview.md
Labels: contribution, first-time-contributor, needs-cherry-pick-release-2.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/done

#6394 Update Ubuntu requirements.
  hardware-and-software-requirements.md
Labels: first-time-contributor, needs-cherry-pick-master, needs-cherry-pick-release-4.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6381 Add documentation for SEM
  system-variables.md
  tidb-configuration-file.md
Labels: sig/docs, sig/sql-infra, size/S, status/LGT2, status/can-merge, translation/from-docs, v5.1

#6406 Add new telemetry feature
  telemetry.md
Labels: needs-cherry-pick-master, requires-version-specific-changes, size/XS, status/LGT1, status/can-merge, translation/doing

#6407 Add docs for dynamic privileges
  privilege-management.md
Labels: requires-followup, sig/docs, sig/sql-infra, size/L, status/LGT2, status/can-merge, translation/from-docs, v5.1

#6417 Update optimistic-transaction.md
  optimistic-transaction.md
Labels: needs-cherry-pick-master, needs-cherry-pick-release-4.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6421 Update SQL Keywords and Reserved Words to CAPS
  mysql-compatibility.md
Labels: contribution, first-time-contributor, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/welcome

#6220 Add document for CTE
  TOC.md
  sql-statements/sql-statement-with.md
Labels: size/L, status/LGT2, status/can-merge, translation/doing, v5.1

#6265 system variables: add system variable cte_max_recursion_depth
  system-variables.md
Labels: size/XS, status/LGT2, status/can-merge, translation/doing, v5.1

#6425 tikv: add configuration docs for I/O rate limiter
  tikv-configuration-file.md
Labels: size/S, status/LGT2, status/can-merge, translation/from-docs, v5.1

#6429 update tiflash documents about cartesian join support
  tiflash/use-tiflash.md
Labels: size/XS, status/LGT2, status/can-merge, translation/doing, v5.1

#6427 mpp support new ops
  tiflash/use-tiflash.md
Labels: size/XS, status/LGT2, status/can-merge, translation/doing, v5.1

#6431 Fix typos in 4.0.13 release notes
  releases/release-4.0.13.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/doing

#6405 tidb-binlog: support binlog for clustered index
  clustered-indexes.md
  tidb-binlog/tidb-binlog-overview.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-release-5.0, requires-version-specific-changes, size/S, status/LGT2, status/can-merge, status/require-change, translation/doing, v5.1

#6385 releases: add tidb 5.0.2 release notes
  TOC.md
  releases/release-5.0.2.md
  releases/release-notes.md
Labels: needs-cherry-pick-release-5.0, requires-version-specific-changes, size/L, status/LGT2, status/can-merge, translation/from-docs

#6436 Fix a typo
  releases/release-5.0.2.md
Labels: needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6428 Update tiflash supported pushdown expression list
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-release-5.0, size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6438 Clarify a note in 5.0.2 release notes
  releases/release-5.0.2.md
Labels: needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6397 tikv config: hibernate region GA
  best-practices/massive-regions-best-practices.md
  experimental-features.md
  system-variables.md
  ticdc/ticdc-overview.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-release-5.0, size/S, status/LGT2, status/can-merge, status/require-change, translation/doing, v5.1

#6410 optimizer: modify docs for analyze behavior
  statistics.md
Labels: sig/docs, sig/execution, sig/planner, size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6442 Add a note to clarify the purpose of the quick start guide
  quick-start-with-tidb.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT2, status/can-merge, translation/doing

#6418 tikv: update cdc config
  tikv-configuration-file.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6430 fix system table replica doc
  tiflash/use-tiflash.md
Labels: size/XS, status/LGT2, status/can-merge, translation/doing, v5.1

#6413 modify the column type change doc
  mysql-compatibility.md
  sql-statements/sql-statement-change-column.md
  sql-statements/sql-statement-modify-column.md
Labels: sig/docs, sig/sql-infra, size/L, status/LGT2, status/can-merge, translation/doing, v5.1

#6408 Add Lock View related documents
  TOC.md
  information-schema/information-schema-data-lock-waits.md
  information-schema/information-schema-deadlocks.md
  information-schema/information-schema-tidb-trx.md
  information-schema/information-schema.md
  tidb-configuration-file.md
  troubleshoot-lock-conflicts.md
Labels: size/XXL, status/LGT2, status/can-merge, translation/doing, v5.1

#6401 Update the tools part in roadmap.md
  roadmap.md
Labels: needs-cherry-pick-release-5.0, require-LGT1, requires-followup, size/S, status/LGT1, status/can-merge, translation/doing, v5.1

#6403 br: add a document for backup restore systables
  br/backup-and-restore-tool.md
Labels: size/S, status/LGT2, status/can-merge, status/require-change, translation/doing, v5.1

#6347 add document about stale read transaction
  TOC.md
  as-of-timestamp.md
  best-practices/three-dc-local-read.md
  read-historical-data.md
  sql-statements/sql-statement-select.md
  sql-statements/sql-statement-set-transaction.md
  sql-statements/sql-statement-start-transaction.md
  stale-read.md
Labels: size/XL, status/LGT2, status/can-merge, translation/doing, v5.1

#6450 update permissions required for BACKUP and RESTORE
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
Labels: size/XS, status/LGT2, status/can-merge, translation/from-docs

#6415 ticdc: update a changefeed state transfer doc
  media/ticdc-state-transfer.png
  ticdc/manage-ticdc.md
Labels: size/M, status/LGT2, status/can-merge, translation/doing, v5.1

#6449 resolevd-ts: add resolved-ts related config doc
  tikv-configuration-file.md
Labels: size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6404 ticdc: remove a experimental feature
  experimental-features.md
  ticdc/ticdc-open-protocol.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT2, status/can-merge, translation/doing

#6399 TiKV config: add abort-on-panic
  tikv-configuration-file.md
Labels: needs-cherry-pick-release-5.0, requires-version-specific-changes, size/S, status/LGT2, status/can-merge, translation/doing

#6452 *: update PD configuration
  pd-configuration-file.md
  pd-control.md
Labels: size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6451 system-variables: add init connect
  system-variables.md
Labels: size/XS, status/LGT2, status/can-merge, translation/from-docs, v5.1

#6453 stale-read: fix ebnf diagram and update the docs
  as-of-timestamp.md
  pd-control.md
  sql-statements/sql-statement-select.md
  stale-read.md
Labels: size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6460 tidb-binlog: correct a typo
  clustered-indexes.md
Labels: needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/no-need

#6464 Add docs for sysvar cache
  system-variables.md
Labels: requires-followup, requires-version-specific-changes, size/XS, status/LGT2, status/can-merge, translation/from-docs, v5.1

#6467 update docs related to partition table dynamic mode
  experimental-features.md
  partitioned-table.md
  system-variables.md
Labels: size/L, status/LGT2, status/can-merge, translation/doing, v5.1

#6468 Clarify tidb lightning backend description
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
Labels: needs-cherry-pick-master, needs-cherry-pick-release-5.0, sig/docs, sig/migrate, size/XS, status/LGT1, status/can-merge, translation/doing

#6250 add docs for enforce mpp
  system-variables.md
  tidb-configuration-file.md
  tiflash/use-tiflash.md
Labels: size/M, status/LGT2, status/can-merge, translation/doing, v5.1

#6474 Update content about upgrade
  upgrade-tidb-using-tiup.md
Labels: size/M, status/LGT2, status/can-merge, translation/doing, v5.1

#6480 Correct the region IDs in the show table example
  sql-statements/sql-statement-show-table-regions.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT2, status/can-merge, translation/doing

#6484 lightning: fix a lightning config bug
  migrate-from-aurora-using-lightning.md
Labels: missing-translation-status, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#6489 Fix a typo in tune-os-
  tune-operating-system.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#5783 Update tidb-configuration-file.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-release-5.1, sig/docs, sig/sql-infra, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/done, v5.1

#6494 system variables: add `tidb_analyze_version`
  statistics.md
  system-variables.md
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6504 Fix typos
  sql-statements/sql-statement-with.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/done

#6476 stale-read: adjust the TOC
  TOC.md
  as-of-timestamp.md
  best-practices/three-dc-local-read.md
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/done

#6507 Delete docker deployment docs
  deploy-test-cluster-using-docker-compose.md
  faq/deploy-and-maintain-faq.md
  production-deployment-using-tiup.md
  test-deployment-using-docker.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, requires-version-specific-changes, size/XL, status/LGT2, status/can-merge, translation/doing

#6515 Fix ebnf display
  sql-statements/sql-statement-with.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, status/LGT1, status/can-merge, translation/done

#6499 add v510 benchmark doc
  TOC.md
  benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md
  benchmark/v5.1-performance-benchmarking-with-tpcc.md
  media/sysbench_v510vsv502_point_select.png
  media/sysbench_v510vsv502_read_write.png
  media/sysbench_v510vsv502_update_index.png
  media/sysbench_v510vsv502_update_non_index.png
  media/tpcc_v510_vs_v502.png
Labels: needs-cherry-pick-release-5.1, size/XL, status/LGT2, status/can-merge, translation/doing, v5.1

#6483 change docs-cn configs to release-5.1
  .circleci/config.yml
  .github/workflows/dispatch.yml
Labels: size/S, status/LGT1, status/can-merge, translation/done

#6510 Add v5.1 mpp tpch test report
  TOC.md
  benchmark/v5.1-performance-benchmarking-with-tpch.md
  media/tidb-v5-tpch-100-vs-gp-spark.png
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/PTAL, status/can-merge, translation/doing, v5.1

#6511 Add alias for 5.0 mpp test report in dev
  benchmark/v5.0-performance-benchmarking-with-tpch.md
Labels: require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6518 Add note about stale read
  as-of-timestamp.md
  experimental-features.md
  stale-read.md
Labels: missing-translation-status, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6517 Bump version for v5.1.0
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-bench.md
  tiup/tiup-command-mirror-rotate.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
Labels: needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, translation/doing, v5.1

#6525 Fix stale read note
  as-of-timestamp.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/no-need

#6527 Bump missing version
  download-ecosystem-tools.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, status/LGT1, status/can-merge, translation/no-need

#6455 Add the release notes for v5.1
  TOC.md
  _index.md
  releases/release-5.1.0.md
  releases/release-notes.md
  sql-statements/sql-statement-modify-column.md
Labels: needs-cherry-pick-release-5.1, size/XL, status/LGT2, status/can-merge, translation/doing, v5.1

#6531 Removed an unneeded line break from 5.1 release note
  releases/release-5.1.0.md
Labels: needs-cherry-pick-master, size/XS, status/LGT2, status/can-merge, translation/doing

#6522 fix ctc doc
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-change-column.md
  sql-statements/sql-statement-modify-column.md
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6503 Update configure-memory-usage.md
  configure-memory-usage.md
Labels: needs-cherry-pick-master, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1, size/XS, status/LGT1, status/can-merge, translation/doing

#6533 system-variables: ensure alphabetical order
  system-variables.md
Labels: needs-cherry-pick-release-5.0, require-LGT1, requires-version-specific-changes, size/L, status/LGT1, status/can-merge, translation/from-docs

#6539 Update dumpling-overview.md
  dumpling-overview.md
Labels: contribution, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1, size/XS, status/LGT1, status/can-merge, translation/doing

#6549 Not support to set Tombstone
  scale-tidb-using-tiup.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, sig/docs, sig/scheduling, size/S, status/LGT2, status/can-merge, translation/doing

#6541 Add workaround about using Stale Read with TiFlash
  as-of-timestamp.md
Labels: needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, translation/done

#6555 *: update roadmap
  roadmap.md
Labels: needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, translation/done

#6560 partitioned-table: adding the correction to incorrect examples
  partitioned-table.md
Labels: needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, translation/doing
