Repository pingcap/docs-cn, pull requests merged in 2021-09, with the labels that each got.

#7042 Fix 2 broken links of tiup config files
  production-offline-deployment-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, size/XS

#7016 add warning messages
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7000 tiup-component-cluster-import.md: fix a typo
  tiup/tiup-component-cluster-import.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7040 Fix typos in incremental-replication-between-clusters.md
  incremental-replication-between-clusters.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.2

#7039 tikv-config: Fix wrong description
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/docs, sig/engine, needs-cherry-pick-release-5.2

#6757 Remove two deprecated flags
  command-line-flags-for-tidb-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, sig/execution, sig/docs, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#6996 tikv configs: add 7 log-related configs
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7007 `kill`: improve kill's description
  sql-statements/sql-statement-kill.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7064 tiflash: Add label schedule for TiFlash.
  tiflash/use-tiflash.md
Labels: type/enhancement, status/LGT2, status/can-merge, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7072 br: rename 命令 to 进程
  br/backup-and-restore-faq.md
  br/use-br-command-line-tool.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/docs, sig/migrate

#6859 sysvar: update doc for tidb_opt_prefer_range_scan
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/planner, sig/docs

#7071 kill: update kill's description
  sql-statements/sql-statement-kill.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#6837 partitioning: Corrected partition management
  partitioned-table.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-5.0, size/S, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#6848 add `referential_constraints` under "information-schema"
  TOC.md
  information-schema/information-schema-referential-constraints.md
  information-schema/information-schema.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.2

#7076 system variables: revise description about `tidb_opt_prefer_range_scan`
  system-variables.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/planner, sig/docs

#7085 chore: add dispatch back
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S

#6674 br: add ratelimit in br commands
  br/use-br-command-line-tool.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/S, sig/docs, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7086 release-notes: add 5.2.1 release notes
  TOC.md
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  releases/release-5.2.0.md
  releases/release-5.2.1.md
  releases/release-notes.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, sig/scheduling, sig/planner, sig/docs, needs-cherry-pick-release-5.2

#7073 tidb: fix placement doc
  configure-placement-rules.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, sig/scheduling, sig/docs, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7074 explore-htap: Update the HTAP blog address
  explore-htap.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, sig/docs, needs-cherry-pick-release-5.2, sig/bigdata

#6782 update the "grafana-tidb-dashboard.md"
  grafana-tidb-dashboard.md
Labels: type/enhancement, status/LGT1, contribution, translation/doing, status/can-merge, require-LGT1, first-time-contributor, size/L, sig/docs, sig/diagnosis

#7043 faq: add info for schema is changed error
  faq/sql-faq.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7006 SQL statement: add a doc "ADMIN SHOW TELEMETRY"
  TOC.md
  sql-statements/sql-statement-admin-show-telemetry.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XL, sig/tiup, sig/docs

#7104 Temporarilty disable zh.md to avoid jenkins error-reporting
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7116 tidb: fix default value of `performance.committer-concurrency`
  tidb-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, requires-version-specific-changes, require-LGT1, size/XS, sig/planner, sig/docs, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7084 fix-enable-compaction-filter-in-tikv-configuration-file
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, sig/docs, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#6884 docs: update pd-configuration about upgrade
  pd-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, status/PTAL, size/S, sig/scheduling, sig/docs, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2

#7127 fix example for expression index
  sql-statements/sql-statement-create-index.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.2

#7093 *: Add use Auth0 as example to login dashboard by sso
  dashboard/dashboard-session-sso.md
  media/dashboard/dashboard-session-sso-auth0-create-app.png
  media/dashboard/dashboard-session-sso-auth0-settings-1.png
  media/dashboard/dashboard-session-sso-auth0-settings-2.png
  media/dashboard/dashboard-session-sso-auth0-settings-3.png
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, sig/docs, sig/diagnosis, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7135 system-variables: improve noop functions warning
  system-variables.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7146 revise the format of `ADMIN SHOW TELEMETRY` in TOC file
  TOC.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/tiup, sig/docs

#7142 tidb-configuration-file: correct the default value of committer-concurrency
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS

#7153 reword some descriptions in MySQL Compatibility
  mysql-compatibility.md
Labels: status/LGT2, status/can-merge, missing-translation-status, size/XS

#7159 reword some descriptions in MySQL Compatibility (#7153)
  mysql-compatibility.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, size/XS

#7165 Correct description about DELETE space release
  faq/sql-faq.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/scheduling, sig/docs, sig/sql-infra, sig/engine, needs-cherry-pick-release-5.2

#7139 Tune TiKV: change the default value of `grpc-concurrency`
  tune-tikv-thread-performance.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/docs, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7147 performance_schema -> information_schema
  statement-summary-tables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7175 update the example in show-processlist
  sql-statements/sql-statement-show-processlist.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/S, sig/sql-infra, needs-cherry-pick-release-5.2

#7183 update some desc
  tune-tikv-thread-performance.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-release-5.0, size/XS, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7129 releases: add tidb 4.0.15 release notes
  TOC.md
  releases/release-4.0.15.md
  releases/release-notes.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7112 releases: add tidb 5.0.4 release notes
  TOC.md
  releases/release-5.0.4.md
  releases/release-notes.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7148 For 4.0.15: tikv(cdc): dynamic online change cdc configuration
  dynamic-config.md
Labels: status/LGT2, translation/done, status/can-merge, missing-translation-status, size/XS, sig/docs, sig/migrate, type/compatibility-or-feature-change

#7199 bump version for v4.0.15
  download-ecosystem-tools.md
  pd-recover.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-cluster-deploy.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/doing, status/can-merge

#7200 bump version for 5.0.4
  download-ecosystem-tools.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-cluster-deploy.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/doing, status/can-merge, size/M

#7202 Add the hint LIMIT_TO_COP()
  optimizer-hints.md
Labels: type/enhancement, translation/doing, size/S, sig/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7203 Move a note in 4.0.15
  releases/release-4.0.15.md
Labels: translation/doing, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7212 remove a unnecessary line
  optimizer-hints.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS

#7149 releases notes: add 5.1.2 release notes
  TOC.md
  releases/release-5.1.2.md
  releases/release-notes.md
Labels: status/LGT1, translation/from-docs, size/L, sig/docs, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7201 bump version for 5.1.2
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/doing

#7176 Update tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-faq.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7161 Add desc of "Storage Write Stall" row in the TiFlash grafana
  tiflash/monitor-tiflash.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/S, sig/docs, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, sig/bigdata

#7222 chore: remove circleci config
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#7230 Delete config.yml
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge, size/L

#7224 Delete config.yml
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge

#7225 Delete config.yml
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge, size/L

#7227 Delete config.yml
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge, size/L

#7228 Delete config.yml
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge, size/L

#7229 Delete config.yml
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge, size/L

#7226 Delete config.yml
  .circleci/config.yml
Labels: status/LGT1, translation/no-need, status/can-merge

#7152 release-5.2.0: Add info about caching_sha2
  releases/release-5.2.0.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.2

#7145 5.1.0 release notes: add the changes to committer-concurrency
  releases/release-5.0.1.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2

#7141 Update system-variables.md
  system-variables.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, first-time-contributor, size/M, sig/docs, sig/sql-infra, needs-cherry-pick-release-5.2

#7134 Remove a tikv config that should not have existed in 4.0
  tikv-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/docs, sig/migrate
