Repository pingcap/docs-cn, pull requests merged in 2021-02, with the labels that each got.

#5453 .github: add asktug link in issue template
  .github/ISSUE_TEMPLATE/change-request.md
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/question.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, status/LGT1, translation/doing

#5468 Fix a typo in a statement example
  sql-plan-management.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5455 Add config of TiFlash coprocessor thread pool
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/PTAL, translation/doing, version-specific-changes-required

#5466 *: add multiple interrelated links and update description
  _index.md
  br/backup-and-restore-faq.md
  overview.md
  ticdc-deployment-topology.md
  tidb-architecture.md
  tidb-binlog-deployment-topology.md
  tidb-scheduling.md
  tidb-storage.md
  tiflash-deployment-topology.md
  tispark-deployment-topology.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, translation/doing, type/enhancement, version-specific-changes-required

#5155 mysql-compatibility: Add GROUP BY implicit order
  mysql-compatibility.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs

#5478 Filter 7 external links to pass ci check
  .github/workflows/link-check.yaml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/no-need

#5287 lightning: add using lighting to migrate aurora data tutorial
  TOC.md
  _index.md
  migrate-from-aurora-using-lightning.md
  migration-overview.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/large, status/LGT3, translation/doing

#5388 fix a typo in ticdc-grafana-dashboard.md
  TOC.md
  ticdc/monitor-ticdc.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/done

#5483 Distinguish `explain <table_name>` and `explain table <table_name>`.
  sql-statements/sql-statement-show-columns-from.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5467 Correct the max column count in tidb-limitations.md
  tidb-limitations.md
Labels: size/small, status/LGT1, translation/doing

#5499 media: use sentence case in tidb-architecture.png
  media/tidb-architecture-1.png
  media/tidb-architecture.png
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/from-docs

#5454 br: add minimum requirements
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, translation/doing

#5475 Add `tiup ctl pd` command in tiup page.
  scale-tidb-using-tiup.md
Labels: needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, status/PTAL, translation/doing

#5438 Fix hibernate region config link error
  best-practices/massive-regions-best-practices.md
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/from-docs

#5456 ticdc: the default value of old value is true
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5515 Refine a description for PD scheduling best practices
  best-practices/pd-scheduling-best-practices.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing, type/bug-fix

#5514 tidb-lightning: add filtering parameters and their descriptions
  get-started-with-tidb-lightning.md
Labels: first-time-contributor, needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, status/PTAL, translation/doing

#5504 Delete Grant privilege in privilege-management.md
  privilege-management.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/done

#5530 tidb-lightning: fix wrong aliases in faq
  tidb-lightning/tidb-lightning-faq.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#5531 doc: fix ddl reorg priority scope problem
  system-variables.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs

#5537 tikv-config-file: update the default value of use-unified-pool
  tikv-configuration-file.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs

#5471 ticdc: update ticdc glossary
  TOC.md
  glossary.md
  ticdc/ticdc-glossary.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/medium, status/LGT2, status/PTAL, translation/doing

#5543 update tiflash pushdown whitelist
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing

#5411 ticdc: add a faq
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-5.0, size/medium, status/LGT2, status/require-change, translation/doing

#5549 rename blacklist-control-plan to blocklist-control-plan
  TOC.md
  analyze-slow-queries.md
  blocklist-control-plan.md
  column-pruning.md
  control-execution-plan.md
  correlated-subquery-optimization.md
  tiflash/use-tiflash.md
  topn-limit-push-down.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing, version-specific-changes-required

#4933 explain: add joins
  explain-joins.md
Labels: follow-up, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/from-docs

#4913 explain: add indexes
  explain-indexes.md
Labels: follow-up, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/large, status/LGT1, status/PTAL, translation/from-docs

#5511 Add tidb-backend necessary instructions
  migrate-from-mysql-dumpling-files.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing

#5562 Media: Update tidb-architecture-1.png
  media/tidb-architecture-1.png
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/done

#5323 Update parameter type description
  tidb-configuration-file.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5566 media: update the TiDB architecture image
  media/tidb-architecture-1.png
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, status/LGT1, status/can-merge, translation/done

#5034 `--consistency auto` description change
  dumpling-overview.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5457 ticdc: using canal or maxwell protocol will not throw an exception
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5173 Update BR automatic GC version
  br/use-br-command-line-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#5579 Fix a typo in tiup-faq.md
  tiup/tiup-faq.md
Labels: first-time-contributor, needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, translation/no-need, type/bug-fix

#5541 improve system-variables documentation
  system-variables.md
Labels: needs-cherry-pick-5.0, size/large, status/LGT2, status/PTAL, translation/from-docs

#5460 tispark: add a description in tispark overview
  tispark-overview.md
Labels: first-time-contributor, needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, status/PTAL, translation/doing

#5594 fix a typo in tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-overview.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-5.0, needs-cherry-pick-master, status/LGT1, status/PTAL, translation/no-need

#5593 tiup: update version info in scale-tidb-using-tiup.md
  scale-tidb-using-tiup.md
Labels: needs-cherry-pick-5.0, status/LGT1, translation/from-docs

#5542 Add details about `table-column-count-limit` and `index-limit`
  tidb-configuration-file.md
  tidb-limitations.md
Labels: first-time-contributor, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5601 Fix a typo in deploy-and-maintain-faq.md
  faq/deploy-and-maintain-faq.md
Labels: needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, translation/no-need

#5605 Fix a wrong tikv config name
  best-practices/massive-regions-best-practices.md
  garbage-collection-configuration.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/from-docs, type/bug-fix

#5613 lightning: fix ambiguous description
  migrate-from-aurora-using-lightning.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/done

#5616 media: rename tidb-architecture.png
  architecture.md
  media/tidb-architecture-v3.1.png
  media/tidb-architecture.png
Labels: status/LGT1, translation/doing

#5618 media: rename image for consistent naming with docs
  media/tidb-architecture-v3.1.png
  tidb-architecture.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/from-docs

#5458 releases: add tidb v4.0.11 release notes
  TOC.md
  releases/release-4.0.11.md
  releases/release-notes.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/from-docs

#5625 tiup: fix a broken link
  maintain-tidb-using-tiup.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  tiup/tiup-cluster.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, status/PTAL, translation/done
