Repository pingcap/docs-cn, pull requests merged in 2021-01, with the labels that each got.

#5196 update description of the variable `tidb_opt_agg_push_down`
  system-variables.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5208 Fix bugs in 5.0 docs
  _index.md
  backup-and-restore-using-dumpling-lightning.md
  log-redaction.md
  system-variables.md
  three-data-centers-in-two-cities-deployment.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/done, type/bug-fix

#5201 tiflash: Update tiflash note of importing data by Lightning
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/done

#5182 Added capacity-mb and `admission-max-result-mb` parameter value types
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5161 tools: add some faq for br, cdc and binlog
  br/backup-and-restore-faq.md
  br/backup-and-restore-tool.md
  glossary.md
  ticdc/ticdc-overview.md
  ticdc/troubleshoot-ticdc.md
  tidb-binlog/handle-tidb-binlog-errors.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/large, status/LGT2, status/PTAL, translation/doing

#5160 Add a note to release-4.0.9.md
  releases/release-4.0.9.md
Labels: first-time-contributor, needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, status/PTAL, translation/doing

#5178 tidb-scheduling: unify the term replica
  tidb-scheduling.md
Labels: first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/no-need

#5250 Fix a display error caused by wrong format
  pd-control.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/no-need

#5254 Fix a typo in 4.0 benchmark report
  benchmark/v4.0-performance-benchmarking-with-tpch.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/no-need

#4624 sql tuning: add EXPLAIN views
  explain-views.md
Labels: follow-up, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/medium, status/LGT1, status/PTAL, translation/from-docs

#5257 update link versions
  dashboard/dashboard-ops-deploy.md
  deploy-test-cluster-using-docker-compose.md
  ecosystem-tool-user-guide.md
  overview.md
  quick-start-with-tidb.md
  test-deployment-using-docker.md
Labels: require-LGT1, status/LGT1, status/can-merge, translation/from-docs

#5210 pd: make some configuration more clear
  pd-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing

#5234 Refine sections in tikv-configuration-file.md
  tikv-configuration-file.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5269 Fix a wrong tikv config value
  tikv-configuration-file.md
Labels: needs-cherry-pick-3.0, size/small, status/LGT1, status/PTAL, translation/no-need, type/bug-fix

#4680 sql-statements: update ddl assertions behavior
  mysql-compatibility.md
  sql-statements/sql-statement-alter-database.md
  sql-statements/sql-statement-alter-table.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/medium, status/LGT2, status/PTAL, status/require-change, translation/from-docs, version-specific-changes-required

#5268 lightning: merge lightning trouble shooting into faq
  TOC.md
  ecosystem-tool-user-case.md
  get-started-with-tidb-lightning.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-glossary.md
  tidb-troubleshooting-map.md
  troubleshoot-tidb-lightning.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/medium, status/LGT1, status/PTAL, translation/doing, version-specific-changes-required

#5220 Update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5274 Added attention to online parameter changes
  dynamic-config.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing

#5221 ticdc: add metrics doc
  TOC.md
  media/ticdc/ticdc-dashboard-changefeed-1.png
  media/ticdc/ticdc-dashboard-changefeed-2.png
  media/ticdc/ticdc-dashboard-changefeed-3.png
  media/ticdc/ticdc-dashboard-events-1.png
  media/ticdc/ticdc-dashboard-events-2.png
  media/ticdc/ticdc-dashboard-events-3.png
  media/ticdc/ticdc-dashboard-overview.png
  media/ticdc/ticdc-dashboard-server.png
  media/ticdc/ticdc-dashboard-tikv-1.png
  media/ticdc/ticdc-dashboard-tikv-2.png
  ticdc/ticdc-grafana-dashboard.md
  tidb-monitoring-framework.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/large, status/LGT2, translation/doing

#5249 update patrol-region-interval 10ms -> 50ms
  pd-control.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5293 *: reviert list partition doc since it doesn't release in 5.0-rc
  partitioned-table.md
  system-variables.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5190 tiup version info modify(v4.0 -> v5.0)
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  tiup/tiup-bench.md
  tiup/tiup-cluster.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
Labels: needs-cherry-pick-5.0, size/large, status/LGT1, status/PTAL, translation/done, v5.0

#3975 Add doc for tidb_executor_concurrency
  system-variables.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing, v5.0

#5295 releases: add tidb 5.0-rc release notes
  TOC.md
  _index.md
  clustered-indexes.md
  dumpling-overview.md
  log-redaction.md
  maintain-tidb-using-tiup.md
  pd-configuration-file.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  releases/release-5.0.0-rc.md
  releases/release-notes.md
  scale-tidb-using-tiup.md
  system-variables.md
  tidb-configuration-file.md
  tikv-configuration-file.md
  upgrade-tidb-using-tiup.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/done, version-specific-changes-required

#5300 Update max column count in tidb-limitations.md
  tidb-limitations.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs

#5310 Fix a typo in 5.0 RC release notes
  releases/release-5.0.0-rc.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5304 release: add tidb 4.0.10 release notes
  TOC.md
  releases/release-4.0.10.md
  releases/release-notes.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/from-docs

#5315 tiup: delete doc from tiup list
  tiup/tiup-overview.md
Labels: first-time-contributor, status/LGT1

#5320 .github: use the latest stale action
  .github/workflows/stale.yml
Labels: status/LGT1, translation/doing

#5318 ticdc: update pd parameters in cdc cli command
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/medium, status/LGT2, status/PTAL, translation/doing

#5326 .github: Update stale.yml
  .github/workflows/stale.yml
Labels: status/LGT1, translation/doing

#5328 Fix an inconsistency between description and config
  hybrid-deployment-topology.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/doing

#5331 Fix a broken external link
  tiup/tiup-documentation-guide.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/no-need

#5327 Fix typos
  _index.md
  ticdc/troubleshoot-ticdc.md
  tidb-binlog/handle-tidb-binlog-errors.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/done, type/bug-fix

#5312 Add more info in upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, translation/doing

#5273 tiflash does not support 0.0.0.0
  quick-start-with-tidb.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5341 tidb-scheduling: fix typo
  tidb-scheduling.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/no-need

#5345 Fix a broken link
  tidb-lightning/tidb-lightning-faq.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, needs-cherry-pick-5.0, translation/no-need, version-specific-changes-required

#5344 Fix a broken external link
  data-type-numeric.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT1, translation/doing

#5324 sql-statements: use EBNF to render syntax diagrams for ADD, ALTER and ANALYZE statements
  expression-syntax.md
  sql-statements/sql-statement-add-column.md
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-admin-cancel-ddl.md
  sql-statements/sql-statement-admin-check-table-index.md
  sql-statements/sql-statement-admin-checksum-table.md
  sql-statements/sql-statement-admin-show-ddl.md
  sql-statements/sql-statement-admin.md
  sql-statements/sql-statement-alter-database.md
  sql-statements/sql-statement-alter-index.md
  sql-statements/sql-statement-alter-instance.md
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-analyze-table.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/doing, version-specific-changes-required

#5357 Update `kafka-version` description
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, translation/doing

#5361 Fix admission-max-result-mb parameter description
  tidb-configuration-file.md
Labels: first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/no-need

#5340 Refine a lightning image
  media/tidb-lightning-architecture.png
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/doing

#5368 Refine ecosystem tool guide document
  ecosystem-tool-user-guide.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/from-docs

#5303 add optimal parameter configrations.
  check-before-deployment.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/large, status/LGT2, translation/doing

#5377 Add 9 aliases to fix broken links
  comment-syntax.md
  functions-and-operators/cast-functions-and-operators.md
  geo-distributed-deployment-topology.md
  information-schema/information-schema-inspection-result.md
  pd-recover.md
  sql-statements/sql-statement-show-create-sequence.md
  support.md
  tiflash/tiflash-alert-rules.md
  upgrade-tidb-using-ansible.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#5380 chore: update dispatch event type
  .github/workflows/dispatch.yml
Labels: status/LGT1

#5379 docs-cn: add a new tidb configuration of coprocessor cache
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5378 Add incompatibility caused by deprecated features in mysql-compatibility.md
  mysql-compatibility.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/from-docs

#5400 chore: update CDN refresh
  .github/workflows/media.yml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/no-need

#5376 sql-statements: use EBNF to render syntax diagrams - second batch
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-begin.md
  sql-statements/sql-statement-change-column.md
  sql-statements/sql-statement-commit.md
  sql-statements/sql-statement-create-binding.md
  sql-statements/sql-statement-create-database.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-create-role.md
  sql-statements/sql-statement-create-sequence.md
  sql-statements/sql-statement-create-table-like.md
  sql-statements/sql-statement-create-table.md
  sql-statements/sql-statement-create-user.md
  sql-statements/sql-statement-create-view.md
  sql-statements/sql-statement-deallocate.md
  sql-statements/sql-statement-delete.md
  sql-statements/sql-statement-do.md
  sql-statements/sql-statement-drop-binding.md
  sql-statements/sql-statement-drop-column.md
  sql-statements/sql-statement-drop-database.md
  sql-statements/sql-statement-drop-index.md
  sql-statements/sql-statement-drop-role.md
  sql-statements/sql-statement-drop-sequence.md
  sql-statements/sql-statement-drop-stats.md
  sql-statements/sql-statement-drop-table.md
  sql-statements/sql-statement-drop-user.md
  sql-statements/sql-statement-drop-view.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/doing, version-specific-changes-required

#5413 Fix a typo in check-before-deployment.md
  check-before-deployment.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, translation/doing

#5325 metrics: update metrics query_summary
  grafana-tidb-dashboard.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5386 tidb: add doc for global kill
  sql-statements/sql-statement-kill.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#5299 BR: reorganize content about BR tool
  TOC.md
  backup-and-restore-using-dumpling-lightning.md
  br/backup-and-restore-faq.md
  br/backup-and-restore-tool.md
  br/backup-and-restore-use-cases.md
  br/use-br-command-line-tool.md
  download-ecosystem-tools.md
  ecosystem-tool-user-case.md
  releases/release-5.0.0-rc.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/doing

#5284 tools: update tools faq
  tidb-binlog/tidb-binlog-faq.md
  tidb-lightning/tidb-lightning-faq.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/large, status/LGT1, status/require-change, translation/doing

#5425 tiup: change unordered list to ordered list
  production-offline-deployment-using-tiup.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/from-docs

#5431 chore: fix an invalid character
  system-variables.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/no-need, type/bug-fix

#5412 metrics: update metrics guide server
  grafana-tidb-dashboard.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5434 Rename `Duration` to `Time`.
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, status/PTAL, translation/doing

#5443 ticdc: update max support kafka version
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing

#5447 Add 5 aliases to fix broken links
  information-schema/information-schema-cluster-config.md
  sql-statements/sql-statement-add-column.md
  sql-statements/sql-statement-create-user.md
  sql-statements/sql-statement-set-names.md
  tiflash/use-tiflash.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#5448 Fix 2 external broken links
  best-practices/tidb-best-practices.md
  data-type-numeric.md
  tidb-best-practices.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#5437 metrics: update metrics guide transaction
  grafana-tidb-dashboard.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing
