Repository pingcap/docs-cn, pull requests merged in 2021-03, with the labels that each got.

#5628 dumpling: Update tidb-mem-quota-query configuration instructions
  dumpling-overview.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5629 credits: replace tools with migrate
  credits.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5560 migrate: change titles to make it clear
  TOC.md
  migrate-from-aurora-mysql-database.md
  migrate-from-mysql-dumpling-files.md
  tidb-lightning/tidb-lightning-faq.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT2, status/PTAL, translation/doing

#5654 fix typo `bootsrap` in pd-recover.md
  pd-recover.md
Labels: needs-cherry-pick-3.0, status/LGT1, status/PTAL, translation/doing

#5652 Correct the default memory threshold for a single SQL statement
  tidb-troubleshooting-map.md
Labels: needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT1, translation/doing

#5640 Refine wording about severity in alert-rules.md
  alert-rules.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5642 Add document for tiup offline patch/upgrade
  best-practices/tidb-best-practices.md
  comment-syntax.md
  configure-load-base-split.md
  functions-and-operators/expressions-pushed-down.md
  tidb-best-practices.md
  tiup/tiup-command-mirror-grant.md
  tiup/tiup-command-mirror-sign.md
  tiup/tiup-command-status.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-dm-topology-reference.md
  tiup/tiup-reference.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5644 ticdc: Update ticdc mysql sink description
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5670 Fix a typo in partitioned-table.md
  partitioned-table.md
Labels: first-time-contributor, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, needs-cherry-pick-master, size/small, status/LGT2, translation/doing

#5612 tidb: Add configuration item description 'committer-concurrency'
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5683 Remove a config that does not exists
  benchmark/benchmark-sysbench-v4-vs-v3.md
  benchmark/v4.0-performance-benchmarking-with-tpcc.md
  media/tidb-architecture.png
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/from-docs

#5666 CI: add file format lint script to check manual line breaks and file encoding
  .circleci/config.yml
  agg-distinct-optimization.md
  benchmark/benchmark-tidb-using-sysbench.md
  best-practices/java-app-best-practices.md
  best-practices/tidb-best-practices.md
  character-set-and-collation.md
  command-line-flags-for-pd-configuration.md
  dashboard/dashboard-diagnostics-usage.md
  error-codes.md
  faq/sql-faq.md
  information-schema/information-schema-metrics-summary.md
  information-schema/information-schema-sql-diagnostics.md
  pd-configuration-file.md
  privilege-management.md
  production-offline-deployment-using-tiup.md
  quick-start-with-tidb.md
  read-historical-data.md
  releases/release-2.1.3.md
  releases/release-3.0.0-beta.1.md
  releases/release-3.0.4.md
  releases/release-rc.3.md
  releases/release-rc.4.md
  resources/markdownlint-rules.md
  role-based-access-control.md
  scripts/check-conflicts.py
  scripts/check-tags.py
  sql-statements/sql-statement-drop-user.md
  sql-statements/sql-statement-grant-privileges.md
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-set-role.md
  statistics.md
  subquery-optimization.md
  system-variables.md
  tidb-best-practices.md
  tidb-binlog/tidb-binlog-configuration-file.md
  tidb-binlog/tidb-binlog-faq.md
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
  tidb-lightning/tidb-lightning-checkpoints.md
  tidb-storage.md
  tikv-configuration-file.md
  tispark-overview.md
  troubleshoot-tidb-cluster.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/from-docs

#5687 Log redact on TiFlash
  log-redaction.md
Labels: needs-cherry-pick-5.0, size/small, status/LGT1, translation/doing

#5688 Log redact on TiFlash and PD (4.0)
  log-redaction.md
  pd-configuration-file.md
  tiflash/tiflash-configuration.md
Labels: size/medium, status/LGT2, translation/doing

#5697 Remove duplicate tidb-best-practices.md
  tidb-best-practices.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, translation/no-need

#5698 Remove duplicate tidb-best-practices.md
  tidb-best-practices.md
Labels: status/LGT1, translation/no-need, type/4.0-cherry-pick

#5700 Remove duplicate tidb-best-practices.md
  tidb-best-practices.md
Labels: status/LGT1, translation/no-need, type/5.0-cherry-pick

#5449 TiCDC: add trouble shooting info about DDL failures
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, size/medium, status/LGT2, translation/doing

#5689 Fix a typo in geo-distributed-deployment-topology.md
  geo-distributed-deployment-topology.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT1, status/PTAL, translation/doing

#5681 Remove notes & aliases for deprecated Ansible in TiUP docs
  maintain-tidb-using-tiup.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, status/PTAL, translation/from-docs, type/enhancement

#5673 Update compatibility for temporary tables in dev
  sql-statements/sql-statement-create-table.md
  system-variables.md
Labels: follow-up, size/small, status/LGT1, status/PTAL, translation/from-docs

#5708 br: correct command line usage
  br/use-br-command-line-tool.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, size/small, status/LGT1, translation/doing

#5450 BR, TiCDC: update br, cdc's docs and FAQ
  br/backup-and-restore-faq.md
  br/backup-and-restore-use-cases.md
  ticdc/troubleshoot-ticdc.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/L, status/LGT2, status/can-merge, translation/doing

#5707 fix wrong location of max-txn-ttl
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/small, status/LGT1, status/PTAL, translation/doing

#5686 update doc for split region
  best-practices/pd-scheduling-best-practices.md
  partitioned-table.md
  sql-statements/sql-statement-split-region.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/S, status/LGT2, status/can-merge, translation/doing

#5719 benchmark: add description to explain the non-index test result
  benchmark/v4.0-performance-benchmarking-with-tpch.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#5723 media: fix a cross-version image display error
  get-started-with-tidb-lightning.md
  media/tidb-lightning-architecture-v2.1.png
  media/tidb-lightning-architecture.png
  tidb-lightning/tidb-lightning-overview.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, size/XS, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5725 Add declaration for scopes of transaction related variables and configurations
  system-variables.md
  transaction-overview.md
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/S, status/LGT2, status/can-merge, translation/doing

#5731 .github: delete stale workflow
  .github/workflows/stale.yml
Labels: size/S, status/LGT2, status/can-merge, translation/done

#5730 Correct the title level of "Y 轴明暗交替：需要关注产生的热点聚集程度"
  dashboard/dashboard-key-visualizer.md
Labels: first-time-contributor, needs-cherry-pick-5.0, needs-cherry-pick-master, size/XS, status/LGT1, status/can-merge, translation/doing

#5528 *: generalize and link to the external storage docs from Lightning
  benchmark/benchmark-tidb-using-tpcc.md
  br/backup-and-restore-storages.md
  br/backup-and-restore-tool.md
  dumpling-overview.md
  ecosystem-tool-user-guide.md
  faq/migration-tidb-faq.md
  get-started-with-tidb-lightning.md
  migrate-from-mysql-dumpling-files.md
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
  table-filter.md
  tidb-lightning/monitor-tidb-lightning.md
  tidb-lightning/tidb-lightning-checkpoints.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-glossary.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-troubleshooting-map.md
  upgrade-tidb-using-tiup.md
Labels: follow-up, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/L, status/LGT2, status/PTAL, status/can-merge, translation/doing

#5716 faq, sysvars: add tidb_multi_statement_mode
  faq/tidb-faq.md
  system-variables.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/M, status/LGT2, status/PTAL, status/can-merge, translation/from-docs, version-specific-changes-required

#5753 Update grafana-tidb-dashboard.md
  grafana-tidb-dashboard.md
Labels: first-time-contributor, needs-cherry-pick-master, size/XS, size/small, status/LGT1, status/can-merge, translation/welcome

#5745 Update troubleshoot-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: first-time-contributor, needs-cherry-pick-5.0, needs-cherry-pick-master, size/XS, size/small, status/LGT1, status/can-merge, translation/welcome

#5762 Update statistics.md
  statistics.md
Labels: first-time-contributor, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/XS, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5758 Update compatibility for temporary tables
  sql-statements/sql-statement-create-table.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/doing, v5.0, version-specific-changes-required

#5699 docs: remove some config fields for copr cache
  tidb-configuration-file.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/done, v5.0

#5704 remove system variable `tidb_track_aggregate_memory_usage`
  system-variables.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/done, v5.0

#5755 enable compaction filter by default
  garbage-collection-configuration.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing, v5.0, version-specific-changes-required

#5770 hide the config global-kill
  explain-joins.md
  explain-overview.md
  explain-subqueries.md
  optimizer-hints.md
  sql-statements/sql-statement-kill.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/L, size/small, status/LGT1, status/can-merge, translation/doing, v5.0

#5756 tikv: Add ttl configuration
  tikv-configuration-file.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/doing, v5.0, version-specific-changes-required

#5740 update SPM documentation for DML SQL Bind and baseline capture
  sql-plan-management.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/L, status/LGT2, status/can-merge, translation/doing, v5.0

#5653 update doc for list partition table
  partitioned-table.md
  system-variables.md
Labels: needs-cherry-pick-5.0, size/L, status/LGT2, status/PTAL, status/can-merge, translation/doing, v5.0, version-specific-changes-required

#5736 update load base split config
  configure-load-base-split.md
  dynamic-config.md
Labels: needs-cherry-pick-5.0, size/S, status/LGT2, status/can-merge, translation/doing, v5.0

#5774 *: remove alter-primary-key configuration
  auto-random.md
  constraints.md
  dynamic-config.md
  mysql-compatibility.md
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-drop-index.md
  sql-statements/sql-statement-show-config.md
  tidb-configuration-file.md
  troubleshoot-hot-spot-issues.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/M, status/LGT1, status/PTAL, status/can-merge, translation/doing, v5.0

#5749 cdc: add more description about Unified Sorter
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/doing, v5.0, version-specific-changes-required

#5788 Remove private info in TiUP document
  tiup/tiup-bench.md
  tiup/tiup-cluster.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5792 sysvars: add tidb_skip_ascii_check
  system-variables.md
Labels: first-time-contributor, needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/PTAL, status/can-merge, translation/done, v5.0, version-specific-changes-required

#5739 tiflash: add more explanation for parameter `bg_task_io_rate_limit`
  tiflash/tiflash-configuration.md
Labels: needs-cherry-pick-5.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/doing

#5484 system variable: add tidb_allow_fallback_to_tikv
  system-variables.md
Labels: first-time-contributor, needs-cherry-pick-5.0, require-LGT1, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/done, v5.0

#5224 br:tidy up the incompatible issues in using BR tools.
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/M, status/LGT1, status/can-merge, translation/doing, version-specific-changes-required

#5804 chore: stop building release-5.0
  .circleci/config.yml
  .github/workflows/dispatch.yml
Labels: missing-translation-status, size/M, status/LGT1, status/can-merge

#5771 Update clustered-indexes.md
  clustered-indexes.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XL, status/LGT1, status/PTAL, status/can-merge, translation/doing, v5.0

#5790 Update the default value of joint consensus
  pd-configuration-file.md
Labels: first-time-contributor, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/done, v5.0

#5759 fix two typos in tiup-mirror-reference.md
  tiup/tiup-mirror-reference.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/PTAL, translation/no-need

#5810 chore: trigger preview build
  .github/workflows/dispatch.yml
Labels: missing-translation-status, size/XS, status/LGT1

#5607 update async commit related documentations
  sql-statements/sql-statement-start-transaction.md
  system-variables.md
  tidb-configuration-file.md
  transaction-overview.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/L, status/LGT2, status/can-merge, translation/doing, v5.0

#4819 SQL variables: add a new variable `tidb_enable_parallel_apply`
  system-variables.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/doing, v5.0

#5728 Tiup 5.0: update deploy, upgrade, maintain docs
  TOC.md
  benchmark/benchmark-tidb-using-sysbench.md
  benchmark/benchmark-tidb-using-tpcc.md
  check-before-deployment.md
  dashboard/dashboard-ops-reverse-proxy.md
  post-installation-check.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  schedule-replicas-by-topology-labels.md
  ticdc/deploy-ticdc.md
  ticdc/manage-ticdc.md
  tiup/tiup-mirror.md
  upgrade-tidb-using-tiup-offline.md
  upgrade-tidb-using-tiup.md
Labels: needs-cherry-pick-5.0, size/XXL, status/LGT2, status/can-merge, translation/doing, v5.0

#5814 correct version info for v5.0
  system-variables.md
Labels: size/XS, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5816 lightning: update config in get started
  get-started-with-tidb-lightning.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/XS, size/small, status/LGT1, status/can-merge, translation/doing

#5702 write document for mpp
  system-variables.md
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/M, status/LGT1, status/PTAL, status/can-merge, translation/doing, v5.0

#5824 .github: add an action to enable manual rebase
  .github/workflows/rebase.yml
Labels: size/S, status/LGT2, status/can-merge, translation/doing

#5754 add document for explain/explain analyze of mpp query.
  TOC.md
  explain-mpp.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/L, status/LGT1, status/can-merge, translation/doing, v5.0

#5833 doc: fix doc typo
  character-set-and-collation.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#5836 pd-ctl: add more jq examples
  pd-control.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/doing

#5822 refine expression of unified sorter
  ticdc/manage-ticdc.md
Labels: require-LGT1, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/no-need

#5832 add binlog usage restrictions
  tidb-binlog/tidb-binlog-overview.md
Labels: needs-cherry-pick-5.0, size/S, status/LGT1, status/LGT2, status/can-merge, translation/doing, v5.0

#5823 Update check-before-deployment.md
  check-before-deployment.md
Labels: first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-master, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5757 Update migration-tidb-faq.md
  faq/migration-tidb-faq.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/doing

#5842 br: update minimum requirements
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5811 Revert "prepared plan cache: Enable by default"
  dashboard/dashboard-faq.md
  optimizer-hints.md
  sql-prepare-plan-cache.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/from-docs, v5.0

#5834 update the description related to clustered indexes
  br/backup-and-restore-tool.md
  clustered-indexes.md
  system-variables.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/M, status/LGT1, status/PTAL, status/can-merge, translation/doing, v5.0

#5853 add V4.0 tidb binlog restriction
  tidb-binlog/tidb-binlog-overview.md
Labels: size/XS, status/LGT1, status/can-merge, translation/doing

#5844 sysvars: add docs for tidb_enable_strict_double_type_check
  system-variables.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/from-docs, v5.0

#5864 fix some wrong statements in clustered-indexes.md
  clustered-indexes.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/done, v5.0

#5856 Update garbage collection docs #4552
  alert-rules.md
  backup-and-restore-using-dumpling-lightning.md
  br/backup-and-restore-tool.md
  br/backup-and-restore-use-cases.md
  br/use-br-command-line-tool.md
  dumpling-overview.md
  error-codes.md
  faq/migration-tidb-faq.md
  faq/sql-faq.md
  faq/tidb-faq.md
  garbage-collection-configuration.md
  garbage-collection-overview.md
  partitioned-table.md
  read-historical-data.md
  sql-statements/sql-statement-flashback-table.md
  system-variables.md
  tidb-troubleshooting-map.md
  tiflash/use-tiflash.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XL, status/LGT1, status/PTAL, status/can-merge, translation/from-docs, v5.0

#5851 Update roadmap
  roadmap.md
Labels: needs-cherry-pick-5.0, requires-version-specific-changes, size/M, status/LGT1, status/LGT3, status/can-merge, translation/done, v5.0

#5871 Add an alias in roadmap.md
  roadmap.md
Labels: require-LGT1, size/XS, status/LGT1, status/can-merge, translation/done

#5874 update the local storage description from 'mocktikv' to 'unistore'
  command-line-flags-for-tidb-configuration.md
  sql-statements/sql-statement-restore.md
Labels: needs-cherry-pick-5.0, size/S, size/small, status/LGT2, status/can-merge, translation/doing

#5878 Fix 3 typos in docs-cn
  predicate-push-down.md
  subquery-optimization.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/XS, size/small, status/LGT1, status/can-merge, translation/no-need

#5881 config: update default value of `max-txn-ttl`
  grafana-tidb-dashboard.md
  pessimistic-transaction.md
  tidb-configuration-file.md
  troubleshoot-lock-conflicts.md
Labels: needs-cherry-pick-5.0, require-LGT1, size/XS, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-docs, v5.0

#5884 tidb: Fix default value of grpc-connection-count
  tidb-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/XS, size/small, status/LGT1, status/can-merge, translation/doing

#5669 update doc to match config default value with TiKV codebase.
  tikv-configuration-file.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-master, requires-followup, requires-version-specific-changes, size/M, status/LGT1, status/PTAL, status/can-merge, translation/doing

#5882 Update TiFlash related info in quickstart page
  quick-start-with-tidb.md
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/from-docs

#5886 Update the default value of grpc-raft-conn-num
  tikv-configuration-file.md
  tune-tikv-performance.md
Labels: needs-cherry-pick-3.0, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/doing
