Repository pingcap/docs-cn, pull requests merged in 2021-12, with the labels that each got.

#7764 release note 5.3.0: fix RPO and RTO wrong description
  releases/release-5.3.0.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7763 experimental-features: add OpenAPI feature
  experimental-features.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-5.3

#7767 fix RPO and RTO in v5.3.0 release note
  releases/release-5.3.0.md
Labels: status/LGT2, translation/done, translation/doing, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.3

#7762 Update haproxy best practices using haproxy2.5.0
  best-practices/haproxy-best-practices.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/M, sig/sql-infra, needs-cherry-pick-release-5.3, ONCALL

#7768 Corrected RTO and RPO in manage-ticdc.md
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7774 Add HTAP tutorial link and extra explanations
  quick-start-with-htap.md
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/bigdata, needs-cherry-pick-release-5.3

#7403 Update the order of tiup startup components
  maintain-tidb-using-tiup.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7715 releases: add TiDB 5.2.3 release note
  TOC.md
  releases/release-5.2.3.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7784 Update migration-tools.png
  media/migration-tools.png
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7786 Added 2 videos
  overview.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, size/XS, needs-cherry-pick-release-5.3

#7714 releases: add TiDB 5.0.5 release notes
  TOC.md
  releases/release-5.0.5.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7758 update commands and tool info about `key-type`
  best-practices/pd-scheduling-best-practices.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, sig/scheduling, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7408 lightning: update config description of checksum and analyze
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7716 releases: add TiDB 5.1.3 release notes
  TOC.md
  releases/release-5.1.3.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7808 Update release-5.3.0.md
  releases/release-5.3.0.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7804 SQL prepare execution plan cache: add the experimental feature warning
  experimental-features.md
  sql-prepare-plan-cache.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/planner, needs-cherry-pick-release-5.1

#7622 Add back a description
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7477 Refined ticdc-overview.md
  ticdc/ticdc-overview.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, sig/migrate, needs-cherry-pick-release-5.3

#7445 tidb-binlog: update kafka-max-message-size configuration
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/tidb-binlog-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, status/PTAL, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7275 Fix alert item
  alert-rules.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7393 文档错误
  data-type-date-and-time.md
  data-type-numeric.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3

#7357 Modify the name of the Oracle and PostgreSQL
  mysql-compatibility.md
Labels: type/enhancement, status/LGT2, contribution, translation/doing, status/can-merge, size/XS, sig/sql-infra

#7350 update binlog deploy configuration
  config-templates/simple-file-binlog.yaml
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7390 system-variables: add configuration tip based on units
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-5.0, size/S, sig/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7805 Update haproxy-best-practices.md
  best-practices/haproxy-best-practices.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, type/bug-fix, first-time-contributor, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3

#7845 .github: use a new external link checker
  .github/exclude-links.txt
  .github/workflows/link-check.yaml
  .github/workflows/link.yaml
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/M

#7848 .github: change cron and assignee
  .github/workflows/link.yaml
  connectors-and-apis.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#7520 Fix a typo in tidb-monitoring-api.md
  tidb-monitoring-api.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, status/PTAL, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/M, sig/diagnosis, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7856 Fix description error in explain-subqueries.md
  explain-subqueries.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/XS, sig/planner, needs-cherry-pick-release-5.3, ONCALL

#7569 add docs templates for reference
  .github/ISSUE_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
  explore-htap.md
  quick-start-with-htap.md
  resources/doc-templates/template-concept.md
  resources/doc-templates/template-new-feature.md
  resources/doc-templates/template-reference.md
  resources/doc-templates/template-task.md
  resources/doc-templates/template-troubleshooting.md
  resources/tidb-docs-template-zh-v1.0.pdf
  tiflash/maintain-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XL

#7861 Updated prechecks
  TOC.md
  tidb-lightning/tidb-lightning-prechecks.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, size/S, sig/migrate, needs-cherry-pick-release-5.3

#7864 Remove duplicated words
  .github/pull_request_template.md
  check-before-deployment.md
  information-schema/information-schema-cluster-load.md
  releases/release-5.0.1.md
  releases/release-5.1.0.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  troubleshoot-tidb-cluster.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/S, needs-cherry-pick-release-5.3

#7570 cdc: add advice for how to use kafka sink in ticdc
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, status/PTAL, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, sig/migrate, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7873 Revert "cdc: add advice for how to use kafka sink in ticdc (#7570)"
  ticdc/manage-ticdc.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/S

#7874 Revert "cdc: add advice for how to use kafka sink in ticdc (#7570)"
  ticdc/manage-ticdc.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/S

#7875 Revert "cdc: add advice for how to use kafka sink in ticdc (#7570)"
  ticdc/manage-ticdc.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/S

#7876 Revert "cdc: add advice for how to use kafka sink in ticdc (#7570)"
  ticdc/manage-ticdc.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/S

#7860 update benchmark/v5.1-performance-benchmarking-with-tpcc.md,benchmark…
  benchmark/v5.1-performance-benchmarking-with-tpcc.md
  benchmark/v5.2-performance-benchmarking-with-tpcc.md
  benchmark/v5.3-performance-benchmarking-with-tpcc.md
  two-data-centers-in-one-city-deployment.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7883 cdc: add advice for how to use kafka sink in ticdc
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S

#7843 Fix config value for tikv compression-per-level
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, status/PTAL, needs-cherry-pick-release-5.0, size/XS, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7891 cdc: add topic-name to sink-uri description.
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, size/XS, sig/migrate

#7866 New docs: add new entry for TiDB DM and TiDB in Kubernetes
  TOC.md
  dm/dm-overview.md
  media/dm/dm-core-features.png
  tidb-in-kubernetes.md
Labels: type/enhancement, status/LGT2, translation/done, translation/doing, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, requires-version-specific-changes, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7835 chore: update dispatch for latest docs site
  .github/workflows/dispatch.yml
Labels: status/LGT2, translation/no-need, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7888 Fix format of 5.3.0 release notes
  releases/release-5.3.0.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.3

#7902 Update parameter name of peer-stale-state-check-interval
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/engine, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7929 Update the description for Prepare Plan Cache
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/planner, needs-cherry-pick-release-5.3

#7928 Fix a typo in sync diff
  sync-diff-inspector/shard-diff.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3, ONCALL

#7903 Fix a typo in tikv configuration file
  tikv-configuration-file.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, status/PTAL, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7761 Optimize structure for quick start with tidb
  quick-start-with-tidb.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/S, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7938 Update quick-start-with-tidb.md
  quick-start-with-tidb.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7772 Update tikv-ctl modify-tikv-config usage for gc
  garbage-collection-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, status/PTAL, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7933 update description of start-tso
  tidb-binlog/tidb-binlog-reparo.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7661 tidb-lightning: add line terminator and update other csv settings
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/from-docs, status/can-merge, status/require-change, requires-version-specific-changes, size/M, sig/migrate, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7963 TiDB: remove invalid log format
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/XS, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7944 add videos to user docs
  command-line-flags-for-tidb-configuration.md
  dumpling-overview.md
  explore-htap.md
  faq/deploy-and-maintain-faq.md
  overview.md
  quick-start-with-tidb.md
  ticdc/ticdc-overview.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-monitoring-framework.md
  user-account-management.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, size/M, needs-cherry-pick-release-5.3

#7907 remove about 'meet_lock' alter
  alert-rules.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, sig/engine, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7968 Fix a TiDB alert rule for `TiDB_tikvclient_backoff_total`
  alert-rules.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#7964 auto-increment: correct the description in 'limit' part
  auto-increment.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/sql-infra, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7858 Delete docker composer deploy from TOC and direct to the latest stable version
  TOC.md
  quick-start-with-tidb.md
Labels: status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-2.1, type/bug-fix, size/S, sig/tiup

#7884 Update description in statistics v2
  statistics.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, sig/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7987 Update the link for how to write a good commit message
  CONTRIBUTING.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7983 Update the description of disabling swap
  check-before-deployment.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8001 Remove a note in release-5.0.5.md
  releases/release-5.0.5.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7984 Move TiUP docs to TiDB Tools and add entry for TiDB Operator
  TOC.md
  download-ecosystem-tools.md
  ecosystem-tool-user-case.md
  ecosystem-tool-user-guide.md
  tidb-operator-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7836 releases: add tidb 4.0.16 release notes
  TOC.md
  releases/release-4.0.16.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7904 Update component stopping order
  maintain-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7890 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  br/backup-and-restore-faq.md
  releases/release-4.0-ga.md
  releases/release-4.0.0-rc.1.md
  releases/release-4.0.0-rc.2.md
  releases/release-4.0.0-rc.md
  releases/release-4.0.10.md
  releases/release-4.0.11.md
  releases/release-4.0.12.md
  releases/release-4.0.13.md
  releases/release-4.0.14.md
  releases/release-4.0.15.md
  releases/release-4.0.2.md
  releases/release-4.0.3.md
  releases/release-4.0.5.md
  releases/release-4.0.6.md
  releases/release-4.0.7.md
  releases/release-4.0.8.md
  releases/release-4.0.9.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XL

#7885 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  br/backup-and-restore-faq.md
  credits.md
  download-ecosystem-tools.md
  releases/release-4.0-ga.md
  releases/release-4.0.0-rc.1.md
  releases/release-4.0.0-rc.2.md
  releases/release-4.0.0-rc.md
  releases/release-4.0.10.md
  releases/release-4.0.11.md
  releases/release-4.0.12.md
  releases/release-4.0.13.md
  releases/release-4.0.14.md
  releases/release-4.0.15.md
  releases/release-4.0.2.md
  releases/release-4.0.3.md
  releases/release-4.0.5.md
  releases/release-4.0.6.md
  releases/release-4.0.7.md
  releases/release-4.0.8.md
  releases/release-4.0.9.md
  releases/release-5.0.0.md
  releases/release-5.0.1.md
  releases/release-5.0.2.md
  releases/release-5.0.3.md
  releases/release-5.0.4.md
  releases/release-5.1.0.md
  releases/release-5.1.1.md
  releases/release-5.1.2.md
  releases/release-5.2.0.md
  releases/release-5.2.2.md
  releases/release-5.3.0.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XXL

#7886 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  br/backup-and-restore-faq.md
  credits.md
  releases/release-4.0-ga.md
  releases/release-4.0.0-rc.1.md
  releases/release-4.0.0-rc.2.md
  releases/release-4.0.0-rc.md
  releases/release-4.0.10.md
  releases/release-4.0.11.md
  releases/release-4.0.12.md
  releases/release-4.0.13.md
  releases/release-4.0.14.md
  releases/release-4.0.15.md
  releases/release-4.0.2.md
  releases/release-4.0.3.md
  releases/release-4.0.5.md
  releases/release-4.0.6.md
  releases/release-4.0.7.md
  releases/release-4.0.8.md
  releases/release-4.0.9.md
  releases/release-5.0.0.md
  releases/release-5.0.1.md
  releases/release-5.0.2.md
  releases/release-5.0.3.md
  releases/release-5.0.4.md
  releases/release-5.1.0.md
  releases/release-5.1.1.md
  releases/release-5.1.2.md
  releases/release-5.2.0.md
  releases/release-5.2.2.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XXL

#7887 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  br/backup-and-restore-faq.md
  credits.md
  releases/release-4.0-ga.md
  releases/release-4.0.0-rc.1.md
  releases/release-4.0.0-rc.2.md
  releases/release-4.0.0-rc.md
  releases/release-4.0.10.md
  releases/release-4.0.11.md
  releases/release-4.0.12.md
  releases/release-4.0.13.md
  releases/release-4.0.14.md
  releases/release-4.0.15.md
  releases/release-4.0.2.md
  releases/release-4.0.3.md
  releases/release-4.0.5.md
  releases/release-4.0.6.md
  releases/release-4.0.7.md
  releases/release-4.0.8.md
  releases/release-4.0.9.md
  releases/release-5.0.0.md
  releases/release-5.0.1.md
  releases/release-5.0.2.md
  releases/release-5.0.3.md
  releases/release-5.0.4.md
  releases/release-5.1.0.md
  releases/release-5.1.1.md
  releases/release-5.1.2.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XXL

#7889 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  br/backup-and-restore-faq.md
  credits.md
  releases/release-4.0-ga.md
  releases/release-4.0.0-rc.1.md
  releases/release-4.0.0-rc.2.md
  releases/release-4.0.0-rc.md
  releases/release-4.0.10.md
  releases/release-4.0.11.md
  releases/release-4.0.12.md
  releases/release-4.0.13.md
  releases/release-4.0.14.md
  releases/release-4.0.15.md
  releases/release-4.0.2.md
  releases/release-4.0.3.md
  releases/release-4.0.5.md
  releases/release-4.0.6.md
  releases/release-4.0.7.md
  releases/release-4.0.8.md
  releases/release-4.0.9.md
  releases/release-5.0.0.md
  releases/release-5.0.1.md
  releases/release-5.0.2.md
  releases/release-5.0.3.md
  releases/release-5.0.4.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XL

#8025 Bump version for v4.0.16
  download-ecosystem-tools.md
  pd-recover.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-cluster-deploy.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/doing, status/can-merge, size/M

#7709 Delete the Configuration File Parameters about the nested-loop-join-cache-capacity
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, status/PTAL, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8031 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow - master
  br/backup-and-restore-faq.md
  credits.md
  dm/dm-overview.md
  download-ecosystem-tools.md
  releases/release-4.0-ga.md
  releases/release-4.0.0-rc.1.md
  releases/release-4.0.0-rc.2.md
  releases/release-4.0.0-rc.md
  releases/release-4.0.10.md
  releases/release-4.0.11.md
  releases/release-4.0.12.md
  releases/release-4.0.13.md
  releases/release-4.0.14.md
  releases/release-4.0.15.md
  releases/release-4.0.16.md
  releases/release-4.0.2.md
  releases/release-4.0.3.md
  releases/release-4.0.5.md
  releases/release-4.0.6.md
  releases/release-4.0.7.md
  releases/release-4.0.8.md
  releases/release-4.0.9.md
  releases/release-5.0.0.md
  releases/release-5.0.1.md
  releases/release-5.0.2.md
  releases/release-5.0.3.md
  releases/release-5.0.4.md
  releases/release-5.1.0.md
  releases/release-5.1.1.md
  releases/release-5.1.2.md
  releases/release-5.2.0.md
  releases/release-5.2.2.md
  releases/release-5.3.0.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XXL, sig/migrate

#8038 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  dm/dm-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#8039 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  dm/dm-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#8037 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  dm/dm-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#8035 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  credits.md
  dm/dm-overview.md
  releases/release-4.0.16.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/M

#8036 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  dm/dm-overview.md
  releases/release-4.0.16.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/M

#8034 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  credits.md
  dm/dm-overview.md
  releases/release-4.0.16.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/M

#8032 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  credits.md
  dm/dm-overview.md
  releases/release-4.0.16.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/M

#8033 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  credits.md
  dm/dm-overview.md
  releases/release-4.0.16.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/M

#8050 update placement rule configuration
  configure-placement-rules.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, sig/scheduling, needs-cherry-pick-release-5.3, ONCALL

#8052 Fix the usage of slash
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8055 Add the missing escape characters
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8062 Updated the code repo link of TiCDC
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-5.3

#8065 chore: add v5.4 to pr template
  .github/pull_request_template.md
Labels: status/LGT1, translation/from-docs, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8076 fix incorrect default value for sysvar wait_timeout
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, for-future-release, size/XS, sig/sql-infra, type/compatibility-or-feature-change

#7958 Update dumpling `--row` description
  dumpling-overview.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7747 Changed the alert rule of TiKV_thread_apply_worker_cpu_seconds
  alert-rules.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.3, ONCALL

#8083 chore: remove useless aliases for DM Dev docs
  dm/deploy-a-dm-cluster-using-tiup.md
  dm/dm-alert-rules.md
  dm/dm-benchmark-v5.3.0.md
  dm/dm-command-line-flags.md
  dm/dm-config-overview.md
  dm/dm-create-task.md
  dm/dm-daily-check.md
  dm/dm-enable-tls.md
  dm/dm-error-handling.md
  dm/dm-export-import-config.md
  dm/dm-faq.md
  dm/dm-generate-self-signed-certificates.md
  dm/dm-glossary.md
  dm/dm-handle-alerts.md
  dm/dm-handle-performance-issues.md
  dm/dm-hardware-and-software-requirements.md
  dm/dm-key-features.md
  dm/dm-manage-schema.md
  dm/dm-manage-source.md
  dm/dm-open-api.md
  dm/dm-overview.md
  dm/dm-pause-task.md
  dm/dm-performance-test.md
  dm/dm-precheck.md
  dm/dm-query-status.md
  dm/dm-resume-task.md
  dm/dm-source-configuration-file.md
  dm/dm-stop-task.md
  dm/dm-task-configuration-guide.md
  dm/dm-tune-configuration.md
  dm/handle-failed-ddl-statements.md
  dm/maintain-dm-using-tiup.md
  dm/migrate-data-using-dm.md
  dm/quick-start-create-task.md
  dm/task-configuration-file-full.md
  dm/usage-scenario-simple-migration.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/M

#8047 ticdc: Use open-protocol instead of default protocol and add missing params
  ticdc/manage-ticdc.md
  ticdc/ticdc-open-api.md
  ticdc/troubleshoot-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, requires-version-specific-changes, needs-cherry-pick-release-5.0, size/M, sig/migrate, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, v5.4

#7480 Refactor data migration
  TOC.md
  _index.md
  filter-binlog-event.md
  filter-dml-event.md
  media/dm/migrate-with-dm.png
  media/lightning/migrate-shared-mysql-01.png
  media/lightning/migrate-shared-mysql-02.png
  media/lightning/shard-merge-using-lightning-procedure.png
  media/lightning/shard-merge-using-lightning.png
  migrate-aurora-to-tidb.md
  migrate-from-aurora-mysql-database.md
  migrate-from-aurora-using-lightning.md
  migrate-from-csv-files-to-tidb.md
  migrate-from-mysql-dumpling-files.md
  migrate-from-sql-files-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  migrate-small-mysql-to-tidb.md
  migrate-with-more-columns-downstream.md
  migrate-with-pt-ghost.md
  migration-overview.md
  migration-tools.md
  releases/release-5.0.0.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/XXL, refactor-migration-docs

#8041 releases: add tidb 5.0.6 release notes
  TOC.md
  releases/release-5.0.6.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3
