Repository pingcap/docs-cn, pull requests merged in 2021-07, with the labels that each got.

#6558 fix partition table doc error
  partitioned-table.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/doing

#6552 *: make the scene of stale read clearer
  stale-read.md
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/doing

#6557 TiKV configuration: update max-peer-down-duration default value
  tikv-configuration-file.md
Labels: for-future-release, size/XS, status/LGT2, status/can-merge, translation/doing

#6575 Remove a blank line that causes display failure
  sql-statements/sql-statement-with.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6577 Correct v5.1 doc errors
  information-schema/information-schema-data-lock-waits.md
  information-schema/information-schema-deadlocks.md
  pd-configuration-file.md
  pd-control.md
  ticdc/manage-ticdc.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/S, status/LGT1, status/can-merge, translation/doing

#6540 releases: add 5.0.3 release notes
  TOC.md
  releases/release-5.0.3.md
  releases/release-notes.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge, translation/from-docs

#6573 system-variables: add datadir and license
  system-variables.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/from-docs

#6574 tidb-configuration-file: add graceful-wait-before-shutdown
  tidb-configuration-file.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/from-docs

#6587 zh.md fix doc typo, /{a_d}*.md
  CONTRIBUTING.md
  _index.md
  alert-rules.md
  analyze-slow-queries.md
  as-of-timestamp.md
  auto-random.md
  backup-and-restore-using-dumpling-lightning.md
  certificate-authentication.md
  character-set-and-collation.md
  command-line-flags-for-pd-configuration.md
  command-line-flags-for-tidb-configuration.md
  command-line-flags-for-tikv-configuration.md
  configure-placement-rules.md
  configure-time-zone.md
  connectors-and-apis.md
  constraints.md
  data-type-date-and-time.md
  data-type-default-values.md
  data-type-json.md
  data-type-numeric.md
  deploy-monitoring-services.md
  dumpling-overview.md
  dynamic-config.md
Labels: contribution, first-time-contributor, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/L, status/LGT1, status/can-merge, translation/no-need

#6570 pd-configuration-file: add hot-region information
  pd-configuration-file.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/S, status/LGT1, status/can-merge, translation/from-docs

#6572 system-variables: add warning count
  system-variables.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/from-docs

#6571 system-variables: update from generated source
  system-variables.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XL, status/LGT1, status/can-merge, translation/from-docs, type/enhancement

#6586 align the Chinese expression of sign-in
  certificate-authentication.md
  check-before-deployment.md
  enable-tls-between-clients-and-servers.md
  maintain-tidb-using-tiup.md
  production-deployment-using-tiup.md
  role-based-access-control.md
  security-compatibility-with-mysql.md
  sql-statements/sql-statement-create-user.md
  tiup/tiup-cluster-topology-reference.md
  tiup/tiup-component-cluster-check.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-list.md
  tiup/tiup-component-cluster-scale-out.md
  tiup/tiup-component-dm-deploy.md
  tiup/tiup-component-dm-list.md
  tiup/tiup-component-dm-scale-out.md
  tiup/tiup-dm-topology-reference.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/M, status/LGT1, status/can-merge, translation/no-need

#6553 zh.md bot checking /tidcd, fix typo error
  ticdc/manage-ticdc.md
  ticdc/monitor-ticdc.md
  ticdc/ticdc-overview.md
  ticdc/troubleshoot-ticdc.md
Labels: contribution, first-time-contributor, needs-cherry-pick-release-5.1, require-LGT1, size/L, status/LGT1, status/can-merge, translation/welcome

#6588 Update the related variable description for CREATE INDEX
  sql-statements/sql-statement-create-index.md
Labels: needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, translation/doing

#6543 Add the default value description for tidb_enforce_mpp
  releases/release-5.1.0.md
  system-variables.md
  tidb-configuration-file.md
Labels: needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, translation/doing

#6520 Add documentation for TiDB specific SQL functions
  TOC.md
  functions-and-operators/information-functions.md
  functions-and-operators/tidb-functions.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge, status/require-change, translation/from-docs

#6542 update docs related to partition table dynamic mode
  experimental-features.md
  partitioned-table.md
  releases/release-5.1.0.md
  system-variables.md
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/doing

#6615 Fix link to optimizer-hints.md
  as-of-timestamp.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/no-need

#6475 Add a note about grpc-compression-type.
  tikv-configuration-file.md
Labels: needs-cherry-pick-master, needs-cherry-pick-release-5.1, size/XS, status/LGT1, status/can-merge, translation/doing

#6546 Update TiUP version
  hardware-and-software-requirements.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, sig/docs, sig/tiup, size/XS, status/LGT2, status/can-merge, translation/doing

#6409 Change tidb_memory_usage_alarm_ratio scope to instance
  system-variables.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, translation/doing

#6377 Remove the swappiness parameter
  check-before-deployment.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing

#6626 Batch fix broken external links
  functions-and-operators/aggregate-group-by-functions.md
  functions-and-operators/expressions-pushed-down.md
  functions-and-operators/json-functions.md
Labels: needs-cherry-pick-release-2.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/M, status/LGT1, status/can-merge, translation/doing

#6635 Update hybrid-deployment-topology.md
  hybrid-deployment-topology.md
Labels: contribution, first-time-contributor, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/done, type/bug-fix

#6502 add command to check tikv user
  br/backup-and-restore-faq.md
Labels: first-time-contributor, sig/docs, sig/migrate, size/M, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6411 Add steps to get lightning goroutine
  tidb-lightning/tidb-lightning-faq.md
Labels: size/S, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6416 Add kafka downstream example
  config-templates/complex-tidb-binlog.yaml
Labels: first-time-contributor, require-LGT1, size/M, status/LGT1, status/can-merge, translation/doing, type/enhancement

#6296 supplement br doc
  br/use-br-command-line-tool.md
Labels: contribution, needs-cherry-pick-master, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1, sig/docs, sig/migrate, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/doing

#6271 binlog: update documents for committs and passoword
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/tidb-binlog-configuration-file.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, status/require-change, translation/doing

#6194 br: add restore to systables
  br/use-br-command-line-tool.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, sig/docs, sig/migrate, size/M, status/LGT2, status/can-merge, translation/doing

#6412 check-before-deployment: add info about chronyd/chronyc on CentOS 8
  check-before-deployment.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, translation/done, translation/from-docs

#6471 Add documentation on how to modify gcttl by tiup
  ticdc/manage-ticdc.md
Labels: first-time-contributor, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, translation/doing

#6655 Remove the roadmap document
  TOC.md
  roadmap.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/M, status/LGT1, status/can-merge, translation/doing

#6657 zh.md fix typo error
  dashboard/dashboard-statement-list.md
  releases/release-1.0-ga.md
  releases/release-1.1-beta.md
  releases/release-2.0-ga.md
  releases/release-2.0.11.md
  releases/release-2.0.7.md
  releases/release-2.1-beta.md
  releases/release-2.1-ga.md
  releases/release-2.1-rc.1.md
  releases/release-2.1.11.md
  releases/release-2.1.12.md
  releases/release-2.1.14.md
  releases/release-2.1.16.md
  releases/release-2.1.17.md
  releases/release-2.1.18.md
  releases/release-2.1.3.md
  releases/release-2.1.8.md
  releases/release-3.0-ga.md
  releases/release-3.0.0-beta.1.md
  releases/release-3.0.0-rc.1.md
  releases/release-3.0.0-rc.3.md
  releases/release-3.0.10.md
  releases/release-3.0.14.md
  releases/release-3.0.15.md
  releases/release-3.0.18.md
  releases/release-3.0.2.md
  releases/release-3.0.4.md
  releases/release-3.0.6.md
  releases/release-3.0.8.md
  releases/release-4.0.0-beta.md
  releases/release-4.0.0-rc.1.md
  releases/release-4.0.0-rc.2.md
  releases/release-4.0.6.md
  releases/release-4.0.7.md
  releases/release-4.0.9.md
  releases/release-5.0.0-rc.md
  releases/release-5.0.0.md
  releases/release-5.1.0.md
  releases/release-pre-ga.md
  releases/release-rc.2.md
  releases/release-rc.3.md
  releases/release-rc.4.md
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-create-database.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-drop-user.md
  sql-statements/sql-statement-explain-analyze.md
  sql-statements/sql-statement-explain.md
  sql-statements/sql-statement-flashback-table.md
  sql-statements/sql-statement-modify-column.md
  sql-statements/sql-statement-split-region.md
Labels: contribution, require-LGT1, size/L, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#6656 zh.md fix typo {b-f}*/*.md
  benchmark/benchmark-sysbench-v4-vs-v3.md
  benchmark/benchmark-sysbench-v5-vs-v4.md
  benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md
  benchmark/benchmark-tidb-using-sysbench.md
  benchmark/benchmark-tidb-using-tpcc.md
  benchmark/benchmark-tpch.md
  benchmark/v3.0-performance-benchmarking-with-sysbench.md
  benchmark/v3.0-performance-benchmarking-with-tpcc.md
  benchmark/v5.1-performance-benchmarking-with-tpcc.md
  best-practices/high-concurrency-best-practices.md
  best-practices/massive-regions-best-practices.md
  best-practices/pd-scheduling-best-practices.md
  best-practices/three-dc-local-read.md
  best-practices/tidb-best-practices.md
  br/backup-and-restore-faq.md
  br/backup-and-restore-use-cases.md
  br/use-br-command-line-tool.md
  dashboard/dashboard-access.md
  dashboard/dashboard-diagnostics-access.md
  dashboard/dashboard-diagnostics-report.md
  dashboard/dashboard-ops-deploy.md
  dashboard/dashboard-ops-reverse-proxy.md
  dashboard/dashboard-ops-security.md
  dashboard/dashboard-overview.md
  dashboard/dashboard-profiling.md
  dashboard/dashboard-statement-details.md
  dashboard/dashboard-statement-list.md
  faq/deploy-and-maintain-faq.md
  faq/migration-tidb-faq.md
  faq/sql-faq.md
  faq/tidb-faq.md
  faq/upgrade-faq.md
  functions-and-operators/aggregate-group-by-functions.md
  functions-and-operators/expressions-pushed-down.md
  functions-and-operators/functions-and-operators-overview.md
  functions-and-operators/operators.md
  functions-and-operators/precision-math.md
  functions-and-operators/set-operators.md
Labels: contribution, require-LGT1, size/XXL, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#6647 tidb-functions: extend tidb_decode_key docs
  functions-and-operators/tidb-functions.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/M, status/LGT1, status/can-merge, translation/from-docs

#6664 Fix a typo in configure-memory-usage.md
  configure-memory-usage.md
Labels: contribution, missing-translation-status, require-LGT1, size/XS, status/LGT1, status/can-merge, type/bug-fix

#6667 TiKV configuration: better description for pin-l0-filter-and-index-blocks
  tikv-configuration-file.md
Labels: sig/docs, sig/engine, size/XS, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6400 ticdc: add mysql sink user privilege
  ticdc/troubleshoot-ticdc.md
Labels: sig/docs, sig/migrate, size/S, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6666 removed some useless configurations
  pd-configuration-file.md
  tiflash/tiflash-configuration.md
Labels: first-time-contributor, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/M, status/LGT1, status/can-merge, translation/from-docs

#6665 Fix ticdc canal json related doc
  ticdc/troubleshoot-ticdc.md
Labels: first-time-contributor, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/from-docs

#6663 Migration FAQs: add the FAQ links of the migration related tools
  faq/migration-tidb-faq.md
Labels: size/S, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6465 Update complex-cdc.yaml
  config-templates/complex-cdc.yaml
Labels: first-time-contributor, needs-cherry-pick-master, needs-cherry-pick-release-5.1, size/XS, status/LGT1, status/can-merge, translation/doing, type/enhancement

#6668 dumping default consistency description
  dumpling-overview.md
Labels: first-time-contributor, sig/docs, sig/migrate, size/XS, status/LGT2, status/can-merge, translation/doing, type/bug-fix

#6633 tiup: add instruction to custom exist offline mirror
  production-deployment-using-tiup.md
  releases/release-2.0.11.md
Labels: size/M, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6514 add notice about scaling in pd node
  scale-tidb-using-tiup.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, requires-version-specific-changes, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/doing, type/compatibility-or-feature-change, type/enhancement

#6648 cdc: add compatibility notes for sort-dir
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, requires-version-specific-changes, size/S, status/LGT2, status/can-merge, translation/doing, type/compatibility-or-feature-change, type/enhancement

#6278 Binlog: add a document for real time replication with BR/Dumpling.
  TOC.md
  incremental-replication-between-clusters.md
Labels: sig/docs, sig/migrate, size/M, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6472 br: update documents for br restore systables
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/doing, v5.1

#6669 update max-replicas description
  pd-configuration-file.md
Labels: require-LGT1, size/XS, status/LGT1, status/can-merge, translation/done, type/enhancement

#6333 TiUP: CDC support Data dir .
  config-templates/complex-cdc.yaml
  tiup/tiup-cluster-topology-reference.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, requires-version-specific-changes, sig/docs, sig/migrate, size/XS, status/LGT2, status/can-merge, translation/doing, type/compatibility-or-feature-change

#5901 credits: update links to the full list of code and docs contributors
  credits.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge, translation/doing

#6659 tiup: add notice about importing cluster that don't have all nodes mo…
  tiup/tiup-component-cluster-import.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, sig/docs, sig/tiup, size/XS, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6660 (4.0) tiup: add notice about importing cluster that don't have all nodes…
  upgrade-tidb-using-tiup.md
Labels: sig/docs, sig/tiup, size/XS, status/LGT1, status/can-merge, translation/doing, type/enhancement

#6613 Add two docs for getting started with HTAP and exploring HTAP
  TOC.md
  _index.md
  explore-htap.md
  quick-start-with-htap.md
Labels: size/XL, status/LGT2, status/can-merge, translation/doing

#6700 sysvar: change the default value of tidb_multi_statement_mode in v4.0.14
  system-variables.md
Labels: sig/docs, sig/sql-infra, status/LGT1, status/can-merge, translation/from-docs, type/compatibility-or-feature-change

#6703 remove useless variable.
  benchmark/v5.1-performance-benchmarking-with-tpch.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing, type/bug-fix

#6704 remove useless variable. (for 5.0)
  benchmark/v5.0-performance-benchmarking-with-tpch.md
Labels: size/XS, status/LGT2, status/can-merge, translation/doing, type/bug-fix

#6708 deploy-tidb-binlog: make the expression on deployment clearer
  tidb-binlog/deploy-tidb-binlog.md
Labels: needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6710 best-practices: add timeout options for Java best practices
  best-practices/java-app-best-practices.md
Labels: size/XS, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6713 system-variables: update for consistency
  system-variables.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/S, status/LGT1, status/can-merge, translation/from-docs, type/bug-fix, type/enhancement

#6697 add zhmd to ci
  .circleci/config.yml
  .zhlint.yaml
  experimental-features.md
  explore-htap.md
  mysql-compatibility.md
  pd-control.md
  quick-start-with-htap.md
  sql-statements/sql-statement-explain-analyze.md
  storage-engine/rocksdb-overview.md
  storage-engine/titan-configuration.md
  storage-engine/titan-overview.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  system-variables.md
  table-filter.md
  tidb-troubleshooting-map.md
  troubleshoot-cpu-issues.md
  troubleshoot-lock-conflicts.md
Labels: contribution, size/XXL, status/LGT2, status/can-merge, translation/no-need, type/bug-fix

#6696 Add security option `require-secure-transport`
  tidb-configuration-file.md
Labels: size/XS, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6718 Update the default value of tidb_stmt_summary_max_stmt_count
  sql-statements/sql-statement-show-variables.md
  statement-summary-tables.md
  system-variables.md
Labels: needs-cherry-pick-master, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, sig/diagnosis, sig/docs, sig/sql-infra, size/XS, status/LGT1, status/can-merge, translation/done

#6702 pr_template: Provides tips for cherry-pick
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: needs-cherry-pick-release-2.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/S, status/LGT1, status/can-merge, translation/doing

#6695 statement summary: update statement summary doc
  statement-summary-tables.md
Labels: first-time-contributor, size/M, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6711 *: Add TiDB Dashboard session docs
  TOC.md
  dashboard/dashboard-session-share.md
  dashboard/dashboard-session-sso.md
  media/dashboard/dashboard-session-share-settings-1.png
  media/dashboard/dashboard-session-share-settings-2.png
  media/dashboard/dashboard-session-share-settings-3.png
  media/dashboard/dashboard-session-share-signin-1.png
  media/dashboard/dashboard-session-share-signin-2.png
  media/dashboard/dashboard-session-share-signin-3.png
  media/dashboard/dashboard-session-sso-disable.png
  media/dashboard/dashboard-session-sso-enable-1.png
  media/dashboard/dashboard-session-sso-enable-2.png
  media/dashboard/dashboard-session-sso-enable-3.png
  media/dashboard/dashboard-session-sso-okta-1.png
  media/dashboard/dashboard-session-sso-okta-2.png
  media/dashboard/dashboard-session-sso-okta-3.png
  media/dashboard/dashboard-session-sso-okta-4.png
  media/dashboard/dashboard-session-sso-okta-info-1.png
  media/dashboard/dashboard-session-sso-okta-info-2.png
  media/dashboard/dashboard-session-sso-okta-info-3.png
  media/dashboard/dashboard-session-sso-reauthorize.png
  media/dashboard/dashboard-session-sso-signin.png
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, requires-version-specific-changes, size/L, status/LGT2, status/can-merge, translation/doing

#6712 system variables: add charset documentation
  system-variables.md
Labels: needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, translation/from-docs

#6698 releases: add tidb 4.0.14 release notes
  TOC.md
  releases/release-4.0.14.md
  releases/release-notes.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge, translation/from-docs

#6741 Bump version for v4.0.14
  download-ecosystem-tools.md
  pd-recover.md
  production-deployment-using-tiup.md
  production-offline-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-cluster-deploy.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, status/can-merge, translation/from-docs

#6742 Fix a wrong link and a inaccurate description
  .github/pull_request_template.md
  ticdc/ticdc-overview.md
Labels: needs-cherry-pick-release-2.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/no-need

#6749 fix a typo for sync_diff_inspector
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, translation/done

#6715 update stale read doc for ga
  as-of-timestamp.md
  experimental-features.md
  stale-read.md
Labels: needs-cherry-pick-release-5.1, requires-version-specific-changes, size/S, status/LGT2, status/can-merge, translation/doing, type/compatibility-or-feature-change

#6755 update golang demo link
  ticdc/ticdc-open-protocol.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/doing, type/bug-fix

#6559 Update dashboard FAQ
  dashboard/dashboard-faq.md
  media/dashboard/dashboard-faq-devtools-application.png
  media/dashboard/dashboard-faq-devtools.png
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/from-docs, type/compatibility-or-feature-change

#6761 Add v5.1.0 / release-5.1 where it is missing
  README.md
Labels: needs-cherry-pick-release-2.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, status/LGT1, status/can-merge, translation/from-docs

#6706 *: add table storage info status api
  tidb-monitoring-api.md
Labels: contribution, first-time-contributor, size/M, status/LGT2, status/can-merge, translation/doing, type/enhancement

#6774 correct document of using br backup and restore system tables
  br/backup-and-restore-tool.md
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, translation/from-docs, type/bug-fix

#6733 releases: add TiDB 5.1.1 release notes
  TOC.md
  releases/release-4.0.14.md
  releases/release-5.1.1.md
  releases/release-notes.md
Labels: needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge, translation/from-docs

#6776 update br faq
  br/backup-and-restore-faq.md
Labels: needs-cherry-pick-release-5.1, require-LGT1, size/M, status/LGT1, status/can-merge, translation/from-docs

#6754 grafana-overview-dashboard: update the monitoring item for CPS
  grafana-overview-dashboard.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, sig/docs, sig/sql-infra, status/LGT2, status/can-merge, translation/doing, type/bug-fix
