Repository pingcap/docs-cn, pull requests merged in 2022-03, with the labels that each got.

#8454 Refactor DM document
  TOC.md
  dm/dm-glossary.md
  dm/dm-hardware-and-software-requirements.md
  dm/dm-overview.md
  dm/quick-start-with-dm.md
  dm/task-configuration-file-full.md
Labels: status/LGT1, type/refactor, translation/doing, status/can-merge, require-LGT1, size/XXL, sig/migrate, area/dm

#8095 explain snapshot read and current read
  pessimistic-transaction.md
  releases/release-3.0.3.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, status/require-change, first-time-contributor, needs-cherry-pick-release-5.0, size/S, sig/transaction, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8316 Update the memory usage size of a transaction
  transaction-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, sig/transaction, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8526 update desc
  pd-recover.md
Labels: type/enhancement, status/LGT1, status/can-merge, require-LGT1, size/XS, sig/scheduling, needs-cherry-pick-release-5.4

#8504 Optimize description of restoring system tables
  br/use-br-command-line-tool.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/S, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8542 update-ngm-reload-for-dashboard
  dashboard/dashboard-faq.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-master, size/S, area/diagnosis

#8538 update-date-for-5.3
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/tiup

#8541 update-date-for-5.4
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, area/tiup

#8537 update-date-for-5.2
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/tiup

#8536 update-date-for-5.1
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/tiup

#8535 update-date-for-5.0
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, area/tiup

#8539 update-version-and-date-for-master
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/M, area/tiup

#8529 update audit time for 4.0 tiup cluster.md
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/S, area/tiup

#8411 update default value of tidb_analyze_version in v5.1 and v5.2
  statistics.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/planner, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2

#8412 Update description for analyze version
  statistics.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/planner, type/compatibility-or-feature-change, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8495 add 5.3.1 release notes
  TOC.md
  releases/release-5.3.1.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8559 Bump version for 5.3.1
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M

#8560 Corrected version info
  ticdc/manage-ticdc.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/XS

#8561 功能增强 --> 提升改进
  releases/release-5.1.4.md
  releases/release-5.3.1.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8554 Update headings of "clinic data instruction"
  clinic/clinic-data-instruction-for-tiup.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/clinic

#8543 pd-ctl: update the deprecated scheduler config names
  best-practices/pd-scheduling-best-practices.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4

#8572 Fix typos in hardware-and-software-requirements.md
  hardware-and-software-requirements.md
Labels: status/LGT1, contribution, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, first-time-contributor, size/XS, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain

#8575 Fix link for Lightning backends
  migrate-from-sql-files-to-tidb.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.4, area/tidb-lightning

#8578 Fix link for lightning backends
  migrate-from-sql-files-to-tidb.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/tidb-lightning

#8333 Add description of can't mix multiple backend
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-5.4, area/tidb-lightning

#8584 Fix tiup storage retention
  tiup/tiup-cluster-topology-reference.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4

#8595 Fix a wrong link in info-schema
  information-schema/information-schema.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, area/sql-infra, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8601 update "v5.4 performance benchmarking with tpch"
  benchmark/v5.4-performance-benchmarking-with-tpch.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-5.4

#8604 Clarified a description about auto-incremental ID
  mysql-compatibility.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, needs-cherry-pick-release-5.4

#8363 update-conent- for scaleout cluster and deploy cluster
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, area/tiup, ONCALL, needs-cherry-pick-release-5.4

#8614 Update issue number to show GET_LOCK() and RELEASE_LOCK() status
  functions-and-operators/miscellaneous-functions.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS

#8607 tools: chagen scanregions endkey default limit
  pd-control.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, size/S, area/scheduling, needs-cherry-pick-release-5.4

#8592 Update tidb-lightning-overview and tidb-lightning-distributed-import
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-overview.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-lightning

#8397 Add a new doc to introduce how to customize monitor servers in tiup environment
  TOC.md
  tiup/customized-montior-in-tiup-environment.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/L, area/tiup, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8632 chore: update rebase secret key
  .github/workflows/rebase.yml
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8639 List Amazon Linux 2 as supported
  hardware-and-software-requirements.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/tiup

#8649 Fix a typo in correlated subquery optimization
  correlated-subquery-optimization.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4

#8661 Add item lists for quick start with tidb
  quick-start-with-tidb.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/S, area/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8660 Update quick-create-migration-task.md
  dm/quick-create-migration-task.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, area/migrate, needs-cherry-pick-release-5.4

#8266 TiKV control: Replace `--db `with `--data-dir`
  tikv-control.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/M, area/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8678 Fix a problem in configure-placement-rules.md
  configure-placement-rules.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8602 Optimize the FAQ TOC
  TOC.md
  dm/dm-hardware-and-software-requirements.md
  faq/deploy-and-maintain-faq.md
  faq/manage-cluster-faq.md
  faq/monitor-faq.md
  migrate-large-mysql-to-tidb.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-requirements.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XXL, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain

#8682 Add TiUP command docs to TOC
  TOC.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/tiup, needs-cherry-pick-release-5.4

#8705 disable trigger website building from docs master
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS

#8642 lightning: add max-err summary output example
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, v6.0, area/tidb-lightning

#8224 dm: add new config for lightning
  dm/task-configuration-file-full.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/S, type/compatibility-or-feature-change, area/dm, v6.0

#8641 lightning: delete experimental warning in error resolution
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/migrate, type/compatibility-or-feature-change, v6.0

#8640 add doc for `start-task --start-time`
  dm/dm-create-task.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/dm, v6.0

#8681 DM: add the description about support dump files store in s3
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, area/dm, v6.0

#8691 add a few explanation for slow logs
  identify-slow-queries.md
  sql-statements/sql-statement-explain-analyze.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/planner

#8625 planner: add explanation about `force_index` and `force index`
  choose-index.md
  optimizer-hints.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/planner

#8230 remove direct placement
  information-schema/information-schema-placement-rules.md
  placement-rules-in-sql.md
  sql-statements/sql-statement-alter-placement-policy.md
  sql-statements/sql-statement-create-placement-policy.md
  sql-statements/sql-statement-drop-placement-policy.md
  sql-statements/sql-statement-show-create-placement-policy.md
  sql-statements/sql-statement-show-placement-for.md
  sql-statements/sql-statement-show-placement.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, area/sql-infra, v6.0

#8697 Update function list supported by TiFlash
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, v6.0

#8409 dm: update dm-precheck.md
  dm/dm-precheck.md
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, area/dm, v6.0

#8701 Updates for Top SQL GA
  dashboard/top-sql.md
  experimental-features.md
  glossary.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, type/compatibility-or-feature-change, v6.0, area/diagnosis

#8624 lightning: support base64 encoding of password
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, v6.0, area/tidb-lightning

#8712 update coprocessor of monitor-tiflash.md
  tiflash/monitor-tiflash.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, first-time-contributor, size/XS, area/bigdata, v6.0, area/diagnosis

#8683 DM: update the description about error handle command's enhancements
  dm/dm-faq.md
  dm/dm-manage-schema.md
  dm/dm-manage-source.md
  dm/dmctl-introduction.md
  dm/handle-failed-ddl-statements.md
  dm/manually-handling-sharding-ddl-locks.md
  dm/quick-start-create-source.md
  dm/shard-merge-best-practices.md
  dm/task-configuration-file.md
  migrate-with-more-columns-downstream.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XXL, type/compatibility-or-feature-change, area/dm, v6.0

#8699 add docs for kill auto analyze
  statistics.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, v6.0

#8718 Add a link to system variable
  sql-plan-management.md
  system-variables.md
Labels: type/enhancement, status/LGT1, status/can-merge, require-LGT1, size/XS, area/planner, ONCALL, needs-cherry-pick-release-5.4

#8396 ref: add doc for pessimistic auto-commit
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, for-future-release, size/XS, area/transaction, type/compatibility-or-feature-change

#8715 dm: remove redundant sentence
  migrate-with-more-columns-downstream.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, v6.0

#8723 docs: update the TiKV store status description
  pd-control.md
  tidb-scheduling.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8611 update tiflash doc add dt_compression_method and dt_compression_level config
  tiflash/tiflash-command-line-flags.md
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, v6.0

#8623 planner: update documents related to Plan Cache
  sql-prepare-plan-cache.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, area/planner, type/compatibility-or-feature-change, v6.0

#8717 Update tiflash-configuration.md, update default value of dt_enable_logical_split
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, area/bigdata, v6.0

#8653 cdc: add special description to canal-json docs.
  ticdc/ticdc-canal-json.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, needs-cherry-pick-release-5.4

#8619 update SPM doc for SQL plan auto capture
  sql-plan-management.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XL, area/sql-infra, type/compatibility-or-feature-change, v6.0

#8540 Add description on ALTER DATABASE SET TIFLASH REPLICA
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/bigdata, v6.0

#8696 tiflash: refine description about join push down
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, v6.0

#8716 change “TiDB Clinic” to “PingCAP Clinic”
  TOC.md
  clinic/clinic-data-instruction-for-tiup.md
  clinic/clinic-introduction.md
  clinic/clinic-user-guide-for-tiup.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/L, area/clinic

#8732 cdc: add timeout to kafka docs.
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, v6.0, area/ticdc

#8706 *: refine placement
  TOC.md
  br/backup-and-restore-tool.md
  information-schema/information-schema-placement-policies.md
  information-schema/information-schema-placement-rules.md
  information-schema/information-schema.md
  placement-rules-in-sql.md
  releases/release-5.3.0.md
  sql-statements/sql-statement-alter-placement-policy.md
  sql-statements/sql-statement-create-placement-policy.md
  sql-statements/sql-statement-show-create-placement-policy.md
  sql-statements/sql-statement-show-placement-for.md
  system-variables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/XL, area/sql-infra, type/compatibility-or-feature-change, v6.0

#8646 Remove Placement Experimental warning
  configure-placement-rules.md
  placement-rules-in-sql.md
  sql-statements/sql-statement-alter-placement-policy.md
  sql-statements/sql-statement-create-placement-policy.md
  sql-statements/sql-statement-drop-placement-policy.md
  sql-statements/sql-statement-show-create-placement-policy.md
  sql-statements/sql-statement-show-placement-for.md
  sql-statements/sql-statement-show-placement-labels.md
  sql-statements/sql-statement-show-placement.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, area/sql-infra, v6.0

#8711 doc: update docs for default checksum strategy
  tiflash/tiflash-configuration.md
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, type/compatibility-or-feature-change, area/bigdata, v6.0

#8612 DM: update openapi spec
  dm/dm-open-api.md
Labels: status/LGT2, translation/done, status/can-merge, size/XXL, area/dm, v6.0

#8464 Change the default value of new_collations_enabled_on_first_bootstrap
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, type/compatibility-or-feature-change, v6.0

#8557 tabe-cache.md: add document for table cache feature
  sql-statements/sql-statement-alter-table.md
  system-variables.md
  table-cache.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, type/compatibility-or-feature-change, v6.0

#8677 Add pdctl balance-leader-scheduler config command
  pd-control.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, status/PTAL, first-time-contributor, size/S, area/scheduling, v6.0

#8707 add description for task scheduler
  tiflash/monitor-tiflash.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, v6.0, area/diagnosis

#8599 Add DM webui guide
  TOC.md
  dm/dm-webui-guide.md
  media/dm/dm-webui-preview-cn.png
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/dm, v6.0

#8738 dumpling: add a note about compression
  dumpling-overview.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-lightning, area/dumpling

#8740 tiflash: remove tidb_opt_broadcast_join
  explain-mpp.md
Labels: translation/done, status/can-merge, status/LGT3, first-time-contributor, size/XS, area/bigdata, v6.0

#8684 revise expressions pushed down
  functions-and-operators/expressions-pushed-down.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/engine, v6.0

#8605 enable of "raft-engine": change the default value
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, status/PTAL, size/XS, area/engine, type/compatibility-or-feature-change, v6.0

#8617 txn: update the document about read-consistency read check ts variable
  system-variables.md
  transaction-isolation-levels.md
Labels: translation/done, status/can-merge, status/LGT3, size/S, area/transaction, type/compatibility-or-feature-change, v6.0

#8645 tikv: update docs about in-memory pessimistic locks
  dynamic-config.md
  grafana-tikv-dashboard.md
  pessimistic-transaction.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/engine, type/compatibility-or-feature-change, v6.0

#8721 add a key feature for 5.3 release note
  releases/release-5.3.0.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8644 tikv: add some new online configs
  dynamic-config.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/engine, type/compatibility-or-feature-change, v6.0

#8648 tikv: add quota limiter doc in config
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/engine, type/compatibility-or-feature-change, v6.0

#8676 tikv: add some new online configurations
  dynamic-config.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, status/PTAL, size/S, area/engine, type/compatibility-or-feature-change, v6.0

#8659 BR: Add a new doc about creating table in batch
  TOC.md
  br/backup-and-restore-faq.md
  br/br-batch-create-table.md
Labels: status/LGT2, translation/doing, status/can-merge, status/PTAL, size/M, v6.0, area/br

#8761 update descriptions of expressions supported to be pushed down
  functions-and-operators/expressions-pushed-down.md
  system-variables.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/engine, v6.0

#8737 ticdc: clarify rowid HandleKey meaning
  ticdc/manage-ticdc.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4, area/ticdc

#8755 topsql: update tidb topsql system variable doc
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, type/compatibility-or-feature-change, v6.0, area/diagnosis

#8763 cdc update docs for `cdc server` command.
  ticdc/deploy-ticdc.md
Labels: translation/doing, status/can-merge, status/LGT3, size/S, ONCALL, needs-cherry-pick-release-5.4, area/ticdc

#8768 update description of TiFlash config: enable_elastic_threadpool
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, area/bigdata, v6.0

#8770 v6.0: adjust TOC
  TOC.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, v6.0

#8767 data-inconsistency-errors: correct a variable name
  data-inconsistency-errors.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, v6.0

#8698 add docs for mpp partition table support
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/bigdata, v6.0

#8736 tikv: configuration change 6.0
  tikv-configuration-file.md
Labels: translation/done, status/can-merge, status/LGT3, size/S, area/engine, type/compatibility-or-feature-change, v6.0

#8774 fixed a typo
  dm/task-configuration-file-full.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/dm

#8776 update LOAD DATA ... REPLACE compatibility
  faq/sql-faq.md
  mysql-compatibility.md
  privilege-management.md
  sql-statements/sql-statement-load-data.md
  tikv-configuration-file.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/sql-infra, v6.0

#8773 Update the default setting of Top SQL
  dashboard/top-sql.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, sig/diagnosis, type/compatibility-or-feature-change, v6.0

#8720 system-variables: update from generated source
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, area/general, require-LGT1, size/S, type/compatibility-or-feature-change, v6.0

#8785 Fix format and define Prometheus v2.27.1's release time in release-5.3.0.md
  releases/release-5.3.0.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, first-time-contributor, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8777 Update continuous-profiling GA for TiDB 6.0.md
  dashboard/continuous-profiling.md
  experimental-features.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, v6.0, area/diagnosis

#8793 modify configuration description
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, area/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8765 tidb: remove stmt-summary config
  releases/release-5.2.0.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, type/compatibility-or-feature-change, v6.0

#8609 update PD's `location-lable`
  schedule-replicas-by-topology-labels.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/M, area/scheduling, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8784 tikv: add missing config threshold for some online config
  dynamic-config.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, area/engine, v6.0

#8787 add a note about raft-engine
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/engine, v6.0

#8806 pdctl:Balance leader Batch
  pd-control.md
Labels: type/enhancement, status/LGT2, contribution, translation/doing, status/can-merge, size/S, area/scheduling, v6.0
