Repository pingcap/docs-cn, pull requests merged in 2022-12, with the labels that each got.

#12161 *: add annotation for localization
  faq/deploy-and-maintain-faq.md
  hardware-and-software-requirements.md
  multi-data-centers-in-one-city-deployment.md
  overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, area/general, require-LGT1, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12169 Fix incorrect description of a ticdc improvement in 6.3 RN
  releases/release-6.3.0.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12172 lightning: fix a term error
  migration-tools.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, area/tidb-lightning

#12168 tikv: updated description about region size
  tidb-storage.md
  tikv-overview.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/engine, ONCALL, needs-cherry-pick-release-6.1

#12176 slow log: fix an error in slow log
  identify-slow-queries.md
Labels: status/LGT2, translation/done, size/XS, area/sql-infra, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12136 Update two-data-centers-in-one-city-deployment.md
  two-data-centers-in-one-city-deployment.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/M, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12075 br: backup checkpoint
  TOC.md
  br/br-checkpoint.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/br, v6.5

#12090 lightning: disk quota GA
  experimental-features.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/tidb-lightning, v6.5

#12162 lightning: docs change for 'disk-quota' GA
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, v6.5

#12091 data migration: continuous data validation goes GA
  dm/dm-continuous-data-validation.md
  experimental-features.md
Labels: status/LGT2, translation/done, status/can-merge, require-LGT1, size/XS, area/dm, v6.5

#12083 dumpling, lightning: add document for compressed files support
  dumpling-overview.md
  tidb-lightning/tidb-lightning-data-source.md
  tidb-lightning/troubleshoot-tidb-lightning.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/tidb-lightning, area/dumpling, v6.5

#11702 add tiflash regexp functions
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, v6.5

#12002 enable metadata lock by default
  experimental-features.md
  metadata-lock.md
  sql-statements/sql-statement-commit.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, type/compatibility-or-feature-change, v6.5

#12111 system-variables.md: update tidb_ddl_enable_fast_reorg
  experimental-features.md
  sql-statements/sql-statement-create-index.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v6.5

#11960 AUTO_INCREMENT: MySQL compatibility mode GA
  auto-increment.md
  experimental-features.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, v6.5

#11712 tidb: add system variable `tidb_source_id` and `tidb_cdc_write_source`
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/ticdc, v6.5

#11719 ticdc: add bidirectional replication
  TOC.md
  media/ticdc/ticdc-bidirectional-replication.png
  system-variables.md
  ticdc/ticdc-bidirectional-replication.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/ticdc, v6.5

#12194 Update oracle-functions-to-tidb.md
  oracle-functions-to-tidb.md
Labels: status/LGT2, contribution, translation/no-need, status/can-merge, type/bug-fix, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12103 TiDB password management
  TOC.md
  functions-and-operators/encryption-and-compression-functions.md
  mysql-schema.md
  password-management.md
  security-compatibility-with-mysql.md
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-create-user.md
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, area/security, size/XXL, type/compatibility-or-feature-change, v6.5

#12191 add some description for GOMEMLIMIT
  configure-memory-usage.md
  media/configure-memory-usage-612-oom.png
  media/configure-memory-usage-613-no-oom.png
  media/configure-memory-usage-oom-example.png
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12137 add 6.1.3 release notes
  TOC.md
  releases/release-6.1.3.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12056 tikv-control.md: update tikv-control.md for raft region
  tikv-control.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/L, area/engine, for-release, v6.5

#11973 doc: support the view hint
  optimizer-hints.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/planner, v6.5

#9871 tikv: change cdc.min-ts-interval from 1s to 200ms
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/engine, type/compatibility-or-feature-change, for-release, v6.5

#12122 Update tiup-component-cluster-audit.md
  TOC.md
  tiup/tiup-component-cluster-audit-cleanup.md
  tiup/tiup-component-cluster-audit.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/tiup, needs-cherry-pick-release-6.4

#12197 ddl: Add some options for add index fast way usage.
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, v6.5

#11980 Update dashboard-intro.md
  dashboard/dashboard-access.md
  dashboard/dashboard-intro.md
  dashboard/dashboard-ops-deploy.md
  dashboard/dashboard-ops-security.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/diagnosis, v6.5

#12189 rawkv: change the deprecation statement back to experiment statement
  br/rawkv-backup-and-restore.md
  experimental-features.md
  releases/release-6.2.0.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12160 log-backup: reduced RPO to 5 mins
  br/backup-and-restore-overview.md
  faq/backup-and-restore-faq.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/br, v6.5

#12076 sync-diff: update passwd description
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sync-diff-inspector, v6.5

#12085 Add docs for global memory control GA
  configure-memory-usage.md
  experimental-features.md
  system-variables.md
  tidb-configuration-file.md
  troubleshoot-tidb-oom.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, v6.5

#12101 ticdc: add how to use base64 encoded mysql password
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-mysql.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/ticdc, v6.5

#12095 explain-index-merge, optimizer-hints: introduce intersection type IndexMerge
  explain-index-merge.md
  optimizer-hints.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/planner, v6.5

#12064 Correct the order of bad-ssts and --data-dir
  tikv-control.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12102 planner: support JSON format explain
  sql-statements/sql-statement-explain.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/planner, v6.5

#12055 FAQ: update deploy-and-maintain.md
  faq/deploy-and-maintain-faq.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12192 add newer go version for environment requirements
  hardware-and-software-requirements.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, area/general, size/XS

#12148 improved Chinese translation
  TOC.md
  ecosystem-tool-user-case.md
Labels: type/enhancement, status/LGT1, contribution, translation/no-need, status/can-merge, require-LGT1, first-time-contributor, size/S

#12047 tiflash: support pushing down json extract
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, v6.5

#12079 add content about nt-dml for insert and update
  non-transactional-dml.md
  sql-statements/sql-statement-batch.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, v6.5

#12181 configuration: add configurations for signing-cert and signing-key
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, needs-cherry-pick-release-6.4

#12238 chore: add v6.6 checkbox in pr template
  .github/pull_request_template.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#12112 docs: add explain analyze info for TableFullScan on TiFlash, and update related sample case
  develop/dev-guide-create-table.md
  explain-mpp.md
  sql-statements/sql-statement-explain-analyze.md
  tiflash/use-tidb-to-read-tiflash.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/bigdata, v6.5

#11825 planner: update documents about cost model
  cost-model.md
  experimental-features.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, type/compatibility-or-feature-change, v6.5

#12218 refine description of txn-total-size-limit and tidb_mem_quota_query
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, v6.5

#12242 Use shard column instead of dividing column to keep it consistent wit…
  develop/dev-guide-delete-data.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12243 remove external storage from toc
  TOC.md
  br/external-storage.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.4

#11701 TiFlash results materialization
  TOC.md
  experimental-features.md
  system-variables.md
  tiflash/tiflash-results-materialization.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/bigdata, v6.5

#12120 add ticdc best pratice and FAQ
  ticdc/deploy-ticdc.md
  ticdc/ticdc-faq.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, status/LGT2, type/refactor, translation/doing, status/can-merge, size/M, area/ticdc, needs-cherry-pick-release-6.4

#12255 sql: fix statement bug
  sql-statements/sql-statement-create-user.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12080 *: `flashback to timestamp` delete experimental flag
  experimental-features.md
  sql-statements/sql-statement-flashback-to-timestamp.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, v6.5

#12252 add doc for experimental variable tidb_store_batch_size
  system-variables.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, for-release, v6.5

#12188 Add tikv-br docs
  br/rawkv-backup-and-restore.md
  releases/release-6.4.0.md
  tikv-configuration-file.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, first-time-contributor, size/M, area/br, v6.5

#12190 tidb: update the description of closest-adaptive
  follower-read.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, v6.5

#12143 PITR: replace tikv_log_backup_store_checkpoint_ts for tidb_log_backup_last_checkpoint
  br/br-monitoring-and-alert.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, area/br, needs-cherry-pick-release-6.4

#12274 br: incorrect description of batch create table
  br/br-batch-create-table.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12271 docs: add tidb_enable_amend_pessimistic_txn depreciation
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, for-release, v6.5

#12273 update changefeed parameters and fix typo
  releases/release-6.3.0.md
  ticdc/ticdc-architecture.md
  ticdc/ticdc-changefeed-config.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/S

#12272 Bump 6.1.3
  br/backup-and-restore-use-cases.md
  check-before-deployment.md
  develop/dev-guide-proxysql-integration.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L

#11839 ticdc: replica changelog to snowflake, add a part about ETL in snowflake
  ticdc/integrate-confluent-using-ticdc.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/L, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12288 add a ticdc compatibility change to 6.1.3 RN
  releases/release-6.1.3.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12286 fix incorrect default value of transaction atomicity
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.1

#12287 add a ticdc compability change to 6.4 RN
  releases/release-6.4.0.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-6.4

#12298 remote session level force priority
  faq/sql-faq.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12144 add cluster commands
  TOC.md
  tiup/tiup-component-cluster-meta-backup.md
  tiup/tiup-component-cluster-meta-restore.md
  tiup/tiup-component-cluster-start.md
  tiup/tiup-component-cluster.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/tiup, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12304 Update ticdc-architecture.md
  ticdc/ticdc-architecture.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, area/br

#12164 v6.5: add lock stats docs
  TOC.md
  experimental-features.md
  sql-statements/sql-statement-lock-stats.md
  sql-statements/sql-statement-show-stats-locked.md
  sql-statements/sql-statement-unlock-stats.md
  statistics.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, area/planner, v6.5

#12239 add a system variable tidb_enable_plan_replayer_capture
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, for-release, v6.5

#12283 develop docs: update Cloud UI
  develop/dev-guide-bookshop-schema-design.md
  develop/dev-guide-build-cluster-in-cloud.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12303 update the support info of amending pessimistic txn
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, v6.5

#12316 tidb: update builtin string function
  functions-and-operators/string-functions.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12046 Develop Guide Python Examples
  TOC.md
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-optimistic-and-pessimistic-transaction.md
  develop/dev-guide-optimize-sql-best-practices.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-sample-application-python.md
  develop/dev-guide-third-party-support.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, requires-version-specific-changes, size/XXL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12279 add config import.memory-use-ratio
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/br, v6.5

#12213 tispark overview
  tispark-overview.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/XL, area/bigdata, needs-cherry-pick-release-6.4

#10310 cached-tables: add description about `mysql.table_cache_meta` table
  cached-tables.md
  mysql-schema.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#8626 mysql-schema.md: update system tables
  mysql-schema.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#8151 statistics.md: update the content of analyze version2 OOM handling
  statistics.md
Labels: status/LGT2, translation/doing, status/can-merge, status/PTAL, size/XS, area/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12339 Remove functions related to MySQL Enterprise Edition that TiDB does n…
  functions-and-operators/encryption-and-compression-functions.md
Labels: status/LGT2, translation/doing, status/can-merge, area/security, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12165 dev-v6.2: remove stats feedback
  basic-features.md
  statistics.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/planner, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12166 v6.1-v5.4: emphasize deprecation for stats feedback
  statistics.md
  tidb-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/planner, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#12167 v5.3-v5.0: emphasize experimental for stats feedback
  statistics.md
  tidb-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#12380 v5.3: update stats feedback description
  statistics.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, size/XS

#12280 update go to v1.19
  pd-control.md
  pd-recover.md
  tidb-control.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12386 Update the variable `max_prepared_stmt_count`
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/planner, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12358 add the reason for changing the default value
  releases/release-6.4.0.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-6.4

#12359 add the reason for changing the default value
  releases/release-6.1.3.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12284 tidb: update follower read guide
  develop/dev-guide-use-follower-read.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, v6.5

#12094 Add the doc for the TTL feature
  TOC.md
  experimental-features.md
  grafana-tidb-dashboard.md
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-create-table.md
  system-variables.md
  time-to-live.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, area/sql-infra, v6.5

#12402 Delete 2 pd parameters that have been deleted in code
  pd-control.md
Labels: status/LGT1, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12340 system_vars: re-set default value to `ON` for outer join reorder
  join-reorder.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, for-release, v6.5

#12250 Update dev-guide-delete-data.md
  develop/dev-guide-delete-data.md
  glossary.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, area/develop, v6.5

#12399 Delete a deprecated tiup command-line arg
  tiup/tiup-mirror.md
  tiup/tiup-overview.md
  tiup/tiup-reference.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/tiup, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12419 add a title for best practices for better findability
  ticdc/ticdc-sink-to-kafka.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, ONCALL, area/ticdc

#12400 Delete deprecated tiflash configs
  tiflash/tiflash-configuration.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.2, area/bigdata, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12332 update metric: CPS by instance
  best-practices/java-app-best-practices.md
  develop/dev-guide-connection-parameters.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12385 Update dashboard-metrics-relation.md
  dashboard/dashboard-cluster-info.md
  dashboard/dashboard-diagnostics-access.md
  dashboard/dashboard-key-visualizer.md
  dashboard/dashboard-metrics-relation.md
  dashboard/dashboard-overview.md
  dashboard/dashboard-session-share.md
  media/dashboard/dashboard-cluster-info-access-v650.png
  media/dashboard/dashboard-cluster-info-disks-v650.png
  media/dashboard/dashboard-cluster-info-hosts-v650.png
  media/dashboard/dashboard-cluster-info-instances-v650.png
  media/dashboard/dashboard-diagnostics-access-v650.png
  media/dashboard/dashboard-diagnostics-gen-compare-report-v650.png
  media/dashboard/dashboard-diagnostics-gen-process-v650.png
  media/dashboard/dashboard-diagnostics-gen-report-v650.png
  media/dashboard/dashboard-keyviz-access-v650.png
  media/dashboard/dashboard-metrics-relation-home-v650.png
  media/dashboard/dashboard-overview-access-v650.png
  media/dashboard/dashboard-session-share-settings-1-v650.png
  media/dashboard/dashboard-session-share-settings-2-v650.png
  media/dashboard/dashboard-session-share-settings-3-v650.png
  media/dashboard/dashboard-session-share-signin-1-v650.png
  media/dashboard/dashboard-session-share-signin-2-v650.png
  media/dashboard/dashboard-session-share-signin-3-v650.png
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, area/diagnosis

#12187 planner: support create binding from existing plan
  experimental-features.md
  sql-plan-management.md
  sql-statements/sql-statement-create-binding.md
  sql-statements/sql-statement-drop-binding.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/planner, v6.5, needs-cherry-pick-release-6.5

#12446 change tidb_enable_gc_aware_memory_track default value to off
  system-variables.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, type/compatibility-or-feature-change, v6.5, needs-cherry-pick-release-6.5

#12314 add v5.1.5 release notes
  TOC.md
  releases/release-5.1.5.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, for-release

#12393 bump version for 5.1.5
  br/backup-and-restore-use-cases.md
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  ticdc/manage-ticdc.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L

#12240 Add tiflash cdc for performance overview
  grafana-performance-overview-dashboard.md
  media/performance/grafana_performance_overview.png
  media/performance/high_disconnections.png
  media/performance/htap_tiflash_mpp.png
  media/performance/internal_stats.png
  media/performance/prepared_statement_leaking.png
  media/performance/tpcc_qps.png
  media/performance/tpcc_source_sql.png
  performance-tuning-methods.md
  performance-tuning-overview.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/diagnosis, v6.5, needs-cherry-pick-release-6.5

#12198 Add `compression` to TiCDC Kafka sink config
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/ticdc, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12452 format: use the standard ASCII vertical bar in table
  functions-and-operators/encryption-and-compression-functions.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, area/security, require-LGT1, size/XS, needs-cherry-pick-release-6.5

#12151 Add documents for cloud storage sink
  TOC.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-csv.md
  ticdc/ticdc-sink-to-cloud-storage.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, area/ticdc, v6.5, needs-cherry-pick-release-6.5

#12471 add doc for br compatibility
  br/backup-and-restore-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/br

#12414 refine the document of metadata lock
  metadata-lock.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/M, area/sql-infra, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12387 Add storage sink consumer developing guide
  TOC.md
  media/ticdc/ticdc-storage-consumer-overview.png
  ticdc/ticdc-storage-consumer-dev-guide.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/ticdc, v6.5, needs-cherry-pick-release-6.5

#12450 index page: bump up to v6.5
  _index.md
Labels: status/LGT1, translation/doing, status/can-merge, size/M, for-release, v6.5

#12268 Update the command and output in SQL statements
  functions-and-operators/set-operators.md
  sql-statements/sql-statement-admin-checksum-table.md
  sql-statements/sql-statement-create-role.md
  sql-statements/sql-statement-drop-role.md
  sql-statements/sql-statement-grant-role.md
  sql-statements/sql-statement-revoke-role.md
  sql-statements/sql-statement-set-default-role.md
  sql-statements/sql-statement-table.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XL, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12337 Update translation
  user-account-management.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#12483 Update ticdc-bidirectional-replication.md
  ticdc/ticdc-bidirectional-replication.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/ticdc, v6.5, needs-cherry-pick-release-6.5

#12100 add v6.5.0 release notes
  TOC.md
  releases/release-6.5.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XL, for-release, v6.5, needs-cherry-pick-release-6.5

#12232 v6.5: update basic-features.md
  basic-features.md
  experimental-features.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/XL, for-release, v6.5, needs-cherry-pick-release-6.5

#12442 TiUP bumpversion 6.5
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, for-release, v6.5, needs-cherry-pick-release-6.5

#12443 v6.5: bump version for tools
  br/backup-and-restore-use-cases.md
  dm/quick-start-create-task.md
  pd-control.md
  quick-start-with-tidb.md
  ticdc/deploy-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, for-release, v6.5, needs-cherry-pick-release-6.5

#12490 Update release-6.5.0.md
  releases/release-6.5.0.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.5

#12482 chore: update cdnfresh.txt for v6.5
  resources/cdnfresh.txt
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS

#12493 Update README.md
  README.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#12484 placement rules: add a role "voter"
  configure-placement-rules.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/XS, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12505 Update OS info for v6.5
  hardware-and-software-requirements.md
Labels: status/LGT1, translation/done, status/can-merge, area/deploy-upgrade-maintain, for-release, v6.5

#11937 troubleshoot: refine doc TOC
  TOC.md
  tidb-troubleshooting-map.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12512 add aliases for manage-ticdc
  ticdc/ticdc-manage-changefeed.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS

#12514 modify release notes 5.1.5
  releases/release-5.1.5.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12145 Update benchmark-tidb-using-ch.md
  benchmark/benchmark-tidb-using-ch.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12529 v6.4: update download address
  releases/release-6.4.0.md
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-master, size/XS, needs-cherry-pick-release-6.5

#12528 docs: add-fix-index-acceleration-compatibility
  releases/release-6.5.0.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, requires-version-specific-changes, size/XS, needs-cherry-pick-release-6.3, v6.5, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5
