Repository pingcap/docs-cn, pull requests merged in 2022-11, with the labels that each got.

#11579 tikv: modify TiKV & PD config docs for TiKV API v2
  experimental-features.md
  pd-configuration-file.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/engine, type/compatibility-or-feature-change, v6.4

#11672 PD: modify the rank-formula-version from experimental to GA
  experimental-features.md
  pd-control.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v6.4

#10978 config, sysvar: update descriptions about instance sysvars
  character-set-and-collation.md
  configure-memory-usage.md
  dashboard/dashboard-slow-query.md
  enable-disk-spill-encrypt.md
  explain-joins.md
  faq/manage-cluster-faq.md
  faq/sql-faq.md
  identify-slow-queries.md
  security-compatibility-with-mysql.md
  system-variables.md
  tidb-configuration-file.md
  tiup/tiup-cluster-topology-reference.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, type/compatibility-or-feature-change, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11822 ticdc: recommand user to use ticdc
  ecosystem-tool-user-case.md
  migration-tools.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11843 Update the processlist column information
  information-schema/information-schema-processlist.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/M, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11852 *: remove TiSpark from TiDB architecture diagrams
  media/tidb-architecture-v6.png
  media/tidb-storage-architecture-1.png
  tidb-architecture.md
  tidb-storage.md
  tiflash/tiflash-overview.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS

#11832 pitr: support restart log-backup task and remove several know issues.
  br/br-log-command-line.md
  br/pitr-known-issues.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/br, v6.4

#11583 tidb: add document for external timestamp read
  TOC.md
  stale-read.md
  system-variables.md
  tidb-external-ts.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, area/scheduling, type/compatibility-or-feature-change, v6.4

#11856 lightning: add an faq about placement rules in sql
  media/lightning-faq-situation-1.jpg
  media/lightning-faq-situation-2.jpg
  media/lightning-faq-source-cluster-topology.jpg
  tidb-lightning/tidb-lightning-faq.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11790 dm: add description about mysql-instance.meta
  dm/task-configuration-file-full.md
  migrate-aurora-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/dm, v6.4

#11854 Fix OS info
  hardware-and-software-requirements.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/deploy-upgrade-maintain

#11858 sysvar: correct sysvar information
  releases/release-6.2.0.md
  releases/release-6.3.0.md
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, requires-version-specific-changes, require-LGT1, size/L, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11755 dm: add some query status
  dm/dm-query-status.md
  dm/handle-failed-ddl-statements.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/dm, v6.4

#11653 [release-6.1] tiflash: Add instructions to improve replica sync performance
  tiflash/create-tiflash-replicas.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, area/bigdata, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.3

#10798 update troubleshoot-tiflash.md
  tiflash/troubleshoot-tiflash.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata

#10750 Update troubleshoot-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, first-time-contributor, size/XS, area/ticdc

#11882 fix typo about enabling tls and sql command
  enable-tls-between-clients-and-servers.md
  sql-statements/sql-statement-load-data.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#11867 release note: add the TiDB downloading info
  releases/release-6.1.0.md
  releases/release-6.2.0.md
  releases/release-6.3.0.md
Labels: status/LGT2, translation/doing, status/can-merge, area/general, requires-version-specific-changes, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11690 complement errors relating to lazy uniqueness check
  character-set-and-collation.md
  constraints.md
  log-redaction.md
  system-variables.md
  transaction-overview.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, v6.4, for-release

#11714 json: add document for json_storage_free
  functions-and-operators/json-functions.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/XS, v6.4

#11893 remove json path restrictions
  data-type-json.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/XS, v6.4

#11857 add external read doc
  sync-diff-inspector/upstream-downstream-diff.md
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/ticdc, v6.4

#11895 fix ngm port
  hardware-and-software-requirements.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, ONCALL, area/diagnosis, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11877 *: Change compatibility description for add index acceleration&PiTR
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.3

#11900 Fix a link
  exporting-grafana-snapshots.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11853 add chunk alloc system variable
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/M, area/engine, type/compatibility-or-feature-change, v6.4

#11881 dashboard: fix a pd-ctl command
  dashboard/dashboard-ops-deploy.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, area/diagnosis, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11443 sql: add `flashback cluster` doc
  TOC.md
  experimental-features.md
  sql-statements/sql-statement-flashback-to-timestamp.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, type/compatibility-or-feature-change, v6.4

#11802 add back tiflash sm4 encryption support
  encryption-at-rest.md
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, area/security, size/S, v6.4

#10885 Add some key descriptions
  migrate-aurora-to-tidb.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11565 Add docs for global memory control
  TOC.md
  configure-memory-usage.md
  experimental-features.md
  information-schema/information-schema-memory-usage-ops-history.md
  information-schema/information-schema-memory-usage.md
  information-schema/information-schema.md
  system-variables.md
Labels: translation/done, status/can-merge, status/LGT3, size/L, type/compatibility-or-feature-change, v6.4

#11713 add system variable tidb_opt_prefix_index_single_scan
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/planner, type/compatibility-or-feature-change, v6.4

#11861 planner: add description for plan cache variable
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, type/compatibility-or-feature-change, v6.4

#11239 add system variable tidb_opt_range_max_size
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, type/compatibility-or-feature-change, v6.4, needs-cherry-pick-release-6.3

#11799 Add descriptions of new panels and update the plan cache doc
  grafana-tidb-dashboard.md
  media/planCache-memoryUsage-planNum-panels.png
  sql-prepared-plan-cache.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, v6.4

#11798 auto-increment: update doc for the new implementation
  auto-increment.md
  experimental-features.md
  mysql-compatibility.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/sql-infra, v6.4

#11340 optimizer-hints, correlated-subquery-optimization: add docs for `no_decorrelate` hint
  correlated-subquery-optimization.md
  optimizer-hints.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/engine, v6.4

#11914 add version to tiup ctl to make the command work
  best-practices/three-nodes-hybrid-deployment.md
  clinic/clinic-data-instruction-for-tiup.md
  dashboard/dashboard-ops-deploy.md
  enable-tls-between-components.md
  migrate-from-tidb-to-mysql.md
  pd-control.md
  replicate-data-to-kafka.md
  three-data-centers-in-two-cities-deployment.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/manage-ticdc.md
  tidb-control.md
  tiflash/create-tiflash-replicas.md
  tiflash/tiflash-configuration.md
  tikv-control.md
  tiup/tiup-cluster.md
  troubleshoot-lock-conflicts.md
  troubleshoot-write-conflicts.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11922 update downloading info
  releases/release-6.1.1.md
  releases/release-6.1.2.md
  releases/release-6.2.0.md
  releases/release-6.3.0.md
Labels: status/LGT1, status/can-merge, requires-version-specific-changes, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11824 Add description about `tidb_auth_token` authentication
  keywords.md
  security-compatibility-with-mysql.md
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, area/security, size/S, type/compatibility-or-feature-change, v6.4

#11716 Add description about user ATTRIBUTE
  TOC.md
  information-schema/information-schema-user-attributes.md
  information-schema/information-schema.md
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-create-user.md
  sql-statements/sql-statement-show-columns-from.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, v6.4

#11876 system variables: add global scope for tidb_opt_agg_push_down
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, v6.4, for-release

#11664 join reorder: add missing part for dp algorithm
  join-reorder.md
  media/join-reorder-1.png
  media/join-reorder-2.png
  media/join-reorder-3.png
  media/join-reorder-4.png
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, v6.4

#11831 tikv: add new config `raftstore.apply-yield-write-size`
  dynamic-config.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/engine, type/compatibility-or-feature-change, v6.4

#11577 add doc for record OOM alarm
  configure-memory-usage.md
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/M, type/compatibility-or-feature-change, v6.4

#11940 fix: in k8s -> on k8s
  tidb-in-kubernetes.md
  tidb-operator-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/k8s, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11864 enable tidb_stats_load_sync_wait by default
  experimental-features.md
  statistics.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, type/compatibility-or-feature-change, v6.4

#11936 dm: update full doc about extend routes
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/dm, v6.4

#11915 sql: add doc for `flashback database`
  TOC.md
  sql-statements/sql-statement-flashback-database.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/sql-infra, v6.4, for-release

#11862 Adapt Serverless Tier in Developer Guide
  TOC.md
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-sample-application-spring-boot.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/L, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#11863 system-variables: add gogc variables
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v6.4, for-release

#11944 add variables `tidb_analyze_partition_concurrency` and `tidb_merge_partition_stats_concurrency`
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, v6.4, for-release

#11953 Change tiflash_fine_grained_shuffle_batch_size description
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/XS, area/bigdata, v6.4, for-release

#11954 Update TiFlash scale-in guidance.
  scale-tidb-using-tiup.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/bigdata, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11958 metrics: Add the PD_cluster_unhealthy_tikv_nums alert
  alert-rules.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/S, area/scheduling, v6.4

#11961 troubleshoot: fix a metric name
  troubleshoot-lock-conflicts.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, area/transaction, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11965 pull_request_template: add v6.5
  .github/pull_request_template.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1

#11938 clustered-indexes.md: change the system variable default value to ON
  clustered-indexes.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, type/compatibility-or-feature-change, v6.4, for-release

#11967 Fix typo in troubleshoot-hot-spot-issues.md
  troubleshoot-hot-spot-issues.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11972 sysvar: correct a default value
  system-variables.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, size/XS, ONCALL

#11981 fix a broken link
  exporting-grafana-snapshots.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11939 add config item pessimistic-txn.constraint-check-in-place-pessimistic
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/transaction, type/compatibility-or-feature-change, v6.4

#11959 tikv: Fix some words for TiKV API v2
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, area/engine, from-doc-test, v6.4

#11982 Refine the style of MySQL Compatibility
  mysql-compatibility.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11654 add sequelize section to Dev Guide 3rd party tools compatibility
  develop/dev-guide-third-party-tools-compatibility.md
Labels: status/LGT1, translation/done, status/can-merge, needs-cherry-pick-master, size/M, area/develop, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11624 *: update the row count display of probe side of IndexJoin and Apply
  correlated-subquery-optimization.md
  explain-joins.md
  explain-overview.md
  explain-subqueries.md
  optimizer-hints.md
  partitioned-table.md
  sql-statements/sql-statement-explain.md
  subquery-optimization.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, area/planner, v6.4, for-release

#11970 system-variables: update tidb_enable_paging, tidb_min_paging_size, tidb_max_paging_size
  media/paging-size-impact-on-tpch.png
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, type/compatibility-or-feature-change, v6.4

#11997 Add aliases for configuration files
  config-templates/complex-cdc.yaml
  config-templates/complex-mini.yaml
  config-templates/complex-tidb-binlog.yaml
  config-templates/complex-tiflash.yaml
  config-templates/complex-tispark.yaml
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-master, size/M

#11998 sysvar: delete two sysvar that has been removed from code
  explain-overview.md
  system-variables.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, v6.4

#12001 Add a prerequisite before query "GENERAL_LOG"
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#12000 sysvar: update tidb_guarantee_linearizability information
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/transaction, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11996 Update os supports for dmr versions
  hardware-and-software-requirements.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12011 v6.4: update _index.md
  _index.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, v6.4, for-release

#12025 Update system-variables.md
  system-variables.md
Labels: status/LGT2, contribution, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#11948 update the basic feature tables for v6.4
  basic-features.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, v6.4, for-release, needs-cherry-pick-release-6.4

#12006 tiup: bump version to 6.4
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, area/tiup, v6.4, for-release, needs-cherry-pick-release-6.4

#11800 Update the descriptions of recovering
  br/backup-and-restore-overview.md
  br/br-snapshot-guide.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/br, needs-cherry-pick-release-6.4

#12015 v6.4: bump version for tools
  br/backup-and-restore-storages.md
  dm/quick-start-create-task.md
  pd-control.md
  quick-start-with-tidb.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, v6.4, for-release, needs-cherry-pick-release-6.4

#11835 add v6.4 release notes
  TOC.md
  releases/release-6.4.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, v6.4, for-release, needs-cherry-pick-release-6.4

#11836 pitr: uncommenting the annotation in the known-issues: pitr truncate
  br/pitr-known-issues.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/br, v6.4

#12037 Update cdnfresh.txt for v6.4
  resources/cdnfresh.txt
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS

#12038 Remove "v" from release notes titles
  releases/release-6.1.0.md
  releases/release-6.2.0.md
  releases/release-6.4.0.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12048 remove arg -B in tiup
  tiup/tiup-overview.md
  tiup/tiup-reference.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12045 release-6.3.0.md: update the download link
  releases/release-6.3.0.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12065 Keep the download description consistent with the product-community
  download-ecosystem-tools.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12063 Remove free sign, avoid effect the update of billing plan
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-create-table.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-sample-application-spring-boot.md
  develop/dev-guide-tidb-crud-sql.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12016 Add details about sysbench and the SQL Plan Cache
  benchmark/benchmark-tidb-using-sysbench.md
  media/performance/sql_plan_cache.png
  sql-prepared-plan-cache.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12044 br: fix typos and add correct aliases
  br/backup-and-restore-overview.md
  br/backup-and-restore-storages.md
  br/br-log-architecture.md
  br/br-monitoring-and-alert.md
  br/br-pitr-guide.md
  br/br-snapshot-architecture.md
  br/br-snapshot-guide.md
  br/br-use-overview.md
  br/external-storage.md
  faq/backup-and-restore-faq.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/M, area/br, needs-cherry-pick-release-6.4

#12081 Add example about how to fill the <cluster_version>
  tiflash/create-tiflash-replicas.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/S

#12089 replace github issue for FD-863
  releases/release-6.4.0.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.4

#11849 ticdc: refactoring the document structure about ticdc
  TOC.md
  enable-tls-between-components.md
  media/ticdc/ticdc-architecture-1.jpg
  media/ticdc/ticdc-architecture-2.jpg
  media/ticdc/ticdc-architecture-3.PNG
  media/ticdc/ticdc-architecture-4.jpg
  media/ticdc/ticdc-architecture-5.jpg
  migrate-from-tidb-to-mysql.md
  migrate-from-tidb-to-tidb.md
  mysql-compatibility.md
  production-deployment-using-tiup.md
  releases/release-5.0.0.md
  releases/release-5.3.0.md
  releases/release-6.0.0-dmr.md
  releases/release-6.1.0.md
  releases/release-6.2.0.md
  releases/release-6.3.0.md
  replicate-between-primary-and-secondary-clusters.md
  replicate-data-to-kafka.md
  sync-diff-inspector/upstream-downstream-diff.md
  ticdc/deploy-ticdc.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/manage-ticdc.md
  ticdc/monitor-ticdc.md
  ticdc/ticdc-architecture.md
  ticdc/ticdc-avro-protocol.md
  ticdc/ticdc-canal-json.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-compatibility.md
  ticdc/ticdc-faq.md
  ticdc/ticdc-filter.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
  ticdc/ticdc-server-config.md
  ticdc/ticdc-sink-to-kafka.md
  ticdc/ticdc-sink-to-mysql.md
  ticdc/troubleshoot-ticdc.md
Labels: status/LGT1, status/LGT2, type/refactor, translation/doing, status/can-merge, size/XXL, area/ticdc

#12099 Update tiup-cluster-topology-reference.md
  tiup/tiup-cluster-topology-reference.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, area/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4

#12121 sysvar: add a note to disable tidb_enable_rate_limit_action
  configure-memory-usage.md
  system-variables.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#12123 Update wording to make text more accurate
  metadata-lock.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12022 Refine BR words
  br/backup-and-restore-design.md
  br/backup-and-restore-overview.md
  br/backup-and-restore-storages.md
  br/backup-and-restore-use-cases.md
  br/br-auto-tune.md
  br/br-batch-create-table.md
  br/br-incremental-guide.md
  br/br-monitoring-and-alert.md
  br/br-pitr-guide.md
  br/br-pitr-manual.md
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
  br/br-use-overview.md
  br/external-storage.md
  br/rawkv-backup-and-restore.md
  br/use-br-command-line-tool.md
  faq/backup-and-restore-faq.md
  glossary.md
  information-schema/information-schema-deadlocks.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/L, area/br, needs-cherry-pick-release-6.4

#12141 fix access-key problem
  br/backup-and-restore-storages.md
  br/br-incremental-guide.md
  br/br-pitr-guide.md
  br/br-pitr-manual.md
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/M, area/br, needs-cherry-pick-release-6.4

#12146 add split transaction release note for ticdc
  releases/release-6.4.0.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.4

#12087 Include FD-931 in release note v6.3.0
  releases/release-6.3.0.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4

#12153 *: change NewSQL to 分布式 SQL
  faq/deploy-and-maintain-faq.md
  hardware-and-software-requirements.md
  multi-data-centers-in-one-city-deployment.md
  overview.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/S, area/sql-infra

#12088 include the description of FD-1094 in release note v6.4.0
  releases/release-6.4.0.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/engine, needs-cherry-pick-release-6.4

#12152 bump version for 5.3.4
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  ticdc/manage-ticdc.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L
