Repository pingcap/docs-cn, pull requests merged in 2022-08, with the labels that each got.

#10524 tiflash: add a new configuration dt_enable_read_thread
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, area/bigdata, v6.2

#10540 lightning: disk quota
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/tidb-lightning, v6.2

#10560 sql: add fast mode
  TOC.md
  develop/dev-guide-read-in-fast-mode.md
  information-schema/information-schema-tiflash-replica.md
  sql-statements/sql-statement-set-tiflash-mode.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/L, area/sql-infra, v6.2

#10605 sql: manual compact GA
  sql-statements/sql-statement-alter-table-compact.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, v6.2

#10515 system-variables: add fine_grained_shuffle
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/bigdata, v6.2

#10694 [Update] add PE link
  develop/dev-guide-overview.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-transaction-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/S, area/develop, needs-cherry-pick-release-6.1

#10734 Revert "v6.2: update tidb_enable_paging default value"
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, v6.2

#10711 add doc for @@tidb_enable_noop_variables
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, type/compatibility-or-feature-change, v6.2

#10735 sql: Add placement columns for `show table regions`
  sql-statements/sql-statement-show-table-regions.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, v6.2

#10726 tiflash: clarify signature of function date_add push down
  releases/release-5.4.0.md
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10465 dm: add a doc for continuous data validation
  TOC.md
  dm/dm-continuous-data-validation.md
  dm/task-configuration-file-full.md
  media/dm/dm-validator-lifecycle.jpg
  media/dm/dm-validator-summary.jpg
Labels: status/LGT2, translation/doing, status/can-merge, size/XL, type/compatibility-or-feature-change, area/dm, v6.2

#10671 Update the compatibility matrix for br
  br/backup-and-restore-overview.md
  br/br-usage-restore.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, type/compatibility-or-feature-change, area/br, v6.2

#10740 tikv: add config item "raw-min-ts-outlier-threshold"
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/engine, type/compatibility-or-feature-change, v6.2

#10742 releases: add a link to release support policy
  releases/versioning.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10621 deprecate gc-merge-rewrite
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, area/engine, type/compatibility-or-feature-change, v6.2

#10712 add doc for information_schema.variables_info
  TOC.md
  information-schema/information-schema-variables-info.md
  information-schema/information-schema.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, v6.2

#10747 fix: add warning for experimental feature
  dm/dm-continuous-data-validation.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/dm, area/tidb-lightning, v6.2

#9615 TiFlash 6.2 upgrade guidline
  TOC.md
  tiflash-620-upgrade-guide.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, area/bigdata, v6.2

#10535 Update grafana-performance-overview-dashboard.md
  TOC.md
  grafana-performance-overview-dashboard.md
  media/dashboard/dashboard-monitoring.png
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/diagnosis, v6.2

#10748 dm: remove a note in validator limitation
  dm/dm-continuous-data-validation.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/dm, v6.2

#10623 Add description of `--overwrite-checkpoint-ts` for changefeed resume
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/ticdc, v6.2

#10534 Update dashboard-slow-query.md
  dashboard/dashboard-slow-query.md
  dashboard/dashboard-statement-details.md
  media/dashboard/dashboard-slow-queries-access-v620.png
  media/dashboard/dashboard-slow-queries-detail1-v620.png
  media/dashboard/dashboard-slow-queries-detail2-v620.png
  media/dashboard/dashboard-slow-queries-list1-v620.png
  media/dashboard/dashboard-slow-queries-list2-v620.png
  media/dashboard/dashboard-slow-queries-list3-v620.png
  media/dashboard/dashboard-statement-detail-v620.png
  media/dashboard/dashboard-visual-plan-2.png
  media/dashboard/dashboard-visual-plan-popup.png
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/M, area/diagnosis, v6.2

#9532 PiTR user document
  TOC.md
  br/br-log-command-line.md
  br/pitr-known-issues.md
  br/pitr-monitoring-and-alert.md
  br/pitr-troubleshoot.md
  br/pitr-usage.md
  br/point-in-time-recovery.md
  media/br/br-log-arch.png
  media/br/pitr-usage.png
Labels: status/LGT2, translation/doing, status/can-merge, size/XXL, area/br, v6.2

#10754 two-dc: remove the useless config
  two-data-centers-in-one-city-deployment.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/scheduling, v6.2

#10670 *: add docs home and tidb docs learning path
  _docHome.md
Labels: status/LGT2, translation/no-need, status/can-merge, area/general, size/L

#10761 *: add docs home link in toc
  TOC.md
Labels: status/LGT1, translation/done, status/can-merge, area/general, require-LGT1

#10763 tiflash: correct major version description
  tiflash-620-upgrade-guide.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, v6.2

#10756 Fix a typo in pitr-usage.md
  br/pitr-usage.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS

#10764 develop: dev-guide-transaction-troubleshoot-typo.md fix typo
  develop/dev-guide-transaction-troubleshoot.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1

#10769 refine expression of pitr limitations
  br/point-in-time-recovery.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/br, v6.2

#10753 Change the foreground quota limiter from experiemental to GAed.
  tikv-configuration-file.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/engine, type/compatibility-or-feature-change, v6.2

#10770 Fix format and remove ambiguous words
  command-line-flags-for-tikv-configuration.md
  dynamic-config.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/M, v6.2

#10760 planner: update documents about cost model
  cost-model.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/planner, v6.2

#10775 tidb: add docs home in toc, and updated learning path
  TOC.md
  _index.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, area/general, needs-cherry-pick-release-4.0, requires-version-specific-changes, require-LGT1, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10773 Update dispatch.yml
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#10774 Update dispatch.yml
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/S

#10786 Use a proper expression for iops limiation
  tikv-configuration-file.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/sql-infra, v6.2

#10799 learning path: fix a broken link
  _index.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, area/general

#10800 learning path: fix a broken link
  _index.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/XS

#10755 system-veriables: add @@tidb_min_paging_size and @@tidb_max_paging_size
  system-variables.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v6.2

#10772 update the limitations of multi-schema change
  mysql-compatibility.md
  sql-statements/sql-statement-alter-table.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, v6.2

#10797 sysvar: update whether to persist to cluster for add tidb_opt_skew_di…
  optimizer-hints.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/S, area/planner, v6.2

#10812 system variable: correct the description about tidb_min_paging_size
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, v6.2

#10813 correct experimental information in docs
  basic-features.md
  experimental-features.md
  statistics.md
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, requires-version-specific-changes, require-LGT1, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, add-missing-sysvar-experimental-docs

#10757 update tikv config for pitr
  br/pitr-usage.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, type/compatibility-or-feature-change, v6.2

#10759 sql-statements: add explanation for `explain format = "brief"`
  sql-statements/sql-statement-explain.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/S, area/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10807 ticdc: add uri encode example
  ticdc/manage-ticdc.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/ticdc

#10810 add missing doc for enable-forwarding
  tidb-configuration-file.md
  tikv-configuration-file.md
Labels: translation/doing, status/can-merge, status/LGT3, needs-cherry-pick-release-5.0, size/S, area/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar-experimental-docs

#10752 tidb-configuration-file: remove the query feedback related configuration
  releases/release-5.0.0.md
  releases/release-5.1.0.md
  releases/release-5.2.0.md
  statistics.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v6.2

#10821 Revert "add recovery guide for two dc deployment"
  tikv-control.md
  two-data-centers-in-one-city-deployment.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, v6.2

#10838 Revert "config: add description of report-min-resolved-ts-interval"
  tikv-configuration-file.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, v6.2

#10829 br: add intro version for log backup configs
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, area/br, v6.2

#10847 Add fast analyze to experimental document
  experimental-features.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, area/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, add-missing-sysvar-experimental-docs

#10811 Add desc for variable `tidb_batch_pending_tiflash_count`
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, add-missing-sysvar-experimental-docs

#10352 Add alert rules for PD_cluster_slow_tikv_nums
  alert-rules.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/scheduling, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10839 br: modify metric name in alert rule and add alert examples
  br/pitr-monitoring-and-alert.md
Labels: translation/done, status/can-merge, status/LGT3, size/L, area/br, v6.2

#10841 br: replace PiTR with PITR
  TOC.md
  br/pitr-known-issues.md
  br/pitr-monitoring-and-alert.md
  br/pitr-troubleshoot.md
  br/pitr-usage.md
  br/point-in-time-recovery.md
  media/br/pitr-usage.png
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/L, area/br

#10830 v6.2: bump version for tools
  br/backup-and-restore-use-cases.md
  dm/quick-start-create-task.md
  migrate-from-tidb-to-mysql.md
  pd-control.md
  quick-start-with-tidb.md
  replicate-data-to-kafka.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/migrate, v6.2

#10840 Not recommend setting tiflash logical split since 6.2
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, v6.2

#10860 fix broken link in binlog-consumer-client.md
  tidb-binlog/binlog-consumer-client.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10844 add some config item for PageStorage V3
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, v6.2

#10863 placement: add some additional syntax tree
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-create-database.md
  sql-statements/sql-statement-create-table.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1

#10808 add more info in tiflash 620 upgrade guide
  tiflash-620-upgrade-guide.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, v6.2

#10865 Add Cascades Planner to experimental-features
  experimental-features.md
Labels: status/LGT1, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, add-missing-sysvar-experimental-docs

#10876 fix wrong description in pitr
  br/point-in-time-recovery.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/br, v6.2

#10879 chore: disable release-6.2
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS

#10845 sysvar: add description in INSTANCE sysvars
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1

#10878 Syncing tab choices using groupId
  clinic/clinic-user-guide-for-tiup.md
  clinic/quick-start-with-clinic.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-get-data-from-single-table.md
  develop/dev-guide-join-tables.md
  develop/dev-guide-optimistic-and-pessimistic-transaction.md
  develop/dev-guide-paginate-results.md
  develop/dev-guide-prepared-statement.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-transaction-restraints.md
  develop/dev-guide-update-data.md
  develop/dev-guide-use-stale-read.md
  develop/dev-guide-use-temporary-tables.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/L, area/clinic, area/develop, needs-cherry-pick-release-6.1

#10805 ticdc: fix missing step and remove a figure
  ticdc/integrate-confluent-using-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, area/ticdc, needs-cherry-pick-release-6.1

#8615 drainer: update config template
  config-templates/complex-tidb-binlog.yaml
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-binlog, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10888 changed Fast Mode to FastScan
  TOC.md
  develop/dev-guide-read-in-fast-mode.md
  develop/dev-guide-use-fastscan.md
  sql-statements/sql-statement-set-tiflash-mode.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/L, area/sql-infra, needs-cherry-pick-release-6.2

#10903 Enable master on 6.2
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#10846 use scale-in to manually remove a TiFlash node
  scale-tidb-using-tiup.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10882 add 4 missing system variables
  system-variables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.2, add-missing-sysvar-experimental-docs

#10397 Remove locking function from the list of unsupported functions
  functions-and-operators/miscellaneous-functions.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10706 develop: add ProxySQL integration guidance
  TOC.md
  develop/dev-guide-proxysql-integration.md
  media/develop/proxysql_config_flow.png
  media/develop/proxysql_config_layer.png
Labels: status/LGT2, translation/no-need, status/can-merge, size/XXL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10913 migration-tidb-faq: update now there is support for load data ... replace into
  faq/migration-tidb-faq.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10919 develop/dev-guide-proxysql-integration.md: fix groupid
  develop/dev-guide-proxysql-integration.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10908 Add 3 transaction related sysvar
  system-variables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/M, area/transaction, needs-cherry-pick-release-6.2, add-missing-sysvar-experimental-docs

#10859 Add max-days and max-backups default value 0 means for PD
  pd-configuration-file.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/scheduling, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#9610 add tidb_txn_commit_batch_size
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/transaction, type/compatibility-or-feature-change, v6.2

#10638 system-variables: add global scope to tidb_replica_read
  system-variables.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10932 best practice: add link to tidb config `networks`
  best-practices/haproxy-best-practices.md
Labels: type/enhancement, status/LGT1, translation/done, area/best-practices, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10866 Update tiflash-620-upgrade-guide.md
  TOC.md
  tiflash-620-upgrade-guide.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/M, area/sql-infra, v6.2, needs-cherry-pick-release-6.2

#10938 fix link and update description
  tiflash-620-upgrade-guide.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.2

#10943 br: rename three br docs under maintain for better search experience
  TOC.md
  backup-and-restore-use-cases-for-maintain.md
  br-usage-backup-for-maintain.md
  br-usage-restore-for-maintain.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XXL, area/br, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10910 tiup bump version 6.2
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L, v6.2, needs-cherry-pick-release-6.2

#10900 *: update binary package for 6.2.0
  binary-package.md
  download-ecosystem-tools.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, v6.2, needs-cherry-pick-release-6.2

#10942 tiup bench: modify command from --output to --output-dir
  tiup/tiup-bench.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, area/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10891 ticdc: refine wording for integrating with kafka
  replicate-data-to-kafka.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/ticdc

#10931 faq: remove error codes content from tidb faq
  error-codes.md
  faq/deploy-and-maintain-faq.md
  faq/manage-cluster-faq.md
  faq/monitor-faq.md
  faq/tidb-faq.md
  sql-statements/sql-statement-load-data.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10969 ci: add link fail fast
  .github/workflows/link-fail-fast.yaml
  .github/workflows/link.yaml
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10971 update open-tracing tidb-configuration description
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10940 sysvar: add 12 missing planner sysvars
  system-variables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, area/planner, needs-cherry-pick-release-6.2, add-missing-sysvar-experimental-docs

#10970 Add 6.2 benchmark doc
  TOC.md
  benchmark/benchmark-sysbench-v6.2.0-vs-v6.1.0.md
  benchmark/v6.2-performance-benchmarking-with-tpcc.md
  benchmark/v6.2-performance-benchmarking-with-tpch.md
  media/sysbench_v610vsv620_point_select.png
  media/sysbench_v610vsv620_read_write.png
  media/sysbench_v610vsv620_update_index.png
  media/sysbench_v610vsv620_update_non_index.png
  media/tpcc_v610_vs_v620.png
Labels: status/LGT2, translation/doing, status/can-merge, area/general, size/XL, v6.2, needs-cherry-pick-release-6.2

#10785 update basic features and experimental features for v6.2
  basic-features.md
  experimental-features.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, v6.2, needs-cherry-pick-release-6.2

#10944 v6.2: bump version for learning path
  _index.md
Labels: status/LGT1, translation/from-docs, status/can-merge, v6.2

#10983 PD Recover: update Go version from v1.13 to v1.16
  pd-recover.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10997 ticdc: highlight integrate with snowflake
  TOC.md
  ticdc/integrate-confluent-using-ticdc.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/M, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10980 ticdc: fix code format and adjust a note
  migrate-from-tidb-to-mysql.md
  migrate-from-tidb-to-tidb.md
  replicate-between-primary-and-secondary-clusters.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10967 tune-operating-system.md: add more links and fix format
  tune-operating-system.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/M, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10979 Add description for auto detect mode of online recovery
  online-unsafe-recovery.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/engine, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10996 sysvar, config: improve force-priority
  system-variables.md
  tidb-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11010 ticdc: emphasize integrating with snowflake in overview
  integration-overview.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11013 update version in TOC for sysbench and tpc-c reports
  TOC.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, v6.2, needs-cherry-pick-release-6.2

#10762 add ch benchmark
  TOC.md
  benchmark/benchmark-tidb-using-ch.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11022 lightning: fix toc issues
  TOC.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11020 migration: add ticdc in migration overview
  migration-overview.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/migrate, needs-cherry-pick-release-6.2

#11029 lightning: delete contents about diagrams in lightning
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/migrate, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#11021 pitr: add known issues
  br/pitr-known-issues.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/br, v6.2, needs-cherry-pick-release-6.2

#11034 Update for outer join reorder
  join-reorder.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, needs-cherry-pick-release-6.1, v6.2, needs-cherry-pick-release-6.2

#10843 *: add 6.2.0 release notes
  TOC.md
  releases/release-6.2.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, v6.2, needs-cherry-pick-release-6.2

#11039 chore: enable build of release 6.2
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#10941 lightning: fix format and typo
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-requirements.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#10714 develop tier feature update
  TOC.md
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-create-database.md
  develop/dev-guide-create-secondary-indexes.md
  develop/dev-guide-create-table.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-tidb-crud-sql.md
  develop/dev-guide-update-data.md
  media/develop/tidb-cloud-connect.png
Labels: status/LGT2, translation/no-need, status/can-merge, size/M, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11046 add 6.2 to the cdnfresh list
  resources/cdnfresh.txt
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#11048 fix the admonition Note format
  develop/dev-guide-transaction-troubleshoot.md
  pd-configuration-file.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11040 chore: enable build of the master branch
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#11051 refine 6.2 release docs
  TOC.md
  releases/release-6.2.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.2

#11054 Update README.md
  README.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.2

#11047 modify pitr doc for comments about log-backup.enable
  br/br-log-command-line.md
  br/pitr-usage.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/br, v6.2, needs-cherry-pick-release-6.2

#11058 fix typo in monitor-tidb-lightning.md
  tidb-lightning/monitor-tidb-lightning.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11066 release 5.3.1: move dm bug fixes from the ticdc module to the dm module
  releases/release-5.3.1.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11072 Update dispatch.yml
  .github/workflows/dispatch.yml
Labels: status/LGT1, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-2.1, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11086 change PNG to png
  media/integrate/confluent-topics.png
  ticdc/integrate-confluent-using-ticdc.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11065 emphasize a ticdc improvement in 6.1 release notes
  releases/release-6.1.0.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11092 Revert "Update a path in haproxy guide"
  best-practices/haproxy-best-practices.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/sql-infra, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11089 faq: add a summary page for all TiDB FAQs
  TOC.md
  _index.md
  faq/faq-overview.md
Labels: type/enhancement, status/LGT1, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11100 faq: add k8s to the summary page
  faq/faq-overview.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11045 add doc for tidb_last_query_info and tidb_shard_allocate_step
  system-variables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/S, area/sql-infra, needs-cherry-pick-release-6.2, add-missing-sysvar-experimental-docs

#11099 fix incorrect description in migration faq
  faq/migration-tidb-faq.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL

#11002 TiCDC FAQ: clarify the scenario when using TiDB Lightning and BR
  ticdc/ticdc-faq.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11108 fix: typo on ticdc open api field description
  ticdc/ticdc-open-api.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/XS

#11116 chore: add 6.3 to PR template
  .github/pull_request_template.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#11073 lightning: fix a heading in physical import mode
  releases/release-6.2.0.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/tidb-lightning

#10313 add transaction-atomicity parameter to TiCDC
  ticdc/manage-ticdc.md
  ticdc/ticdc-faq.md
  ticdc/ticdc-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, type/compatibility-or-feature-change, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11121 fix format
  releases/release-6.0.0-dmr.md
  tikv-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.1

#11127 tidb: add a new entry in release notes 5.1.4
  releases/release-5.1.4.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-5.1, ONCALL, needs-cherry-pick-release-6.1

#9884 clinic v0.8.0: Support collection of SQL query plan related information
  TOC.md
  clinic/clinic-collect-sql-query-plan.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/L, area/clinic, needs-cherry-pick-release-6.1

#11141 br: refine sst file naming format
  br/backup-and-restore-design.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, area/br, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11136 clinic: revise clinic plan replayer load
  clinic/clinic-collect-sql-query-plan.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/clinic, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#11110 revise plan replayer load
  sql-plan-replayer.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/M, area/planner, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#11152 dev guide: fix title of fastscan
  develop/dev-guide-use-fastscan.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, area/develop, needs-cherry-pick-release-6.2

#11103 ci: add prevent deletion
  .github/workflows/prevent-deletion.yaml
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2
