Repository pingcap/docs-cn, pull requests merged in 2022-04, with the labels that each got.

#8778 Rename table cache to cached tables
  TOC.md
  cached-tables.md
  sql-statements/sql-statement-alter-table.md
  system-variables.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/S, area/sql-infra, v6.0

#8811 Add tiflash repo link to overview
  tiflash/tiflash-overview.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/bigdata, v6.0

#8807 Add more warnings about running mpp on partition table.
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, v6.0

#8810 Disable Raft Engine by default
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/engine, type/compatibility-or-feature-change, v6.0

#8808 Update dynamic-config.md
  dynamic-config.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/XS, area/engine

#8813 fix typo in placement rules
  placement-rules-in-sql.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, area/sql-infra, v6.0, needs-cherry-pick-release-6.0

#8809 add doc for new-collation-enable in br
  br/backup-and-restore-tool.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, v6.0, area/br, needs-cherry-pick-release-6.0

#8802 Clarify unclear description
  sql-plan-management.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, v6.0, needs-cherry-pick-release-6.0

#8816 tiup-bump-version-6.0
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  tiup/tiup-bench.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, v6.0, needs-cherry-pick-release-6.0

#8818 Update-telemetry
  telemetry.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/tiup, area/diagnosis, needs-cherry-pick-release-6.0

#8823 commented out incorrect links
  dm/dm-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.0

#8827 Add new functions to the pushdown lists
  functions-and-operators/expressions-pushed-down.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/engine, v6.0

#8733 Clinic: add "quick-start-with-clinic".md
  TOC.md
  clinic/quick-start-with-clinic.md
  media/clinic-get-token.png
Labels: status/LGT2, translation/doing, status/can-merge, size/L, v6.0, area/clinic, needs-cherry-pick-release-6.0

#8833 Change monitoring_servers to grafana_servers
  tiup/customized-montior-in-tiup-environment.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.0

#8792 update the data inconsistency doc
  TOC.md
  error-codes.md
  system-variables.md
  troubleshoot-data-inconsistency-errors.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/transaction, v6.0, needs-cherry-pick-release-6.0

#8783 update experimental features and basic features in 6.0
  basic-features.md
  experimental-features.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/XL, v6.0, needs-cherry-pick-release-6.0

#8758 Clinic: update content for 6.0
  TOC.md
  clinic/clinic-data-instruction-for-tiup.md
  clinic/clinic-introduction.md
  clinic/clinic-user-guide-for-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, v6.0, area/clinic, needs-cherry-pick-release-6.0

#8841 Clinic: Revise a link
  clinic/clinic-user-guide-for-tiup.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/clinic

#8829 Fix typo: set `stats` value to `pseudo`
  identify-expensive-queries.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8608 fix wrong jdbc sqlite url in ticdc confluent integration doc
  ticdc/integrate-confluent-using-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/ticdc

#8742 tidb-configuration-file.md: add grpc-compression-type
  tidb-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, require-LGT1, size/XS, area/sql-infra

#8853 placement-rules-in-sql: add some lightning descriptions
  placement-rules-in-sql.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, first-time-contributor, size/XS, area/sql-infra, v6.0, needs-cherry-pick-release-6.0

#8779 add 6.0 terms in glossary
  glossary.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/M, v6.0, needs-cherry-pick-release-6.0

#8842 PD Control: add a line about `store limit`
  pd-control.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/scheduling

#8843 Clinic: Revise a link for 6.0 branch
  clinic/clinic-user-guide-for-tiup.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/clinic

#8858 Add alter partition demo in placement in sql
  placement-rules-in-sql.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, v6.0, needs-cherry-pick-release-6.0

#8857 Unify title for explain-overview
  blocklist-control-plan.md
  explain-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/planner, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8865 add 6.0 benchmark
  TOC.md
  benchmark/benchmark-sysbench-v6.0.0-vs-v5.4.0.md
  benchmark/v6.0-performance-benchmarking-with-tpcc.md
  media/sysbench_v540vsv600_point_select.png
  media/sysbench_v540vsv600_read_write.png
  media/sysbench_v540vsv600_update_index.png
  media/sysbench_v540vsv600_update_non_index.png
  media/tpcc_v540_vs_v600.png
Labels: status/LGT2, translation/done, status/can-merge, size/XL, v6.0, needs-cherry-pick-release-6.0

#8863 Adjust the structure of replica creation and az setting
  tiflash/use-tiflash.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, area/bigdata, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8830 align multiple pr sql
  mysql-compatibility.md
  releases/release-5.3.0.md
  sql-statements/sql-statement-select.md
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/M, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8871 fix 6.0 release notes
  releases/release-6.0.0-dmr.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, v6.0, needs-cherry-pick-release-6.0

#8890 Revert "disable trigger website building from docs master (#8705)"
  .github/workflows/dispatch.yml
Labels: status/LGT1, status/can-merge, require-LGT1, first-time-contributor, missing-translation-status, size/XS

#8891 Clarify the ambiguous description of `data-dir` free space
  ticdc/deploy-ticdc.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/S, needs-cherry-pick-release-5.4, area/ticdc, needs-cherry-pick-release-6.0

#8900 Remove aliases from feature-expression-filter
  dm/feature-expression-filter.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS

#8897 refine cn-name of elastic thread pool
  releases/release-6.0.0-dmr.md
  tiflash/tiflash-configuration.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/no-need, status/can-merge, size/XS, area/bigdata, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8904 releases: change the order of new features and compatibility changes
  releases/release-6.0.0-dmr.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L, v6.0, needs-cherry-pick-release-6.0

#8917 Update release-6.0.0-dmr.md
  releases/release-6.0.0-dmr.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.0

#8481 Create dm-compatibility-catalog.md
  TOC.md
  dm/dm-compatibility-catalog.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8923 Update use-tiflash.md: add semicolon for sqls
  tiflash/use-tiflash.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/S, area/bigdata, needs-cherry-pick-release-6.0

#8915 Fix improper title levels of use tiflash
  tiflash/use-tiflash.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/bigdata

#8920 fix-spaces-and-punctuation
  tidb-scheduling.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, first-time-contributor, size/XS

#8926 fix typo "tidb_ignore_clost_stmt_cmd" in tidb 6.0.0 release notes
  releases/release-6.0.0-dmr.md
  sql-prepare-plan-cache.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/XS, area/sql-infra, needs-cherry-pick-release-6.0

#8903 Remove aliases from migration-overview.md and sql-statement-set-names.md
  migration-overview.md
  sql-statements/sql-statement-set-names.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, size/XS

#8826 tidb-lightning: clarify an ambiguous description for sorted-kv-dir
  migrate-aurora-to-tidb.md
  migrate-from-csv-files-to-tidb.md
  migrate-from-sql-files-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-requirements.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, requires-version-specific-changes, require-LGT1, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.0

#8864 update binlog proto URI
  tidb-binlog/binlog-consumer-client.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-binlog, needs-cherry-pick-release-6.0

#8945 Add TiFlash to the credits.md
  credits.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.0

#8905 Remove aliases from query-execution-plan.md
  query-execution-plan.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#8906 Remove aliases from query-execution-plan.md and tidb-lightning-faq.md
  query-execution-plan.md
  tidb-lightning/tidb-lightning-faq.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, size/XS

#8794 Add RBAC desc and fix format for Dashboard user management
  dashboard/dashboard-user.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/diagnosis, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8907 Remove aliases from query-execution-plan.md
  faq/tidb-faq.md
  functions-and-operators/control-flow-functions.md
  functions-and-operators/operators.md
  query-execution-plan.md
  tidb-binlog/binlog-consumer-client.md
  tidb-binlog/tidb-binlog-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, size/M

#8951 sync-diff: fix the download link in v3.0
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, size/XS

#8953 sync-diff: remove the download link in v3.1
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, size/XS, area/sync-diff-inspector

#8955 sync-diff: fix the download link in v5.1
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, size/XS, area/sync-diff-inspector

#8952 Remove the default value of `idb_analyze_version` in v5.1 and v5.2
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, size/XS, area/planner, needs-cherry-pick-release-5.2

#8968 Update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/tiup, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8967 Fix typos in placement-rules-in-sql.md
  placement-rules-in-sql.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/XS, area/sql-infra, needs-cherry-pick-release-6.0

#8564 Clarify the meaning of small transaction for TTL
  tidb-troubleshooting-map.md
Labels: type/enhancement, translation/doing, status/can-merge, status/LGT3, size/XS, area/transaction, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8889 TiDB Dashboard: Polish v6.0 features
  TOC.md
  basic-features.md
  dashboard/continuous-profiling.md
  dashboard/dashboard-faq.md
  dashboard/dashboard-profiling.md
  dashboard/top-sql.md
  hardware-and-software-requirements.md
  media/dashboard/dashboard-conprof-access.png
  media/dashboard/top-sql-access.png
  media/dashboard/top-sql-details.png
  media/dashboard/top-sql-usage-change-timerange.png
  media/dashboard/top-sql-usage-chart.png
  media/dashboard/top-sql-usage-refresh.png
  media/dashboard/top-sql-usage-select-instance.png
  tiup/tiup-cluster-topology-reference.md
Labels: type/enhancement, status/LGT1, status/LGT2, status/can-merge, size/XL, area/diagnosis, needs-cherry-pick-release-6.0

#8971 fix description of OPM
  grafana-tidb-dashboard.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.4, area/diagnosis, needs-cherry-pick-release-6.0

#8831 system-variables: document tidb-enable-alter-placement
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/sql-infra, needs-cherry-pick-release-5.3

#8984 chore: add 6.1 in pr template
  .github/pull_request_template.md
  README.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#8989 update dumpling eg format
  dumpling-overview.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, needs-cherry-pick-release-5.4, area/dumpling, needs-cherry-pick-release-6.0

#8995 Delete performance.max-memory
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, area/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8927 Add a warning in exporting-grafana-snapshots.md
  exporting-grafana-snapshots.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/clinic, needs-cherry-pick-release-6.0

#9005 Revert #8186 in release-5.4
  statement-summary-tables.md
  system-variables.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, size/S, sig/diagnosis, type/compatibility-or-feature-change

#8992 Update tidb-configuration-file.md
  tidb-configuration-file.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, area/planner, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8996 TiUP: revise a wrong link
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, area/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9006 Revise the format of a warning in exporting-grafana-snapshots.md
  exporting-grafana-snapshots.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/clinic

#8991 *: rename prepare-plan-cache to prepared-plan-cache
  TOC.md
  basic-features.md
  optimizer-hints.md
  releases/release-6.0.0-dmr.md
  sql-optimization-concepts.md
  sql-prepared-plan-cache.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, area/planner, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8961 Add a warning about upgrading tiflash using tiup
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-master, size/S, area/tiup, area/bigdata, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8944 Fix connector/j version
  connectors-and-apis.md
Labels: status/LGT1, translation/done, status/can-merge, status/PTAL, require-LGT1, size/S

#8997 manage-cluster-faq: add an faq to introduce how to estimate table size
  faq/manage-cluster-faq.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/sql-infra, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8970 Modify the filename that appears in the br command
  br/use-br-command-line-tool.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, first-time-contributor, size/XS, needs-cherry-pick-release-5.4, area/br, needs-cherry-pick-release-6.0

#8950 ticdc: update overview
  ticdc/ticdc-overview.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/ticdc, needs-cherry-pick-release-6.0

#8457 Description of custom osc tool's table names
  dm/feature-online-ddl.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/dm, needs-cherry-pick-release-6.0

#8986 Remove spark-defaults.conf in statistics
  tispark-overview.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, area/bigdata

#9019 Add parameter -i to specify the key file used to connect to the target machine
  quick-start-with-tidb.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, area/tiup, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9015 Change the description of shell profile after install TiDB and fix format
  quick-start-with-tidb.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, area/tiup, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9049 Fix typo in quick-start-with-tidb.md
  quick-start-with-tidb.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/tiup, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9026 Modify OpenSSL x509 command line parameters
  certificate-authentication.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, area/security, needs-cherry-pick-release-4.0, require-LGT1, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8724 Relink some missed docs
  TOC.md
  dm/dm-benchmark-v5.3.0.md
  dm/dm-benchmark-v5.4.0.md
  dm/dm-handle-performance-issues.md
  dm/quick-create-migration-task.md
  dm/scenarios.md
  dm/task-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XL, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9053 ticdc: refine DR Introduction
  ticdc/manage-ticdc.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/ticdc, needs-cherry-pick-release-6.0

#9063 Update the data index inconsistency docs
  troubleshoot-data-inconsistency-errors.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/transaction, needs-cherry-pick-release-6.0

#8969 dm: fix quick-start
  dm/dm-overview.md
  dm/quick-start-with-dm.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/L, area/dm, needs-cherry-pick-release-6.0

#9076 remove missing docs for 5.4
  dm/scenarios.md
  dm/task-configuration-file.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/L, area/dm

#8985 Update TiSpark documentation
  .gitignore
  TOC.md
  get-started-with-tispark.md
  tispark-overview.md
Labels: status/LGT1, status/LGT2, type/refactor, translation/from-docs, status/can-merge, size/XL, area/bigdata, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9079 Modify Mac to macOS in quick-start-with-tidb.md
  quick-start-with-tidb.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.0

#9074 Fix broken links
  tidb-binlog/binlog-consumer-client.md
  tidb-binlog/tidb-binlog-overview.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-binlog, needs-cherry-pick-release-6.0

#9078 Fix example errors in placement-rules-in-sql.md
  placement-rules-in-sql.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/sql-infra, needs-cherry-pick-release-6.0

#8957 Remove backup-and-restore-using-dumpling-lightning.md from 5.0-dev
  backup-and-restore-using-dumpling-lightning.md
  br/backup-and-restore-tool.md
  table-filter.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/br, needs-cherry-pick-release-6.0

#8958 Add backup-and-restore-using-dumpling-lightning.md to TOC of the 4.0 branch
  TOC.md
  br/backup-and-restore-tool.md
  table-filter.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/br

#8988 tool: update the tool downloading links and instructions
  br/backup-and-restore-tool.md
  br/backup-and-restore-use-cases.md
  dm/deploy-a-dm-cluster-using-binary.md
  dm/quick-start-create-task.md
  download-ecosystem-tools.md
  dumpling-overview.md
  get-started-with-tidb-lightning.md
  pd-control.md
  pd-recover.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  tidb-binlog/binlog-control.md
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-binlog/tidb-binlog-reparo.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-overview.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, area/migrate, needs-cherry-pick-release-6.0

#9073 Modify column signed int to unsigned int also raises ERROR 8200
  sql-statements/sql-statement-modify-column.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/S, ONCALL, needs-cherry-pick-release-6.0

#9102 Dashboard: fix typo on dashboard-key-visualizer.md
  dashboard/dashboard-key-visualizer.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/diagnosis, needs-cherry-pick-release-6.0

#8828 update raft log gc related tikv configurations
  tikv-configuration-file.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/engine, type/compatibility-or-feature-change, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8987 fix remove no-schema config
  get-started-with-tidb-lightning.md
  migrate-from-csv-files-to-tidb.md
  migrate-from-sql-files-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.0

#8977 Update tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.0

#9122 Fix the rule of TiKV_GC_can_not_work
  alert-rules.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/engine, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9131 fix 2 broken links in dm docs
  dm/shard-merge-best-practices.md
  migrate-from-sql-files-to-tidb.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#8781 add introduction of dm's safe-mode
  TOC.md
  dm/dm-safe-mode.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, area/dm

#8990 Update docs for TiDB Dashboard
  dashboard/dashboard-faq.md
  dashboard/dashboard-profiling.md
  dashboard/top-sql.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/M, area/diagnosis, needs-cherry-pick-release-6.0

#8739 add aliyun oss example
  br/backup-and-restore-storages.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, needs-cherry-pick-release-5.4, area/br, needs-cherry-pick-release-6.0

#9139 Actions: Fix "fatal: unsafe repository" in rebase.yml
  .github/workflows/rebase.yml
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9099 Refine the format of JSON and add one more method to change pd config in placement rules
  two-data-centers-in-one-city-deployment.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, area/scheduling, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9088 TiEM: add blank files and TOC
  TOC.md
  tiem/tiem-clone-cluster.md
  tiem/tiem-cluster-check.md
  tiem/tiem-cluster-management.md
  tiem/tiem-data-import-and-export.md
  tiem/tiem-data-replication.md
  tiem/tiem-faq.md
  tiem/tiem-install-and-maintain.md
  tiem/tiem-overview.md
  tiem/tiem-product-initialization.md
  tiem/tiem-quick-start.md
  tiem/tiem-release-1.0.0.md
  tiem/tiem-release-notes.md
  tiem/tiem-resource-management.md
  tiem/tiem-system-management.md
  tiem/tiem-take-over-cluster.md
  tiem/tiem-task-management.md
  tiem/tiem-user-management.md
Labels: translation/doing, size/M, area/tiem

#9143 fix-description-checksum
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-glossary.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, requires-version-specific-changes, size/XS, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.0

#9157 develop: add dev guide
  TOC.md
  develop/bookshop-schema-design.md
  develop/build-cluster-in-cloud.md
  develop/choose-driver-or-orm.md
  develop/client-connection-parameters.md
  develop/connect-to-tidb.md
  develop/connection-parameters.md
  develop/create-database.md
  develop/create-secondary-indexes.md
  develop/create-table.md
  develop/delete-data.md
  develop/developer-guide-overview.md
  develop/get-data-from-single-table.md
  develop/implicit-type-conversion.md
  develop/insert-data.md
  develop/join-tables.md
  develop/object-naming-guidelines.md
  develop/optimistic-and-pessimistic-transaction.md
  develop/paginate-results.md
  develop/prepared-statement.md
  develop/sample-application-java.md
  develop/sample-application-spring-boot.md
  develop/schema-design-overview.md
  develop/sql-development-specification.md
  develop/subquries.md
  develop/supported-by-community.md
  develop/supported-by-pingcap.md
  develop/temporary-table.md
  develop/tidb-crud-sql.md
  develop/timeouts-in-tidb.md
  develop/transaction-overview.md
  develop/transaction-restraints.md
  develop/unique-serial-number-generation.md
  develop/unstable-result-set.md
  develop/update-data.md
  develop/views.md
  media/develop/IMG_20220331-232643794.png
  media/develop/IMG_20220331-232726165.png
  media/develop/IMG_20220331-232800929.png
  media/develop/IMG_20220401-234316020.png
  media/develop/IMG_20220402-003303222.png
  media/develop/IMG_20220402-003350731.png
  media/develop/IMG_20220402-003416079.png
  media/develop/IMG_20220402-003505846.png
  media/develop/IMG_20220402-003528474.png
  media/develop/IMG_20220402-003549966.png
  media/develop/IMG_20220402-003659102.png
  media/develop/IMG_20220406-153503103.png
  media/develop/autocommit_selectforupdate_nowaitlock.png
  media/develop/transaction_isolation_level.png
Labels: status/LGT1, translation/doing, size/XXL, area/develop

#8790 Add description of ignore-checking-items
  dm/dm-precheck.md
  dm/task-configuration-file-full.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/dm, needs-cherry-pick-release-6.0

#9162 fix error
  develop/delete-data.md
  develop/optimistic-and-pessimistic-transaction.md
Labels: translation/no-need, size/XXL, area/develop

#8919 Remove `importer` backend and Improve other backend's description
  ecosystem-tool-user-guide.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-backends.md
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XXL, area/tidb-lightning, needs-cherry-pick-release-6.0

#8925 Replace `route` with `mydumper.files` due to `route` feature not GA yet
  migrate-large-mysql-shards-to-tidb.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/migrate, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9016 Add a notice for table attributes on release-6.0
  table-attributes.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-master, size/XS, area/scheduling

#9017 Add a notice for table attributes on release-5.4
  table-attributes.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/scheduling

#9018 Add a notice for table attributes on release-5.3
  table-attributes.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/scheduling

#9090 TiKV Config: Update the values of `compaction-style`
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, area/engine, needs-cherry-pick-release-5.1, type/compatibility-or-feature-change

#9172 Change copyable "shell-regular" to copyable "sql"
  migrate-large-mysql-shards-to-tidb.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/migrate

#9103 add dumpling parameter
  dumpling-overview.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, needs-cherry-pick-release-5.4, area/dumpling, needs-cherry-pick-release-6.0

#9164 Fix typo of macOS in tiup-faq.md
  tiup/tiup-faq.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9175 develop: update developer guide
  TOC.md
  develop/bookshop-schema-design.md
  develop/build-cluster-in-cloud.md
  develop/common-table-expression.md
  develop/create-secondary-indexes.md
  develop/follower-read.md
  develop/hybrid-oltp-and-olap-queries.md
  develop/index-best-practice.md
  develop/optimistic-and-pessimistic-transaction.md
  develop/optimize-sql-best-practices.md
  develop/optimize-sql-overview.md
  develop/optimize-sql.md
  develop/stale-read.md
  develop/transaction-restraints.md
  develop/transaction-troubleshoot.md
  develop/troubleshoot-overview.md
  media/develop/importing_bookshop_data.png
  media/develop/tidb_cloud_import_bookshop_data.png
  media/develop/write-skew.png
Labels: status/LGT1, translation/doing, size/XXL, do-not-merge/hold, area/develop

#9115 tikv: add flow-control config override hint
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/engine, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9183 Unify IP addresses in tiflash config doc and the config file
  tiflash-deployment-topology.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9161 tiem: add deploy doc and 1.0.0 release notes
  TOC.md
  config-templates/tiem-metadata-restore-config.yaml
  config-templates/tiem-topology-config.yaml
  scripts/tiem-online-deploy.sh
  tiem/tiem-install-and-maintain.md
  tiem/tiem-release-1.0.0.md
Labels: translation/doing, size/XXL, area/tiem

#9052 release notes: add v5.2.4 release notes
  TOC.md
  releases/release-5.2.4.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, area/general, size/L, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9141 Add hardware configurations and aliases to 5.4 tpch
  benchmark/v5.4-performance-benchmarking-with-tpch.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata

#9140 Create v6.0-performance-benchmarking-with-tpch.md
  TOC.md
  benchmark/v5.4-performance-benchmarking-with-tpch.md
  benchmark/v6.0-performance-benchmarking-with-tpch.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/L, area/bigdata, ONCALL

#9197 Fix typo and align title with heading in TiUP
  tiup/tiup-documentation-guide.md
  tiup/tiup-overview.md
  tiup/tiup-reference.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/S, area/tiup, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9190 [Update] add href in SimpleTab to unique URL
  develop/delete-data.md
  develop/developer-guide-overview.md
  develop/get-data-from-single-table.md
  develop/join-tables.md
  develop/optimistic-and-pessimistic-transaction.md
  develop/paginate-results.md
  develop/prepared-statement.md
  develop/sample-application-java.md
  develop/stale-read.md
  develop/temporary-table.md
  develop/update-data.md
Labels: first-time-contributor, missing-translation-status, size/L

#9181 v5.2.4: Bump version for v5.2 docs
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  ticdc/manage-ticdc.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/L

#8722 Fix statistics content errors
  statistics.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, area/planner, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9200 tiem: add faq and quick start
  media/tiem/tiem-architecture.png
  tiem/tiem-faq.md
  tiem/tiem-quick-start.md
  tiem/tiem-release-notes.md
Labels: translation/doing, size/XL, area/tiem

#9203 develop: fix some links and add copyable block in the read data chapter
  TOC.md
  develop/delete-data.md
  develop/get-data-from-single-table.md
  develop/hybrid-oltp-and-olap-queries.md
  develop/join-tables.md
  develop/paginate-results.md
  develop/use-common-table-expression.md
  develop/use-follower-read.md
  develop/use-stale-read.md
  develop/use-subqueries.md
  develop/use-temporary-tables.md
  develop/use-views.md
Labels: missing-translation-status, do-not-merge/hold, size/XL, area/develop

#9025 Troubleshoot hotspot issues: add hotspot scenarios
  troubleshoot-hot-spot-issues.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/scheduling, ONCALL, needs-cherry-pick-release-6.0

#9091 TiKV Config: Update some optional values of TiKV configuration items
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, status/PTAL, size/M, area/engine, type/compatibility-or-feature-change, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9182 System Variable: Update `tidb-restricted-read-only`
  system-variables.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9176 remove no-schema config
  migrate-aurora-to-tidb.md
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-faq.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, type/compatibility-or-feature-change, area/tidb-lightning, needs-cherry-pick-release-6.0

#9227 develop: add media
  media/develop/IMG_20220331-232643794.png
  media/develop/IMG_20220331-232726165.png
  media/develop/IMG_20220331-232800929.png
  media/develop/IMG_20220401-234316020.png
  media/develop/IMG_20220402-003303222.png
  media/develop/IMG_20220402-003350731.png
  media/develop/IMG_20220402-003416079.png
  media/develop/IMG_20220402-003505846.png
  media/develop/IMG_20220402-003528474.png
  media/develop/IMG_20220402-003549966.png
  media/develop/IMG_20220402-003659102.png
  media/develop/IMG_20220406-153503103.png
  media/develop/autocommit_selectforupdate_nowaitlock.png
  media/develop/importing_bookshop_data.png
  media/develop/tidb_cloud_import_bookshop_data.png
  media/develop/transaction_isolation_level.png
  media/develop/write-skew.png
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/develop

#9212 add cloud doc url and periods
  develop/bookshop-schema-design.md
  develop/build-cluster-in-cloud.md
  develop/choose-driver-or-orm.md
  develop/connect-to-tidb.md
  develop/connection-parameters.md
  develop/create-database.md
  develop/create-secondary-indexes.md
  develop/create-table.md
  develop/delete-data.md
  develop/developer-guide-overview.md
  develop/timeouts-in-tidb.md
  develop/update-data.md
Labels: translation/doing, first-time-contributor, size/L, area/develop

#9209 rewrite by unique grammar
  develop/create-database.md
  develop/create-secondary-indexes.md
  develop/create-table.md
  develop/delete-data.md
  develop/sample-application-java.md
  develop/sample-application-spring-boot.md
  develop/schema-design-overview.md
  develop/tidb-crud-sql.md
  develop/update-data.md
Labels: translation/doing, first-time-contributor, size/M, area/develop

#9230 Update an FAQ according to discussion
  faq/manage-cluster-faq.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9070 Add log redaction info into clinic doc
  clinic/clinic-user-guide-for-tiup.md
  clinic/quick-start-with-clinic.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/clinic, needs-cherry-pick-release-6.0

#8956 Update HAProxy deploy operating system introduction.
  best-practices/haproxy-best-practices.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9239 remove legacy versions from pr template
  .github/pull_request_template.md
Labels: status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#9235 Feat review change
  TOC.md
  develop/bookshop-schema-design.md
  develop/build-cluster-in-cloud.md
  develop/choose-driver-or-orm.md
  develop/client-connection-parameters.md
  develop/connect-to-tidb.md
  develop/connection-parameters.md
  develop/create-database.md
  develop/create-secondary-indexes.md
  develop/create-table.md
  develop/delete-data.md
  develop/developer-guide-overview.md
  develop/get-data-from-single-table.md
  develop/hybrid-oltp-and-olap-queries.md
  develop/implicit-type-conversion.md
  develop/index-best-practice.md
  develop/insert-data.md
  develop/join-tables.md
  develop/object-naming-guidelines.md
  develop/optimistic-and-pessimistic-transaction.md
  develop/optimize-sql-best-practices.md
  develop/optimize-sql-overview.md
  develop/optimize-sql.md
  develop/paginate-results.md
  develop/prepared-statement.md
  develop/sample-application-java.md
  develop/sample-application-spring-boot.md
  develop/schema-design-overview.md
  develop/sql-development-specification.md
  develop/supported-by-pingcap.md
  develop/tidb-crud-sql.md
  develop/timeouts-in-tidb.md
  develop/transaction-overview.md
  develop/transaction-restraints.md
  develop/transaction-troubleshoot.md
  develop/troubleshoot-overview.md
  develop/unique-serial-number-generation.md
  develop/unstable-result-set.md
  develop/update-data.md
  develop/use-common-table-expression.md
  develop/use-follower-read.md
  develop/use-stale-read.md
  develop/use-subqueries.md
  develop/use-temporary-tables.md
  develop/use-views.md
Labels: status/LGT1, first-time-contributor, missing-translation-status, size/XXL, area/develop

#9231 develop: fix typos in read-data
  develop/bookshop-schema-design.md
  develop/hybrid-oltp-and-olap-queries.md
  develop/join-tables.md
  develop/paginate-results.md
  develop/use-common-table-expression.md
  develop/use-stale-read.md
  develop/use-subqueries.md
  develop/use-temporary-tables.md
  develop/use-views.md
Labels: translation/doing, size/L, area/develop

#9250 tiem: add tiem cluster management
  media/tiem/tiem-checkhosts.png
  tiem/tiem-manage-clusters.md
Labels: missing-translation-status, size/XL, area/tiem

#9206 Align 2 PRs from docs about collations
  character-set-and-collation.md
  information-schema/information-schema-collations.md
  mysql-compatibility.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.0

#9249 Fix dead link to TiDB Cloud quick start guide
  quick-start-with-tidb.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-master, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain

#9248 [Update] add developer guide to master branch
  TOC.md
  develop/bookshop-schema-design.md
  develop/build-cluster-in-cloud.md
  develop/choose-driver-or-orm.md
  develop/client-connection-parameters.md
  develop/connect-to-tidb.md
  develop/connection-parameters.md
  develop/create-database.md
  develop/create-secondary-indexes.md
  develop/create-table.md
  develop/delete-data.md
  develop/developer-guide-overview.md
  develop/get-data-from-single-table.md
  develop/hybrid-oltp-and-olap-queries.md
  develop/implicit-type-conversion.md
  develop/index-best-practice.md
  develop/insert-data.md
  develop/join-tables.md
  develop/object-naming-guidelines.md
  develop/optimistic-and-pessimistic-transaction.md
  develop/optimize-sql-best-practices.md
  develop/optimize-sql-overview.md
  develop/optimize-sql.md
  develop/paginate-results.md
  develop/prepared-statement.md
  develop/sample-application-java.md
  develop/sample-application-spring-boot.md
  develop/schema-design-overview.md
  develop/sql-development-specification.md
  develop/supported-by-community.md
  develop/supported-by-pingcap.md
  develop/tidb-crud-sql.md
  develop/timeouts-in-tidb.md
  develop/transaction-overview.md
  develop/transaction-restraints.md
  develop/transaction-troubleshoot.md
  develop/troubleshoot-overview.md
  develop/unique-serial-number-generation.md
  develop/unstable-result-set.md
  develop/update-data.md
  develop/use-common-table-expression.md
  develop/use-follower-read.md
  develop/use-stale-read.md
  develop/use-subqueries.md
  develop/use-temporary-tables.md
  develop/use-views.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XXL, area/develop
