Repository pingcap/docs-cn, pull requests merged in 2022-07, with the labels that each got.

#10321 ticdc: fix faq link
  ticdc/ticdc-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/ticdc, needs-cherry-pick-release-6.1

#8143 Add example about how to apply hotfix to dm cluster
  TOC.md
  tiup/tiup-component-dm-patch.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, needs-cherry-pick-release-5.3, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10307 fix format: remove >> in code block
  best-practices/massive-regions-best-practices.md
  pd-control.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/L, area/scheduling, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10312 add experimental warning for br incremental backup
  br/use-br-command-line-tool.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, area/br

#10315 Fix typos in placement rules command
  configure-placement-rules.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10283 clinic: update the clinic-user-guide-for-tiup
  TOC.md
  clinic/clinic-introduction.md
  clinic/clinic-user-guide-for-tiup.md
  clinic/quick-start-with-clinic.md
  media/clinic-get-token.png
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/S, area/clinic, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10343 dashboard: update status of continuous profiling
  dashboard/continuous-profiling.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, sig/diagnosis, needs-cherry-pick-release-6.1

#10344 ci: use concurrency to cancel previous workflow
  .github/workflows/ci.yaml
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10314 dm: fix a 404 link
  dm/dm-overview.md
Labels: status/LGT1, translation/done, status/can-merge, size/XS, area/dm

#10361 update tiflash-command-line-flags.md
  tiflash/tiflash-command-line-flags.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata

#10366 tiunimanager: fix version inconsistency issue
  tiunimanager/tiunimanager-install-and-maintain.md
Labels: status/LGT2, status/can-merge, type/bug-fix, size/S, ONCALL, area/tunimanager, needs-cherry-pick-release-6.1

#10368 fix 404 link in release notes
  releases/release-5.3.2.md
  releases/release-6.1.0.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10286 *: add docs of backup and restore using Dumpling and Lightning
  TOC.md
  backup-and-restore-using-dumpling-lightning.md
  br/br-usage-backup.md
  br/br-usage-restore.md
  migrate-large-mysql-to-tidb.md
Labels: status/LGT1, status/LGT2, type/refactor, translation/doing, status/can-merge, size/L, area/br, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10376 delete dp diagrams
  dumpling-overview.md
  media/parallel-import-shard-tables.png
  media/parallel-import-single-tables.png
  migrate-large-mysql-shards-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  migration-tools.md
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.1

#10382 tiflash: update upgrade warning
  upgrade-tidb-using-tiup.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, area/bigdata

#10383 add the doc for `rename user`
  TOC.md
  releases/release-5.1.0.md
  sql-statements/sql-statement-rename-user.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10392 fix typo in `SHOW BACKUPS|RESTORES` command
  br/br-deployment.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-5.4, area/br, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10400 table filter: remove unfriendly special symbols
  table-filter.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/S, area/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10276 ticdc: add 4 docs for data replication scenarios
  TOC.md
  backup-and-restore-using-dumpling-lightning.md
  dm/migrate-data-using-dm.md
  integration-overview.md
  media/integrate/add-snowflake-sink-connector.png
  media/integrate/authentication.png
  media/integrate/configuration.png
  media/integrate/confluent-topics.PNG
  media/integrate/credentials.png
  media/integrate/data-preview.png
  media/integrate/results.png
  media/integrate/select-from-orders.png
  media/integrate/sql-query-result.png
  media/integrate/topic-selection.png
  migrate-aurora-to-tidb.md
  migrate-from-csv-files-to-tidb.md
  migrate-from-sql-files-to-tidb.md
  migrate-from-tidb-to-mysql.md
  migrate-from-tidb-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  migrate-small-mysql-to-tidb.md
  migrate-with-more-columns-downstream.md
  migration-overview.md
  migration-tools.md
  replicate-between-primary-and-secondary-clusters.md
  replicate-data-to-kafka.md
  ticdc/integrate-confluent-using-ticdc.md
Labels: status/LGT1, status/LGT2, type/refactor, translation/doing, status/can-merge, size/XXL, area/ticdc, needs-cherry-pick-release-6.1

#10410 fix a link to common-table-expression
  non-transactional-dml.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/transaction, needs-cherry-pick-release-6.1

#10414 bump versions for v5.4.2
  check-before-deployment.md
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  ticdc/manage-ticdc.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, size/L

#10416 lightning: fix a few mistakes in lightning refactor
  ecosystem-tool-user-case.md
  migrate-from-csv-files-to-tidb.md
  tidb-lightning/migrate-from-csv-using-tidb-lightning.md
  tikv-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XL, area/tidb-lightning

#10275 releases: add 5.4.2 release notes
  TOC.md
  releases/release-5.4.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10422 fix table
  tidb-lightning/tidb-lightning-data-source.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/M

#10423 trigger pdf build
  releases/release-5.4.2.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#10412 br: update br code repo address
  br/backup-and-restore-design.md
  br/backup-and-restore-overview.md
  migrate-from-tidb-to-tidb.md
  releases/release-3.1.0-ga.md
  replicate-between-primary-and-secondary-clusters.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, ONCALL, area/br, needs-cherry-pick-release-6.1

#10427 ci: add a workflow to flush pdf
  .github/workflows/flush.yaml
  resources/cdnfresh.txt
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/M

#10399 Modify the description of P99 from .99 to 99%
  alert-rules.md
  troubleshoot-high-disk-io.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10357 *: Remove hdd descriptions in placement-rules-in-sql
  configure-placement-rules.md
  placement-rules-in-sql.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10442 system variable: remove unnecessary examples
  system-variables.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, area/sql-infra, ONCALL

#10441 Fix a typo for tidb_restricted_read_only
  system-variables.md
Labels: status/LGT2, contribution, translation/no-need, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10428 fix duplicate content
  tidb-lightning/tidb-lightning-error-resolution.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/S, area/tidb-lightning, needs-cherry-pick-release-6.1

#10424 tiflash refactor: split use-tiflash into multiple docs
  TOC.md
  develop/dev-guide-create-table.md
  develop/dev-guide-hybrid-oltp-and-olap-queries.md
  develop/dev-guide-sql-development-specification.md
  explain-mpp.md
  explore-htap.md
  production-deployment-using-tiup.md
  quick-start-with-htap.md
  quick-start-with-tidb.md
  releases/release-5.0.0.md
  releases/release-5.4.0.md
  releases/release-6.0.0-dmr.md
  releases/release-6.1.0.md
  resources/doc-templates/template-concept.md
  resources/doc-templates/template-new-feature.md
  resources/doc-templates/template-task.md
  scale-tidb-using-tiup.md
  system-variables.md
  tiflash/create-tiflash-replicas.md
  tiflash/tiflash-compatibility.md
  tiflash/tiflash-data-validation.md
  tiflash/tiflash-overview.md
  tiflash/tiflash-supported-pushdown-calculations.md
  tiflash/use-tidb-to-read-tiflash.md
  tiflash/use-tiflash-mpp-mode.md
  tiflash/use-tiflash.md
  tiflash/use-tispark-to-read-tiflash.md
Labels: status/LGT1, type/refactor, translation/from-docs, status/can-merge, require-LGT1, size/XXL, area/bigdata, needs-cherry-pick-release-6.1

#10434 [Debug] wait_timeout default value changed
  develop/dev-guide-connection-parameters.md
  develop/dev-guide-timeouts-in-tidb.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1

#10435 [Debug] bulk-delete description error
  develop/dev-guide-delete-data.md
Labels: status/LGT1, status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1

#10453 update the doc of `drop index`
  sql-statements/sql-statement-drop-index.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#9893 Update tiup-cluster.md
  tiup/tiup-cluster.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/M, area/tiup, needs-cherry-pick-release-6.1

#10401 add a doc for binary package
  TOC.md
  binary-package.md
  download-ecosystem-tools.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1

#9986 dm: support ignore online-ddl in precheck
  dm/dm-precheck.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, area/dm, needs-cherry-pick-release-6.1

#10478 废弃 tiup tispark 组件
  tispark-deployment-topology.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/XS

#10458 ticdc: add a warning for the eventually consistent replication feature
  ticdc/manage-ticdc.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, area/ticdc, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10449 Update sql-statement-admin-show-ddl.md
  sql-statements/sql-statement-admin-show-ddl.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, needs-cherry-pick-release-5.0, size/S, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#9557 Fix the default value of the log config of PD
  pd-configuration-file.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, area/engine, needs-cherry-pick-release-5.1

#10494 fix incorrect relationship between x86_64 and arm
  quick-start-with-tidb.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#9889 update for third party tools supported by TiDB
  TOC.md
  develop/dev-guide-supported-by-pingcap.md
  develop/dev-guide-third-party-support.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/L, area/develop, needs-cherry-pick-release-6.1

#10362 add content for clinic us server
  TOC.md
  clinic/clinic-data-instruction-for-tiup.md
  clinic/clinic-introduction.md
  clinic/clinic-user-guide-for-tiup.md
  clinic/quick-start-with-clinic.md
Labels: status/LGT1, translation/doing, status/can-merge, status/LGT3, size/L, type/compatibility-or-feature-change, area/clinic, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#9900 update --rows description
  dumpling-overview.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/dumpling, needs-cherry-pick-release-6.1

#10516 tiflash: add a missing field and fix format
  tiflash/maintain-tiflash.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, area/bigdata, ONCALL, needs-cherry-pick-release-6.1

#10490 [Update] add CREATE INDEX statement in add index optmize doc
  develop/dev-guide-optimize-sql-best-practices.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1

#10521 clinic: remove technical preview
  clinic/clinic-user-guide-for-tiup.md
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, size/XS, area/clinic, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10520 fix a typo of create_time
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10355 add tiflash label settings example
  config-templates/complex-tiflash.yaml
  schedule-replicas-by-topology-labels.md
  tiflash/create-tiflash-replicas.md
  tiflash/tiflash-configuration.md
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, status/LGT2, status/can-merge, first-time-contributor, size/L, area/bigdata, needs-cherry-pick-release-6.1

#10537 br: remove an unclear usage tip about checksum
  br/backup-and-restore-overview.md
Labels: status/LGT2, translation/done, status/can-merge, ONCALL, area/br, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10528 tidb lightning: fix old download location for lightning.json
  tidb-lightning/monitor-tidb-lightning.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10536 add unit of schedule.max-merge-region-size
  best-practices/pd-scheduling-best-practices.md
  dynamic-config.md
  pd-configuration-file.md
  pd-control.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/XS, area/scheduling, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10562 Update data-type-string.md
  data-type-string.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-6.1

#10559 Remove GA features from experimental doc
  experimental-features.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10586 sync-diff-inspector: fix typos
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/sync-diff-inspector, needs-cherry-pick-release-6.1

#10596 [Debug] specification typo
  develop/dev-guide-sql-development-specification.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1

#10614 disable trigger website building from master
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#10556 develop: fix simpletab
  develop/dev-guide-bookshop-schema-design.md
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-get-data-from-single-table.md
  develop/dev-guide-hybrid-oltp-and-olap-queries.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-join-tables.md
  develop/dev-guide-optimistic-and-pessimistic-transaction.md
  develop/dev-guide-optimize-sql-best-practices.md
  develop/dev-guide-optimize-sql.md
  develop/dev-guide-paginate-results.md
  develop/dev-guide-prepared-statement.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-transaction-restraints.md
  develop/dev-guide-update-data.md
  develop/dev-guide-use-common-table-expression.md
  develop/dev-guide-use-follower-read.md
  develop/dev-guide-use-stale-read.md
  develop/dev-guide-use-temporary-tables.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XL, area/develop, needs-cherry-pick-release-6.1

#10617 remove SimpleTab tag
  production-deployment-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10522 lightning: add docs for table-level local-backend
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, type/compatibility-or-feature-change, area/tidb-lightning, v6.2

#10587 doc: add explain for show-processlist
  sql-statements/sql-statement-show-processlist.md
Labels: type/enhancement, status/LGT2, status/can-merge, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1

#10626 doc: update information_schema tidb_index
  information-schema/information-schema-tidb-indexes.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1

#10568 add TiKV minimal version limit.
  tidb-limitations.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, v6.2

#10630 sync_diff_inspector: update unsupport types
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/sync-diff-inspector, needs-cherry-pick-release-6.1

#10561 br: remove s3 region param
  backup-and-restore-using-dumpling-lightning.md
  br/backup-and-restore-storages.md
  br/backup-storage-S3.md
  dumpling-overview.md
  encryption-at-rest.md
  migrate-aurora-to-tidb.md
  migrate-from-csv-files-to-tidb.md
  migrate-from-sql-files-to-tidb.md
  migrate-large-mysql-to-tidb.md
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
  sql-statements/sql-statement-show-backups.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/M, area/tidb-lightning, v6.2

#10641 Fix markdown display error
  tidb-lightning/tidb-lightning-data-source.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/S, area/tidb-lightning, needs-cherry-pick-release-6.1

#10629 tidb-lightning: update wording and format
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/S, area/tidb-lightning, needs-cherry-pick-release-6.1

#10564 system variable: add tidb_opt_skew_distinct_agg
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/XS, area/planner, type/compatibility-or-feature-change, v6.2

#10599 tikv,v6.2: Add CDC intro for API v2
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/engine, v6.2

#10648 Fix wrong link format
  tiflash/tiflash-configuration.md
Labels: status/LGT1, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/bigdata, needs-cherry-pick-release-6.1

#10646 add TiSpark 3.0
  tispark-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, area/bigdata, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10647 planner: add docs for auto analyze
  statistics.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/planner, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10639 br: synchronize the usage tips of the latest version to 5.4
  br/backup-and-restore-tool.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, ONCALL, area/br

#10637 [Update] change Beta tag to Compatible tag
  develop/dev-guide-third-party-support.md
Labels: status/LGT2, translation/no-need, status/can-merge, area/develop, needs-cherry-pick-release-6.1

#10661 Add `spring-data-jpa` to support list
  develop/dev-guide-third-party-support.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/develop, needs-cherry-pick-release-6.1

#10663 Fix jooq items
  develop/dev-guide-third-party-support.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/develop, needs-cherry-pick-release-6.1

#10666 [Update] spring-data-jpa using hibernate, hibernate already tested
  develop/dev-guide-third-party-support.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/develop, needs-cherry-pick-release-6.1

#10429 br: restore system privilege table on default
  br/backup-and-restore-faq.md
  br/br-usage-restore.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/M, type/compatibility-or-feature-change, area/br, v6.2

#10373 planner: update the doc for merge hint
  develop/dev-guide-use-common-table-expression.md
  optimizer-hints.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/S, area/planner, v6.2

#10331 planner: update the doc for the leading hint
  optimizer-hints.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, v6.2

#10672 Fix spelling of 'true'
  faq/manage-cluster-faq.md
  releases/release-5.0.0-rc.md
  releases/release-5.0.0.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#10668 system-variables: explain tidb_enable_concurrent_ddl
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/sql-infra, type/compatibility-or-feature-change, v6.2

#10682 remote the avro support from experimental feature list
  experimental-features.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, area/ticdc

#10615 tikv: add command line flag `--config-info`
  command-line-flags-for-tikv-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/engine, v6.2

#10594 system-variables: add description for `tidb_default_string_match_selectivity`
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/planner, type/compatibility-or-feature-change, v6.2

#10669 config: add description of report-min-resolved-ts-interval
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/engine, type/compatibility-or-feature-change, v6.2

#9700 add doc for savepoint
  TOC.md
  best-practices/java-app-best-practices.md
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-transaction-restraints.md
  mysql-compatibility.md
  sql-statements/sql-statement-rollback.md
  sql-statements/sql-statement-savepoint.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/transaction, v6.2

#10438 Update information-schema-data-lock-waits.md
  information-schema/information-schema-data-lock-waits.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/transaction, v6.2

#10457 Update the multi-schema change DDL limitation
  mysql-compatibility.md
  sql-statements/sql-statement-add-column.md
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-change-column.md
  sql-statements/sql-statement-drop-column.md
  sql-statements/sql-statement-modify-column.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, v6.2

#10360 Chinese doc for auto analyze auto tune support
  dynamic-config.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/M, area/engine, type/compatibility-or-feature-change, v6.2

#10679 v6.2: update tidb_enable_paging default value
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/transaction, type/compatibility-or-feature-change, v6.2

#10684 dm: remove s3.region parameter
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, area/dm, v6.2

#10525 br: Add docs for br debug
  br/br-usage-backup.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/M, needs-cherry-pick-release-5.4, area/br, needs-cherry-pick-release-6.1

#10519 tikv: update the Load Base Split introduction
  configure-load-base-split.md
  dynamic-config.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/scheduling, type/compatibility-or-feature-change, v6.2

#10455 [Debug] fix typo and grammer
  develop/dev-guide-delete-data.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-optimistic-and-pessimistic-transaction.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/S, area/develop, needs-cherry-pick-release-6.1

#10692 Try to hide escape character
  functions-and-operators/operators.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, ONCALL, needs-cherry-pick-release-6.1

#10687 wording refine: 家目录 -> Home 目录
  geo-distributed-deployment-topology.md
  hybrid-deployment-topology.md
  minimal-deployment-topology.md
  ticdc-deployment-topology.md
  tidb-binlog-deployment-topology.md
  tiflash-deployment-topology.md
  tispark-deployment-topology.md
  tiup/tiup-command-mirror-genkey.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/S, ONCALL, needs-cherry-pick-release-6.1

#10585 *: add description about the binary plan
  identify-slow-queries.md
  information-schema/information-schema-slow-query.md
  statement-summary-tables.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XL, area/diagnosis, v6.2

#10665 tikv: add a new config `server.simplify-metrics`
  dynamic-config.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/engine, type/compatibility-or-feature-change, v6.2

#10607 planner: add the doc for the SEMI_JOIN_REWRITE hint
  optimizer-hints.md
  subquery-optimization.md
Labels: status/LGT2, translation/done, status/can-merge, status/PTAL, size/M, area/planner, v6.2

#10696 br: fix typo
  br/rawkv-backup-and-restore.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/br, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#10699 fix table format in tidb-lightning-data-source
  tidb-lightning/tidb-lightning-data-source.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.1

#10685 add system variable tidb_enable_analyze_snapshot
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, area/sql-infra, type/compatibility-or-feature-change, v6.2

#10584 doc: show create schema
  TOC.md
  sql-statements/sql-statement-show-create-database.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1

#10557 ticdc: add row filter config
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, type/compatibility-or-feature-change, area/ticdc, v6.2

#10609 planner: add documents for cost model variables
  TOC.md
  cost-model.md
  media/cost-model.png
  sql-physical-optimization.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/planner, v6.2

#10686 br: deprecate rawkv backup and restore
  br/rawkv-backup-and-restore.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, area/br, v6.2

#10608 make statement of using rules of Placement Rules in SQL more clear
  placement-rules-in-sql.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, area/sql-infra, needs-cherry-pick-release-6.1

#10603 tiflash: Change format_version default value to 4
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, area/bigdata, v6.2

#10622 br: add backup file layout description
  br/backup-and-restore-design.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, first-time-contributor, size/M, area/br

#10717 Fix 2 alert rules
  alert-rules.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/diagnosis, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#8669 add recovery guide for two dc deployment
  tikv-control.md
  two-data-centers-in-one-city-deployment.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, area/engine, type/compatibility-or-feature-change, v6.2

#10716 Fix format error
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.1

#10704 add multi-schema change to experimental feature page
  experimental-features.md
Labels: status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/XS, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#10600 tikv: add a new dynamic config
  dynamic-config.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/engine, v6.2
