Repository pingcap/docs-cn, pull requests merged in 2022-02, with the labels that each got.

#8214 5.4.0 tiup bump version
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, status/can-merge, status/LGT3, size/M, sig/tiup, v5.4

#8249 lightning: add usage restriction for tidb-lightning
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/S, sig/migrate, needs-cherry-pick-release-5.3

#8283 Add back a deleted image for other branches
  media/cdc-cyclic-replication.png
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, sig/migrate

#8277 add link for TPC
  tiup/tiup-bench.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, area/general, require-LGT1, first-time-contributor, size/XS

#8285 system-variables: update from generated source
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/M, sig/sql-infra, type/compatibility-or-feature-change, v5.4

#8282 Move TiCDC-related images to /media/ticdc
  media/ticdc/cdc-architecture.png
  media/ticdc/cdc-cyclic-replication.png
  media/ticdc/ticdc-state-transfer.png
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, requires-version-specific-changes, require-LGT1, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7514 Remove cyclic replication feature: Cherry pick 7336 to release 5.0
  experimental-features.md
  releases/release-5.0.0.md
  releases/release-5.0.4.md
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, type/cherry-pick-for-release-5.0, size/L

#7513 Remove cyclic replication feature (#7336) Cherry pick 7336 to release 5.1
  experimental-features.md
  releases/release-5.0.0.md
  releases/release-5.1.2.md
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, size/L, sig/migrate, type/cherry-pick-for-release-5.1

#8294 Fix unclear description and typos in br docs
  br/backup-and-restore-faq.md
  br/backup-and-restore-use-cases.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3, ONCALL

#8293 Add a note to some tikv configs
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, status/can-merge, size/M, sig/engine, needs-cherry-pick-release-5.3, ONCALL

#8205 BR FAQ: only remain 5.3 parts in 5.3 branch
  br/backup-and-restore-faq.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, sig/migrate

#8295 cdc: update cdc architecture
  media/ticdc/cdc-architecture.png
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8228 更新 Lightning 所需权限描述
  TOC.md
  migrate-large-mysql-shards-to-tidb.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-requirements.md
Labels: status/LGT2, type/refactor, translation/doing, status/can-merge, size/L, sig/migrate, needs-cherry-pick-release-5.3

#8307 Remove `canal-json` protocol from v5.3 docs
  ticdc/manage-ticdc.md
  ticdc/troubleshoot-ticdc.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#8300 chore: use TabsPanel
  keywords-and-reserved-words.md
Labels: status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, size/XS

#8299 chore: use TabsPanel
  keywords.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#7637 tools: update the usage of region startkey to region keys
  pd-control.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, first-time-contributor, size/M, sig/scheduling, v5.4

#8298 Remove REFERENTIAL_CONSTRAINTS from v5.2
  TOC.md
  information-schema/information-schema-referential-constraints.md
  information-schema/information-schema.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix

#8319 Added a note for ignore txn commit ts
  tidb-binlog/tidb-binlog-configuration-file.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, size/XS, sig/migrate

#8320 Fix typo in complex-tiflash.yaml
  config-templates/complex-tiflash.yaml
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, sig/bigdata, needs-cherry-pick-release-5.3

#8326 Fix image description
  troubleshoot-hot-spot-issues.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, sig/diagnosis, needs-cherry-pick-release-5.3, ONCALL

#8328 Delete an outdated note
  sql-statements/sql-statement-explain.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-5.3, ONCALL

#8337 Fix border format
  tidb-lightning/tidb-lightning-requirements.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4

#8339 Add some tableoptions about Alter table
  sql-statements/sql-statement-alter-table.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8332 sql-statement-create-index.md: fix the example of expression index create by 'create table'
  sql-statements/sql-statement-create-index.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8154 add-prometheuse-change-desc
  releases/release-5.3.0.md
  upgrade-tidb-using-tiup.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/tiup, sig/diagnosis, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8351 Add v5.4 to the DM overview documentation
  dm/dm-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, needs-cherry-pick-release-5.4

#8237 remove - Experimental-label-for- DM-Offline-deployment
  dm/deploy-a-dm-cluster-using-tiup-offline.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/tiup, type/compatibility-or-feature-change, needs-cherry-pick-release-5.3, v5.4, needs-cherry-pick-release-5.4

#8358 Fix typo in TiDB lightning distributed import
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/migrate, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8353 Add terms for v5.4
  glossary.md
Labels: status/LGT2, translation/doing, status/can-merge, area/general, size/S, v5.4, needs-cherry-pick-release-5.4

#8347 ticdc: fix wrong max-message-bytes
  ticdc/manage-ticdc.md
Labels: status/LGT1, status/can-merge, missing-translation-status, size/XS

#8367 Fix a typo in release-timeline
  releases/release-timeline.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS

#8121 Update experimental features for v5.4
  basic-features.md
  experimental-features.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/XL, v5.4, needs-cherry-pick-release-5.4

#8368 enable build for master
  .github/workflows/dispatch.yml
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#8370 Fix SimpleTab format for deployment using tiup
  production-deployment-using-tiup.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, sig/tiup, needs-cherry-pick-release-5.4

#8361 fix ping latency alert solution
  alert-rules.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, sig/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4

#8372 Fix spaces and names
  TOC.md
  releases/release-5.4.0.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/M, needs-cherry-pick-release-5.4

#8379 Update dm-release-notes.md
  dm/dm-release-notes.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-5.4

#8383 binlog: warn Bidirectional Replication
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-3.1, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8394 Fix wrong default values
  releases/release-5.4.0.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4

#8399 Fix format in deployment using tiup
  production-deployment-using-tiup.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, sig/tiup, ONCALL, needs-cherry-pick-release-5.4

#8402 fix a number in tiup prod deployment
  production-deployment-using-tiup.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, ONCALL

#8386 name correspondence
  system-variables.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, sig/sql-infra, needs-cherry-pick-release-5.4

#8415 Fix the PDF table format issue for a table
  migrate-with-more-columns-downstream.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S

#8414 rn: add document links to rn-5.4
  releases/release-5.4.0.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.4

#8385 Cleanup documents that are not referenced anywhere
  connectors-and-apis.md
  contribute.md
  report-issue.md
  support.md
  whats-new-in-tidb-4.0.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/L, needs-cherry-pick-release-5.4

#8413 fix a typo in java best practices
  best-practices/java-app-best-practices.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-5.4

#8423 Fix a typo in sql-plan-replayer.md
  sql-plan-replayer.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/planner, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8398 update tidb operator version description
  TOC.md
  tidb-operator-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8352 docs: revised the performance documentation
  tune-tikv-memory-performance.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, sig/engine, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4

#8440 Fix format in migration tidb faq
  faq/migration-tidb-faq.md
Labels: status/LGT1, contribution, translation/doing, status/can-merge, type/bug-fix, require-LGT1, first-time-contributor, size/XS, sig/migrate, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8438 fix format in release-3.0.3.md
  releases/release-3.0.3.md
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.0, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, size/XS, needs-cherry-pick-release-5.4

#8422 tidb_replica_read support global set
  follower-read.md
Labels: status/LGT1, contribution, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/engine, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8455 Remove use of v5.4.0 in dev version
  tiup/tiup-playground.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, sig/tiup, ONCALL

#8437 Add use casdoor as example to login dashboard by sso
  dashboard/dashboard-session-sso.md
  media/dashboard/dashboard-session-sso-casdoor-settings-1.png
  media/dashboard/dashboard-session-sso-casdoor-settings-2.png
  media/dashboard/dashboard-session-sso-casdoor-settings-3.png
  releases/release-3.0.3.md
Labels: type/enhancement, status/LGT2, contribution, translation/from-docs, status/can-merge, first-time-contributor, size/M, sig/diagnosis, needs-cherry-pick-release-5.4

#8336 Release notes 5.1.4
  TOC.md
  releases/release-5.1.4.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8462 Remove version from tiup playground and add two examples
  tiup/tiup-playground.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-master, needs-cherry-pick-release-5.0, size/S, sig/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#8478 fix format in TOC.md
  TOC.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS

#8477 add 6.0 option in pr template
  .github/pull_request_template.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.4

#8453 Bump version for 5.1.4
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
Labels: status/LGT1, translation/done, status/can-merge, size/M

#8235 Add some configs in tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, sig/migrate, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8485 tools: fix region keys typo
  pd-control.md
Labels: status/LGT1, contribution, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.4

#8465 change the example of `admin show ddl job`
  sql-statements/sql-statement-admin-show-ddl.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, sig/sql-infra

#8452 Fix wrong feature name for index merge
  basic-features.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/planner, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8450 Fix a dead link in tidb-binlog-overview.md
  tidb-binlog/tidb-binlog-overview.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8449 Cleanup 5 documents
  connectors-and-apis.md
  contribute.md
  report-issue.md
  support.md
  whats-new-in-tidb-4.0.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/L

#8487 lightning: adjust lightning precheck version
  tidb-lightning/tidb-lightning-prechecks.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, sig/migrate, needs-cherry-pick-release-5.4

#8451 Fix a TOC issue for PDF generation
  TOC.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, needs-cherry-pick-release-5.4

#8498 update-version-for-5.3
  tiup/tiup-cluster.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, sig/tiup

#8315 cdc: update cdc architecture
  media/ticdc/cdc-architecture.png
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8503 update-version-for-4.0
  tiup/tiup-cluster.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, sig/tiup

#8502 change-version-for-5.0
  tiup/tiup-cluster.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, sig/tiup

#8500 update-version for 5.2
  tiup/tiup-cluster.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/M, sig/tiup

#8501 chang-version-for-5.1
  tiup/tiup-cluster.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/M, sig/tiup

#8480 tmp_path is required if user deploy tiflash instance other than tiup/tidb-operator
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, sig/bigdata, needs-cherry-pick-release-5.3
