Repository pingcap/docs-cn, pull requests merged in 2022-01, with the labels that each got.

#8108 bump version for v5.0.6
  download-ecosystem-tools.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tiup/tiup-component-cluster-deploy.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/from-docs, status/can-merge, size/M

#8116 Added a video about TiDB architecture
  tidb-architecture.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.3

#8118 Update vedio code
  tidb-architecture.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.3

#8115 sync_diff: update description about tidb collation
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate

#8125 Remove sql from copyable snippet
  migrate-large-mysql-to-tidb.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS

#8112 update configuration for FD-323
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/XS, type/compatibility-or-feature-change, sig/bigdata, v5.4

#8106 update functions supported by TiFlash
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/bigdata, v5.4

#8127 Disable build on master
  .github/workflows/dispatch.yml
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS

#8128 fix pdf build
  migrate-from-csv-files-to-tidb.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS

#8094 Update the description about DM collation_compatible config
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/XS, type/compatibility-or-feature-change, v5.4, area/dm

#8093 system-variables: add tidb_enable_paging
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, sig/transaction, type/compatibility-or-feature-change, v5.4

#8107 dm: update openapi config field
  dm/dm-open-api.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, v5.4, area/dm

#8082 update doc for IndexMerge GA
  explain-aggregation.md
  explain-index-merge.md
  explain-indexes.md
  explain-joins.md
  explain-mpp.md
  explain-overview.md
  explain-partitions.md
  explain-subqueries.md
  explain-views.md
  optimizer-hints.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/M, sig/planner, type/compatibility-or-feature-change, v5.4

#7962 Change the default values of multiple tiflash configs
  tiflash/tiflash-configuration.md
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/M, type/compatibility-or-feature-change, sig/bigdata, v5.4

#8110 pd-configuration: fix the log level
  command-line-flags-for-pd-configuration.md
  command-line-flags-for-tidb-configuration.md
  pd-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/scheduling, type/compatibility-or-feature-change, v5.4

#8130 replace dm external link with internal link
  filter-dml-event.md
  migrate-aurora-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  migrate-small-mysql-to-tidb.md
  migrate-with-pt-ghost.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/L

#8077 add dttool version 3 docs
  tiflash/tiflash-command-line-flags.md
  tiflash/tiflash-configuration.md
  tiflash/use-tiflash.md
Labels: status/LGT2, translation/doing, status/can-merge, first-time-contributor, size/L, type/compatibility-or-feature-change, sig/bigdata, v5.4

#7476 Optimize description to production deployment using tiup
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  tiup/tiup-mirror.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, sig/tiup

#8102 Add log archiving and rotation doc
  command-line-flags-for-tikv-configuration.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/engine, type/compatibility-or-feature-change, v5.4

#8040 cdc: Add canal json docs
  TOC.md
  ticdc/ticdc-canal-json.md
  ticdc/ticdc-open-protocol.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XL, sig/migrate, v5.4

#8081 br: added auto tune
  TOC.md
  br/br-auto-tune.md
  media/br/backup-auto-throttle.png
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/migrate, type/compatibility-or-feature-change, v5.4

#8119 Update DM TOC and remove redundant files
  TOC.md
  dm/feature-expression-filter.md
  dm/feature-online-ddl.md
  dm/migrate-from-mysql-aurora.md
  dm/quick-create-migration-task.md
  dm/scenarios.md
  dm/usage-scenario-downstream-more-columns.md
  dm/usage-scenario-incremental-migration.md
  dm/usage-scenario-shard-merge.md
  dm/usage-scenario-simple-migration.md
  ecosystem-tool-user-case.md
  filter-dml-event.md
  migrate-aurora-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  migrate-small-mysql-to-tidb.md
  migrate-with-more-columns-downstream.md
  migration-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XXL, sig/migrate, area/dm

#8113 align relay log behaviour in v5.4.0
  dm/relay-log.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, v5.4, area/dm

#7163 doc:add config for hot region history and add command for pd ctl
  pd-configuration-file.md
  pd-control.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, status/PTAL, first-time-contributor, size/L, sig/scheduling, sig/docs, type/compatibility-or-feature-change, v5.4

#8084 Update conprof &prof.md
  dashboard/continuous-profiling.md
  dashboard/dashboard-faq.md
  dashboard/dashboard-profiling.md
  media/dashboard/dashboard-conprof-access.png
  media/dashboard/dashboard-conprof-download.png
  media/dashboard/dashboard-conprof-has-not-NGM.png
  media/dashboard/dashboard-conprof-history.png
  media/dashboard/dashboard-conprof-single.png
  media/dashboard/dashboard-conprof-start.png
  media/dashboard/dashboard-conprof-stop.png
  media/dashboard/dashboard-profiling-download.png
  media/dashboard/dashboard-profiling-history.png
  media/dashboard/dashboard-profiling-start.png
  media/dashboard/dashboard-profiling-view-progress.png
  media/dashboard/dashboard-profiling-view-single.png
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/diagnosis, v5.4

#8139 lightning: add missing new config in release-5.3 release note
  releases/release-5.3.0.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, type/compatibility-or-feature-change, needs-cherry-pick-release-5.3

#8137 update dynamic-config.md
  dynamic-config.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, sig/engine, v5.4

#8140 revise an expression in "Highly Concurrent Write Best Practices"
  best-practices/high-concurrency-best-practices.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3, ONCALL

#7164 information-schema: add tidb_hot_regions_history docs and update tidb_hot_regions
  TOC.md
  information-schema/information-schema-tidb-hot-regions-history.md
  information-schema/information-schema-tidb-hot-regions.md
  information-schema/information-schema.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, first-time-contributor, size/L, sig/scheduling, v5.4

#8146 BR: udpate BR auto tune
  br/br-auto-tune.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, v5.4

#7515 br: Backup impact
  br/backup-and-restore-faq.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, sig/migrate, v5.4

#8101 Add GBK charset description
  TOC.md
  br/backup-and-restore-tool.md
  character-set-and-collation.md
  character-set-gbk.md
  dm/dm-overview.md
  mysql-compatibility.md
  tidb-lightning/tidb-lightning-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/sql-infra, v5.4

#8123 Add Top SQL doc
  TOC.md
  dashboard/top-sql.md
  media/dashboard/top-sql-details.png
  media/dashboard/top-sql-overview.png
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, sig/diagnosis, type/compatibility-or-feature-change, v5.4

#8122 Add description on analyze predicate columns
  sql-statements/sql-statement-analyze-table.md
  statistics.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/planner, type/compatibility-or-feature-change, v5.4

#8063 br: add azure blob storage usage document
  TOC.md
  br/backup-and-restore-azblob.md
  br/backup-and-restore-storages.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/migrate, v5.4

#8148 Added an example in ticdc-canal-json.md
  ticdc/ticdc-canal-json.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, sig/migrate, v5.4

#7859 *: remove configuration `allow-remove-leader` and `raft-msg-flush-interval`
  dynamic-config.md
  releases/release-5.3.0.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, status/PTAL, size/S, sig/engine, type/compatibility-or-feature-change, v5.4

#7345 add config description for opentracing
  tidb-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, status/PTAL, size/M, sig/sql-infra, needs-cherry-pick-release-5.3

#8141 Update warning for DDL execution before cluster upgrade
  faq/upgrade-faq.md
  sql-statements/sql-statement-add-index.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, sig/tiup, needs-cherry-pick-release-5.3, ONCALL

#8155 br: remove experimental properties
  br/backup-and-restore-azblob.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, v5.4

#8085 add doc for adding session variable for stale read
  TOC.md
  stale-read.md
  system-variables.md
  tidb_read_staleness.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, sig/scheduling, type/compatibility-or-feature-change, v5.4

#8129 lightning: add new configuration for incremental restore
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-prechecks.md
Labels: status/LGT2, translation/done, translation/doing, status/can-merge, size/M, sig/migrate, type/compatibility-or-feature-change, v5.4

#8132 tidb-lightning: max-error and duplicate-resolution
  TOC.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: translation/done, status/can-merge, status/LGT3, size/XL, sig/migrate, v5.4

#8138 update `txn-total-size-limit` upper limit
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/transaction, type/compatibility-or-feature-change, needs-cherry-pick-release-5.3

#8156 ticdc: clarify rowid HandleKey meaning
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8159 dm: add dm task timezone config
  dm/dm-task-configuration-guide.md
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, needs-cherry-pick-release-5.3, area/dm

#8174 Fix an ebnf display failure
  sql-statements/sql-statement-alter-table.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, size/XS

#8165 Update dm-worker-configuration-file.md
  dm/dm-worker-configuration-file.md
  dm/relay-log.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, v5.4, area/dm

#8175 Fix ebnf errors
  sql-statements/sql-statement-show-create-placement-policy.md
  sql-statements/sql-statement-with.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8133 Update plan cache doc
  sql-prepare-plan-cache.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/planner

#8176 fix a typo in a rroubleshoot related doc
  troubleshoot-high-disk-io.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/engine, needs-cherry-pick-release-5.3, ONCALL

#8172 Add information for the synchronously loading statistics content
  statistics.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, v5.4

#8190 remove underscore in filename
  TOC.md
  stale-read.md
  tidb-read-staleness.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS

#8189 fix dm openapi http method
  dm/dm-open-api.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/M, v5.4, area/dm

#8193 BR: Fix some inaccurate description in auto tune
  br/br-auto-tune.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#8195 Fix a typo in links in ticdc-open-protocol.md
  ticdc/ticdc-open-protocol.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, sig/migrate, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8187 TiKV config: add docs for raft engine configurations
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/M, sig/engine, v5.4

#8181 Add v5.4 TPCH report
  TOC.md
  benchmark/v5.4-performance-benchmarking-with-tpch.md
  media/tidb-v5.4-tpch-100-vs-gp-spark.png
Labels: status/LGT2, translation/done, status/can-merge, size/S, v5.4, needs-cherry-pick-release-5.4

#8183 Add aliases to v5.3 TPCH report
  benchmark/v5.3-performance-benchmarking-with-tpch.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#8157 planner: introduce a new variable `tidb_regard_null_as_point`
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/planner, type/compatibility-or-feature-change, v5.4

#8206 Revert "TiKV config: add docs for raft engine configurations"
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, sig/engine, v5.4

#8160 lightning: add clean up metadata schema
  tidb-lightning/tidb-lightning-faq.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, sig/migrate, needs-cherry-pick-release-5.3

#8191 Refine docs: troubleshoot lock conflicts
  media/pessimistic-transaction-commit.png
  media/pessimistic-transaction-in-tidb.png
  pessimistic-transaction.md
  troubleshoot-lock-conflicts.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XL

#8212 Revert "Revert "TiKV config: add docs for raft engine configurations""
  tikv-configuration-file.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, v5.4

#8211 Added max-error and task-info-schema-name in tidb-lightning-configuration
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: type/enhancement, translation/from-docs, status/can-merge, status/LGT3, size/S, v5.4

#8194 br: fix br azblob typos
  br/backup-and-restore-azblob.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, sig/migrate, v5.4

#8192 Update placement-rules-in-sql.md
  placement-rules-in-sql.md
Labels: type/enhancement, status/LGT2, translation/done, requires-followup, status/can-merge, first-time-contributor, size/XS, sig/sql-infra

#8216 Bump version for v5.4.0 - ecosystem tools
  download-ecosystem-tools.md
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, sig/migrate, v5.4

#8215 DM: add dm 5.4.0 performance test report
  TOC.md
  dm/dm-benchmark-v5.4.0.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, v5.4, area/dm

#8203 BR FAQ: only remain v5.4 parts
  br/backup-and-restore-faq.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, sig/migrate, v5.4

#8225 update: the execution plan details of Top SQL
  dashboard/top-sql.md
  media/dashboard/top-sql-details.png
  media/dashboard/top-sql-overview.png
Labels: status/LGT2, translation/from-docs, status/can-merge, size/XS

#8222 Add 5.4.0 benchmark
  TOC.md
  benchmark/benchmark-sysbench-v5.4.0-vs-v5.3.0.md
  benchmark/v5.4-performance-benchmarking-with-tpcc.md
  media/sysbench_v530vsv540_point_select.png
  media/sysbench_v530vsv540_read_write.png
  media/sysbench_v530vsv540_update_index.png
  media/sysbench_v530vsv540_update_non_index.png
  media/tpcc_v530_vs_v540.png
Labels: status/LGT2, translation/done, status/can-merge, size/XL, v5.4

#8223 dm: update version description
  dm/deploy-a-dm-cluster-using-tiup-offline.md
  dm/deploy-a-dm-cluster-using-tiup.md
  dm/dm-precheck.md
  dm/dmctl-introduction.md
  dm/maintain-dm-using-tiup.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/M, sig/migrate, v5.4, area/dm

#8204 Update profiling docs
  dashboard/continuous-profiling.md
  dashboard/dashboard-faq.md
  dashboard/dashboard-profiling.md
  media/dashboard/dashboard-profiling-access.png
Labels: type/enhancement, status/LGT2, translation/no-need, status/can-merge, size/M, sig/diagnosis, v5.4

#8227 remove useless description for mem control
  configure-memory-usage.md
Labels: type/enhancement, status/LGT2, status/can-merge, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, sig/bigdata, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#8144 Remove no-schema config
  get-started-with-tidb-lightning.md
  migrate-from-csv-files-to-tidb.md
  migrate-from-sql-files-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, sig/migrate, type/compatibility-or-feature-change, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8173 *: update character-set-and-collation
  character-set-and-collation.md
  character-set-gbk.md
  mysql-compatibility.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, v5.4

#8244 Fixed a typo
  explore-htap.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1

#8158 5.4.0-tiup-deployment-change
  dashboard/dashboard-access.md
  production-deployment-using-tiup.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, sig/tiup, v5.4

#8242 update: column header description
  sql-statements/sql-statement-show-stats-meta.md
  statistics.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S

#8239 Placement rules: fix the version that Placement Rules was introduced
  configure-placement-rules.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, sig/scheduling, needs-cherry-pick-release-5.3, ONCALL

#8238 Correct the partition number supported by a table
  tidb-limitations.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#8220 Fix improper "or" between item lists
  tidb-troubleshooting-map.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, sig/sql-infra, ONCALL

#8219 fix typo of tidb_distsql_scan_concurrency
  configure-memory-usage.md
  system-variables.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3

#8217 Fix GC alert expression
  alert-rules.md
Labels: status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.0, type/bug-fix, needs-cherry-pick-release-4.0, size/XS, sig/engine

#8218 Fix a typo about system variables
  tidb-configuration-file.md
Labels: status/LGT1, contribution, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.3

#8201 add raftstore.capacity configuration
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, sig/engine, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL

#8185 Fix name of config item `wake-up-delay-duration` in TiKV config file
  tikv-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/transaction, needs-cherry-pick-release-5.3

#8186 `tidb_capture_plan_baselines` and statement summary related variables are global only
  statement-summary-tables.md
  system-variables.md
Labels: status/LGT2, status/can-merge, for-future-release, size/S, sig/sql-infra, type/compatibility-or-feature-change

#8162 update a typo in 4.0 RC Release Notes
  releases/release-4.0.0-rc.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-4.0, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3, ONCALL

#8161 revise a number in "EXPLAIN indexes" doc
  explain-indexes.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3, ONCALL

#8104 Add a note for JDBC streaming result
  best-practices/java-app-best-practices.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/sql-infra, needs-cherry-pick-release-5.3

#8202 Add log redaction to learner toml
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, sig/bigdata, needs-cherry-pick-release-5.3

#7946 Update tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-faq.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#7969 TiKV config: add `cert-allowed-cn`
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, area/security, size/XS, sig/engine, needs-cherry-pick-release-5.3

#7736 Add docs for version_compile_* variables
  system-variables.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, sig/sql-infra

#7516 Remove cyclic replication feature: Cherry pick 7336 to release 4.0
  media/cdc-cyclic-replication.png
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, translation/doing, status/can-merge, size/L, sig/migrate, type/compatibility-or-feature-change

#6716 sysvar: add doc for tidb-restricted-read-only
  privilege-management.md
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#8111 ADD: authentication and authorization user doc
  tispark-overview.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/M, sig/bigdata, v5.4
