Repository pingcap/docs-cn, pull requests merged in 2022-10, with the labels that each got.

#11491 learning path: add reference in TiDB learning path
  _index.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/S

#11493 learning path: add reference in TiDB learning path for v6.3
  _index.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/S

#11494 learning path: add reference in TiDB learning path for v6.1
  _index.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/S

#11328 Add the description of sysvar `max_allowed_packet`
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar-experimental-docs, needs-cherry-pick-release-6.3

#11499 Update pd-control.md
  pd-control.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, requires-version-specific-changes, require-LGT1, size/XS, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11404 tools: corrected decriptions about lightning modes
  ecosystem-tool-user-guide.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/S, area/migrate

#11408 update CH-benCHmark
  TOC.md
  benchmark/benchmark-tidb-using-ch.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/S, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11500 Release notes: add release date
  releases/release-notes.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XL, needs-cherry-pick-release-6.1

#11505 update system variable
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar-experimental-docs, needs-cherry-pick-release-6.3

#11516 add avx2 description to 6.3 release notes
  releases/release-6.3.0.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-master, size/XS

#11506 tiup: add a notice to tiup dm import
  tiup/tiup-component-dm-import.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/tiup, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11537 Fix the data dir of monitored
  config-templates/complex-multi-instance.yaml
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11550 video: updated video size to make it fill the div automatically
  dm/dm-overview.md
  dumpling-overview.md
  explore-htap.md
  faq/manage-cluster-faq.md
  overview.md
  quick-start-with-tidb.md
  ticdc/ticdc-overview.md
  tidb-architecture.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-monitoring-framework.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, area/general, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11539 faq: correct description about TiDB versions
  faq/manage-cluster-faq.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11425 update tiflash-configuration.md
  tiflash/tiflash-configuration.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11392 Update dm-compatibility-catalog.md
  dm/dm-compatibility-catalog.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11568 backup: change the location for s3-multi-part-size
  tikv-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/br, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11575 git add adding index acceleration to key feature
  releases/release-6.3.0.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, v6.3, needs-cherry-pick-release-6.3

#10339 [Debug] mybatis expected output
  develop/dev-guide-sample-application-java.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#9494 fix: fix the desc for query result after enable tiflash
  develop/dev-guide-hybrid-oltp-and-olap-queries.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11584 Fix typo and table format in dm-ddl-compatible
  dm/dm-ddl-compatible.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/M, ONCALL, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11567 sysvar: add 12 sysvars to docs-cn
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, requires-version-specific-changes, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar, needs-cherry-pick-release-6.3

#11588 Bump version for v6.1.1
  br/backup-and-restore-use-cases.md
  check-before-deployment.md
  develop/dev-guide-proxysql-integration.md
  dm/quick-start-create-task.md
  migrate-from-tidb-to-mysql.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  replicate-data-to-kafka.md
  scale-tidb-using-tiup.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L

#11269 system_var, planner: add variable for controlling the algorithm of jo…
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/planner, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar, needs-cherry-pick-release-6.3

#11495 sysvar: add 12 sysvars to docs-cn
  functions-and-operators/aggregate-group-by-functions.md
  functions-and-operators/date-and-time-functions.md
  functions-and-operators/encryption-and-compression-functions.md
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/L, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar, needs-cherry-pick-release-6.3

#11507 update the Forgot root password
  user-account-management.md
Labels: status/LGT2, contribution, translation/doing, status/can-merge, area/security, first-time-contributor, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11598 Add an example for byte-threshold and region-cpu-overload-threshold-ratio adjustment
  configure-load-base-split.md
Labels: status/LGT2, translation/done, status/can-merge, requires-version-specific-changes, needs-cherry-pick-release-5.0, size/S, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11262 troubleshooting: add TiDB OOM troubleshooting tips
  TOC.md
  tidb-troubleshooting-map.md
  troubleshoot-tidb-oom.md
Labels: type/enhancement, status/LGT2, translation/done, area/best-practices, status/can-merge, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11449 add v5.4.3 release notes
  TOC.md
  releases/release-5.4.2.md
  releases/release-5.4.3.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11427 Bump version for v5.4.3
  check-before-deployment.md
  download-ecosystem-tools.md
  pd-control.md
  pd-recover.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  ticdc/manage-ticdc.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/L

#11329 [Update] 3rd party tools compatibility
  TOC.md
  develop/dev-guide-third-party-support.md
  develop/dev-guide-third-party-tools-compatibility.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11631 Fix admonitions syntax in release-5.4
  br/use-br-command-line-tool.md
  ticdc/troubleshoot-ticdc.md
  tidb-lightning/tidb-lightning-error-resolution.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS

#11622 Change default value of tidb_enable_clustered_index back to INT_ONLY
  clustered-indexes.md
  releases/release-6.3.0.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, ONCALL, needs-cherry-pick-release-6.3

#11459 Add RHE Linux 8 stream and AWS linux to software requirement doc
  hardware-and-software-requirements.md
Labels: status/LGT1, translation/done, status/can-merge, size/XS, area/deploy-upgrade-maintain

#11391 Add Golang at Choose Driver or ORM
  develop/dev-guide-choose-driver-or-orm.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, ONCALL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11623 sysvar: add 3 sysvars
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, requires-version-specific-changes, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar, needs-cherry-pick-release-6.3

#11649 fix typos in performance tuning methods
  performance-tuning-methods.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11405 tiflash: Add instructions to improve replica sync performance
  tiflash/create-tiflash-replicas.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/M, area/bigdata

#11658 Update release-6.3.0.md
  releases/release-6.3.0.md
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.3

#11240 ticdc: add three ticdc faqs
  ticdc/ticdc-faq.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/S, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11566 pd: add `rank-formula-version` config for hot scheduler
  experimental-features.md
  pd-control.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, v6.4, needs-cherry-pick-release-6.3

#11673 Fix the docs-cn-merge pipeline failure issue
  develop/dev-guide-third-party-tools-compatibility.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11674 drainer: add read-timeout configuration explanation
  tidb-binlog/tidb-binlog-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11218 Add TiCDC TSO acquisition in sync-diff-inspector doc
  sync-diff-inspector/upstream-downstream-diff.md
Labels: type/enhancement, status/LGT1, status/LGT2, contribution, translation/doing, status/can-merge, size/XS, area/ticdc, area/sync-diff-inspector, needs-cherry-pick-release-6.3

#10437 Add backup and restore content for tiup-cluster.md
  tiup/tiup-cluster.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/S, area/tiup, needs-cherry-pick-release-6.1

#10968 ADMIN related statements: add more links and fix format
  error-codes.md
  explain-walkthrough.md
  faq/deploy-and-maintain-faq.md
  identify-slow-queries.md
  information-schema/information-schema-ddl-jobs.md
  online-unsafe-recovery.md
  sql-statements/sql-statement-admin-cancel-ddl.md
  sql-statements/sql-statement-admin.md
  system-variables.md
  tidb-lightning/tidb-lightning-faq.md
  troubleshoot-data-inconsistency-errors.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11689 sysvar: add 4 batch-dml related sysvars
  non-transactional-dml.md
  system-variables.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar, needs-cherry-pick-release-6.3

#11706 sql-mode: fix wrong description
  sql-mode.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11715 remove tiflash and placement in sql incompatible description
  placement-rules-in-sql.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/sql-infra

#11707 sysvar: add 12 missing planner-related sysvars
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/L, area/planner, add-missing-sysvar, needs-cherry-pick-release-6.3

#11717 Add white space after ANALYZE TABLE
  statistics.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/planner, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11721 sysvar: add a sysvar to v6.1
  system-variables.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/XS, add-missing-sysvar

#11711 Fix tiup scale-in commands after online unsafe recovery
  online-unsafe-recovery.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, area/engine, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11730 Fix format in TiDB INDEXES
  analyze-slow-queries.md
  enable-tls-between-clients-and-servers.md
  information-schema/information-schema-tidb-indexes.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11734 refine document for the block_encryption_mode function
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-sysvar, needs-cherry-pick-release-6.3

#11738 Modify the recommended way as the first tab
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XXL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11729 sysvar: add a sysvar
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, needs-cherry-pick-release-6.2, add-missing-sysvar, needs-cherry-pick-release-6.3

#11678 add v6.1.2 release notes
  TOC.md
  releases/release-6.1.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11679 Bump version for v6.1.2
  br/backup-and-restore-use-cases.md
  check-before-deployment.md
  develop/dev-guide-proxysql-integration.md
  dm/quick-start-create-task.md
  migrate-from-tidb-to-mysql.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  replicate-data-to-kafka.md
  scale-tidb-using-tiup.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1

#11750 Fix format in analyze slow queries
  analyze-slow-queries.md
  releases/release-6.1.2.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11406 Change jdbc maxPerformance properties
  best-practices/java-app-best-practices.md
  develop/dev-guide-connection-parameters.md
Labels: type/enhancement, status/LGT2, contribution, translation/done, status/can-merge, first-time-contributor, size/S, needs-cherry-pick-release-6.0, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11761 remove the info about configuring tolerant-size-ratio
  three-data-centers-in-two-cities-deployment.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11762 update deployment docs
  TOC.md
  media/multi-data-centers-in-one-city-deployment-sample.png
  media/three-data-centers-in-two-cities-deployment-01.png
  media/three-data-centers-in-two-cities-deployment-02.png
  media/three-data-centers-in-two-cities-deployment-03.png
  multi-data-centers-in-one-city-deployment.md
  three-data-centers-in-two-cities-deployment.md
  two-data-centers-in-one-city-deployment.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XL, ONCALL

#11760 Update sql-statement-split-region.md
  sql-statements/sql-statement-split-region.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#11746 v6.3 release notes: Add HAProxy note
  releases/release-6.3.0.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, v6.3, needs-cherry-pick-release-6.3

#11777 Fix format in advanced placement options
  placement-rules-in-sql.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11791 fix the default value of slow-threshold
  tidb-configuration-file.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11778 Update configure-placement-rules.md
  configure-placement-rules.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/scheduling, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11754 develop: update tidb cloud import steps
  develop/dev-guide-bookshop-schema-design.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/M, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11808 add description for enable-table-lock
  experimental-features.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, add-missing-docs, needs-cherry-pick-release-6.3

#11804 Change Developer Tier to Serverless Tier in TOC.md
  TOC.md
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-create-database.md
  develop/dev-guide-create-secondary-indexes.md
  develop/dev-guide-create-table.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-tidb-crud-sql.md
  develop/dev-guide-update-data.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11826 [Update] remove cloud picture link in the doc
  develop/dev-guide-build-cluster-in-cloud.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#11554 br: more accurate expression
  backup-and-restore-use-cases-for-maintain.md
  br/backup-and-restore-use-cases.md
  br/pitr-known-issues.md
  br/point-in-time-recovery.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, needs-cherry-pick-release-6.1

#11220 update information-schema/information-schema-tiflash-replica.md
  information-schema/information-schema-tiflash-replica.md
  quick-start-with-htap.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/bigdata, v6.4

#11641 update sql-statement-alter-table-compact.md
  sql-statements/sql-statement-alter-table-compact.md
  sql-statements/sql-statement-alter-table.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/sql-infra, v6.4

#11640 lightning: add doc for migrating parquet files
  TOC.md
  migrate-from-csv-files-to-tidb.md
  migrate-from-parquet-files-to-tidb.md
  migration-overview.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, area/migrate, area/tidb-lightning, needs-cherry-pick-release-6.3

#11718 add workaround for charset error when migrate data
  dm/dm-faq.md
  tidb-lightning/troubleshoot-tidb-lightning.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/dm, v6.4

#11710 dm: update precheck document
  dm/dm-precheck.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/dm, v6.4
