Repository pingcap/docs-cn, pull requests merged in 2023-09, with the labels that each got.

#14955 Improve the description of password policy management
  sql-statements/sql-statement-create-user.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14890 feat: golang example simplify
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
Labels: translation/doing, size/XXL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14909 feat: add Node.js mysql2/mysql.js/Prisma chinese tutorial
  TOC.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
Labels: translation/from-docs, size/XXL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14924 develop: refactor Python dev guide
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
Labels: translation/done, first-time-contributor, size/XXL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14912 add tiup link doc
  tiup/tiup-component-management.md
Labels: translation/doing, size/M, approved, needs-1-more-lgtm, lgtm

#14987 develop: update python guide
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
Labels: translation/done, size/XS, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14949 dm: update contents about wildcards
  dm/dm-binlog-event-filter.md
  dm/dm-block-allow-table-lists.md
  dm/dm-table-routing.md
Labels: translation/done, type/bug-fix, size/S, area/dm, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14986 Add window function push down restriction
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14973 fix the size description of the statement summary table
  statement-summary-tables.md
Labels: type/bug-fix, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15011 add keywords ROLLUP and HYPO
  keywords.md
Labels: translation/from-docs, area/general, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14961 Update explore-htap.md, add tiflash recommendation
  explore-htap.md
Labels: type/enhancement, translation/doing, size/S, approved, lgtm

#15012 docs: fix br tools compatibility
  br/backup-and-restore-overview.md
Labels: translation/doing, size/S, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14926 br: add restore sql binding steps
  br/br-snapshot-manual.md
Labels: type/enhancement, translation/done, size/M, area/br, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15016 develop: add TypeORM quickstart
  TOC.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
Labels: translation/from-docs, size/XL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15025 feat: add ruby mysql2/rails chinese tutorial
  TOC.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
Labels: translation/from-docs, size/XXL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15046 fix tiflash resource usage pic error
  tiflash-performance-tuning-methods.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15054 sql planner: add `ORDER_INDEX` and `NO_ORDER_INDEX` hints for planner
  optimizer-hints.md
Labels: translation/done, size/M, ONCALL, approved, lgtm

#15055 dumpling: add PROCESS privilege
  dumpling-overview.md
Labels: translation/done, size/XS, ONCALL, area/dumpling, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15059 FastScan: rename dev-guide-use-fastscan to use-fastscan
  TOC.md
  basic-features.md
  releases/release-6.2.0.md
  releases/release-6.3.0.md
  system-variables.md
  tiflash-620-upgrade-guide.md
  tiflash/use-fastscan.md
Labels: contribution, translation/done, size/S, approved, needs-1-more-lgtm, lgtm

#15060 sql: fix a typo
  explain-index-merge.md
Labels: type/bug-fix, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15040 add release notes for v6.5.5
  TOC.md
  releases/release-6.5.4.md
  releases/release-6.5.5.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14748 Add missing field in deploy example yaml file
  config-templates/complex-tiflash.yaml
Labels: translation/done, size/XS, area/bigdata, approved, needs-1-more-lgtm, lgtm

#15047 Add bump version to 6.5.5
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#14963 DTFile use V3 version as default
  tiflash-upgrade-guide.md
  tiflash/tiflash-configuration.md
Labels: translation/done, size/S, area/bigdata, for-release, approved, lgtm, v7.4

#15077 docs: add --with-sys-table detail description
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
Labels: contribution, translation/welcome, size/S, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15045 ticdc: delete useless contents
  ticdc/ticdc-manage-changefeed.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15091 top sql: remove experimental warning
  system-variables.md
Labels: translation/done, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15068 Modify the leading hint conflict information
  optimizer-hints.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14970 resource_control: add background task resource control
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-create-resource-group.md
  tidb-resource-control.md
Labels: translation/done, size/L, approved, lgtm, v7.4

#15013 optimizer hints: add the docs for hint SET_VAR
  optimizer-hints.md
  system-variables.md
Labels: translation/done, size/XL, approved, lgtm, v7.4

#15092 Update MySQL Reference Manuals to use 8.0
  character-set-and-collation.md
  comment-syntax.md
  data-type-date-and-time.md
  data-type-numeric.md
  data-type-string.md
  develop/dev-guide-client-connection-parameters.md
  develop/dev-guide-connect-to-tidb.md
  develop/dev-guide-use-stale-read.md
  dm/dm-block-allow-table-lists.md
  dm/dm-enable-tls.md
  dm/dm-glossary.md
  dm/dm-worker-intro.md
  dm/handle-failed-ddl-statements.md
  dm/shard-merge-best-practices.md
  dm/usage-scenario-master-slave-switch.md
  enable-tls-between-clients-and-servers.md
  functions-and-operators/aggregate-group-by-functions.md
  functions-and-operators/bit-functions-and-operators.md
  functions-and-operators/cast-functions-and-operators.md
  functions-and-operators/control-flow-functions.md
  functions-and-operators/date-and-time-functions.md
  functions-and-operators/encryption-and-compression-functions.md
  functions-and-operators/expressions-pushed-down.md
  functions-and-operators/functions-and-operators-overview.md
  functions-and-operators/information-functions.md
  functions-and-operators/json-functions.md
  functions-and-operators/locking-functions.md
  functions-and-operators/miscellaneous-functions.md
  functions-and-operators/numeric-functions-and-operators.md
  functions-and-operators/operators.md
  functions-and-operators/precision-math.md
  functions-and-operators/string-functions.md
  functions-and-operators/type-conversion-in-expression-evaluation.md
  literal-values.md
  partitioned-table.md
  password-management.md
  schema-object-names.md
  statement-summary-tables.md
  tidb-lightning/tidb-lightning-faq.md
  user-defined-variables.md
Labels: translation/from-docs, size/XXL, approved, needs-1-more-lgtm, lgtm, v7.4

#15082 Add TIDB_PARSE_TSO_LOGICAL()
  functions-and-operators/tidb-functions.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, v7.4

#15104 metricstool: fix a broken link
  exporting-grafana-snapshots.md
Labels: translation/from-docs, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, approved, needs-1-more-lgtm, lgtm

#15103 explain joins: fix the TableReader operator
  explain-joins.md
Labels: translation/done, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#14919 planner: update document about non-prepared plan cache
  optimizer-fix-controls.md
  sql-non-prepared-plan-cache.md
  sql-prepared-plan-cache.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v7.4

#14866 system-variables: add docs for new variable `tidb_opt_objective`
  system-variables.md
Labels: translation/done, size/S, approved, lgtm, v7.4

#15080 update tidb_stats_cache_mem_quota description
  system-variables.md
  tidb-configuration-file.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.4

#14913 add ticdc to pulsar doc
  TOC.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-pulsar.md
Labels: contribution, translation/done, first-time-contributor, size/XL, type/compatibility-or-feature-change, approved, lgtm, v7.4

#15033 *: update go to v1.21
  hardware-and-software-requirements.md
  pd-control.md
  pd-recover.md
  tidb-control.md
Labels: translation/done, area/general, approved, needs-1-more-lgtm, lgtm, v7.4

#14972 add doc for sysvar `tidb_session_alias`
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, approved, lgtm, v7.4

#14347 Update ticdc sink configuration
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
Labels: type/enhancement, translation/doing, size/S, area/ticdc, approved, needs-1-more-lgtm, lgtm

#14837 Update ticdc canal json doc
  ticdc/ticdc-canal-json.md
  ticdc/ticdc-open-api-v2.md
Labels: translation/doing, size/M, area/ticdc, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15075 Update lock stats docs
  privilege-management.md
  sql-statements/sql-statement-lock-stats.md
  sql-statements/sql-statement-show-stats-locked.md
  sql-statements/sql-statement-unlock-stats.md
  statistics.md
Labels: translation/done, size/XL, approved, lgtm, v7.4

#15116 release-6.5.4: add missing fix note
  releases/release-6.5.4.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15114 cdc: remove description about the enable-old-value
  ticdc/ticdc-avro-protocol.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-csv.md
  ticdc/ticdc-faq.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-open-api.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-sink-to-kafka.md
  ticdc/troubleshoot-ticdc.md
Labels: contribution, translation/doing, size/L, approved, needs-1-more-lgtm, lgtm

#15041 add table style plan on tidb dashboard
  dashboard/dashboard-slow-query.md
  dashboard/dashboard-statement-details.md
  media/dashboard/dashboard-slow-queries-detail-plans-basic.png
  media/dashboard/dashboard-slow-queries-detail-plans-cop-read.png
  media/dashboard/dashboard-slow-queries-detail-plans-time.png
  media/dashboard/dashboard-slow-queries-detail-plans-transaction.png
  media/dashboard/dashboard-slow-queries-detail1-v740.png
  media/dashboard/dashboard-slow-queries-detail2-v740.png
  media/dashboard/dashboard-statement-detail-v740.png
  media/dashboard/dashboard-table-plan-columnpicker.png
  media/dashboard/dashboard-table-plan.png
  releases/release-6.2.0.md
Labels: translation/done, size/L, area/diagnosis, approved, lgtm, v7.4
