Repository pingcap/docs-cn, pull requests merged in 2023-07, with the labels that each got.

#14033 resource_control: ru consistent with serverless
  tidb-resource-control.md
Labels: type/enhancement, translation/doing, size/M, area/sql-infra, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#14393 resource-control: fix html tag issue
  tidb-resource-control.md
Labels: translation/no-need, type/bug-fix, area/sql-infra, approved, needs-1-more-lgtm, lgtm

#14272 ticdc: fix date-separator config of storage sink
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-cloud-storage.md
Labels: translation/doing, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14399 *: fix html table in resource control
  tidb-resource-control.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14361 include warning message in tidb control
  tidb-control.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14414 feat: change django support level to full cause of we added test cases to pipeline already
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-third-party-support.md
Labels: translation/done, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14405 Update tidb-roadmap.md since last LTS
  tidb-roadmap.md
Labels: translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm

#14406 lightning: add a note for physical import mode
  migrate-large-mysql-to-tidb.md
Labels: translation/done, size/XS, area/tidb-lightning, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14398 tikv config doc: update check and compact related docs
  releases/release-7.1.0.md
  tikv-configuration-file.md
Labels: translation/done, first-time-contributor, size/S, type/compatibility-or-feature-change, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14365 import into: add known issue
  sql-statements/sql-statement-import-into.md
Labels: translation/done, translation/doing, size/XS, approved, lgtm, needs-cherry-pick-release-7.2

#14432 .github: add 7.3 in pr template
  .github/pull_request_template.md
Labels: translation/from-docs, size/XS, approved, lgtm

#14424 add calibrate resource error for 7.1
  dashboard/dashboard-resource-manager.md
  sql-statements/sql-statement-calibrate-resource.md
Labels: translation/done, size/S, area/sql-infra, approved, lgtm

#14436 dispatch.yml: remove the achvied release-v6.6
  .github/workflows/dispatch.yml
Labels: translation/done, size/XS, approved, lgtm

#14437 v6.3/v6.4/v6.6 release notes: add archive info
  .github/pull_request_template.md
  releases/release-6.3.0.md
  releases/release-6.4.0.md
  releases/release-6.6.0.md
Labels: translation/doing, status/require-change, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14435 lightning: refine desciption about analyze
  tidb-lightning/data-import-best-practices.md
Labels: translation/from-docs, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14446 add experimental label to smooth upgrade
  releases/release-7.1.0.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#13963 Update exporting-grafana-snapshots.md
  exporting-grafana-snapshots.md
Labels: status/LGT1, translation/done, size/XS, needs-cherry-pick-release-5.4, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14040 lightning: add detailed log message explanation
  TOC.md
  tidb-lightning/tidb-lightning-log-message-explanation.md
Labels: translation/from-docs, size/XL, area/tidb-lightning, approved, lgtm

#14101 Update dashboard-slow-query.md
  dashboard/dashboard-slow-query.md
  media/dashboard/dashboard-slow-queries-export-v651.png
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14224 TiFlash: update the JSON push-down instruction
  data-type-json.md
Labels: translation/done, type/bug-fix, size/XS, area/bigdata, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14273 sql-statements: update the compability comment for `SHOW INDEX`
  sql-statements/sql-statement-show-indexes.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14471 system-variables: fix a typo for "GROUP"
  system-variables.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14404 release: add v6.1.7 release notes
  TOC.md
  releases/release-6.1.7.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14453 bump version for v6.1.7
  br/backup-and-restore-use-cases.md
  check-before-deployment.md
  develop/dev-guide-proxysql-integration.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#14461 Expand JOB_TYPE documentation for ADMIN SHOW DDL... output
  sql-statements/sql-statement-admin-show-ddl.md
  system-variables.md
Labels: translation/from-docs, size/XS, area/sql-infra, area/tidb-lightning, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14490 tikv config: correct location of report-region-buckets-tick-interval
  tikv-configuration-file.md
Labels: area/engine, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14481 *: modify some deprecated configuration items
  dashboard/dashboard-overview.md
  dashboard/dashboard-slow-query.md
  dynamic-config.md
  faq/deploy-and-maintain-faq.md
  quick-start-with-tidb.md
  tidb-configuration-file.md
Labels: translation/doing, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14496 update the feature name of Partitioned Raft KV
  TOC.md
  partitioned-raft-kv.md
  releases/release-6.6.0.md
  releases/release-7.1.0.md
  tidb-roadmap.md
  tikv-configuration-file.md
Labels: translation/no-need, size/M, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14509 releases: fix the issue and contributor format in release notes
  releases/release-5.2.2.md
  releases/release-6.1.6.md
  releases/release-6.2.0.md
  releases/release-6.5.0.md
  releases/release-6.5.1.md
Labels: translation/done, size/M, needs-cherry-pick-release-7.1, approved, lgtm

#14521 feat: SQLAlchemy and Sequelize were added to test pipeline
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-third-party-support.md
  develop/dev-guide-third-party-tools-compatibility.md
Labels: translation/done, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14522 feat: MySQL Connector/Python example add some log to give some instructions
  develop/dev-guide-sample-application-python.md
Labels: translation/done, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14516 ci: update the git diff command in the prevent deletion workflow to improve accuracy
  .github/workflows/prevent-deletion.yaml
Labels: translation/no-need, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14489 lightning: refine description about --check-requirements *bool*
  tidb-lightning/tidb-lightning-command-line-full.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14507 lightning: refine dsecription of check-requirements
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14518 lightning: refine description about checksum-via-sql
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14319 briefly update the grafana tikv dashboard doc
  grafana-tikv-dashboard.md
  media/tikv-dashboard-raft-process.png
Labels: translation/doing, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14564 cdc matcher rule explaination example
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, type/bug-fix, size/S, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14572 fix pd dashboard
  grafana-pd-dashboard.md
Labels: translation/doing, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14580 select: Add tablesample
  sql-statements/sql-statement-select.md
Labels: translation/from-docs, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14587 *: remove unnecessary character from sql examples
  character-set-and-collation.md
  partitioned-table.md
  sql-statements/sql-statement-create-binding.md
  sql-statements/sql-statement-create-table.md
  sql-statements/sql-statement-drop-binding.md
  sql-statements/sql-statement-show-bindings.md
  transaction-overview.md
Labels: translation/doing, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14434 修正笔误
  faq/sql-faq.md
Labels: contribution, translation/no-need, first-time-contributor, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14600 sql statement: fix SQL syntax error
  dm/dm-safe-mode.md
  sql-statements/sql-statement-create-index.md
Labels: translation/no-need, type/bug-fix, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14511 v7.1.1: support ARM 64 for openEuler
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, approved, lgtm

#14581 plan cache: TiDB v7.1.1 supports queries with more than 200 parameters
  optimizer-fix-controls.md
  sql-non-prepared-plan-cache.md
Labels: translation/done, size/S, area/planner, approved, needs-1-more-lgtm, lgtm

#14506 release v7.1.1
  TOC.md
  releases/release-7.1.0.md
  releases/release-7.1.1.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14508 v7.1.1: add tidb_lock_unchanged_keys
  system-variables.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm

#14514 bump version to v7.1.1
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-open-api-v2.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#14608 cdc update release-note about fix avro handle incorrect enum type value
  releases/release-7.1.1.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14616 error codes: update the support contact
  error-codes.md
Labels: translation/no-need, type/bug-fix, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14612 sql: fix an error in sql-statement-select.md
  sql-statements/sql-statement-select.md
Labels: size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14615 Update TiSpark close telemetry time
  telemetry.md
Labels: translation/done, needs-cherry-pick-master, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.2

#14483 Update tidb-lightning-physical-import-mode.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: type/enhancement, translation/doing, size/XS, area/tidb-lightning, approved, lgtm

#14626 Fix formatting of v620 release notes
  releases/release-6.2.0.md
Labels: translation/from-docs, type/bug-fix, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14488 include privilege check for temp-dir
  check-before-deployment.md
  hardware-and-software-requirements.md
  system-variables.md
  tidb-configuration-file.md
  tidb-distributed-execution-framework.md
Labels: type/enhancement, translation/done, size/M, area/sql-infra, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14643 revert "change compaction-guard-min-output-file-size to 1MB"
  releases/release-7.1.1.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14642 Partitioned Raft KV: add incompatibility with TiFlash
  partitioned-raft-kv.md
  releases/release-7.1.0.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14614 Include extra restrictions for multi-valued indexes
  choose-index.md
  releases/release-6.6.0.md
  releases/release-7.1.0.md
  sql-statements/sql-statement-create-index.md
Labels: translation/doing, size/S, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14523 feat: divide the chinese example docs
  TOC.md
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-overview.md
  develop/dev-guide-playground-gitpod.md
  develop/dev-guide-prepared-statement.md
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-mysqlclient.md
  develop/dev-guide-sample-application-python-peewee.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-python.md
Labels: translation/from-docs, size/XXL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2
