Repository pingcap/docs-cn, pull requests merged in 2023-08, with the labels that each got.

#14184 update sql statement show analyze status
  information-schema/information-schema-analyze-status.md
  sql-statements/sql-statement-show-analyze-status.md
Labels: translation/done, size/L, approved, lgtm, v7.3

#14524 sql-plan-replayer: add doc for historical stats integration into the plan replayer
  sql-plan-replayer.md
Labels: translation/done, size/XS, approved, lgtm, v7.3

#14650 fix: gorm serverless dsn
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
Labels: translation/done, size/S, ONCALL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14569 Remove server version upgrade
  tidb-configuration-file.md
  upgrade-tidb-using-tiup.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14510 Create upgrade-monitoring-services.md
  TOC.md
  upgrade-monitoring-services.md
Labels: translation/doing, size/L, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14355 br: support to write/ready azure blobs with customer provided key
  br/backup-and-restore-storages.md
  encryption-at-rest.md
Labels: translation/done, size/M, approved, lgtm, v7.3

#14519 RU info in explain analyze
  sql-statements/sql-statement-explain-analyze.md
  tidb-resource-control.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14665 fix: correct whitespace usage
  dashboard/dashboard-faq.md
  dashboard/dashboard-ops-reverse-proxy.md
  dashboard/dashboard-session-sso.md
  develop/dev-guide-unstable-result-set.md
  dm/feature-online-ddl.md
  production-deployment-using-tiup.md
  quick-start-with-htap.md
  statistics.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-bench.md
Labels: translation/done, type/bug-fix, size/XL, approved, needs-1-more-lgtm, lgtm

#14428 add calibrate resource error and metrics description for 7.2 and master
  dashboard/dashboard-resource-manager.md
  grafana-resource-control-dashboard.md
  sql-statements/sql-statement-calibrate-resource.md
Labels: translation/done, type/bug-fix, size/S, area/sql-infra, approved, lgtm, needs-cherry-pick-release-7.2

#14681 cdc update about force-replicate
  ticdc/ticdc-avro-protocol.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-overview.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.3

#14634 optimizer: add docs for shared cte and explain enhancement
  explain-walkthrough.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v7.3

#14657 cdc add docs about handle-key only
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/M, approved, lgtm, v7.3

#14687 analyze table: fix typo AnlyzeOption should be AnalyzeOption
  sql-statements/sql-statement-analyze-table.md
Labels: translation/from-docs, type/bug-fix, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14664 planner: add document about some new introduced hints
  optimizer-hints.md
Labels: translation/done, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, v7.3

#14599 lightning: add `enable-diagnose-logs` param
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, area/tidb-lightning, approved, lgtm, v7.3

#14609 lightning: update docs for duplicate detection
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-error-resolution.md
  tidb-lightning/tidb-lightning-logical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: translation/done, size/L, type/compatibility-or-feature-change, area/tidb-lightning, approved, lgtm, v7.3

#14517 Add runtime filter docs
  TOC.md
  explain-joins.md
  runtime-filter.md
  system-variables.md
Labels: translation/done, size/XL, approved, lgtm, v7.3

#14641 update compaction-guard-min-output-file-size
  tikv-configuration-file.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.3

#14702 add table `mysql.tidb_timers`
  mysql-schema.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.3

#14290 add a system variable tidb_lock_unchanged_keys
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, needs-cherry-pick-release-7.1, approved, lgtm, v7.3

#14701 change the stable of tidb-in-k8s pdf to v1.5
  resources/cdnfresh.txt
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#14288 Add some security notation for tcp_port in sample config file
  tiflash/tiflash-configuration.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm

#14658 Added List DEFAULT partition
  partitioned-table.md
Labels: translation/from-docs, size/L, area/sql-infra, approved, needs-1-more-lgtm, lgtm, v7.3

#14640 Update Parameter Name from `tikv-importer.incremental-import` to `tikv-importer.parallel-import`
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-prechecks.md
Labels: translation/done, size/S, approved, lgtm, v7.3

#14647 add system variable tidb_skip_missing_partition_stats
  statistics.md
  system-variables.md
Labels: contribution, translation/doing, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.3

#14598 update user doc for multirocksdb
  partitioned-raft-kv.md
  tikv-configuration-file.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.3

#14651 v7.3: update default values for RocksDB config
  tikv-configuration-file.md
Labels: translation/from-docs, size/S, type/compatibility-or-feature-change, for-release, approved, needs-1-more-lgtm, lgtm, v7.3

#14644 add `query watch` docs for the manual managment of runaway watch
  TOC.md
  information-schema/information-schema-runaway-watches.md
  mysql-schema.md
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-drop-resource-group.md
  sql-statements/sql-statement-query-watch.md
  sql-statements/sql-statement-set-resource-group.md
  sql-statements/sql-statement-show-create-resource-group.md
  tidb-resource-control.md
Labels: translation/done, size/XL, area/sql-infra, approved, lgtm, v7.3

#14179 add a system variable tiflash_replica_read
  system-variables.md
  tiflash/create-tiflash-replicas.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, area/bigdata, approved, lgtm, v7.3

#14692 cdc: add hex encoding to csv
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-csv.md
Labels: translation/doing, size/XS, type/compatibility-or-feature-change, area/ticdc, for-release, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, v7.3

#14276 sql-statements: tiny update for smooth upgrade TiDB
  sql-statements/sql-statement-add-index.md
Labels: translation/doing, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14700 Garbage Collection: add more description of system variables and how …
  garbage-collection-configuration.md
  system-variables.md
Labels: type/enhancement, translation/done, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14709 release-6.5.0: update the release note introduction
  releases/release-6.5.0.md
Labels: translation/from-docs, area/general, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14535 optimizer-fix-control: add doc for the new optimizer fix controls introduced in v7.3.0
  optimizer-fix-controls.md
  sql-non-prepared-plan-cache.md
Labels: translation/done, size/S, for-release, approved, lgtm, v7.3

#14716 update default bucket size
  tikv-configuration-file.md
  tune-region-performance.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.3

#14570 feat: full support for prisma
  develop/dev-guide-third-party-support.md
Labels: translation/done, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14724 Update docs for newly added locking functions
  functions-and-operators/locking-functions.md
Labels: translation/from-docs, size/XS, for-release, approved, lgtm, v7.3, needs-cherry-pick-release-7.3

#14704 DTFile supports V3 version
  TOC.md
  releases/release-6.2.0.md
  tiflash-upgrade-guide.md
  tiflash/tiflash-command-line-flags.md
  tiflash/tiflash-configuration.md
Labels: translation/done, size/S, area/bigdata, approved, lgtm, v7.3, needs-cherry-pick-release-7.3

#14734 lightning: refine description about conflict.strategy
  tidb-lightning/tidb-lightning-logical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: type/enhancement, translation/done, size/XS, area/tidb-lightning, approved, lgtm, needs-cherry-pick-release-7.3

#14736 update the name of TiFlash upgrade help
  TOC.md
  releases/release-6.2.0.md
Labels: translation/no-need, size/XS, area/bigdata, approved, needs-1-more-lgtm, lgtm

#14741 update learning path for v7.3
  _index.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, v7.3

#14742 fix the statement to update statistics of partitioned tables
  partitioned-table.md
Labels: translation/doing, size/S, area/sql-infra, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14744 trigger 7.3 pdf build
  comment-syntax.md
Labels: translation/done, size/XS, approved, lgtm

#14749 trigger 7.3 pdf again
  comment-syntax.md
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#14515 resource_control: add description for current resource group
  functions-and-operators/information-functions.md
  functions-and-operators/tidb-functions.md
Labels: translation/done, size/M, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14662 Clarify swap descriptions
  check-before-deployment.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14755 add configs for in memory slow query
  tidb-configuration-file.md
Labels: translation/done, size/S, for-release, approved, lgtm, v7.3, needs-cherry-pick-release-7.3

#14762 pr template: add v7.4
  .github/pull_request_template.md
Labels: translation/done, area/general, size/XS, approved, needs-1-more-lgtm, lgtm

#14764 clinic: extend free expiration
  clinic/clinic-introduction.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14565 add release notes for v7.3.0
  TOC.md
  releases/release-7.3.0.md
  releases/release-notes.md
  releases/release-timeline.md
  system-variables.md
Labels: translation/doing, size/XL, for-release, approved, lgtm, v7.3, needs-cherry-pick-release-7.3

#14607 add 7.3 in basic features
  basic-features.md
Labels: translation/done, size/XL, for-release, approved, lgtm, v7.3, needs-cherry-pick-release-7.3

#14760 tidb: explain the `pseudo` stats
  sql-statements/sql-statement-analyze-table.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14775 update the package link in v7.2.0 release notes
  releases/release-7.2.0.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14781 rm redundant heading in 7.3 rn
  releases/release-7.3.0.md
Labels: translation/no-need, size/XS, approved, lgtm, needs-cherry-pick-release-7.3

#14663 feat: python example simplify
  develop/dev-guide-sample-application-python-mysqlclient.md
Labels: translation/doing, size/XL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14789 fix a typo in sql statement alter table
  sql-statements/sql-statement-alter-table.md
Labels: translation/no-need, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14802 fix typo: 登陆 -> 登录
  releases/release-6.1.0.md
  tiunimanager/tiunimanager-manage-host-resources.md
  tiunimanager/tiunimanager-quick-start.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14806 update links to clustered index in basic feature
  basic-features.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14811 tidb-lightning: delete record option in conflict detection
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: translation/done, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#14738 sql: update statement summary doc
  statement-summary-tables.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14798 lightning: delete content about tpcc
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: type/enhancement, translation/done, size/S, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14800 docs: add limitations for the performance impacts of backup task
  br/backup-and-restore-overview.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14815 planner: update document about multi-valued indexes
  choose-index.md
Labels: translation/done, size/M, area/planner, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14838 dev-guide: add note about not using tidb-loadbalance in production environments
  develop/dev-guide-choose-driver-or-orm.md
Labels: translation/doing, size/XS, ONCALL, area/ticdc, area/develop, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14799 ticdc: refine changefeed overview
  media/ticdc/ticdc-changefeed-state-transfer.png
  media/ticdc/ticdc-state-transfer.png
  ticdc/ticdc-changefeed-overview.md
Labels: translation/doing, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3

#14851 tikv: fixed some description about `--db` and `compact-cluster`
  tikv-control.md
Labels: translation/done, size/S, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14860 Revert "dev-guide: add note about not using tidb-loadbalance in production environments"
  develop/dev-guide-choose-driver-or-orm.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14867 TiDB-JDBC SM3 introduce
  develop/dev-guide-choose-driver-or-orm.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14874 releases: fix a typo
  releases/release-6.5.3.md
  releases/release-7.1.0.md
Labels: translation/no-need, type/bug-fix, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14883 sql: does not support using ALTER TABLE to add columns with AUTO_INCREMENT
  auto-increment.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14888 fix typos and update example
  enable-tls-between-clients-and-servers.md
  faq/tidb-faq.md
  schedule-replicas-by-topology-labels.md
  tidb-limitations.md
Labels: translation/done, type/bug-fix, size/S, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14879 make binding doc clearer with examples
  sql-plan-management.md
Labels: translation/done, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14828 add release notes v6.5.4
  TOC.md
  releases/release-6.5.4.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14882 bump version to v6.5.4
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#14835 ticdc: add ddl replication documents
  TOC.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-ddl.md
  ticdc/ticdc-filter.md
Labels: translation/doing, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14908 Document what ADMIN CHECK does
  sql-statements/sql-statement-admin-check-table-index.md
Labels: type/enhancement, translation/from-docs, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14880 ticdc: refine changefeed scheduler configuration description
  TOC.md
  releases/release-6.3.0.md
  sync-diff-inspector/sync-diff-inspector-overview.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-upstream-downstream-check.md
Labels: translation/doing, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14881 Update tiflash-performance-tuning-methods.md
  tiflash-performance-tuning-methods.md
Labels: translation/done, size/S, needs-cherry-pick-release-6.5, area/performance, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14889 roadmap: add v7.3.0 release notes
  tidb-roadmap.md
Labels: contribution, translation/done, size/XS, approved, lgtm

#14925 develop: add OWNERS for develop docs
  OWNERS_ALIASES
  develop/OWNERS
Labels: translation/done, size/S, approved, lgtm

#14836 edit upgrade-monitoring-services.md
  upgrade-monitoring-services.md
Labels: translation/from-docs, size/S, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14902 develop: improve python mysqlclient sample code doc
  develop/dev-guide-sample-application-python-mysqlclient.md
Labels: type/enhancement, translation/from-docs, size/L, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14843 feat: java example simplify
  develop/dev-guide-playground-gitpod.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
Labels: translation/doing, size/XXL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#14810 placement rules: fix duplicate id in rule.json
  two-data-centers-in-one-city-deployment.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3
