Repository pingcap/docs-cn, pull requests merged in 2023-10, with the labels that each got.

#15127 sql: fix an error in AUTO_ID_CACHE
  auto-increment.md
Labels: translation/no-need, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15043 add doc for tiflash resource control
  releases/release-7.2.0.md
  sql-statements/sql-statement-calibrate-resource.md
  system-variables.md
  tidb-resource-control.md
  tiflash/tiflash-configuration.md
  tiflash/tiflash-pipeline-model.md
Labels: translation/done, size/L, type/compatibility-or-feature-change, approved, lgtm, v7.4

#15090 Add docs for information_schema.CHECK_CONSTRAINTS
  TOC.md
  information-schema/information-schema-check-constraints.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, v7.4

#14964 *: add doc for `tikv_client_read_timeout` system variable
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v7.4

#15074 cdc: add docs about the claim check.
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/doing, size/L, type/compatibility-or-feature-change, approved, lgtm, v7.4

#15105 sysvar: add system variable `tidb_opt_enable_hash_join`
  optimizer-hints.md
  system-variables.md
Labels: translation/from-docs, size/S, type/compatibility-or-feature-change, approved, needs-1-more-lgtm, lgtm, v7.4

#15132 sql: refine description about compatibility with msql
  constraints.md
Labels: translation/done, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, approved, needs-1-more-lgtm, lgtm

#14969 add doc for tiflash query level spill
  system-variables.md
  tiflash/tiflash-spill-disk.md
Labels: translation/done, size/L, area/bigdata, approved, lgtm, v7.4

#15053 doc: add tidb rollup syntax
  TOC.md
  explain-aggregation.md
  functions-and-operators/aggregate-group-by-functions.md
  functions-and-operators/group-by-modifier.md
  mysql-compatibility.md
  sql-statements/sql-statement-select.md
Labels: translation/done, size/L, approved, lgtm, v7.4

#15039 tiflash: add descriptions for some conf items under [flash] section
  tiflash/tiflash-configuration.md
Labels: translation/done, size/XS, area/bigdata, approved, lgtm, v7.4

#15052 Remove experimental note of tiflash disaggregated arch
  tiflash/tiflash-disaggregated-and-s3.md
Labels: translation/done, size/S, area/bigdata, approved, lgtm, v7.4

#14907 Support MEMBER OF function pushdown to TiKV
  functions-and-operators/expressions-pushed-down.md
Labels: translation/done, size/XS, approved, lgtm, v7.4

#15139 hardware-and-software-requirements: clarify UOS name
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3

#15001 tidb: add a new system variable `tidb_service_scope`
  system-variables.md
  tidb-distributed-execution-framework.md
Labels: translation/done, first-time-contributor, size/S, type/compatibility-or-feature-change, approved, lgtm, v7.4

#15044 dumpling: add csv line terminator option
  dumpling-overview.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, area/dumpling, approved, lgtm, v7.4

#15121 resource_control: fix resource control usage restriction
  tidb-resource-control.md
Labels: translation/done, size/XS, approved, lgtm, v7.4

#15146 fix PDF build failure: escape special characters
  dumpling-overview.md
Labels: translation/done, type/bug-fix, size/XS, approved, needs-1-more-lgtm, lgtm

#15069 Added REMOVE PARTITIONING and ALTER TABLE t PARTITION BY
  partitioned-table.md
Labels: translation/from-docs, size/M, area/sql-infra, approved, needs-1-more-lgtm, lgtm, v7.4

#15115 cdc: update topic expression description
  ticdc/ticdc-sink-to-kafka.md
Labels: contribution, translation/done, size/S, area/ticdc, approved, lgtm, v7.4

#15145 *: add doc for system variable tidb_schema_version_cache_limit
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v7.4

#15102 Add global sort related docs.
  TOC.md
  media/dist-task/global-sort.jpeg
  system-variables.md
  tidb-global-sort.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, v7.4

#15147 ticdc: add ddl replication documents
  ticdc/ticdc-ddl.md
Labels: translation/from-docs, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, v7.4

#14751 update tiflash upgrade guide
  tiflash-upgrade-guide.md
Labels: translation/doing, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.4

#15151 add experimental warning for lock/unlock stats
  sql-statements/sql-statement-lock-stats.md
  sql-statements/sql-statement-show-stats-locked.md
  sql-statements/sql-statement-unlock-stats.md
  statistics.md
Labels: translation/doing, size/S, approved, needs-1-more-lgtm, lgtm, v7.4, needs-cherry-pick-release-7.4

#14996 ticdc : async exec ddl doc update
  ticdc/ticdc-ddl.md
Labels: translation/done, size/S, area/ticdc, for-release, approved, lgtm, v7.4, needs-cherry-pick-release-7.4

#14152 feat: hide the non-full support level drivers/ORMs
  develop/dev-guide-third-party-support.md
Labels: translation/no-need, size/L, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15156 tidb-lightning: fix strategy number
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: size/XS, ONCALL, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14962 Update the param size for mark cache and minmax index cache for TiFlash
  releases/release-7.0.0.md
  tiflash/tiflash-configuration.md
Labels: translation/doing, size/XS, area/bigdata, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#14774 Documenting binary encoding used with Canal-JSON
  ticdc/ticdc-canal-json.md
Labels: translation/from-docs, size/M, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15163 learning path: update links to v7.4
  _index.md
Labels: contribution, translation/done, size/M, approved, needs-1-more-lgtm, lgtm, v7.4

#15101 add 7.4 in basic features
  basic-features.md
Labels: translation/done, size/XL, approved, lgtm, v7.4, needs-cherry-pick-release-7.4

#15081 develop: update peewee guide
  develop/dev-guide-sample-application-python-peewee.md
Labels: translation/done, size/XL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15021 import into: add doc for 7.4
  sql-statements/sql-statement-import-into.md
Labels: translation/done, size/M, approved, lgtm, v7.4, needs-cherry-pick-release-7.4

#14954 add release notes for v7.4.0
  TOC.md
  releases/release-7.4.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/XL, approved, lgtm, v7.4, needs-cherry-pick-release-7.4

#15136 roadmap: add v7.4.0 release notes
  tidb-roadmap.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, v7.4

#15155 bump version to 7.4.0
  README.md
  br/backup-and-restore-use-cases.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-open-api-v2.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, lgtm, v7.4, needs-cherry-pick-release-7.4

#15184 fix PDF build failure: escape special characters
  releases/release-7.4.0.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15186 Update cdnfresh.txt for v7.4, v7.3, v7.1
  resources/cdnfresh.txt
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#15182 v7.3: update download address
  releases/release-7.3.0.md
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, v7.4, needs-cherry-pick-release-7.4

#15192 ticdc: add the Storage Sink feature to ticdc-overview.md
  media/ticdc/cdc-architecture.png
  migration-tools.md
  production-deployment-using-tiup.md
  ticdc-deployment-topology.md
  ticdc/ticdc-overview.md
Labels: translation/from-docs, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15198 add v7.5 to the PR template
  .github/pull_request_template.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, v7.5

#15199 Update 7.4.0 release notes to add deprecation plan
  releases/release-7.4.0.md
Labels: contribution, translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.4

#15200 Use support.md instead of direct links to GitHub
  dr-secondary-cluster.md
  sql-statements/sql-statement-admin-check-table-index.md
  sql-statements/sql-statement-alter-database.md
  sql-statements/sql-statement-create-database.md
  sql-statements/sql-statement-create-role.md
  sql-statements/sql-statement-create-table-like.md
  sql-statements/sql-statement-deallocate.md
  sql-statements/sql-statement-delete.md
  sql-statements/sql-statement-do.md
  sql-statements/sql-statement-drop-database.md
  sql-statements/sql-statement-drop-role.md
  sql-statements/sql-statement-drop-view.md
  sql-statements/sql-statement-execute.md
  sql-statements/sql-statement-flush-privileges.md
  sql-statements/sql-statement-grant-role.md
  sql-statements/sql-statement-insert.md
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-prepare.md
  sql-statements/sql-statement-rename-index.md
  sql-statements/sql-statement-rename-table.md
  sql-statements/sql-statement-rename-user.md
  sql-statements/sql-statement-replace.md
  sql-statements/sql-statement-revoke-role.md
  sql-statements/sql-statement-set-default-role.md
  sql-statements/sql-statement-set-names.md
  sql-statements/sql-statement-set-password.md
  sql-statements/sql-statement-set-role.md
  sql-statements/sql-statement-show-character-set.md
  sql-statements/sql-statement-show-collation.md
  sql-statements/sql-statement-show-columns-from.md
  sql-statements/sql-statement-show-create-database.md
  sql-statements/sql-statement-show-create-table.md
  sql-statements/sql-statement-show-databases.md
  sql-statements/sql-statement-show-errors.md
  sql-statements/sql-statement-show-grants.md
  sql-statements/sql-statement-show-indexes.md
  sql-statements/sql-statement-show-plugins.md
  sql-statements/sql-statement-show-privileges.md
  sql-statements/sql-statement-show-table-status.md
  sql-statements/sql-statement-show-tables.md
  sql-statements/sql-statement-show-variables.md
  sql-statements/sql-statement-show-warnings.md
  sql-statements/sql-statement-shutdown.md
  sql-statements/sql-statement-truncate.md
  sql-statements/sql-statement-use.md
  support.md
  tidb-resource-control.md
  troubleshoot-tidb-cluster.md
Labels: translation/from-docs, size/L, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15208 v7.4: remove a note
  releases/release-7.4.0.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15213 keywords: add TPCH_10
  keywords.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, v7.4, needs-cherry-pick-release-7.4

#15212 add more desc about replicatuin-factor
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15201 system-variables: write the version info of tidb_read_consistency in Chinese
  system-variables.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15215 link to docs repo
  geo-distributed-deployment-topology.md
  hybrid-deployment-topology.md
  minimal-deployment-topology.md
  production-deployment-using-tiup.md
  ticdc-deployment-topology.md
  tidb-binlog-deployment-topology.md
  tiflash-deployment-topology.md
  tiflash/tiflash-configuration.md
  tispark-deployment-topology.md
  tiunimanager/tiunimanager-install-and-maintain.md
Labels: translation/no-need, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, approved, needs-1-more-lgtm, lgtm

#15210 add collapsible topology files
  config-templates/complex-cdc.yaml
  config-templates/complex-mini.yaml
  config-templates/complex-multi-instance.yaml
  config-templates/complex-tidb-binlog.yaml
  config-templates/complex-tiflash.yaml
  config-templates/complex-tispark.yaml
  config-templates/em-topology-config.yaml
  config-templates/geo-redundancy-deployment.yaml
  config-templates/simple-cdc.yaml
  config-templates/simple-file-binlog.yaml
  config-templates/simple-mini.yaml
  config-templates/simple-multi-instance.yaml
  config-templates/simple-tidb-binlog.yaml
  config-templates/simple-tiflash.yaml
  config-templates/simple-tispark.yaml
  geo-distributed-deployment-topology.md
  hybrid-deployment-topology.md
  minimal-deployment-topology.md
  production-deployment-using-tiup.md
  ticdc-deployment-topology.md
  tidb-binlog-deployment-topology.md
  tiflash-deployment-topology.md
  tiflash/tiflash-configuration.md
  tispark-deployment-topology.md
  tiunimanager/tiunimanager-install-and-maintain.md
Labels: missing-translation-status, size/XXL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15240 release notes: add more items in 7.4
  releases/release-7.4.0.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#14992 ticdc: Update cdc server config
  ticdc/ticdc-server-config.md
Labels: type/enhancement, translation/done, size/M, area/ticdc, approved, lgtm, needs-cherry-pick-release-7.4

#15191 *: optimize 4 docs descriptions
  quick-start-with-tidb.md
  ticdc/ticdc-overview.md
Labels: translation/from-docs, size/M, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15179 *: Improve documentation readability and consistency
  mysql-compatibility.md
  overview.md
Labels: translation/from-docs, size/M, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15221 update some GitHub links for tidb repo reorganization
  deploy-monitoring-services.md
  develop/dev-guide-proxysql-integration.md
  functions-and-operators/precision-math.md
  maintain-tidb-using-tiup.md
  performance-tuning-methods.md
  production-deployment-using-tiup.md
  tidb-binlog/binlog-consumer-client.md
  tidb-configuration-file.md
  troubleshoot-lock-conflicts.md
Labels: translation/done, size/S, area/develop, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15189 statistics: add info about tidb_auto_analyze_partition_batch_size
  statistics.md
Labels: translation/doing, size/XS, area/sql-infra, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15076 tiflash: add mpp glossary and diagram
  glossary.md
  media/tiflash/tiflash-mpp.png
  schedule-replicas-by-topology-labels.md
  tiflash/use-tiflash-mpp-mode.md
Labels: translation/from-docs, size/M, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15281 tiflash: refine descriptions
  glossary.md
  schedule-replicas-by-topology-labels.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15283 pull request template: remove v7.2 and v7.0
  .github/pull_request_template.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#15271 planner: update the SPM doc
  sql-plan-management.md
Labels: translation/done, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15256 v7.1.2: add release notes
  TOC.md
  releases/release-7.1.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/doing, size/L, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15286 v7.1 docs: bump the example TiDB version to v7.1.2
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-open-api-v2.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/doing, area/general, size/L, approved, needs-1-more-lgtm, lgtm

#15294 removed description about not supporting FLOAT4/FLOAT8
  mysql-compatibility.md
Labels: translation/no-need, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15297 release-7.1.2.md: fix an issue number
  releases/release-7.1.2.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15301 Connector/J: fix broken links
  best-practices/java-app-best-practices.md
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-connect-to-tidb.md
  develop/dev-guide-connection-parameters.md
  develop/dev-guide-third-party-tools-compatibility.md
  system-variables.md
  tispark-overview.md
Labels: translation/done, size/S, area/develop, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15302 chore: update pull_request_template
  .github/pull_request_template.md
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#15289 dumpling: add URI formats
  TOC.md
  br/backup-and-restore-overview.md
  br/backup-and-restore-storages.md
  br/br-incremental-guide.md
  br/br-pitr-manual.md
  br/br-snapshot-guide.md
  br/use-br-command-line-tool.md
  dumpling-overview.md
  error-codes.md
  external-storage-uri.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-import-into.md
  sql-statements/sql-statement-restore.md
  system-variables.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-kafka.md
  tidb-lightning/tidb-lightning-command-line-full.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-data-source.md
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-overview.md
Labels: translation/done, size/L, area/dumpling, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15311 update URI examples
  external-storage-uri.md
Labels: translation/done, area/general, size/M, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15120 ticdc: update ticdc docs
  hardware-and-software-requirements.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-faq.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-overview.md
  ticdc/troubleshoot-ticdc.md
Labels: translation/done, requires-version-specific-changes, size/M, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#15321 tiup: add the GitHub link of release notes
  tiup/tiup-documentation-guide.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#14797 collation: improve some new_collation_enabled relateds doc
  br/backup-and-restore-overview.md
  character-set-and-collation.md
  faq/backup-and-restore-faq.md
  migration-tools.md
  mysql-schema.md
Labels: translation/doing, size/S, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15272 tikv: update the default value of periodic-compaction and ttl
  releases/release-7.4.0.md
  tikv-configuration-file.md
Labels: translation/done, size/XS, area/engine, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15207 system-variables: update docs for hint SET_VAR
  system-variables.md
Labels: contribution, translation/done, size/S, approved, lgtm, needs-cherry-pick-release-7.4

#15331 release notes: remove duplicate notes
  releases/release-6.5.3.md
  releases/release-6.5.5.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4
