Repository pingcap/docs-cn, pull requests merged in 2023-01, with the labels that each got.

#12536 Update clinic-introduction.md
  clinic/clinic-introduction.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/clinic, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12537 add aliases for br snapshot guide
  br/br-snapshot-guide.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/br

#12543 troubleshoot: add some doc link to troubleshooting map
  tidb-troubleshooting-map.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12547 sysvar: add type info and correct some other info
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/L, area/sql-infra, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12557 add aliases for br docs in 6.5 branch
  br/backup-and-restore-overview.md
  br/backup-and-restore-storages.md
  br/backup-and-restore-use-cases.md
  br/br-pitr-guide.md
  br/br-pitr-manual.md
  faq/backup-and-restore-faq.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/br

#12552 Revert "Remove cyclic replication feature: Cherry pick 7336 to release 4.0"
  media/cdc-cyclic-replication.png
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, status/LGT2, translation/no-need, status/can-merge, size/L

#12553 Revert "Remove cyclic replication feature: Cherry pick 7336 to release 5.0"
  experimental-features.md
  releases/release-5.0.0.md
  releases/release-5.0.4.md
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, status/LGT2, translation/no-need, status/can-merge, size/L

#12554 Revert "Remove cyclic replication feature (#7336) Cherry pick 7336 to release 5.1"
  experimental-features.md
  releases/release-5.0.0.md
  releases/release-5.1.2.md
  ticdc/manage-ticdc.md
  ticdc/ticdc-overview.md
Labels: status/LGT1, status/LGT2, translation/no-need, status/can-merge, size/L

#12548 releases: update release notes wording, summary, punctuation
  releases/release-6.1.0.md
  releases/release-6.5.0.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.5

#12562 fix a typo in subquery optimization
  subquery-optimization.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, area/planner, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#12572 tidb configuration file: adjust the position of temp-dir
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, ONCALL, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12560 *: align 3 SQL related PRs
  command-line-flags-for-tidb-configuration.md
  data-type-string.md
  faq/high-reliability-faq.md
  tidb-configuration-file.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12559 faq: add some faqs to documention
  faq/high-reliability-faq.md
  faq/manage-cluster-faq.md
  faq/sql-faq.md
  faq/tidb-faq.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12513 modify tune-tiflash-performance.md
  tiflash/tune-tiflash-performance.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S, area/bigdata, needs-cherry-pick-release-6.5

#12594 FAQ: add a faq (blacklist a sql execution)
  faq/sql-faq.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/planner, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12579 sql: fix ebnf diagram
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-create-user.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5

#12492 privileges: provide descriptions about 3 dynamic privileges
  privilege-management.md
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, area/security, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12606 fix cdc consistent config
  ticdc/ticdc-sink-to-mysql.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#12612 More verbose status docs
  dashboard/dashboard-cluster-info.md
  tiup/tiup-command-status.md
  tiup/tiup-component-cluster-display.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#12613 mysql-compatibility: refined descriptions about lower_case_table_names
  mysql-compatibility.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, ONCALL, needs-cherry-pick-release-6.5

#12625 add examples in tiflash docs
  tiflash/tiflash-results-materialization.md
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/L, area/bigdata, needs-cherry-pick-release-6.5

#12639 ticdc: fix typo
  ticdc/ticdc-architecture.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/ticdc, needs-cherry-pick-release-6.5

#12629 add desc for tiflash system tables
  TOC.md
  information-schema/information-schema-tiflash-segments.md
  information-schema/information-schema-tiflash-tables.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/L, area/bigdata, ONCALL, needs-cherry-pick-release-6.5

#12624 ticdc: fix some error
  migrate-from-tidb-to-mysql.md
  migrate-from-tidb-to-tidb.md
  replicate-between-primary-and-secondary-clusters.md
  replicate-data-to-kafka.md
  ticdc/deploy-ticdc.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/monitor-ticdc.md
  ticdc/ticdc-avro-protocol.md
  ticdc/ticdc-canal-json.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-sink-to-mysql.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/M, area/ticdc, needs-cherry-pick-release-6.5

#12637 Add tiflash execution tuning materials
  tiflash/tune-tiflash-performance.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/L, area/bigdata

#12649 ttl: improve seo
  time-to-live.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-6.5

#12601 mention force and add 2 uuid functions
  auto-increment.md
  functions-and-operators/miscellaneous-functions.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, area/sql-infra, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12664 Correct the unit of tidb_max_tiflash_threads
  tiflash/tune-tiflash-performance.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.5

#12570 [Update] Spring Boot reversion and remove all of the copyable marks
  develop/dev-guide-bookshop-schema-design.md
  develop/dev-guide-connect-to-tidb.md
  develop/dev-guide-connection-parameters.md
  develop/dev-guide-create-database.md
  develop/dev-guide-create-secondary-indexes.md
  develop/dev-guide-create-table.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-get-data-from-single-table.md
  develop/dev-guide-hybrid-oltp-and-olap-queries.md
  develop/dev-guide-implicit-type-conversion.md
  develop/dev-guide-index-best-practice.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-join-tables.md
  develop/dev-guide-optimistic-and-pessimistic-transaction.md
  develop/dev-guide-optimize-sql-best-practices.md
  develop/dev-guide-optimize-sql.md
  develop/dev-guide-paginate-results.md
  develop/dev-guide-prepared-statement.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-sample-application-python.md
  develop/dev-guide-sample-application-spring-boot.md
  develop/dev-guide-tidb-crud-sql.md
  develop/dev-guide-transaction-overview.md
  develop/dev-guide-transaction-restraints.md
  develop/dev-guide-transaction-troubleshoot.md
  develop/dev-guide-unstable-result-set.md
  develop/dev-guide-update-data.md
  develop/dev-guide-use-common-table-expression.md
  develop/dev-guide-use-follower-read.md
  develop/dev-guide-use-stale-read.md
  develop/dev-guide-use-subqueries.md
  develop/dev-guide-use-temporary-tables.md
  develop/dev-guide-use-views.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XXL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#11986 Synchronise the syntax tree of drop stats
  sql-statements/sql-statement-drop-stats.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.5

#12663 tiflash: update config description of max_memory_usage_for_all_queries
  tiflash/tiflash-configuration.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/S, type/compatibility-or-feature-change, area/bigdata, for-release, v6.6

#12689 dashboard: fix a typo in disk list
  dashboard/dashboard-cluster-info.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, sig/diagnosis, needs-cherry-pick-release-6.5

#12679 Update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.5

#12697 fix typos
  dashboard/dashboard-faq.md
  releases/release-5.0.6.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#12700 fix a typo in 5.3.1 RN
  releases/release-5.3.1.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#12723 chore: add the TiDB Cloud doc PDF to cdnfresh.txt
  resources/cdnfresh.txt
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS

#12295 Update enable-tls-between-components and add TLS rotation description
  enable-tls-between-components.md
Labels: status/LGT2, translation/doing, status/can-merge, area/security, first-time-contributor, size/XS, needs-cherry-pick-release-6.5

#11341 develop: fix paging sql with multiple columns for cluster index table
  develop/dev-guide-paginate-results.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12692 add notice of tiflash avx3
  upgrade-tidb-using-tiup.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#11501 Update hardware-and-software-requirements.md
  hardware-and-software-requirements.md
Labels: status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/bigdata, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12738 add description of avx2 in tiflash overview
  tiflash/tiflash-overview.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/XS, area/bigdata, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12691 adjust the order of titles under Reference in TOC
  TOC.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.5

#12740 Update tiup-playground.md
  tiup/tiup-playground.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/S, area/tiup, needs-cherry-pick-release-6.5

#11957 Clarify unsafe recovery cmd input requirements
  online-unsafe-recovery.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/engine, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12302 Develop Guide Django Examples
  TOC.md
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-sample-application-django.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-sample-application-python.md
  develop/dev-guide-sample-application-spring-boot.md
  develop/dev-guide-third-party-support.md
  media/develop/postman_player_count.png
  media/develop/postman_player_create.png
  media/develop/postman_player_getbyid.png
  media/develop/postman_player_getbylimit.png
  media/develop/postman_player_getbypage.png
  media/develop/postman_player_import.png
  media/develop/postman_player_trade.png
Labels: status/LGT2, translation/doing, status/can-merge, size/XXL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12748 develop: remove details of mysql compatibility
  develop/dev-guide-choose-driver-or-orm.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, area/develop, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12687 *: merge experimental-feature.md to basic-features.md
  TOC.md
  _index.md
  basic-features.md
  experimental-features.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, area/general, size/L, needs-cherry-pick-release-6.5

#12762 basic-features: refine note
  basic-features.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/XS, needs-cherry-pick-release-6.5

#12678 Tiflash perf tuning add examples
  tiflash/tune-tiflash-performance.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XL, area/bigdata, needs-cherry-pick-release-6.5

#12684 tiup: modify the scale-in --force warning
  tiup/tiup-component-cluster-scale-in.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, area/tiup, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12685 tiup: correct indentation in config
  maintain-tidb-using-tiup.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/tiup, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12626 hardware-and-software-requirements: Correct CentOS info
  hardware-and-software-requirements.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12573 sql-statement-load-data: update compatibility info
  sql-statements/sql-statement-load-data.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, area/sql-infra, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12696 br: add a PITR FAQ to backup and restore FAQs
  faq/backup-and-restore-faq.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/br, needs-cherry-pick-release-6.5

#12803 fix typos in FAQ
  faq/migration-tidb-faq.md
  faq/sql-faq.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.5

#12815 *: updated video poster links
  command-line-flags-for-tidb-configuration.md
  dm/dm-overview.md
  dumpling-overview.md
  explore-htap.md
  faq/manage-cluster-faq.md
  overview.md
  quick-start-with-tidb.md
  tidb-architecture.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-monitoring-framework.md
  user-account-management.md
Labels: status/LGT1, translation/no-need, status/can-merge, area/general, require-LGT1, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12829 *: correct video links
  faq/manage-cluster-faq.md
  tidb-architecture.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12806 learning path: add more popular links to Reference
  _index.md
Labels: status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/XS, needs-cherry-pick-release-6.5

#10883 Modify downstream database permissions
  dm/dm-worker-intro.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12804 lightning: improve wording for the description of config on-duplicate
  tidb-lightning/tidb-lightning-configuration.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, requires-version-specific-changes, require-LGT1, size/XS, ONCALL, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12846 ticdc: update architecture figure
  media/ticdc/ticdc-architecture-6.jpg
  ticdc/ticdc-architecture.md
Labels: status/LGT1, status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, area/ticdc, needs-cherry-pick-release-6.5

#12844 optimizer: fix optimizer hint identifier
  optimizer-hints.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/planner, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12852 br: add a warning for br debug
  br-usage-backup-for-maintain.md
  br/br-usage-backup.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/br

#12814 [TiUP] add support check the yaml file before scale out
  tiup/tiup-component-cluster-check.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/M, area/tiup, ONCALL, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12853 br: remove br debug info due to a known issue
  br-usage-backup-for-maintain.md
  br/br-usage-backup.md
Labels: status/LGT1, status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/M, area/br

#12854 dr: update support contact
  two-data-centers-in-one-city-deployment.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5
