Repository pingcap/docs-cn, pull requests merged in 2023-05, with the labels that each got.

#13509 system-variables.md: add version tag for tidb_enable_ddl
  system-variables.md
  tidb-configuration-file.md
Labels: translation/doing, status/can-merge, status/LGT3, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13468 system-variables: Link various resources related to MAX_EXECUTION_TIME
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13839 lightning: update the import capability spec
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13697 add config unit for tidb_adaptive_closest_read_threshold
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13841 chore: add v7.2 to the PR template
  .github/pull_request_template.md
  tiflash/tiflash-results-materialization.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS

#13855 system variable: clarify timezone for tidb_auto_analyze_time
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13838 foreign-key: add a note about the usage
  foreign-key.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13465 fix range columns examples
  partitioned-table.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#11390 update slow query doc
  identify-slow-queries.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, sig/diagnosis, ONCALL

#13868 Remove TRUNCATE PARTITION as non-supported
  mysql-compatibility.md
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13840 add configuration performance.force-init-stats
  releases/release-7.1.0.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, for-release, v7.1, needs-cherry-pick-release-7.1

#13883 develop: fix typo
  develop/dev-guide-connection-parameters.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13870 Fix typos for LOAD
  sql-statements/sql-statement-operate-load-data-job.md
  sql-statements/sql-statement-show-load-data.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-7.0

#13869 cdc: add some explanations about lossy DDL
  releases/release-7.1.0.md
  ticdc/ticdc-faq.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/ticdc, for-release, v7.1

#13872 br: change the permission for external storage when do restore
  br/backup-and-restore-storages.md
  br/backup-and-restore-use-cases.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, v7.1

#13623 ticdc: add docs for old value behavior
  ticdc/ticdc-avro-protocol.md
  ticdc/ticdc-csv.md
  ticdc/ticdc-faq.md
  ticdc/ticdc-sink-to-kafka.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/M, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#13498 add the doc for cache-prep-stmt
  ticdc/ticdc-sink-to-mysql.md
Labels: translation/done, status/can-merge, status/LGT3, size/XS, area/ticdc, needs-cherry-pick-release-7.0

#7392 statistics: refine format
  statistics.md
Labels: status/LGT2, translation/done, status/can-merge, status/PTAL, size/M, area/planner, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13891 foreign-key: add note about inline references
  foreign-key.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/S, area/sql-infra, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13893 tidb config: add description about proxy protocol
  command-line-flags-for-tidb-configuration.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13653 update description about compatible-kill-query configuration
  tidb-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13920 Add notice for adding index acceleration without support checkpoint.
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS

#13934 tispark: remove the svg image
  tispark-overview.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13892 Describe auto_id_cache = 0 behavior and add link how to address TiKV_pending_task alert
  alert-rules.md
  auto-increment.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, area/sql-infra, sig/diagnosis, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13898 update links; clarify dumpling auto gc setting
  dumpling-overview.md
  glossary.md
  tidb-troubleshooting-map.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13765 ticdc: Fix some ticdc docs master 6.5
  ticdc/ticdc-changefeed-config.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, needs-cherry-pick-release-6.5

#13766 fix ticdc config descriptions in 6.1
  ticdc/manage-ticdc.md
Labels: status/LGT2, translation/doing, status/can-merge, size/S

#13952 learning path: update the link for deployment on k8s
  _index.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, area/web, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#13948 add description about force-init-stats in introduction to statistics
  statistics.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, area/general, size/XS, v7.1

#13957 resource_control: fix resource group related ebnf syntax
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-drop-resource-group.md
  sql-statements/sql-statement-set-resource-group.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13969 update precision of DATETIME and TIMESTAMP values
  data-type-date-and-time.md
Labels: translation/done, status/can-merge, type/bug-fix, size/XS, status/LGT4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13611 chore: migrate to new prow reviewing
  OWNERS
Labels: status/LGT2, translation/no-need, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, first-time-contributor, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13908 ticdc: add ddl detail to bidirectional replication doc
  ticdc/ticdc-bidirectional-replication.md
  ticdc/ticdc-filter.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13947 disable non-prep plan cache
  sql-non-prepared-plan-cache.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, type/compatibility-or-feature-change, v7.1

#13950 sql-plan-replayer: update description about plan replayer zip file GC strategy
  sql-plan-replayer.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, for-release, v7.1

#13871 Update Keywords
  keywords.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M

#13578 ticdc: update scale out config
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/ticdc, needs-cherry-pick-release-7.0

#13705 Add dist task framework introduction doc
  TOC.md
  media/dist-task/dist-task-architect.jpg
  system-variables.md
  tidb-distributed-execution-framework.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, v7.1

#13994 foreign_key: fix typo
  foreign-key.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13962 how-to-run-sysbench: update cmd
  benchmark/benchmark-tidb-using-sysbench.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, area/performance, needs-cherry-pick-release-7.0

#13968 sql-statements: clarify the MySQL compatibility of `LOAD DATA`
  sql-statements/sql-statement-load-data.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#8859 update some desc about auto-analyze
  statistics.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/planner

#13989 update the behavior change about schedule.enable-diagnostic
  pd-configuration-file.md
  releases/release-7.1.0.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, v7.1

#13990 keywords: v7.1 add CLOSE;CONTINUE;CURSOR;DECLARE;ELSEIF;EXIT;FOUND;HA…
  keywords.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, for-release, v7.1

#13991 multirocks related config update
  configure-load-base-split.md
  releases/release-7.1.0.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, for-release, v7.1

#13660 update reference-style links to inline links
  functions-and-operators/expressions-pushed-down.md
  functions-and-operators/json-functions.md
  tidb-lightning/tidb-lightning-data-source.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XL

#13985 configuration: add document for the log.timeout configuration
  releases/release-7.1.0.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, for-release, v7.1

#14016 add some missing rocksdb options
  releases/release-6.2.0.md
  releases/release-7.1.0.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/S, type/compatibility-or-feature-change, for-release, v7.1

#12186 pd-recovery: add the new way to recover
  pd-recover.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/M, area/scheduling, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#14014 ticdc: refine the ticdc changefeed configuration file
  ticdc/ticdc-changefeed-config.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/M, type/compatibility-or-feature-change, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#14017 Revert "sql: GA load data logical mode and add experimental physical mode"
  TOC.md
  basic-features.md
  error-codes.md
  mysql-schema.md
  releases/release-7.0.0.md
  releases/release-7.1.0.md
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-operate-load-data-job.md
  sql-statements/sql-statement-show-load-data.md
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XL, for-release, needs-cherry-pick-release-7.0, v7.1

#14026 Add tidb_server_memory_limit tip
  configure-memory-usage.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, ONCALL

#14031 LOAD DATA: remove two sql statements
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-operate-load-data-job.md
  sql-statements/sql-statement-show-load-data.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, needs-cherry-pick-master, size/L

#14028 update Golang version to 1.19
  hardware-and-software-requirements.md
  pd-control.md
  pd-recover.md
  tidb-control.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.6

#14029 update Golang version to 1.20
  hardware-and-software-requirements.md
  pd-control.md
  pd-recover.md
  tidb-control.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-7.0

#14001 *: refine docs for ddl dist framework
  system-variables.md
  tidb-distributed-execution-framework.md
  tiflash/use-tiflash-mpp-mode.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, v7.1

#13664 cdc: the e2e checksum integrity check functionality
  TOC.md
  functions-and-operators/tidb-functions.md
  system-variables.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-integrity-check.md
Labels: translation/done, status/can-merge, status/LGT3, size/L, type/compatibility-or-feature-change, v7.1

#14015 Add link how to address TiDB_tikvclient_region_err_total
  alert-rules.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, area/engine

#13907 resource-control: add dashboard panel
  TOC.md
  dashboard/continuous-profiling.md
  dashboard/dashboard-cluster-info.md
  dashboard/dashboard-diagnostics-access.md
  dashboard/dashboard-intro.md
  dashboard/dashboard-profiling.md
  dashboard/dashboard-resource-manager.md
  dashboard/dashboard-slow-query.md
  dashboard/dashboard-statement-list.md
  dashboard/top-sql.md
  media/dashboard/dashboard-resource-manager-calibrate-by-hardware.png
  media/dashboard/dashboard-resource-manager-calibrate-by-workload.png
  media/dashboard/dashboard-resource-manager-info.png
  releases/release-7.0.0.md
  releases/release-7.1.0.md
  tidb-resource-control.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, area/diagnosis, v7.1

#13958 lightning: add parameters to make it more stable to import large mount of data
  releases/release-6.2.0.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, area/tidb-lightning, v7.1

#13899 auth, variables: add description about ldap authentication
  security-compatibility-with-mysql.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, type/compatibility-or-feature-change, v7.1

#14043 dashboard: fix a render issue
  dashboard/dashboard-resource-manager.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS

#14044 br: fix a command error
  br/backup-storage-gcs.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, area/br

#14046 tiflash: add description about behavior after executing ALTER DATABASE
  tiflash/create-tiflash-replicas.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#14041 *: update GCP name to Google Cloud
  basic-features.md
  faq/deploy-and-maintain-faq.md
  releases/release-6.3.0.md
  releases/release-7.0.0.md
  tiflash/tiflash-configuration.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S

#14053 auto-random.md: add description about max allocation times
  auto-random.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#14054 Fix doc wrong related with `substring` which can be pushed down now
  predicate-push-down.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#13688 update usage limitation of partitioned-raft-kv
  partitioned-raft-kv.md
Labels: translation/done, status/can-merge, status/LGT3, size/XS, v7.1, needs-cherry-pick-release-7.1

#14064 update absolute links in learning path and others
  _index.md
  dashboard/dashboard-user.md
  dm/task-configuration-file-full.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  ticdc/ticdc-changefeed-config.md
  tidb-lightning/tidb-lightning-configuration.md
  tiflash/tiflash-configuration.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L, for-release

#13967 support openEuler 22.03 LTS SP1 x86
  hardware-and-software-requirements.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, for-release, v7.1

#14068 update hardware-and-software-requirements for v7.1
  hardware-and-software-requirements.md
Labels: status/LGT2, translation/done, status/can-merge, require-LGT1, size/M

#14075 Fix pages linking to the old MySQL Internals Manual
  best-practices/java-app-best-practices.md
  develop/dev-guide-connect-to-tidb.md
  dm/dm-glossary.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/S, needs-cherry-pick-release-7.1

#14073 ticdc: add docs for insecure-skip-verify
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, v7.1, needs-cherry-pick-release-7.1

#14052 *: add a limit for smooth upgrade
  smooth-upgrade-tidb.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, v7.1, needs-cherry-pick-release-7.1

#14078 Revert "Add description on `admin pause ddl jobs` and `admin resume ddl jobs`"
  basic-features.md
  ddl-introduction.md
  releases/release-7.1.0.md
  smooth-upgrade-tidb.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, needs-cherry-pick-release-7.1

#14072 Update cdnfresh.txt for v7.1
  resources/cdnfresh.txt
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#14071 update README for v7.1
  README.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-7.1

#14088 flashback: add alert msg in flashback statement
  sql-statements/sql-statement-flashback-to-timestamp.md
Labels: status/LGT2, translation/done, status/can-merge, needs-cherry-pick-master, size/XS, area/sql-infra, for-release, v7.1

#14087 Update release notes for release-6.6.0
  releases/release-6.6.0.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#13918 basic features: update v7.1 features
  basic-features.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, for-release, v7.1, needs-cherry-pick-release-7.1

#14077 bump tidb version on tiup docs
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, size/L, needs-cherry-pick-release-7.1

#14085 tiup: fix table format
  scale-tidb-using-tiup.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#14084 tiup: fix table format
  scale-tidb-using-tiup.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#14098 update installation package for v7.0.0
  releases/release-7.0.0.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1
