Repository pingcap/docs-cn, pull requests merged in 2023-03, with the labels that each got.

#13161 planner: supply privilege description binding need
  sql-plan-management.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/planner, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13229 TiFlash: Revise the pushdown information
  functions-and-operators/expressions-pushed-down.md
  functions-and-operators/window-functions.md
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/M, area/bigdata, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13233 config: add important cdc configs to server_configs
  config-templates/complex-cdc.yaml
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#11284 *: add instruction for editing config
  pd-configuration-file.md
  tidb-configuration-file.md
  tiflash/tiflash-configuration.md
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, ONCALL, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#11440 add document for DDL
  TOC.md
  ddl-introduction.md
  faq/sql-faq.md
  media/ddl-owner.png
  sql-statements/sql-statement-admin-cancel-ddl.md
  sql-statements/sql-statement-admin-show-ddl.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XL, area/sql-infra, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13236 tikv: add some missing dynamic config items
  dynamic-config.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/engine, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#13249 index: clarifed descriptions about TableReader
  choose-index.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13260 unify the format of system variable titles
  system-variables.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13263 dm: add a link to dm precheck for better user experience
  dm/task-configuration-file-full.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, ONCALL, area/dm, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13234 update description of cdc_checkpoint_high_delay
  ticdc/ticdc-alert-rules.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, type/bug-fix, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13276 tiflash: fix a rendering error
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/bigdata, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13272 grafana-tidb-dashboard: update DDL related metrics
  grafana-tidb-dashboard.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13275 Add description about `SUPER` privilege
  privilege-management.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#11026 tikv-control: make a parameter in right places
  tikv-control.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/M, area/engine, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13297 ticdc-sink-to-mysql: add note about path
  ticdc/ticdc-sink-to-mysql.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13304 sql: update incorrect mysql compatibility info
  sql-statements/sql-statement-update.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, ONCALL

#13013 add more explanation about tiflash encryption
  encryption-at-rest.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/L, area/bigdata, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12868 *: refine statements doc
  dashboard/dashboard-statement-list.md
  media/dashboard/dashboard-statement-other-row.png
  statement-summary-tables.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, sig/diagnosis, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13317 partitioning: change formatting
  partition-pruning.md
  partitioned-table.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12952 sql: add sql statements and document fields of TABLE_STORAGE_STATS
  TOC.md
  information-schema/information-schema-cluster-info.md
  information-schema/information-schema-table-storage-stats.md
  sql-statements/sql-statement-admin-cleanup.md
  sql-statements/sql-statement-admin-recover.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/L, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, add-missing-docs, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13333 resource_control: fix rfc link
  tidb-resource-control.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.6

#13301 sql-statements: add doc of lock tables and unlock tables
  TOC.md
  basic-features.md
  sql-statements/sql-statement-lock-tables-and-unlock-tables.md
  tidb-configuration-file.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, needs-cherry-pick-release-5.0, size/L, area/transaction, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13337 tidb: add proxy-protocol-fallbackable
  command-line-flags-for-tidb-configuration.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.5

#13340 Update the max value of max-thread-count
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, needs-cherry-pick-release-6.5

#13279 add v6.5.1 release notes
  TOC.md
  releases/release-6.5.1.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13335 v6.5: bump up version for v6.5.1
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, size/L

#12297 update the format, command, and output of information schemas
  information-schema/client-errors-summary-by-host.md
  information-schema/client-errors-summary-by-user.md
  information-schema/client-errors-summary-global.md
  information-schema/information-schema-character-sets.md
  information-schema/information-schema-collation-character-set-applicability.md
  information-schema/information-schema-columns.md
  information-schema/information-schema-deadlocks.md
  information-schema/information-schema-metrics-tables.md
  information-schema/information-schema-partitions.md
  information-schema/information-schema-referential-constraints.md
  information-schema/information-schema-sequences.md
  information-schema/information-schema-session-variables.md
  information-schema/information-schema-slow-query.md
  information-schema/information-schema-table-storage-stats.md
  information-schema/information-schema-tidb-servers-info.md
  information-schema/information-schema-tidb-trx.md
  information-schema/information-schema-tiflash-replica.md
  information-schema/information-schema-tikv-region-peers.md
  information-schema/information-schema-tikv-store-status.md
  information-schema/information-schema-user-privileges.md
  information-schema/information-schema-views.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XXL, area/sql-infra, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13362 [Update] new version of JPA adaption
  develop/dev-guide-sample-application-spring-boot.md
Labels: status/LGT2, translation/done, translation/no-need, status/can-merge, size/M, ONCALL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13367 Correct the location of table lock in TOC
  TOC.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13322 pd control: use jq for region check command
  pd-control.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, area/scheduling, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13386 fix the usage of tidb-ctl decoder
  troubleshoot-lock-conflicts.md
Labels: status/LGT1, translation/doing, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13399 conprof: fix version desc
  dashboard/continuous-profiling.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13311 pd control: add service-gc-safepoint command
  pd-control.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, area/scheduling, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13404 dumpling: fix format
  dumpling-overview.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/dumpling, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#10884 add some desc
  dumpling-overview.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/dm, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12777 br: restore json type
  data-type-json.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/doing, status/can-merge, size/XS, area/br, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13395 br: remove an inaccurate prerequisite
  br/backup-and-restore-use-cases.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, ONCALL, area/br

#13420 partitioned-table: fix a command
  partitioned-table.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, area/planner, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13425 update the copyright date to 2023
  templates/copyright.tex
Labels: status/LGT1, translation/done, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13439 Fix the conflict in copyright.tex
  templates/copyright.tex
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#12995 Add cdc tiflash tuning guide
  TOC.md
  media/performance/cdc/cdc-fast-1.png
  media/performance/cdc/cdc-fast-2.png
  media/performance/cdc/cdc-slow.png
  media/performance/tiflash/ch-1tiflash-raft-io-flow-cloud.png
  media/performance/tiflash/ch-2tiflash-op.png
  media/performance/tiflash/ch-2tiflash-raft-io-flow.png
  media/performance/tiflash/tiflash-resource-usage.png
  media/performance/tiflash/tiflash_request_duration_by_type.png
  ticdc-performance-tuning-methods.md
  tiflash-performance-tuning-methods.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, area/performance

#13424 add encode password description for ticdc doc
  ticdc/ticdc-open-api.md
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13450 fix exchange partition
  partitioned-table.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13309 pitr: compatibility between pitr and accelerated indexing
  faq/backup-and-restore-faq.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/br, v7.0

#13313 planner: add the doc for hint
  optimizer-hints.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/planner, type/compatibility-or-feature-change, v7.0

#13381 [TiKV] Enable log recycling by default.
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/engine, type/compatibility-or-feature-change, v7.0

#13398 system-variables: add description for variable `tidb_opt_ordering_index_selectivity_threshold`
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/planner, type/compatibility-or-feature-change, v7.0

#13458 Update Fast DDL compatibility doc description
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, v7.0

#13228 planner: plan cache support subquery
  sql-prepared-plan-cache.md
  system-variables.md
Labels: translation/done, status/can-merge, status/LGT3, size/S, area/planner, type/compatibility-or-feature-change, v7.0

#13348 sql: update the doc about show-config
  sql-statements/sql-statement-show-config.md
Labels: translation/no-need, status/can-merge, status/LGT3, size/XS, area/sql-infra, v7.0

#13303 FastScan GA
  TOC.md
  basic-features.md
  releases/release-6.2.0.md
  releases/release-6.3.0.md
  system-variables.md
  tiflash-620-upgrade-guide.md
  tiflash/use-fastscan.md
Labels: translation/done, status/can-merge, status/LGT3, size/M, area/bigdata, v7.0

#13316 tiflash: add docs about null-aware semi join push down to tiflash
  system-variables.md
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: type/enhancement, translation/done, status/can-merge, status/LGT3, size/XS, type/compatibility-or-feature-change, area/bigdata, v7.0

#13382 add doc for load-based replica read variable
  system-variables.md
Labels: translation/done, status/can-merge, status/LGT3, size/S, area/transaction, type/compatibility-or-feature-change, v7.0

#13449 lightning: set compress-kv-pairs as experimental
  releases/release-6.6.0.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT1, translation/doing, status/can-merge, size/XS, area/tidb-lightning

#13467 copyright: add a white space between copyright symbol and the year
  templates/copyright.tex
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13455 fix rule of PD_miss_peer_region_count
  alert-rules.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13230 ttl: add ttl running tasks sysvar
  system-variables.md
  time-to-live.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/M, type/compatibility-or-feature-change, v7.0

#13464 functions-and-operators: Correct support for SOUNDS LIKE
  functions-and-operators/operators.md
  functions-and-operators/string-functions.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13342 add TiFlash spill doc
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, area/bigdata, v7.0

#13446 *: update document about auto-increment column must be key constraint
  auto-increment.md
  mysql-compatibility.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, v7.0

#13336 *: rename server.snap-max-write-bytes-per-sec
  dynamic-config.md
  tiflash/create-tiflash-replicas.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, for-release, v7.0

#13500 dev: fix minor errors
  clinic/clinic-data-instruction-for-tiup.md
  clinic/quick-start-with-clinic.md
  develop/dev-guide-build-cluster-in-cloud.md
  tidb-binlog/tidb-binlog-faq.md
  tiunimanager/tiunimanager-install-and-maintain.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/M

#13501 resource_control: fix resource group rfc link
  tidb-resource-control.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13405 *: add a note to the `tidb_rc_read_check_ts` system variable
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/transaction, type/compatibility-or-feature-change, v7.0

#13391 lightning: add add-index-by-sql
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/tidb-lightning, v7.0

#13224 ticdc: add open api v2 doc
  TOC.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-open-api.md
Labels: status/LGT2, translation/done, status/can-merge, size/XXL, area/ticdc, v7.0

#13448 ticdc: add index design for cdc storage sink
  ticdc/ticdc-csv.md
  ticdc/ticdc-sink-to-cloud-storage.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/ticdc, v7.0

#13426 add TiFlash spill to disk doc
  TOC.md
  system-variables.md
  tiflash/tiflash-spill-disk.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, type/compatibility-or-feature-change, area/bigdata, v7.0

#13385 sql infra: update system variable changes about enhanced lock waiting model
  releases/release-6.6.0.md
  system-variables.md
  troubleshoot-lock-conflicts.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v7.0

#13341 ticdc: update changefeed scheduler configs
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/ticdc, v7.0

#13218 Add TiFlash disaggregate architecture and S3 support
  TOC.md
  media/tiflash/tiflash-s3.png
  tiflash/tiflash-configuration.md
  tiflash/tiflash-disaggregated-and-s3.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, area/bigdata, v7.0

#13463 Explain the third party means
  develop/dev-guide-third-party-support.md
  develop/dev-guide-third-party-tools-compatibility.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13359 tiflash late materialization
  TOC.md
  system-variables.md
  tiflash/tiflash-late-materialization.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, type/compatibility-or-feature-change, v7.0

#13223 Partition: add key-partiton document
  mysql-compatibility.md
  partitioned-table.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, v7.0

#13339 [TiKV] Introduce `raft-engine.prefill-for-recycle` configuration.
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, v7.0

#13511 release-6.5.1: remove batch update support description for TiCDC
  releases/release-6.5.1.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13445 add docs for derive topn from window
  TOC.md
  blocklist-control-plan.md
  derive-topn-from-window.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, type/compatibility-or-feature-change, v7.0

#13514 dm: add newly added lightning kv configurations
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/dm, for-release, v7.0

#13466 update tikv pushdownlist
  blocklist-control-plan.md
  functions-and-operators/expressions-pushed-down.md
  functions-and-operators/operators.md
  releases/release-6.0.0-dmr.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13310 resource_control: updates some changes about resource group in 7.0
  TOC.md
  functions-and-operators/information-functions.md
  information-schema/information-schema-resource-groups.md
  optimizer-hints.md
  pd-configuration-file.md
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-calibrate-resource.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-drop-resource-group.md
  sql-statements/sql-statement-set-resource-group.md
  sql-statements/sql-statement-show-create-resource-group.md
  system-variables.md
  tidb-resource-control.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XXL, area/sql-infra, type/compatibility-or-feature-change, v7.0

#13524 tiflash-spill-disk: make SQL code stacked
  tiflash/tiflash-spill-disk.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S

#13515 lightning: update the default value of add-index-by-sql to false
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/tidb-lightning, v7.0

#13344 lightning: add load data doc
  TOC.md
  error-codes.md
  mysql-schema.md
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-operate-load-data-job.md
  sql-statements/sql-statement-show-load-data.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, area/tidb-lightning, v7.0

#13332 update plan replayer continuous capture feature
  sql-plan-replayer.md
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/planner, for-release, v7.0

#13525 fix heading levels and wrong anchor link
  sql-plan-replayer.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/planner, v7.0

#13488 sql-statement-alter-table: Beter example for schema dependency
  sql-statements/sql-statement-alter-table.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12138 Added REORGANIZE PARTITION
  mysql-compatibility.md
  partitioned-table.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, area/bigdata, v7.0

#13519 Update docs of SHARD_ROW_ID_BITS
  clustered-indexes.md
  shard-row-id-bits.md
  troubleshoot-hot-spot-issues.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/S, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13534 fix a table issue for PDF generation
  functions-and-operators/expressions-pushed-down.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13533 resource_groups: add description about default resource group
  information-schema/information-schema-resource-groups.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-set-resource-group.md
  tidb-resource-control.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/sql-infra, v7.0

#13537 sysvar: update tidb_dml_batch_size for load data
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/dm, v7.0

#13541 resource control: change resource control to experimental
  system-variables.md
  tidb-resource-control.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, area/sql-infra, v7.0

#13211 metrics: update resource manager panel
  grafana-resource-control-dashboard.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, for-release, v7.0

#13461 Lightning: fix default value in configuration
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/tidb-lightning, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13548 *: update absolute links for learning path and others
  _index.md
  dashboard/dashboard-user.md
  develop/dev-guide-third-party-support.md
  dm/task-configuration-file-full.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  ticdc/ticdc-changefeed-config.md
  tidb-lightning/tidb-lightning-configuration.md
  tiflash/tiflash-configuration.md
Labels: status/LGT1, translation/from-docs, status/can-merge, size/L, v7.0

#13547 *: update readme and pdf refresh list for 7.0
  README.md
  resources/cdnfresh.txt
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, v7.0

#13462 cdc add description about avro float incompatible change
  ticdc/ticdc-avro-protocol.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/ticdc, needs-cherry-pick-release-7.0

#13552 migration: add note about experimental feature for sql-statement-load-data
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-operate-load-data-job.md
  sql-statements/sql-statement-show-load-data.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/tidb-lightning, v7.0, needs-cherry-pick-release-7.0

#13538 bump tiup version to v7.0
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L, v7.0, needs-cherry-pick-release-7.0

#13539 Update the LICENSE
  LICENSE
  README.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XXL, v7.0, needs-cherry-pick-release-7.0

#13543 bump tool versions for v7.0
  br/backup-and-restore-use-cases.md
  dm/quick-start-create-task.md
  pd-control.md
  quick-start-with-tidb.md
  ticdc/deploy-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, for-release, v7.0, needs-cherry-pick-release-7.0

#13503 *: update basic features for 7.0
  basic-features.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/XL, v7.0, needs-cherry-pick-release-7.0

#13551 [Update] tomcat-jdbc version update
  best-practices/java-app-best-practices.md
  develop/dev-guide-connection-parameters.md
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13565 add highlight links to 7.0
  releases/release-6.6.0.md
  releases/release-7.0.0.md
Labels: status/LGT1, translation/from-docs, status/can-merge, requires-version-specific-changes, require-LGT1, size/S, v7.0, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#12746 migration-tools: avoid wide table
  migration-tools.md
  tidb-lightning/troubleshoot-tidb-lightning.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/L, area/migrate, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0
