Repository pingcap/docs-cn, pull requests merged in 2023-02, with the labels that each got.

#12241 *: always enable block cache
  hybrid-deployment-topology.md
  tikv-configuration-file.md
  tune-tikv-memory-performance.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/engine, type/compatibility-or-feature-change, for-release, v6.6

#12869 ALTER TABLE .. CHANGE COLUMS is affected by metadata lock
  metadata-lock.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/sql-infra, needs-cherry-pick-release-6.5

#12644 fix flow-round-by-digit in pd cfg docs
  pd-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, area/scheduling, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12808 v6.0 and v6.2: add a note for docs archiving
  releases/release-6.0.0-dmr.md
  releases/release-6.2.0.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, requires-version-specific-changes, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12828 Update tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12891 online unsafe recovery: fix wrong table name in INFORMATION_SCHEMA.TABLES
  online-unsafe-recovery.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, area/engine, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12898 sysvar: correct a wrong sysvar default value
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, ONCALL, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12888 *: move external storage to dumpling and lightning docs
  br/backup-and-restore-storages.md
  br/external-storage.md
  develop/dev-guide-insert-data.md
  dumpling-overview.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
  tidb-lightning/tidb-lightning-command-line-full.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-data-source.md
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-overview.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, requires-version-specific-changes, size/XL, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12904 sql: Update shard-row-id-bits description for non-clustered-index
  shard-row-id-bits.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12807 system-variables: Add units wherever possible
  system-variables.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12914 security: add TiCDC for certificate reloading descriptions
  enable-tls-between-components.md
Labels: status/LGT2, translation/done, status/can-merge, area/security, needs-cherry-pick-master

#12801 backup: refactor some docs for easier understanding
  br/backup-and-restore-overview.md
  br/backup-and-restore-storages.md
  br/br-pitr-guide.md
  br/br-snapshot-guide.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/M, ONCALL, area/br, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12896 chore: stop uploading media and pdf to aws
  .github/workflows/media.yml
  scripts/upload.py
Labels: status/LGT1, translation/done, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-4.0, require-LGT1, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12927 docs: add limitations of PITR
  br/backup-and-restore-overview.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/br, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12765 tikv: support dynamic modifications on `raftstore.store-io-pool-size`
  dynamic-config.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, v6.6

#12812 Add minimum requirement in arm when deploying TiFlash
  hardware-and-software-requirements.md
  releases/release-6.3.0.md
  tiflash/tiflash-overview.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12673 docs: add tidb_ddl_enable_fast_reorg compatibility with unique index
  system-variables.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12816 add v6.1.4 release notes
  TOC.md
  releases/release-6.1.4.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, for-release, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12681 Add description about `--initialize-sql-file` option
  command-line-flags-for-tidb-configuration.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, type/compatibility-or-feature-change, v6.6

#12924 bump version 6.1.4
  br/backup-and-restore-use-cases.md
  check-before-deployment.md
  develop/dev-guide-proxysql-integration.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/L

#12929 tiflash: add a missing note
  tiflash/create-tiflash-replicas.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/S, area/bigdata

#12776 sync-diff: add description for the new parameter `skip-non-existing-table`
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/M, type/compatibility-or-feature-change, area/sync-diff-inspector, v6.6

#12958 Revert "br: add a warning for br debug"
  br-usage-backup-for-maintain.md
  br/br-usage-backup.md
Labels: status/LGT1, status/LGT2, translation/no-need, status/can-merge, size/XS, area/br

#12653 fix cdc redo log storage configuration
  ticdc/ticdc-sink-to-mysql.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/ticdc, needs-cherry-pick-release-6.1, for-release, v6.6, needs-cherry-pick-release-6.5

#12863 Refine TiDB features document
  basic-features.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, area/general, require-LGT1, size/XL, needs-cherry-pick-release-6.5

#12968 br: fix an incorrect command in log backup flowchart
  media/br/br-log-backup-ts.png
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#11974 *: add foreign key doc
  TOC.md
  constraints.md
  develop/dev-guide-third-party-tools-compatibility.md
  faq/tidb-faq.md
  foreign-key.md
  information-schema/information-schema-referential-constraints.md
  mysql-compatibility.md
  sql-statements/sql-statement-admin-check-table-index.md
  sql-statements/sql-statement-create-table.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, area/sql-infra, type/compatibility-or-feature-change, v6.6

#12638 slow-query: add `Warnings` field to slow log and the slow query table
  identify-slow-queries.md
  information-schema/information-schema-slow-query.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, v6.6

#12693 ticdc: add scale out for kafka changefeed
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/ticdc, v6.6

#12296 integrate lightning into DM
  dm/dm-precheck.md
  dm/monitor-a-dm-cluster.md
  dm/task-configuration-file-full.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, area/dm, v6.6

#12318 support `tidb_enable_plan_replayer` variable
  sql-plan-replayer.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, v6.6

#12811 sql-statements: flashback cluster support through ddl history
  sql-statements/sql-statement-flashback-to-timestamp.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/sql-infra, v6.6

#12865 [TiDB] Add new mode option `prefer-leader` for `tidb_replica_read`.
  develop/dev-guide-use-follower-read.md
  follower-read.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/scheduling, v6.6

#12623 *: remove related document of amend transaction
  latency-breakdown.md
  releases/release-5.0.0-rc.md
  releases/release-5.0.0.md
  releases/release-6.5.0.md
  system-variables.md
  tidb-binlog/tidb-binlog-overview.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, for-release, v6.6

#12093 Add document for enanced pessimistic lock model
  system-variables.md
  troubleshoot-lock-conflicts.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/transaction, type/compatibility-or-feature-change, v6.6

#12634 tidb: add multi-valued index doc
  choose-index.md
  functions-and-operators/json-functions.md
  sql-statements/sql-statement-create-index.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, area/sql-infra, v6.6

#12813 deprecate enable-statistics
  tikv-configuration-file.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/XS, type/compatibility-or-feature-change, for-release, v6.6

#12630 doc: add the doc for (no_)order_index hint
  optimizer-hints.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/planner, v6.6

#12676 sysvar: stabilize `tidb_store_batch_size`
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, v6.6

#12736 planner: binding from history GA user doc
  sql-plan-management.md
  sql-statements/sql-statement-create-binding.md
  sql-statements/sql-statement-drop-binding.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, v6.6

#12921 update system-variables.md: add `mpp_version` and `mpp_exchange_compression_mode`
  explain-mpp.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, area/bigdata, v6.6

#12739 planner: update docs related to plan cache
  sql-prepared-plan-cache.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/planner, v6.6

#12680 remove tidb_enable_concurrent_ddl
  basic-features.md
  releases/release-6.2.0.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, for-release, v6.6

#12817 tidb-dashboard: add doc for creating SQL binding from statement history
  dashboard/dashboard-statement-details.md
  media/dashboard/dashboard-quick-binding-entry-bound.png
  media/dashboard/dashboard-quick-binding-entry-notbound.png
  media/dashboard/dashboard-quick-binding-popup-bound.png
  media/dashboard/dashboard-quick-binding-popup-notbound.png
  media/dashboard/dashboard-statement-detail-v660.png
Labels: status/LGT2, translation/done, status/can-merge, size/M, sig/diagnosis, v6.6

#12974 fix a typo in 6.4.0 release notes
  releases/release-6.4.0.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12688 Update stale_read doc for the support of TiFlash
  as-of-timestamp.md
  develop/dev-guide-use-stale-read.md
  stale-read.md
  tidb-external-ts.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/bigdata, v6.6

#12643 Add docs for gctuner in pd
  pd-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/transaction, type/compatibility-or-feature-change, v6.6

#12677 Add persistent statements summary
  statement-summary-tables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, area/diagnosis, v6.6

#12301 dm: enhance description about error triggering condition
  dm/dm-handle-alerts.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/dm, v6.6

#12683 Support regexp_replace function in tiflash
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/bigdata, v6.6

#12930 ticdc: add `required-acks` configuration
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/ticdc, for-release, v6.6

#12980 fix typo in Deployment FAQs
  faq/deploy-and-maintain-faq.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.5

#12979 fix description of `tidb_enable_ddl`
  system-variables.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#12948 lightning: support compression when sending kv pairs to tikv
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/tidb-lightning, v6.6

#12990 tikv: add raftstore.report-min-resolved-ts-interval
  tikv-configuration-file.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/XS, area/engine, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12963 lightning: introduce a new parameter `header-schema-match` for CSV
  tidb-lightning/tidb-lightning-configuration.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/tidb-lightning, v6.6

#12858 tiup&dm: update a wrong tidb version
  tiup/tiup-component-dm-patch.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/tiup, needs-cherry-pick-release-5.3, area/dm, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12635 add backup faq for flashback
  faq/backup-and-restore-faq.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, ONCALL, area/br, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12998 update tiup ctl:<version> to tiup clt:v<version>
  best-practices/three-nodes-hybrid-deployment.md
  clinic/clinic-data-instruction-for-tiup.md
  dashboard/dashboard-ops-deploy.md
  enable-tls-between-components.md
  migrate-from-tidb-to-mysql.md
  pd-control.md
  replicate-data-to-kafka.md
  scale-tidb-using-tiup.md
  three-data-centers-in-two-cities-deployment.md
  ticdc/deploy-ticdc.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/ticdc-changefeed-overview.md
  tidb-control.md
  tiflash/create-tiflash-replicas.md
  tiflash/tiflash-configuration.md
  tikv-control.md
  tiup/tiup-cluster.md
  troubleshoot-lock-conflicts.md
  troubleshoot-write-conflicts.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, ONCALL, needs-cherry-pick-release-6.5

#13010 TiDB Monitoring Metrics: update key metrics from list to headings
  grafana-tidb-dashboard.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/XL, ONCALL, area/diagnosis, needs-cherry-pick-release-6.5

#12737 support reloading TLS certificates for TiFlash
  enable-tls-between-components.md
Labels: status/LGT2, translation/done, status/can-merge, area/security, size/S, v6.6

#13012 TiCDC scale out: experimental feature
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/ticdc, v6.6

#12682 placementinsql: add the survival preferences docs
  placement-rules-in-sql.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, v6.6

#12988 cloud: update quick start for Serverless Tier cluster creation
  develop/dev-guide-build-cluster-in-cloud.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#13028 sql: add a special keywords section
  keywords.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#13032 stmtsummary: add system vars description
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/diagnosis, v6.6

#12885 *: add tidb_ddl_distribute_reorg item to system-variables
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v6.6

#12857 update document about TTL
  grafana-tidb-dashboard.md
  releases/release-6.5.0.md
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-create-table.md
  system-variables.md
  time-to-live.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, for-release, v6.6

#13033 *: update table name to tidb_background_subtask_history
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, v6.6

#13034 tikv config: remove note of grpc-compression-type
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/engine, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#12686 planner: prepared plan cache support limit
  sql-prepared-plan-cache.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/planner, type/compatibility-or-feature-change, v6.6

#10680 Add new syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n'
  sql-statements/sql-statement-admin-show-ddl.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/M, area/sql-infra, ONCALL, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#13046 TiFlash config: fix the value options of logger.level
  tiflash/tiflash-configuration.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, area/bigdata, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#12997 sysvar: introduce a new variable `tidb_index_join_double_read_penalty_cost_rate`
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, type/compatibility-or-feature-change, v6.6

#12959 add more information to debug TTL
  grafana-tidb-dashboard.md
  media/ttl/delete-fast.png
  media/ttl/insert-fast.png
  media/ttl/scan-fast.png
  mysql-schema.md
  time-to-live.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, for-release, v6.6

#12972 sysvar: change prepared-plan-cache variable names
  releases/release-6.3.0.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, require-LGT1, type/compatibility-or-feature-change, for-release, v6.6

#12655 sql-infra: document for resource control feature
  TOC.md
  grafana-resource-control-dashboard.md
  grafana-tikv-dashboard.md
  information-schema/information-schema-processlist.md
  information-schema/information-schema-resource-groups.md
  mysql-compatibility.md
  privilege-management.md
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-create-user.md
  sql-statements/sql-statement-drop-resource-group.md
  sql-statements/sql-statement-show-create-resource-group.md
  sql-statements/sql-statement-show-privileges.md
  system-variables.md
  tidb-resource-control.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/XXL, area/sql-infra, type/compatibility-or-feature-change, v6.6

#13045 explain for connection: fix the compatibility with MySQL
  sql-statements/sql-statement-explain.md
Labels: status/LGT2, translation/from-docs, status/can-merge, needs-cherry-pick-release-3.0, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.0

#13063 update default value of block-size
  tikv-configuration-file.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, first-time-contributor, size/XS, type/compatibility-or-feature-change, for-release, v6.6

#13072 TiUniManager: remove redundant character
  tiunimanager/tiunimanager-manage-clusters.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, area/tunimanager, needs-cherry-pick-release-6.5

#12947 lightning/br/dumpling: add session-token to external storage url
  br/backup-and-restore-overview.md
  br/backup-and-restore-storages.md
  br/br-incremental-guide.md
  br/br-pitr-manual.md
  br/br-snapshot-guide.md
  br/use-br-command-line-tool.md
  dumpling-overview.md
  migrate-aurora-to-tidb.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-large-mysql-to-tidb.md
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-lightning/tidb-lightning-command-line-full.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-data-source.md
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-logical-import-mode-usage.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/tidb-lightning, v6.6, needs-cherry-pick-release-6.6

#13077 block-size default value change
  tikv-configuration-file.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, type/compatibility-or-feature-change, for-release, v6.6, needs-cherry-pick-release-6.6

#13031 br: change the compatiblity table
  br/backup-and-restore-overview.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/br, for-release, v6.6, needs-cherry-pick-release-6.6

#13081 upgrade: move compatibility changes to a more noticeable position
  upgrade-tidb-using-tiup.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13078 sql-statement: update `flashback cluster` related msg
  sql-statements/sql-statement-flashback-to-timestamp.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, for-release, v6.6, needs-cherry-pick-release-6.6

#13080 system-variables: Correct links for tidb_enable_paging
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13050 sql: add missing dynamic privileges and update optm lock version
  faq/sql-faq.md
  privilege-management.md
Labels: status/LGT1, status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13096 update _index.md for v6.6
  _index.md
Labels: status/LGT1, translation/from-docs, status/can-merge, size/L, for-release, v6.6

#13009 *: disable telemetry by default
  dashboard/dashboard-intro.md
  pd-configuration-file.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  system-variables.md
  telemetry.md
  tidb-configuration-file.md
  tispark-overview.md
  tiup/tiup-command-telemetry.md
  tiup/tiup-overview.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, for-release, v6.6, needs-cherry-pick-release-6.6

#12973 bump version 6.6 tiup
  production-deployment-using-tiup.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/deploy-upgrade-maintain, for-release, v6.6, needs-cherry-pick-release-6.6

#12960 v6.6: bump version for tools
  br/backup-and-restore-use-cases.md
  dm/quick-start-create-task.md
  pd-control.md
  quick-start-with-tidb.md
  ticdc/deploy-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, for-release, v6.6, needs-cherry-pick-release-6.6

#13087 Add priviledge info for dashboard-statement-details.md
  dashboard/dashboard-statement-details.md
  dashboard/dashboard-user.md
Labels: status/LGT2, status/can-merge, requires-version-specific-changes, size/S, for-release, v6.6, needs-cherry-pick-release-6.6

#12967 basic-features: updates for v6.6
  basic-features.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/XL, for-release, v6.6, needs-cherry-pick-release-6.6

#12652 releases: add 6.6.0 release notes
  TOC.md
  _index.md
  releases/release-6.6.0.md
  releases/release-notes.md
  releases/release-timeline.md
  system-variables.md
  tidb-resource-control.md
  tikv-configuration-file.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT2, translation/done, status/can-merge, size/XXL, for-release, v6.6, needs-cherry-pick-release-6.6

#13070 Update cdnfresh.txt for v6.6
  resources/cdnfresh.txt
Labels: status/LGT2, translation/no-need, status/can-merge, size/XS, for-release, v6.6

#13104 Fix a wrong link in partitioned-table.md
  partitioned-table.md
Labels: status/LGT1, contribution, status/can-merge, translation/welcome, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13108 update download link for v6.5
  releases/release-6.5.0.md
Labels: status/LGT1, translation/no-need, status/can-merge, needs-cherry-pick-master, size/XS, needs-cherry-pick-release-6.6

#13112 v6.6: add dmr to toc
  TOC.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, for-release, v6.6, needs-cherry-pick-release-6.6

#13114 chore: Update pdf list and flush workflow
  .github/workflows/flush.yaml
  resources/cdnfresh.txt
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/S

#13111 develop: use cross-references link instead of detailed tables
  develop/dev-guide-schema-design-overview.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/M, ONCALL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13071 lightning: add a limitation during data migration
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/tidb-lightning, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13101 tiflash: update some description in troubleshooting
  tiflash/troubleshoot-tiflash.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/bigdata, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12986 Update JDBC information
  best-practices/java-app-best-practices.md
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-connection-parameters.md
  faq/tidb-faq.md
  tispark-overview.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12987 Correct MySQL Shell/Client section
  develop/dev-guide-connect-to-tidb.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/M, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12978 add partitioned raft kv page
  TOC.md
  partitioned-raft-kv.md
  releases/release-6.6.0.md
  tikv-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/L, area/engine, v6.6, needs-cherry-pick-release-6.6

#12527 add tidb dr solution summary doc and multi-replica based DR solution docs
  TOC.md
  dr-backup-restore.md
  dr-multi-replica.md
  dr-secondary-cluster.md
  dr-solution-introduction.md
  media/dr/bdr-ticdc.png
  media/dr/br-dr.png
  media/dr/dr-backup-and-restore.png
  media/dr/dr-ticdc-secondary-cluster.png
  media/dr/multi-replica-dr.png
  media/dr/rto-rpo.png
  media/dr/ticdc-dr.png
  media/dr/ticdc-multi-replica-dr.png
  media/dr/tidb-architecture.png
Labels: status/LGT2, contribution, translation/done, status/can-merge, first-time-contributor, size/XXL, area/br, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13139 chore: update pr template for v7.0
  .github/pull_request_template.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1

#12953 *: update tidb minimal topology from 3 to 2
  config-templates/complex-mini.yaml
  config-templates/simple-mini.yaml
  minimal-deployment-topology.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, ONCALL, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12810 Add UUID best practices
  README.md
  TOC.md
  best-practices/uuid.md
  media/best-practices/uuid_keyviz.png
Labels: type/enhancement, status/LGT1, translation/from-docs, area/best-practices, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#13140 online unsafe recovery: use a numbered procedure for step 3
  online-unsafe-recovery.md
Labels: type/enhancement, status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/S, area/engine, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12086 three-dc-local-read: set tidb_replica_read as closest replicas
  best-practices/three-dc-local-read.md
Labels: type/enhancement, status/LGT2, translation/done, area/best-practices, status/can-merge, requires-version-specific-changes, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12809 tiup-mirror: Extend and update
  tiup/tiup-mirror.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/from-docs, status/can-merge, size/L, area/tiup, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5

#13166 fix format and admonitions in dr-multi-replica
  dr-multi-replica.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13160 add minimal storage for pd and tidb
  minimal-deployment-topology.md
Labels: type/enhancement, status/LGT1, status/LGT2, status/can-merge, size/XS, ONCALL, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13175 alert rule: fix the rule of TiKV_scheduler_command_duration_seconds
  alert-rules.md
Labels: status/LGT1, translation/done, status/can-merge, type/bug-fix, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13187 tiny update foreign key doc
  constraints.md
  foreign-key.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.6

#13186 fix the rule of NODE_memory_used_more_than_80%
  alert-rules.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12654 fix cdc overview and some release notes
  releases/release-6.5.0.md
  ticdc/ticdc-overview.md
Labels: type/enhancement, status/LGT1, status/LGT2, translation/done, status/can-merge, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13049 clinic: add Diag repo link
  clinic/clinic-collect-sql-query-plan.md
  clinic/clinic-data-instruction-for-tiup.md
  clinic/clinic-introduction.md
  clinic/clinic-report.md
  clinic/clinic-user-guide-for-tiup.md
  clinic/quick-start-with-clinic.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/S, area/clinic, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13065 auto-random: support composite clustered primary key
  auto-random.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13169 add missing TiKV configuration items
  releases/release-6.6.0.md
  tikv-configuration-file.md
  tune-tikv-memory-performance.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, requires-version-specific-changes, size/XL, area/engine, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#12897 *: update description about getting support resources
  TOC.md
  alert-rules.md
  clinic/clinic-introduction.md
  dashboard/dashboard-faq.md
  dm/dm-error-handling.md
  non-transactional-dml.md
  sql-plan-management.md
  support.md
  tidb-binlog/monitor-tidb-binlog-cluster.md
  tidb-binlog/troubleshoot-tidb-binlog.md
  troubleshoot-data-inconsistency-errors.md
Labels: status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13189 Refine an expression in tidb-resource-control.md
  tidb-resource-control.md
Labels: type/enhancement, status/LGT1, contribution, status/can-merge, translation/welcome, require-LGT1, size/XS, needs-cherry-pick-release-6.6

#13192 v6.1: bump version for v6.1.5
  br/backup-and-restore-use-cases.md
  check-before-deployment.md
  develop/dev-guide-proxysql-integration.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, area/general, size/L

#13217 chore: change pdf list; change pdf update date
  .github/workflows/flush.yaml
  resources/cdnfresh.txt
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#13216 update the note in follower read
  follower-read.md
Labels: status/LGT2, translation/no-need, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6
