Repository pingcap/docs-cn, pull requests merged in 2023-06, with the labels that each got.

#14102 release notes: fix broken link
  releases/release-7.1.0.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-7.1

#14106 Update system-variables.md
  system-variables.md
Labels: status/LGT2, contribution, translation/no-need, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#14086 Add a known issue for TiFlash mpp.
  tiflash/use-tiflash-mpp-mode.md
Labels: status/LGT1, translation/doing, status/can-merge, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#14089 sql: add more descriptions about create table parameters
  auto-increment.md
  auto-random.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-7.1

#14104 release note: update configuration item
  releases/release-7.1.0.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, needs-cherry-pick-release-7.1

#14107 lightning: change english names to chinese
  TOC.md
  dm/task-configuration-file-full.md
  migration-tools.md
  releases/release-6.2.0.md
  releases/release-6.6.0.md
  releases/release-7.0.0.md
  tidb-lightning/deploy-tidb-lightning.md
  tidb-lightning/tidb-lightning-command-line-full.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-error-resolution.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-logical-import-mode-usage.md
  tidb-lightning/tidb-lightning-logical-import-mode.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: type/enhancement, status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/L, area/tidb-lightning, needs-cherry-pick-release-7.1

#14119 fix: jdbc 3.0.33 fixed some bugs, recommend the latest version
  develop/dev-guide-choose-driver-or-orm.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#14121 bump version for v7.1
  dm/maintain-dm-using-tiup.md
  information-schema/information-schema-tidb-servers-info.md
  post-installation-check.md
  quick-start-with-tidb.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-open-api-v2.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, needs-cherry-pick-release-7.1

#14062 tidb: rename products
  TOC.md
  br/backup-and-restore-overview.md
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-create-database.md
  develop/dev-guide-create-secondary-indexes.md
  develop/dev-guide-create-table.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-sample-application-django.md
  develop/dev-guide-sample-application-golang.md
  develop/dev-guide-sample-application-java.md
  develop/dev-guide-sample-application-python.md
  develop/dev-guide-sample-application-spring-boot.md
  develop/dev-guide-tidb-crud-sql.md
  develop/dev-guide-update-data.md
  ecosystem-tool-user-guide.md
  releases/release-5.2.0.md
  releases/release-6.0.0-dmr.md
  releases/release-7.0.0.md
  releases/release-7.1.0.md
  tidb-in-kubernetes.md
  tidb-operator-overview.md
  tiflash-performance-tuning-methods.md
  time-to-live.md
  tiunimanager/tiunimanager-release-1.0.0.md
Labels: status/LGT2, translation/doing, status/can-merge, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#14134 lightning: refine comment format in the config file
  tidb-lightning/tidb-lightning-configuration.md
  tidb-limitations.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/M, ONCALL, area/tidb-lightning, needs-cherry-pick-release-7.1

#14118 4.0: update the usage for self-hosted deployment
  ecosystem-tool-user-guide.md
  tidb-in-kubernetes.md
  tidb-operator-overview.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#14146 v6.6: rename TiDB Cloud Serverless Tier to TiDB Serverless
  time-to-live.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#14148 lightning: change english names to chinese
  br/backup-and-restore-overview.md
  dm/dm-precheck.md
  dm/task-configuration-file-full.md
  ecosystem-tool-user-guide.md
  faq/backup-and-restore-faq.md
  migrate-large-mysql-to-tidb.md
  releases/release-6.2.0.md
  releases/release-6.6.0.md
  releases/release-7.0.0.md
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-glossary.md
  tidb-lightning/tidb-lightning-logical-import-mode-usage.md
  tidb-lightning/tidb-lightning-logical-import-mode.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tidb-lightning/tidb-lightning-prechecks.md
  tidb-lightning/tidb-lightning-requirements.md
Labels: type/enhancement, translation/no-need, require-LGT1, size/L, area/tidb-lightning, needs-cherry-pick-release-7.1, approved, lgtm

#14151 Update tidb-lightning-physical-import-mode.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm

#14157 remove experimental note in tidb_enable_resource_control
  system-variables.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm

#14159 fix broken links in release notes
  releases/release-6.1.6.md
  releases/release-6.5.2.md
Labels: translation/done, type/bug-fix, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#14153 Update tidb-lightning-physical-import-mode.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: type/enhancement, translation/done, size/XS, area/tidb-lightning, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#14173 Modify ticdc 7.1 release note
  releases/release-7.1.0.md
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, v7.1, needs-cherry-pick-release-7.1, approved, lgtm

#14174 ticdc: remove only-output-updated-columns from v7.0 and earlier versions
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, approved, lgtm

#14027 update ticdc alert rule
  ticdc/ticdc-alert-rules.md
Labels: status/LGT1, translation/doing, size/S, ONCALL, area/ticdc, needs-cherry-pick-release-7.1, approved, lgtm

#14160 tikv,pd: add config of min-resolved-ts
  pd-configuration-file.md
  tikv-configuration-file.md
Labels: translation/doing, requires-version-specific-changes, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#13956 ticdc: update storage sink doc
  ticdc/ticdc-sink-to-cloud-storage.md
Labels: translation/doing, size/M, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#14208 update ticdc failed changefeed gc mechanism description
  ticdc/ticdc-changefeed-overview.md
Labels: type/enhancement, translation/done, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#14213 Update task-configuration-file-full.md
  dm/task-configuration-file-full.md
Labels: translation/done, translation/no-need, type/bug-fix, size/XS, ONCALL, area/dm, needs-cherry-pick-release-7.1, approved, lgtm

#14207 add description of stale read metrics
  grafana-tidb-dashboard.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, approved, lgtm

#14186 tikv-control: support the Flashback command trigger
  grafana-tikv-dashboard.md
  pd-control.md
  sql-statements/sql-statement-flashback-to-timestamp.md
  tikv-control.md
Labels: translation/done, size/M, approved, lgtm

#14168 add v6.5.3 release notes
  TOC.md
  releases/release-6.5.3.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#14223 bump versions to v6.5.3
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/from-docs, size/L, approved, lgtm

#14235 fix deploy-ticdc
  ticdc/deploy-ticdc.md
Labels: translation/doing, type/bug-fix, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#14243 fix wrong sha256 checksum
  download-ecosystem-tools.md
  pd-control.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#12571 functions-and-operators: Improve format, add vitess_hash
  functions-and-operators/date-and-time-functions.md
  functions-and-operators/tidb-functions.md
Labels: type/enhancement, status/LGT1, translation/from-docs, needs-cherry-pick-release-5.0, size/L, area/sql-infra, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#13942 *: add TiDB roadmap
  TOC.md
  _index.md
  tidb-roadmap.md
Labels: translation/from-docs, requires-version-specific-changes, size/XL, approved, lgtm

#14259 add roadmap absolute link to toc and index
  TOC.md
  _index.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, approved, needs-1-more-lgtm, lgtm

#14051 update ticdc acl
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/doing, type/bug-fix, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14190 Update Warning Section For FastScan
  tiflash/use-fastscan.md
Labels: type/enhancement, translation/doing, size/M, area/bigdata, needs-cherry-pick-release-7.1, approved, lgtm

#14258 lightning: refined description about duplicate-resolution
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, type/bug-fix, size/S, area/tidb-lightning, needs-cherry-pick-release-7.1, approved, lgtm

#14260 lightning: fix a wrong solution in lightning faq
  tidb-lightning/tidb-lightning-faq.md
Labels: translation/doing, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, approved, needs-1-more-lgtm, lgtm

#14275 v7.1: remove the support info of optimize-filters-for-memory
  releases/release-7.1.0.md
  tikv-configuration-file.md
Labels: translation/done, size/S, ONCALL, approved, needs-1-more-lgtm, lgtm

#13895 update ticdc faq
  ticdc/ticdc-faq.md
Labels: type/enhancement, status/LGT1, translation/doing, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#14282 Change the description for max_execution_time.
  develop/dev-guide-timeouts-in-tidb.md
  system-variables.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm

#14283 ticdc: fix changefeed config doc
  ticdc/ticdc-changefeed-config.md
Labels: translation/doing, size/S, approved, lgtm

#14291 *: remove the limit on single column data size
  data-type-string.md
  tidb-limitations.md
Labels: translation/done, type/bug-fix, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14045 change default value of `tidb_remove_orderby_in_subquery` to true
  system-variables.md
Labels: status/LGT1, translation/done, size/XS, type/compatibility-or-feature-change, v7.2, approved, lgtm

#14205 planner: update the doc of SPM
  optimizer-hints.md
  sql-plan-management.md
Labels: translation/done, size/L, area/planner, needs-cherry-pick-release-7.1, v7.2, approved, lgtm

#14202 system-variables: add doc for tidb_expensive_txn_time_threshold
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, v7.2, approved, lgtm

#14182 add new changefeed level config
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, area/ticdc, for-release, v7.2, approved, lgtm

#14234 br: support access by azure sas token
  br/backup-and-restore-storages.md
Labels: translation/done, size/S, v7.2, approved, lgtm

#14289 cdc: add ticdc integrity check golang implementation explanation.
  ticdc/ticdc-integrity-check.md
Labels: type/enhancement, translation/doing, size/M, area/ticdc, needs-cherry-pick-release-7.1, approved, lgtm

#14188 tiflash: add doc for tiflash pipeline model
  TOC.md
  media/tiflash/tiflash-pipeline-model.png
  system-variables.md
  tiflash/tiflash-pipeline-model.md
Labels: translation/done, size/L, v7.2, approved, lgtm

#14172 add "latin1" encoding support for lightning
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, size/XS, area/tidb-lightning, v7.2, approved, lgtm

#14232 dm: add description about strict-optimistic-shard-mode
  dm/feature-shard-merge-optimistic.md
  dm/task-configuration-file-full.md
Labels: translation/done, size/XS, v7.2, approved, needs-1-more-lgtm, lgtm

#14199 Add description on `admin pause ddl jobs` and `admin resume ddl jobs`
  TOC.md
  ddl-introduction.md
  error-codes.md
  sql-statements/sql-statement-admin-pause-ddl.md
  sql-statements/sql-statement-admin-resume-ddl.md
  sql-statements/sql-statement-admin-show-ddl.md
  sql-statements/sql-statement-admin.md
Labels: contribution, translation/done, size/L, v7.2, approved, lgtm

#14042 `FIRST_VALUE` and `LAST_VALUE` pushdown
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: translation/done, size/XS, area/bigdata, v7.2, approved, lgtm

#14274 v7.2: Update the support info of optimize-filters-for-memory
  releases/release-7.1.0.md
  tikv-configuration-file.md
Labels: translation/done, size/XS, for-release, v7.2, approved, needs-1-more-lgtm, lgtm

#14309 migration: add MyLoader version requirement
  migrate-from-tidb-to-mysql.md
Labels: translation/done, size/XS, area/migrate, ONCALL, area/tidb-lightning, needs-cherry-pick-release-7.1, approved, lgtm

#14227 Add description about check constraint
  constraints.md
  sql-statements/sql-statement-create-table.md
Labels: translation/done, size/M, area/sql-infra, v7.2, approved, lgtm

#14185 add document for system variable "tidb_enable_fast_table_check"
  system-variables.md
Labels: translation/doing, size/S, v7.2, approved, lgtm

#14278 system-variables: update upper limit for `last_insert_id`
  system-variables.md
Labels: translation/done, size/XS, v7.2, approved, lgtm

#14242 resource_control: add runaway queries
  error-codes.md
  information-schema/information-schema-resource-groups.md
  mysql-schema.md
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-drop-resource-group.md
  tidb-resource-control.md
Labels: translation/done, size/L, area/sql-infra, v7.2, approved, lgtm

#14221 add system variable tidb_analyze_skip_column_types
  statistics.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, v7.2, approved, lgtm

#14196 explicitly mention mysql 8.0 in MySQL compatibility
  mysql-compatibility.md
Labels: translation/done, size/XS, v7.2, approved, lgtm

#14187 *: add a page and related description for the Optimizer Fix Control
  TOC.md
  control-execution-plan.md
  optimizer-fix-controls.md
  system-variables.md
Labels: translation/done, size/M, for-release, needs-cherry-pick-release-7.1, v7.2, approved, lgtm

#14176 lightning: add doc for send-kv-size
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, area/tidb-lightning, v7.2, approved, lgtm

#14316 sql: correct SELECT statement
  read-historical-data.md
Labels: translation/done, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#13993 lightning: refine some TiDB Lightning docs
  dm/dm-open-api.md
  migrate-aurora-to-tidb.md
  tidb-lightning/tidb-lightning-faq.md
Labels: type/enhancement, status/LGT1, translation/done, size/L, area/tidb-lightning, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14308 tikv: update the default value of compaction-guard-min-output-file-si…
  tikv-configuration-file.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, v7.2, approved, needs-1-more-lgtm, lgtm

#14326 lightning: correct send-kv-pairs value
  tidb-lightning/tidb-lightning-configuration.md
Labels: type/enhancement, translation/no-need, area/tidb-lightning, approved, needs-1-more-lgtm, lgtm

#14327 Update dumpling-overview.md
  dumpling-overview.md
Labels: translation/done, size/XS, area/dumpling, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14329 sql: update optimizer-fix-controls version
  optimizer-fix-controls.md
Labels: translation/no-need, size/XS, area/sql-infra, approved, needs-1-more-lgtm, lgtm

#14331 br: add s3 params that were mistakenly deleted during refactor
  br/backup-and-restore-storages.md
Labels: translation/doing, size/XS, area/br, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm

#14315 resource_control: update bind to default resource group
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-set-resource-group.md
Labels: translation/done, size/XS, area/sql-infra, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14342 chore: add v7.2 to dispatch.yml
  .github/workflows/dispatch.yml
Labels: translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14317 tidb: update the default value of variable `tidb_enable_non_prepared_plan_cache`
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14306 turn on lite-init-stats and force-init-stats by default
  statistics.md
  tidb-configuration-file.md
Labels: translation/done, size/S, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14318 system-variables: add description for `tidb_opt_enable_cte_mpp_shared_execution`
  system-variables.md
Labels: translation/done, size/S, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14320 sql: add switch for check constraint
  constraints.md
  system-variables.md
Labels: translation/done, size/S, area/sql-infra, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14183 data import: add IMPORT INTO stmt
  TOC.md
  error-codes.md
  mysql-schema.md
  privilege-management.md
  sql-statements/sql-statement-cancel-import-job.md
  sql-statements/sql-statement-import-into.md
  sql-statements/sql-statement-show-import-job.md
  system-variables.md
  tidb-configuration-file.md
  tidb-distributed-execution-framework.md
Labels: translation/done, size/XL, type/compatibility-or-feature-change, area/dm, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14328 add runtime filter session variable
  system-variables.md
Labels: translation/doing, size/S, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14312 rocksdb.*cf: supply descriptions on `ttl` and `periodic-compaction-seconds`.
  tikv-configuration-file.md
Labels: translation/from-docs, size/S, area/engine, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14343 v7.2.0: update v7.2 index page link
  _index.md
Labels: translation/done, size/M, for-release, v7.2, approved, needs-1-more-lgtm, lgtm

#14354 Update cdnfresh.txt for v7.2
  resources/cdnfresh.txt
Labels: translation/no-need, approved, needs-1-more-lgtm, lgtm

#14198 ticdc: add kafka oauth configurations
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, size/S, area/ticdc, needs-cherry-pick-release-6.5, approved, lgtm, needs-cherry-pick-release-7.2

#14271 tidb-lightning: add 50 TB data import best practices
  TOC.md
  tidb-lightning/data-import-best-practices.md
Labels: translation/done, area/best-practices, first-time-contributor, size/L, area/tidb-lightning, approved, lgtm, needs-cherry-pick-release-7.2

#14337 cdc: add ticdc checksum verification sample
  TOC.md
  ticdc/ticdc-avro-checksum-verification.md
  ticdc/ticdc-integrity-check.md
Labels: translation/doing, size/XXL, area/ticdc, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14236 TiDB features: add the v7.2 column
  basic-features.md
Labels: translation/done, size/XL, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14154 Add v7.2.0 release notes
  TOC.md
  releases/release-7.2.0.md
  releases/release-notes.md
  releases/release-timeline.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/XL, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14338 bump tidb and tiup version to 7.2.0
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-open-api-v2.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/doing, first-time-contributor, size/L, for-release, v7.2, approved, lgtm, needs-cherry-pick-release-7.2

#14353 fix cdc changefeed config error
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14371 release-7.1.0: update package downloading link
  releases/release-7.1.0.md
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14375 update the supported macos version
  hardware-and-software-requirements.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.2

#14310 pd: bugfix for the descriptions on `Slow Score`.
  best-practices/pd-scheduling-best-practices.md
Labels: translation/from-docs, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.2

#14376 add the link of v7.2 release notes to TiDB roadmap
  README.md
  tidb-roadmap.md
Labels: translation/done, size/XS, approved, lgtm
