Repository pingcap/docs-cn, pull requests merged in 2023-11, with the labels that each got.

#15343 tidb-resource-control: Add info about unbind
  tidb-resource-control.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15257 br: update restriction of ratelimit and concurrency
  br/br-auto-tune.md
  br/br-snapshot-guide.md
Labels: type/enhancement, translation/doing, size/XS, area/br, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15359 global sort is experimental in v7.4
  releases/release-7.4.0.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.4

#15357 add snappy restriction note
  dumpling-overview.md
  sql-statements/sql-statement-import-into.md
  storage-engine/titan-overview.md
  ticdc/ticdc-sink-to-kafka.md
  tidb-lightning/tidb-lightning-data-source.md
  tidb-lightning/troubleshoot-tidb-lightning.md
  tikv-configuration-file.md
  tune-tikv-memory-performance.md
Labels: translation/done, size/M, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15303 mysql-schema: add description for MDL related table
  mysql-schema.md
  sql-statements/sql-statement-admin.md
  sql-statements/sql-statement-show-table-next-rowid.md
Labels: translation/done, size/M, area/sql-infra, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15378 Add FLOAT4, FLOAT8 and MIDDLEINT to the docs
  keywords.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15379 Add deprecate-integer-display-length to TIDB Config
  tidb-configuration-file.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15368 update TiKV hardware requirements
  best-practices/massive-regions-best-practices.md
  hardware-and-software-requirements.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15382 tikv: modify the recommend disk size of tikv from 2TB to 4TB
  geo-distributed-deployment-topology.md
  hardware-and-software-requirements.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15392 ticdc: remove source id desciption
  ticdc/ticdc-bidirectional-replication.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15393 fix the operator info
  correlated-subquery-optimization.md
  explain-subqueries.md
Labels: translation/from-docs, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15390 server recommendations: add a note for production environment
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15365 tikv: add the user's guide of stale read and safe ts
  TOC.md
  grafana-tidb-dashboard.md
  grafana-tikv-dashboard.md
  media/stale-read/example-ops.png
  media/stale-read/example-ts-gap.png
  media/stale-read/metrics-hit-miss.png
  media/stale-read/metrics-ops.png
  media/stale-read/traffic.png
  releases/release-6.5.4.md
  releases/release-7.1.2.md
  releases/release-7.3.0.md
  stale-read.md
  tikv-control.md
  troubleshoot-stale-read.md
Labels: translation/from-docs, size/XL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15347 Add a new doc about TSO
  TOC.md
  tso.md
Labels: translation/from-docs, area/general, size/L, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15391 mark the support of foreign key as experimental
  basic-features.md
  constraints.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  foreign-key.md
  releases/release-6.6.0.md
Labels: translation/from-docs, size/S, area/develop, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15420 information-schema.md: add `CHECK_CONSTRAINTS`
  information-schema/information-schema.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15329 dm: add update validation description
  dm/dm-continuous-data-validation.md
Labels: translation/done, size/S, approved, lgtm, v7.5

#15361 cdc: add ticdc sql mode config
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-ddl.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, needs-1-more-lgtm, lgtm, v7.5

#15375 add tidb_gogc_tuner_max_value and tidb_gogc_tuner_min_value
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.5

#15348 v7.5 supports Rocky Linux 9.1
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, for-release, approved, needs-1-more-lgtm, lgtm, v7.5

#15310 deprecate Mydumper
  dumpling-overview.md
  ecosystem-tool-user-guide.md
  mydumper-overview.md
Labels: needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, v7.5

#15296 deprecate Mydumper and tikv-importer
  binary-package.md
  develop/dev-guide-timeouts-in-tidb.md
  dumpling-overview.md
  ecosystem-tool-user-guide.md
  migration-overview.md
  tidb-lightning/monitor-tidb-lightning.md
  tidb-lightning/tidb-lightning-command-line-full.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
  tidb-lightning/troubleshoot-tidb-lightning.md
  tidb-troubleshooting-map.md
Labels: translation/from-docs, size/L, type/compatibility-or-feature-change, area/develop, approved, needs-1-more-lgtm, lgtm, v7.5

#15395 sql: pause and resume ddl jobs GA
  ddl-introduction.md
  sql-statements/sql-statement-admin-pause-ddl.md
  sql-statements/sql-statement-admin-resume-ddl.md
Labels: contribution, translation/done, size/S, approved, lgtm, v7.5

#15270 tidb: remove fast and incremental analyze
  grafana-tidb-dashboard.md
  releases/release-7.3.0.md
  sql-statements/sql-statement-analyze-table.md
  sql-statements/sql-statement-show-variables.md
  statistics.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.5

#15364 cdc: update description about partition dispatcher and add column selector descriptions.
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.5

#15432 fix a typo
  releases/release-7.4.0.md
Labels: translation/no-need, type/bug-fix, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4

#15336 tidb: `tidb_service_scope` GA
  system-variables.md
  tidb-distributed-execution-framework.md
Labels: translation/done, size/XS, area/sql-infra, approved, needs-1-more-lgtm, lgtm, v7.5

#15335 system-variable: add tidb_enable_async_merge_global_stats
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v7.5

#15305 br: public parameter `--ignore-stats` to backup statistic data
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
  faq/backup-and-restore-faq.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, area/br, approved, lgtm, v7.5

#15309 dm: add error binlog filter description
  dm/dm-binlog-event-filter.md
Labels: translation/done, size/M, area/dm, approved, lgtm, v7.5

#15333 system-variable: update variable for analyze
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v7.5

#15389 update analyze concurrency for statistics
  media/analyze_concurrency.png
  statistics.md
Labels: translation/done, size/S, approved, lgtm, v7.5

#15404 remove TiSpark from offline package
  binary-package.md
  download-ecosystem-tools.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v7.5

#15190 *: refine placement rule in sql docs
  TOC.md
  placement-rules-in-sql.md
  releases/release-6.3.0.md
  releases/release-6.6.0.md
  sql-statements/sql-statement-alter-placement-policy.md
  sql-statements/sql-statement-alter-range.md
  sql-statements/sql-statement-create-placement-policy.md
Labels: type/enhancement, translation/done, size/XXL, for-release, approved, lgtm, v7.5

#15443 include limitation of LIKE when it works with non-binary collation
  character-set-and-collation.md
  character-set-gbk.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4

#15448 GA- tidb-distributed-execution-framework
  system-variables.md
  tidb-distributed-execution-framework.md
Labels: contribution, translation/done, size/XS, approved, lgtm, v7.5

#15453 update dispatch for release-7.5
  .github/workflows/dispatch.yml
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#15454 bump version to release-7.5
  best-practices/massive-regions-best-practices.md
  best-practices/pd-scheduling-best-practices.md
  br/br-monitoring-and-alert.md
  br/br-snapshot-architecture.md
  br/br-snapshot-guide.md
  deploy-monitoring-services.md
  dm/dm-best-practices.md
  dm/dm-open-api.md
  dm/dm-overview.md
  dm/dm-precheck.md
  dumpling-overview.md
  faq/backup-and-restore-faq.md
  functions-and-operators/precision-math.md
  grafana-resource-control-dashboard.md
  information-schema/information-schema-cluster-info.md
  maintain-tidb-using-tiup.md
  migrate-from-tidb-to-tidb.md
  pd-configuration-file.md
  performance-tuning-methods.md
  production-deployment-using-tiup.md
  replicate-between-primary-and-secondary-clusters.md
  system-variables.md
  ticdc/ticdc-avro-checksum-verification.md
  ticdc/ticdc-open-protocol.md
  ticdc/ticdc-overview.md
  ticdc/ticdc-storage-consumer-dev-guide.md
  tidb-binlog/binlog-consumer-client.md
  tidb-binlog/tidb-binlog-configuration-file.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-configuration-file.md
  tidb-resource-control.md
  tidb-scheduling.md
  tidb-troubleshooting-map.md
  tiflash/tiflash-late-materialization.md
  tikv-configuration-file.md
  tiup/tiup-playground.md
  troubleshoot-lock-conflicts.md
  tune-tikv-memory-performance.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#15452 update absolute links in learning path
  TOC.md
  _index.md
  dashboard/dashboard-user.md
  dm/task-configuration-file-full.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  ticdc/ticdc-changefeed-config.md
  tidb-roadmap.md
  tiflash/tiflash-configuration.md
Labels: translation/done, size/XL, approved, needs-1-more-lgtm, lgtm

#15456 develop: fix broken links
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-mysqlclient.md
  develop/dev-guide-sample-application-python-peewee.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
Labels: translation/no-need, type/bug-fix, size/M, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15434 upgrade using tiup: add FAQ for concurrent DDL
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/S, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15367 import into 7.5
  sql-statements/sql-statement-import-into.md
  tidb-global-sort.md
Labels: translation/doing, size/S, approved, lgtm, v7.5, needs-cherry-pick-release-7.5

#15468 Update disk space requirements for import into
  hardware-and-software-requirements.md
Labels: type/enhancement, contribution, translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15442 update tiup doc
  tiup/tiup-cluster-topology-reference.md
  upgrade-tidb-using-tiup.md
Labels: translation/from-docs, size/M, area/tiup, approved, lgtm, needs-cherry-pick-release-7.5

#15475 ticdc: change encoder tool
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-mysql.md
Labels: translation/done, ONCALL, area/ticdc, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15473 string-functions: convert the table of supported functions to a list
  functions-and-operators/string-functions.md
Labels: type/enhancement, translation/doing, size/XL, approved, needs-1-more-lgtm, lgtm

#15480 Add a limitation for "Import into " SQL statement
  sql-statements/sql-statement-import-into.md
Labels: contribution, translation/done, size/XS, approved, lgtm, v7.5, needs-cherry-pick-release-7.5

#15356 add ticdc aws glue schema registry config docs
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/doing, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15342 tidb-binlog: depreciate binlog as a data sync tool
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-binlog/upgrade-tidb-binlog.md
Labels: contribution, translation/done, size/S, approved, lgtm, v7.5, needs-cherry-pick-release-7.5

#15439 Update ticdc changefeed filter case senssitive default value
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-kafka.md
  ticdc/ticdc-sink-to-mysql.md
  ticdc/ticdc-sink-to-pulsar.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.5, needs-cherry-pick-release-7.5

#15488 Clarify statement on backup-and-restore-using-dumpling page
  backup-and-restore-using-dumpling-lightning.md
  dm/dm-hardware-and-software-requirements.md
  migrate-large-mysql-to-tidb.md
  tidb-lightning/tidb-lightning-requirements.md
Labels: translation/from-docs, size/L, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15469 *: update resource control about background example
  releases/release-7.4.0.md
  system-variables.md
  tidb-resource-control.md
Labels: translation/doing, size/M, approved, lgtm, v7.4, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15441 update tidb roadmap
  tidb-roadmap.md
Labels: translation/from-docs, size/L, for-release, approved, needs-1-more-lgtm, lgtm, v7.5

#15495 dashboard: Add the support of TiKV for heap profiling
  dashboard/continuous-profiling.md
  dashboard/dashboard-profiling.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v7.5, needs-cherry-pick-release-7.5

#15496 Add some explanation for tiflash tuning performance doc
  tiflash/tune-tiflash-performance.md
Labels: type/enhancement, translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, 2024–tidb-docs-dash

#15440 tidb-lightning: rename tables and databases
  tidb-lightning/tidb-lightning-data-source.md
Labels: translation/done, size/M, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15503 Update tidb-lightning-physical-import-mode.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15514 dm: Cleanup typo in feature-online-ddl and update dm-faq
  dm/dm-faq.md
  dm/dm-online-ddl-tool-support.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#15516 ticdc: update best practices
  ticdc/ticdc-overview.md
Labels: type/enhancement, translation/done, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15526 pr template: add the option for v7.6
  .github/pull_request_template.md
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#10579 v5.3: update downloading links of sync_diff_inspector
  download-ecosystem-tools.md
Labels: translation/doing, type/bug-fix, size/XS, area/migrate, approved, needs-1-more-lgtm, lgtm

#15328 add more explains and examples for `SELECT ... INTO OUTFILE` statements
  sql-statements/sql-statement-select.md
Labels: translation/from-docs, size/M, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15332 Polish pd-scheduling-best-practice on slow nodes.
  best-practices/pd-scheduling-best-practices.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15528 BRIE: add experimental notice in BACKUP and RESTORE sql
  migrate-from-tidb-to-tidb.md
  replicate-between-primary-and-secondary-clusters.md
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
Labels: translation/doing, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15552 fix typo "Tiflash"
  tiflash-upgrade-guide.md
Labels: translation/no-need, type/bug-fix, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15565 Fix broken link to Connector/J docs
  develop/dev-guide-sample-application-java-jdbc.md
Labels: translation/from-docs, size/XS, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15079 *: add more contents about supported versions and upgrade methods
  smooth-upgrade-tidb.md
Labels: translation/done, size/M, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5
