Repository pingcap/docs-cn, pull requests merged in 2023-12, with the labels that each got.

#15455 update hardware-and-software-requirements for v7.5
  hardware-and-software-requirements.md
Labels: translation/done, needs-cherry-pick-master, size/M, approved, needs-1-more-lgtm, lgtm, v7.5

#15276 releases: add release notes for v7.5.0
  TOC.md
  releases/release-7.5.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/XL, for-release, approved, lgtm, v7.5, needs-cherry-pick-release-7.5

#15436 bump version to 7.5.0
  README.md
  br/backup-and-restore-use-cases.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-open-api-v2.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, for-release, approved, needs-1-more-lgtm, lgtm, v7.5, needs-cherry-pick-release-7.5

#15595 update keywords.md
  keywords.md
Labels: translation/from-docs, size/M, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#11669 Update KILL TIDB descriptions for v5.3
  sql-statements/sql-statement-kill.md
Labels: status/LGT1, contribution, translation/done, first-time-contributor, size/S, area/sql-infra, needs-cherry-pick-release-5.4, approved, needs-1-more-lgtm, lgtm

#15579 cdc: add description about canal-json content-compatible.
  ticdc/ticdc-canal-json.md
Labels: translation/done, size/XS, area/ticdc, needs-cherry-pick-release-6.5, approved, lgtm

#14877 ticdc: add binary_encoding_method to openapi v2
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-server-config.md
Labels: translation/done, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#15525 v6.5.6: add release notes
  TOC.md
  releases/release-6.5.6.md
  releases/release-7.1.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/doing, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15599 v6.5: bump TiDB version to v6.5.6
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-overview.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#15614 Add cdc redo configuration
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-open-api-v2.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#15628 Update the introduced info for tidb_opt_enable_hash_join
  optimizer-hints.md
  releases/release-7.4.0.md
  system-variables.md
Labels: translation/doing, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15631 fix a typo for store procedure
  mysql-compatibility.md
Labels: translation/no-need, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15640 fix redundant quotation marks
  br/br-pitr-guide.md
Labels: translation/done, size/S, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15648 fix typo
  system-variables.md
Labels: translation/from-docs, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, approved, needs-1-more-lgtm, lgtm

#15654 fix version comment
  system-variables.md
Labels: translation/done, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#15655 update the variable scope
  information-schema/information-schema-variables-info.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15647 Update ddl-introduction.md
  ddl-introduction.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15674 Table name typo fixed
  sql-non-prepared-plan-cache.md
Labels: translation/from-docs, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15669 tidb config doc: coprocessor request timeout
  releases/release-7.5.0.md
  tidb-configuration-file.md
Labels: contribution, translation/done, size/S, type/compatibility-or-feature-change, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5

#15602 Update tidb-distributed-execution-framework.md
  TOC.md
  basic-features.md
  external-storage-uri.md
  releases/release-7.1.0.md
  releases/release-7.1.1.md
  releases/release-7.2.0.md
  releases/release-7.4.0.md
  releases/release-7.5.0.md
  sql-statements/sql-statement-import-into.md
  system-variables.md
  tidb-distributed-execution-framework.md
  tidb-global-sort.md
Labels: translation/done, size/L, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15629 Update tiflash-results-materialization.md
  tiflash/tiflash-results-materialization.md
Labels: translation/done, size/S, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15671 add doc for tidb_allow_tiflash_cop
  releases/release-7.3.0.md
  system-variables.md
Labels: translation/done, size/S, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15696 transaction: add english for a term
  transaction-isolation-levels.md
Labels: translation/no-need, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15596 update serverless connect steps
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-mysqlclient.md
  develop/dev-guide-sample-application-python-peewee.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
Labels: translation/done, size/M, area/develop, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15673 sync-diff-inspector: add descriptions and examples of table routers
  sync-diff-inspector/route-diff.md
Labels: contribution, translation/from-docs, size/L, area/sync-diff-inspector, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#15708 backup: add experimetal description for sql br
  br/backup-and-restore-tool.md
Labels: contribution, translation/doing, size/S, approved, needs-1-more-lgtm, lgtm

#12506 faq: add PD encryption error "fail to get encryption key from file"
  faq/manage-cluster-faq.md
Labels: type/enhancement, translation/welcome, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#14383 restore: add faq for rule not found
  faq/backup-and-restore-faq.md
Labels: translation/welcome, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024–tidb-docs-dash

#14834 br: add document for backup compression
  br/use-br-command-line-tool.md
Labels: translation/welcome, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024–tidb-docs-dash

#15287 br: add one missing pitr bugfix
  releases/release-7.1.1.md
Labels: translation/welcome, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024–tidb-docs-dash

#12059 lightning: update get started doc
  get-started-with-tidb-lightning.md
Labels: translation/doing, size/M, ONCALL, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15750 dm: add new openapi config about import_mode
  dm/dm-open-api.md
Labels: translation/done, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#15753 Update dm-open-api.md
  dm/dm-open-api.md
Labels: translation/from-docs, size/S, approved, lgtm, needs-cherry-pick-release-7.5

#15366 br: modify the faqs of pitr
  faq/backup-and-restore-faq.md
  system-variables.md
Labels: translation/doing, size/S, area/br, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15756 br: update PITR FAQ for v7.1 branch
  faq/backup-and-restore-faq.md
  system-variables.md
Labels: translation/doing, size/S, area/br, approved, needs-1-more-lgtm, lgtm

#15757 use code format in basic features
  basic-features.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15663 load data: update the notes about committing rows
  sql-statements/sql-statement-load-data.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15670 grafana: supply the explanation on the metrics of Flow-Control in TiKV.
  grafana-tikv-dashboard.md
  media/tikv-dashboard-flow-control.png
Labels: contribution, translation/doing, size/S, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15627 update the error message of OOM
  troubleshoot-tidb-oom.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15583 v7.1.2: update doc of `require_secure_transport`
  system-variables.md
Labels: translation/done, size/XS, approved, lgtm

#15798 Update release-7.1.2.md
  releases/release-7.1.2.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15799 tikv: update the screenshot of tikv-dashboard-flow-control.
  grafana-tikv-dashboard.md
  media/tikv-dashboard-flow-control.png
Labels: contribution, translation/doing, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15771 update the foreign key feature description
  foreign-key.md
Labels: translation/from-docs, size/XS, area/sql-infra, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15817 Update tidb-distributed-execution-framework.md
  mysql-schema.md
  tidb-distributed-execution-framework.md
Labels: contribution, translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15823 Update tidb-lightning-physical-import-mode.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#14314 faq: update br faq for restore
  faq/backup-and-restore-faq.md
Labels: translation/welcome, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#15836 Update release-6.5.4.md
  releases/release-6.5.4.md
Labels: contribution, translation/doing, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#13246 *: refined contributing doc
  CONTRIBUTING.md
  README.md
  media/one-page-style-guide.png
Labels: type/enhancement, translation/doing, area/general, size/L, approved, lgtm

#15797 cdc: change the default value of case_sensitive in v6.5.6 and v7.1.3,…
  ticdc/ticdc-canal-json.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-open-api-v2.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#15416 Change description of ONLY_FULL_GROUP_BY
  sql-mode.md
Labels: contribution, translation/welcome, type/bug-fix, first-time-contributor, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#15842 ticdc: fix tiup cmd, change `tiup ctl:v<CLUSTER_VERSION> cdc` to `tiup cdc:v<CLUSTER_VERSION> cli`
  migrate-from-tidb-to-mysql.md
  replicate-data-to-kafka.md
  ticdc/deploy-ticdc.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/ticdc-changefeed-overview.md
Labels: contribution, translation/done, size/S, ONCALL, area/ticdc, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15672 release: add v7.1.3 release notes
  TOC.md
  releases/release-7.1.3.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15833 bump version for 7.1.3
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-open-api-v2.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  tso.md
  upgrade-tidb-using-tiup.md
Labels: translation/from-docs, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#15849 tiunimanager: delete tiunimanager from 6.5 and later
  TOC.md
  _index.md
  download-ecosystem-tools.md
  ecosystem-tool-user-guide.md
  faq/faq-overview.md
  faq/manage-cluster-faq.md
  tiunimanager/tiunimanager-faq.md
  tiunimanager/tiunimanager-import-and-export-data.md
  tiunimanager/tiunimanager-install-and-maintain.md
  tiunimanager/tiunimanager-login-and-initialize.md
  tiunimanager/tiunimanager-manage-clusters.md
  tiunimanager/tiunimanager-manage-host-resources.md
  tiunimanager/tiunimanager-manage-system.md
  tiunimanager/tiunimanager-manage-tasks.md
  tiunimanager/tiunimanager-overview.md
  tiunimanager/tiunimanager-quick-start.md
  tiunimanager/tiunimanager-release-1.0.0.md
  tiunimanager/tiunimanager-release-1.0.1.md
  tiunimanager/tiunimanager-release-1.0.2.md
  tiunimanager/tiunimanager-release-notes.md
Labels: contribution, translation/no-need, size/XXL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15438 pitr: update limitation of first time restore.
  br/br-pitr-manual.md
Labels: translation/welcome, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#15864 *: add descriptions for some system tables
  mysql-schema.md
Labels: translation/done, size/S, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5

#15600 tikv: recorrect the descriptions on the feature `region-split-size` part.
  releases/release-6.1.0.md
  tune-region-performance.md
Labels: contribution, translation/done, size/S, area/engine, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15870 *: add pingcap terms
  CONTRIBUTING.md
  resources/tidb-terms.md
Labels: translation/no-need, size/XL, approved, lgtm

#15889 changefeed: add the info about configuring SQL mode
  releases/release-6.5.6.md
  releases/release-7.1.3.md
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15894 fix rendering issue in create-tiflash-replicas
  tiflash/create-tiflash-replicas.md
Labels: translation/no-need, type/bug-fix, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15904 declare the scope of runaway queries management
  tidb-resource-control.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15903 recommend eligible deployments for resource control test
  tidb-resource-control.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15606 TOC: Simplify statement names
  TOC.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#15911 contribution guide: add info about TiDB Docs Dash 2024
  CONTRIBUTING.md
Labels: missing-translation-status, size/M, approved, needs-1-more-lgtm, lgtm

#15607 Correct show index output
  sql-statements/sql-statement-show-indexes.md
Labels: translation/from-docs, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15608 statements: Add SHOW BINARY LOG STATUS info
  sql-statements/sql-statement-show-master-status.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#15883 add single backticks to inline code
  sql-mode.md
Labels: type/enhancement, contribution, translation/doing, first-time-contributor, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#15880 Update use-tidb-to-read-tiflash.md
  tiflash/use-tidb-to-read-tiflash.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15881 Removed unsupported Azure Blob storage via import into
  external-storage-uri.md
  sql-statements/sql-statement-import-into.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: contribution, translation/done, size/M, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15926 cached table: clarify usage scenarios
  cached-tables.md
Labels: type/enhancement, translation/welcome, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#15936 upgrade TiDB: check DDL and backup status before checking cluster health
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/S, ONCALL, area/deploy-upgrade-maintain, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15895 Update use-tidb-to-read-tiflash.md
  tiflash/use-tidb-to-read-tiflash.md
Labels: translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm
