Repository pingcap/docs-cn, pull requests merged in 2023-04, with the labels that each got.

#13576 TTL: fix SQL statement
  time-to-live.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13583 chore: update pr template for v7.1
  .github/pull_request_template.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS

#13585 bump version in upgrade guide
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/deploy-upgrade-maintain, needs-cherry-pick-release-7.0

#13586 lightning: update descriptions of some parameters
  tidb-lightning/tidb-lightning-configuration.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#12845 tidb: add warning message of drop table
  sql-statements/sql-statement-drop-table.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#13504 fix value ranges fo tidb_server_memory_limit
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13523 sql-faq: add missing DELAYED priority
  faq/sql-faq.md
Labels: type/enhancement, status/LGT2, translation/from-docs, status/can-merge, size/S, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13612 ci: remove assignees in Links, update the deprecated set-output command
  .github/workflows/dispatch.yml
  .github/workflows/link-fail-fast.yaml
  .github/workflows/link.yaml
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13622 update issue template chooser
  .github/ISSUE_TEMPLATE/config.yml
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS

#13447 Add ilike pushdown function for tiflash
  functions-and-operators/operators.md
  releases/release-7.0.0.md
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/bigdata, v7.0, needs-cherry-pick-release-7.0

#13368 Add the incompatibility about `grant` and `revoke`
  sql-statements/sql-statement-grant-privileges.md
  sql-statements/sql-statement-revoke-privileges.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-7.0

#13605 fix the wrong description of the dump tool
  basic-features.md
Labels: status/LGT1, contribution, translation/no-need, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#13574 fix the scope of `tidb_enable_gogc_tuner` and `tidb_gogc_tuner_threshold`
  system-variables.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#12084 improved-translation-metrics-schema.md
  metrics-schema.md
Labels: type/enhancement, status/LGT1, contribution, translation/no-need, status/can-merge, require-LGT1, first-time-contributor, size/XS

#13518 planner: supply description about plan cache supporting limit
  releases/release-6.6.0.md
  sql-prepared-plan-cache.md
Labels: status/LGT2, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13639 add description about the compatibility with tools for multi-valued index
  sql-statements/sql-statement-create-index.md
Labels: status/LGT1, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.6

#11700 add description about PessimisticLockNotFound relating to lazy uniqueness check
  constraints.md
  releases/release-6.5.1.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, area/transaction, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13522 tidb: add missing labels in config file
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13559 Add error code description for 'Information schema is changed'
  metadata-lock.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/XS, area/sql-infra, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13651 sync-diff: update docker images
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: type/enhancement, status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, area/sync-diff-inspector

#13665 ci: update specified actions to the latest
  .github/workflows/link-fail-fast.yaml
  .github/workflows/link.yaml
  .github/workflows/media.yml
  .github/workflows/rebase.yml
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13666 add k8s v1.5 to pdf list
  resources/cdnfresh.txt
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS

#13625 alert rules: update the solution of some rules
  alert-rules.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/S, area/scheduling, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13577 release: add 6.1.6 release notes
  TOC.md
  releases/release-6.1.6.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13679 bump version for v6.1.6
  br/backup-and-restore-use-cases.md
  check-before-deployment.md
  develop/dev-guide-proxysql-integration.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/manage-ticdc.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/L

#13689 partitioned-table: updated the structure of Partition management
  partitioned-table.md
Labels: status/LGT2, translation/no-need, status/can-merge, area/sql-infra, needs-cherry-pick-release-7.0

#13649 resource_control: add a example to reset user resource group to default value
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-create-resource-group.md
  tidb-resource-control.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, require-LGT1, size/M, area/sql-infra, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13331 add ticdc summary monitor doc
  TOC.md
  media/ticdc/ticdc-summary-monitor-changefeed.png
  media/ticdc/ticdc-summary-monitor-cloud-storage.png
  media/ticdc/ticdc-summary-monitor-dataflow-mounter.png
  media/ticdc/ticdc-summary-monitor-dataflow-puller.png
  media/ticdc/ticdc-summary-monitor-dataflow-sink.png
  media/ticdc/ticdc-summary-monitor-dataflow-sorter.png
  media/ticdc/ticdc-summary-monitor-mq-sink.png
  media/ticdc/ticdc-summary-monitor-redo.png
  media/ticdc/ticdc-summary-monitor-server.png
  media/ticdc/ticdc-summary-monitor-transaction-sink.png
  media/ticdc/ticdc-summary-monitor.png
  ticdc/monitor-ticdc.md
  ticdc/ticdc-summary-monitor.md
Labels: type/enhancement, status/LGT2, translation/done, status/can-merge, size/L, ONCALL, area/ticdc, needs-cherry-pick-release-7.0

#13658 resource-control: add the error number comments
  error-codes.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13698 *: adjust tool order in toc and learning path
  TOC.md
  _index.md
  migration-tools.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13715 *: add mirror dependency on CPU
  hardware-and-software-requirements.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, area/general, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#12741 toc: remove recommended from tiup deployment
  TOC.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#11150 lightning: fix a wrong description in command line flags
  tidb-lightning/tidb-lightning-command-line-full.md
Labels: status/LGT1, translation/no-need, status/can-merge, type/bug-fix, require-LGT1, size/XS, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13707 Update command-line-flags-for-tidb-configuration.md
  command-line-flags-for-tidb-configuration.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13706 Update tidb-configuration-file.md
  tidb-configuration-file.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13396 tidb: doc for multi-valued index GA
  choose-index.md
  sql-statements/sql-statement-create-index.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, v7.1

#13584 document `tidb_load_based_replica_read_threshold`
  system-variables.md
  troubleshoot-hot-spot-issues.md
Labels: translation/done, status/can-merge, status/LGT3, size/S, type/compatibility-or-feature-change, v7.1

#13654 ticdc: fix sink uri for storage sink
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-kafka.md
Labels: status/LGT2, translation/doing, status/can-merge, size/M, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13748 system-variables: update description of datadir
  system-variables.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, type/compatibility-or-feature-change, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#13383 Generated Columns GA
  develop/dev-guide-create-table.md
  develop/dev-guide-schema-design-overview.md
  generated-columns.md
  time-to-live.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, v7.1

#13714 resource_control: add privilege for calibrate resource
  privilege-management.md
  sql-statements/sql-statement-calibrate-resource.md
Labels: translation/done, status/can-merge, status/LGT3, size/S, area/sql-infra, v7.1

#13700 add 6.5.2 release notes
  TOC.md
  releases/release-6.5.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13755 bump version for v6.5.2
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: status/LGT1, translation/no-need, status/can-merge, size/L

#13730 plan-replayer, slow-queries: update new diagnostic information in tidb
  identify-slow-queries.md
  sql-plan-replayer.md
Labels: translation/done, status/can-merge, area/general, status/LGT3, size/XS, v7.1

#13662 planner: update the doc of non-prepared plan cache
  media/non-prepapred-plan-cache-unsupprot.png
  sql-non-prepared-plan-cache.md
  sql-prepared-plan-cache.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/planner, type/compatibility-or-feature-change, v7.1

#13761 v6.5: modify default value descriptions for enable-partition-separator
  releases/release-6.5.2.md
  ticdc/ticdc-changefeed-config.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, type/compatibility-or-feature-change, area/ticdc

#13764 6.5.2 release notes: fix an issue number
  releases/release-6.5.2.md
  ticdc/ticdc-changefeed-config.md
Labels: status/LGT1, translation/no-need, status/can-merge, require-LGT1, size/XS, area/ticdc

#13738 add notice for now usage in stale read
  develop/dev-guide-use-stale-read.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/develop, needs-cherry-pick-release-6.5

#13770 *: correct TiDB disk type
  hardware-and-software-requirements.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, ONCALL

#13709 sql-statement: calibrate resource support workload
  sql-statements/sql-statement-calibrate-resource.md
Labels: translation/done, status/can-merge, status/LGT3, size/L, area/sql-infra, v7.1

#13719 *: add configuration performance.lite-init-stats
  statistics.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, area/general, size/S, type/compatibility-or-feature-change, v7.1

#13733 system-variables: add `tidb_opt_fix_control`
  control-execution-plan.md
  system-variables.md
Labels: translation/done, status/can-merge, status/LGT3, size/S, type/compatibility-or-feature-change, v7.1

#13769 sql-plan: add description about plan baseline
  sql-plan-management.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, area/sql-infra, ONCALL

#13732 resource control: GA for 7.1
  information-schema/information-schema-resource-groups.md
  tidb-resource-control.md
Labels: translation/done, status/can-merge, status/LGT3, size/M, area/sql-infra, v7.1

#13708 sql: GA load data logical mode and add experimental physical mode
  error-codes.md
  sql-statements/sql-statement-load-data.md
  sql-statements/sql-statement-operate-load-data-job.md
  sql-statements/sql-statement-show-load-data.md
  tidb-configuration-file.md
Labels: status/LGT2, translation/done, status/can-merge, size/L, area/sql-infra, type/compatibility-or-feature-change, v7.1

#13624 br: restore checkpoint
  TOC.md
  br/br-checkpoint-backup.md
  br/br-checkpoint-restore.md
  releases/release-6.5.0.md
Labels: translation/done, status/can-merge, status/LGT3, size/L, area/br, v7.1

#13775 tiup: fix the scale-out yaml example
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  tiup/tiup-component-cluster-check.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/M, area/tiup, ONCALL, needs-cherry-pick-release-5.4, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13776 credits: remove outdated contributor link and repos
  credits.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13549 system variable: rename tidb_ddl_distribute_reorg to tidb_enable_dist_task
  releases/release-6.6.0.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, area/sql-infra, type/compatibility-or-feature-change, v7.1

#13791 system-variables: update the default value of datadir
  system-variables.md
Labels: status/LGT1, translation/from-docs, status/can-merge, require-LGT1, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13793 lihgtning: add parrallel import method
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: type/enhancement, status/LGT1, translation/done, status/can-merge, require-LGT1, area/tidb-lightning, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13638 Delete binlog recommendation
  migration-tools.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13637 add ticdc command line server flag description
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-kafka.md
  ticdc/ticdc-sink-to-mysql.md
Labels: status/LGT1, translation/doing, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0, needs-cherry-pick-release-7.1

#13731 Add description on `admin pause ddl jobs` and `admin resume ddl jobs`
  ddl-introduction.md
Labels: status/LGT2, contribution, translation/done, status/can-merge, first-time-contributor, size/S, v7.1

#13579 Remove TiFlash http service
  config-templates/complex-tiflash.yaml
  hardware-and-software-requirements.md
  tiflash/tiflash-configuration.md
  tiup/tiup-cluster-topology-reference.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, type/compatibility-or-feature-change, v7.1

#13588 add sys variables `tidb_prefer_broadcast_join_by_exchange_data_size` to docs-cn
  system-variables.md
  tiflash/use-tiflash-mpp-mode.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, area/bigdata, v7.1

#13652 TiFlash Late Materialization GA
  system-variables.md
  tiflash/tiflash-late-materialization.md
Labels: status/LGT2, translation/done, status/can-merge, size/M, area/bigdata, v7.1

#13678 Update S3 TiFlash doc
  tiflash/tiflash-disaggregated-and-s3.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, v7.1

#13687 update doc for insert select pushdown to tiflash
  system-variables.md
  tiflash/tiflash-results-materialization.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v7.1

#13692 Make INTERVAL Partitioning GA
  partitioned-table.md
Labels: status/LGT2, translation/from-docs, status/can-merge, area/sql-infra, v7.1

#13729 Added COALESCE PARTITION
  glossary.md
  mysql-compatibility.md
  partitioned-table.md
Labels: status/LGT2, translation/from-docs, status/can-merge, size/L, area/sql-infra, v7.1

#13763 v7.1: modify default value descriptions for enable-partition-separator
  ticdc/ticdc-changefeed-config.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XS, area/ticdc, v7.1

#13792 ticdc: fix the description of safe-mode
  ticdc/ticdc-faq.md
Labels: status/LGT2, translation/from-docs, status/can-merge, type/bug-fix, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13808 tiup: update the default value of transfer-timeout from 300 to 600
  dm/maintain-dm-using-tiup.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-reload.md
  tiup/tiup-component-cluster-scale-in.md
  tiup/tiup-component-cluster-upgrade.md
Labels: status/LGT2, translation/done, status/can-merge, type/bug-fix, size/S, area/tiup, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#13768 pd: add configuration for store_limit_v2
  configure-store-limit.md
  pd-configuration-file.md
  pd-control.md
Labels: status/LGT2, translation/done, status/can-merge, first-time-contributor, size/S, type/compatibility-or-feature-change, v7.1

#13756 system-variables: update `tidb_ddl_enable_fast_reorg`
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/XS, v7.1

#13807 planner: add doc for the new variable `tidb_plan_cache_max_plan_size`
  sql-non-prepared-plan-cache.md
  sql-prepared-plan-cache.md
  system-variables.md
Labels: status/LGT2, translation/done, status/can-merge, size/S, type/compatibility-or-feature-change, v7.1

#13819 add a note on max_prepared_stmt_count for 6.5.2
  releases/release-6.5.2.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#10477 dumpling: update some desc for migrating from aurora
  migrate-aurora-to-tidb.md
Labels: type/enhancement, status/LGT2, translation/doing, status/can-merge, size/XS, area/dumpling

#13740 update basic features for 7.1
  basic-features.md
Labels: status/LGT2, translation/done, status/can-merge, size/XL, for-release, v7.1

#13831 v7.1: update the description of fast online ddl
  releases/release-7.1.0.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/XS

#13823 Update Lightning import error handling
  tidb-lightning/tidb-lightning-distributed-import.md
Labels: status/LGT1, translation/done, status/can-merge, require-LGT1, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0
