Repository pingcap/docs-cn, pull requests merged in 2024-02, with the labels that each got.

#16243 tiup, tiproxy: add version flags to tiup cluster upgrade
  tiproxy/tiproxy-overview.md
  tiup/tiup-component-cluster-upgrade.md
Labels: translation/doing, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6

#16379 [v6.5.8] tikv configuration doc: add gc thread number
  tikv-configuration-file.md
Labels: translation/done, requires-version-specific-changes, needs-cherry-pick-master, size/XS, type/compatibility-or-feature-change, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16477 pr-template: remove v7.3 and add v8.0
  .github/pull_request_template.md
  README.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#16373 add release note for v6.5.8
  TOC.md
  releases/release-6.5.8.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16421 bump version for v6.5.8
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#16466 vaunt: update achievement images and add vaunt documentation
  .vaunt/1st_place.png
  .vaunt/add-tidb-docs-dash-badge.md
  .vaunt/contributor.png
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, ok-to-test

#16490 develop: use absolute URLs in href
  develop/dev-guide-third-party-support.md
Labels: translation/doing, needs-cherry-pick-master, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16491 add instructions about connection collation
  character-set-and-collation.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16498 add-tidb-docs-dash-badge.md: correct a link
  .vaunt/add-tidb-docs-dash-badge.md
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#16392 Update config.yaml to fix PR bonus points
  .vaunt/config.yaml
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#16420 Update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: contribution, translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm, needs-ok-to-test

#16503 dev guide: update link for backend sql courses
  develop/dev-guide-overview.md
Labels: translation/no-need, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16510 truncate statement ebnf
  sql-statements/sql-statement-truncate.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6

#16512 More MySQL 8.x compatibility updates
  dm/dm-overview.md
  error-codes.md
  faq/tidb-faq.md
  generated-columns.md
  overview.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16522 fix the description of wal_dir
  tikv-configuration-file.md
Labels: contribution, translation/done, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, ok-to-test

#16516 function-and-operators: enrich instructions for string functions BIT_LENGTH() and CHAR() #15482
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm

#16517 functions-and-operators: enrich instructions for string functions CHAR_LENGTH() and CHARACTER_LENGTH #15483
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm

#16538 develop: fix admonitions
  develop/dev-guide-gui-mysql-workbench.md
  develop/dev-guide-gui-navicat.md
Labels: translation/no-need, type/bug-fix, size/XS, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16233 ticdc: Add a description of the compatibility between BR and Lightning
  ticdc/ticdc-faq.md
  ticdc/ticdc-overview.md
Labels: translation/done, size/S, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16545 add missing release note in 6.5.7
  releases/release-6.5.7.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16552 develop: replace angle brackets with curly brackets
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
Labels: translation/from-docs, size/M, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16200 add dev guide(zh)
  TOC.md
  develop/dev-guide-sample-application-aws-lambda.md
  develop/dev-guide-sample-application-nextjs.md
  develop/dev-guide-sample-application-nodejs-sequelize.md
Labels: translation/from-docs, needs-cherry-pick-master, size/XXL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.6

#16568 Update ticdc-overview.md
  ticdc/ticdc-overview.md
Labels: translation/no-need, size/S, approved, needs-1-more-lgtm, lgtm

#16184 Update syncpoint doc
  ticdc/ticdc-upstream-downstream-check.md
Labels: translation/doing, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16539 Enrich instructions for string functions INSTR() and LCASE()
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm

#16579 reference: add an example for S3 URI in sink-uri
  external-storage-uri.md
Labels: type/enhancement, translation/done, size/S, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16577 Update sql-statement-show-profiles.md to reference statement summary tables
  sql-statements/sql-statement-show-profiles.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#16582 chore: test the build watcher
  releases/release-6.1.0.md
Labels: translation/no-need, size/XS, approved, lgtm

#16584 Revert "chore: test the build watcher "
  releases/release-6.1.0.md
Labels: missing-translation-status, size/XS, approved, needs-1-more-lgtm, lgtm

#16375 pd-ctl: add resource-manager command
  pd-control.md
Labels: translation/done, size/M, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16583 tiflash: fix scale-in command argument -R
  tiflash/tiflash-disaggregated-and-s3.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16514 fix desc for String Function SUBSTRING_INDEX () and TO_BASE64
  functions-and-operators/string-functions.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, ok-to-test

#16590 tikv: refine description of MVCC
  tidb-storage.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16410 update placement-rules doc about max-replica
  configure-placement-rules.md
  tiflash/troubleshoot-tiflash.md
Labels: translation/doing, size/S, area/scheduling, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16521 fix: wait_timeout update for the best practices
  best-practices/java-app-best-practices.md
  develop/dev-guide-connection-parameters.md
Labels: translation/no-need, size/S, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#15977 update playground doc
  quick-start-with-htap.md
  tiup/tiup-faq.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16603 Update schedule-replicas-by-topology-labels.md
  schedule-replicas-by-topology-labels.md
Labels: contribution, translation/no-need, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-ok-to-test

#16578 fix: transactin_ts in slow query is start_ts, not commit_ts
  identify-slow-queries.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16601 system-variables: add a warning about tidb_enable_dist_task in v7.1
  system-variables.md
  tidb-distributed-execution-framework.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#15872 customize-montior: remove a sentence with duplicated meaning
  tiup/customized-montior-in-tiup-environment.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16587 ticdc: fix pulsar sink documentation error
  ticdc/ticdc-sink-to-pulsar.md
Labels: translation/done, requires-version-specific-changes, size/M, for-release, approved, lgtm, needs-cherry-pick-release-7.5, v8.0

#15581 update doc of `require_secure_transport`
  system-variables.md
Labels: translation/doing, requires-version-specific-changes, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#16591 resource_control: add note for the conflict between resource control and sql priority
  faq/sql-faq.md
  system-variables.md
  tidb-configuration-file.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16468 adjust the recommend value of raft election-timeout in multi dc deployment
  dr-multi-replica.md
  geo-distributed-deployment-topology.md
  three-data-centers-in-two-cities-deployment.md
Labels: translation/done, size/S, type/cherry-pick-for-release-6.5, type/cherry-pick-for-release-7.1, approved, needs-1-more-lgtm, lgtm, type/cherry-pick-for-release-7.5, type/cherry-pick-for-release-7.6

#16640 v7.6: update upgrade-tidb-using-tiup.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/XS, area/tiup, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6

#16642 *: fix two oncall issues
  faq/sql-faq.md
  foreign-key.md
Labels: contribution, translation/done, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16645 tidb: add status.record-db-label docs
  tidb-configuration-file.md
Labels: contribution, translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16648 release-7.5.0 release notes: add two TiCDC parameter changes
  releases/release-7.5.0.md
  releases/release-7.6.0.md
Labels: translation/done, size/XS, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16388 ticdc: update cdc gc service doc and failed changefeed faq
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-faq.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16621 cdc: Add description about protocol behavior change.
  TOC.md
  releases/release-6.5.3.md
  releases/release-6.5.4.md
  releases/release-7.1.1.md
  releases/release-7.1.2.md
  releases/release-7.2.0.md
  releases/release-7.4.0.md
  ticdc/ticdc-behavior-change.md
Labels: translation/doing, size/M, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16647 tidb: remove INCREMENTAL syntax of analyze table statement
  sql-statements/sql-statement-analyze-table.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16666 update the compatibility issue between Connector/J 8.0 and TiDB v7.5
  develop/dev-guide-choose-driver-or-orm.md
Labels: translation/from-docs, size/XS, area/develop, approved, needs-1-more-lgtm, lgtm

#16351 tidb: remove experimental warnings for stats lock
  basic-features.md
  releases/release-7.4.0.md
  sql-statements/sql-statement-lock-stats.md
  sql-statements/sql-statement-show-stats-locked.md
  sql-statements/sql-statement-unlock-stats.md
  statistics.md
Labels: translation/done, size/S, approved, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16674 fix: mycuster should be mycluster
  tiflash/tiflash-disaggregated-and-s3.md
Labels: translation/from-docs, type/bug-fix, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16670 Update placement-rules-in-sql.md to fix the incorrect part
  placement-rules-in-sql.md
Labels: translation/done, type/bug-fix, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16680 Update string function description and examples
  functions-and-operators/string-functions.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6

#16687 tiproxy: add experimental warning for v0.2.0
  tiproxy/tiproxy-overview.md
Labels: translation/done, size/XS, approved, lgtm

#16681 Enrich instructions for string functions LIKE and LOCATE()
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/XL, approved, needs-1-more-lgtm, lgtm

#16682 Enrich instructions for string functions HEX() and INSERT()
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm

#16250 remove support for tls 1.1 and 1.0
  enable-tls-between-clients-and-servers.md
  tidb-configuration-file.md
Labels: translation/from-docs, missing-translation-status, size/XS, for-release, approved, lgtm, v8.0

#16628 v7.5.1: tikv configuration doc: add gc thread number
  tikv-configuration-file.md
Labels: translation/done, requires-version-specific-changes, needs-cherry-pick-master, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6

#16660 add release note for v7.5.1
  TOC.md
  releases/release-7.5.1.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16646 bump version for v7.5.1
  br/backup-and-restore-use-cases.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  external-storage-uri.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#16699 update the definition of group_concat_max_len
  functions-and-operators/aggregate-group-by-functions.md
  system-variables.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16675 Note that GC Disabling is a must despite Dumpling's auto extend feature
  migrate-from-tidb-to-mysql.md
Labels: translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6
