Repository pingcap/docs-cn, pull requests merged in 2024-11, with the labels that each got.

#18914 tiproxy: add docs for label-based balance
  media/tiproxy/tiproxy-balance-label.png
  tiproxy/tiproxy-configuration.md
  tiproxy/tiproxy-grafana.md
  tiproxy/tiproxy-load-balance.md
Labels: type/enhancement, translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18294 cdc: add more detail about the authorization
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18783 cdc: make mq encoding protocol related more clear
  ticdc/ticdc-avro-protocol.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18621 *: add docs for TiFlash MinTSO scheduler
  TOC.md
  media/tiflash/tiflash_mintso_v1.png
  media/tiflash/tiflash_mintso_v2.png
  tiflash/tiflash-mintso-scheduler.md
Labels: translation/done, size/M, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18776 Correct some configs' notes
  tikv-configuration-file.md
Labels: contribution, translation/doing, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19005 br: remove duplicated release notes from release-8.3.0.md
  releases/release-8.3.0.md
Labels: translation/done, type/bugfix, size/XS, approved, lgtm, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19008 pull_request_template: add the option for v8.5
  .github/pull_request_template.md
Labels: translation/from-docs, size/XS, approved, lgtm

#18927 tiup: add kvcdc server topylogy example
  tiup/tiup-cluster-topology-reference.md
Labels: type/enhancement, translation/from-docs, size/M, ONCALL, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.4

#18996 add example to generate dm key
  dm/dm-customized-secret-key.md
  dm/dm-master-configuration-file.md
Labels: translation/from-docs, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.4

#19014 sys-var: add `2` for `mpp_version`
  system-variables.md
Labels: translation/doing, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19020 release-8.1: fix kvcdc parameters
  tiup/tiup-cluster-topology-reference.md
Labels: translation/no-need, size/XS, approved, lgtm

#18974 tiproxy: add performance report of traffic capture
  tiproxy/tiproxy-performance-test.md
  tiproxy/tiproxy-traffic-replay.md
Labels: translation/done, type/bugfix, size/M, approved, lgtm, v8.4, needs-cherry-pick-release-8.4

#19027 Update best-practices-on-public-cloud.md
  best-practices-on-public-cloud.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.4

#18893 cdnfresh.txt: add v8.4 PDF
  resources/cdnfresh.txt
Labels: translation/no-need, size/XS, for-release, approved, needs-1-more-lgtm, lgtm, v8.4

#18556 releases: add release notes for v8.4.0
  README.md
  TOC.md
  releases/release-8.4.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/XL, for-release, approved, lgtm, v8.4, needs-cherry-pick-release-8.4

#18877 v8.4: bump the latest TiDB version to v8.4.0
  br/backup-and-restore-use-cases.md
  certificate-authentication.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  functions-and-operators/tidb-functions.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  performance-schema/performance-schema-session-connect-attrs.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-microservices-using-tiup.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, for-release, approved, needs-1-more-lgtm, lgtm, v8.4, needs-cherry-pick-release-8.4

#18697 add 8.4 in basic features
  basic-features.md
Labels: translation/done, size/XL, for-release, approved, needs-1-more-lgtm, lgtm, v8.4, needs-cherry-pick-release-8.4

#19041 fix: correct release link from 7.5.3 to 7.5.4
  releases/release-timeline.md
Labels: translation/no-need, type/bugfix, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19040 planner: update sql-prepared-plan-cache.md
  sql-prepared-plan-cache.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19034 Update docs related to locking
  information-schema/information-schema-data-lock-waits.md
  mysql-schema/mysql-schema.md
  troubleshoot-lock-conflicts.md
Labels: type/enhancement, translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm

#19039 Updated the limitation of Schema Cache
  schema-cache.md
Labels: contribution, translation/done, size/XS, approved, lgtm, v8.4, needs-cherry-pick-release-8.4

#19057 dm: update compatibility info
  dm/dm-compatibility-catalog.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#19047 cdc: add description about ticdc lightning compatibility
  ticdc/ticdc-compatibility.md
  tidb-lightning/tidb-lightning-compatibility-and-scenarios.md
Labels: type/enhancement, translation/doing, size/S, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19055 ticdc: add detailed instructions for verifying if TiCDC has synchronized all updates to downstream
  ticdc/ticdc-faq.md
Labels: type/enhancement, translation/doing, size/L, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19029 glossary: Add more abbreviations
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
  dm/dm-glossary.md
  glossary.md
  latency-breakdown.md
  ticdc/ticdc-faq.md
  ticdc/ticdc-glossary.md
  tidb-lightning/tidb-lightning-glossary.md
  tiflash/tiflash-mintso-scheduler.md
  tiflash/use-tiflash-mpp-mode.md
Labels: type/enhancement, translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm

#19026 Update hardware-and-software-requirements.md
  hardware-and-software-requirements.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19052 *: update TOC and title wording for on-boarding docs
  TOC.md
  quick-start-with-tidb.md
  tidb-in-kubernetes.md
Labels: type/enhancement, translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm

#19098 feat: navicat supported tidb
  develop/dev-guide-gui-navicat.md
  media/develop/navicat-premium-add-new-connection.png
  media/develop/navicat-premium-connection-config-dedicated-general.png
  media/develop/navicat-premium-connection-config-dedicated-ssl.png
  media/develop/navicat-premium-connection-config-self-hosted-general.png
  media/develop/navicat-premium-connection-config-serverless-general.png
  media/develop/navicat-premium-connection-config-serverless-ssl.png
Labels: translation/done, size/M, ONCALL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19107 fix: update broken TiDB binary download link
  binary-package.md
  production-deployment-using-tiup.md
Labels: translation/no-need, type/bugfix, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19072 migration: Add information about Vitess to TiDB migration
  TOC.md
  media/vitess_to_tidb.png
  media/vitess_to_tidb_dm.png
  media/vitess_to_tidb_dumpling_local.png
  migrate-from-vitess.md
  migration-overview.md
Labels: translation/from-docs, size/M, sig/docs, approved, needs-1-more-lgtm, lgtm

#19115 readme: update the display of active contributors
  README.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#18773 v8.4: update CentOS 7-related descriptions
  develop/dev-guide-build-cluster-in-cloud.md
  hardware-and-software-requirements.md
  ticdc/deploy-ticdc.md
Labels: translation/done, size/S, area/develop, for-release, approved, needs-1-more-lgtm, lgtm, v8.4, needs-cherry-pick-release-8.4

#19097 update description about CentOS 7 EOL
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#19126 releases: fix a typo in v8.2 release notes
  releases/release-8.2.0.md
Labels: translation/no-need, type/bugfix, size/XS, approved, lgtm, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19030 toc: reorganize TiCDC docs in left navigation
  TOC.md
Labels: type/enhancement, translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm

#18997 Add mintso config parameters
  tiflash/tiflash-configuration.md
  tiflash/tiflash-mintso-scheduler.md
Labels: translation/done, requires-version-specific-changes, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19056 release notes 7.1.6
  TOC.md
  releases/release-7.1.6.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/XL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18705 tidb: make Foreign Key GA
  constraints.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  foreign-key.md
  sql-statements/sql-statement-alter-table.md
Labels: translation/done, size/S, area/develop, approved, lgtm, v8.5

#18857 system-variable: add a warning message for `tidb_partition_prune_mode` variable
  partitioned-table.md
  system-variables.md
  tiflash/use-tiflash-mpp-mode.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.5

#19025 pd: GA active follower
  system-variables.md
  tune-region-performance.md
Labels: translation/done, size/XS, approved, lgtm, v8.5

#19032 enable fast create table on default
  accelerated-table-creation.md
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.5

#19053 partitioned-table: remove some restrictions on global index
  partitioned-table.md
Labels: translation/from-docs, size/S, for-release, approved, needs-1-more-lgtm, lgtm, v8.5

#19153 sync-diff-inspector: add limitations
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: type/enhancement, translation/doing, size/XS, area/sync-diff-inspector, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#19117 encryption: remove experimental for GCP KMS
  encryption-at-rest.md
Labels: contribution, translation/from-docs, first-time-contributor, size/XS, approved, lgtm, ok-to-test, v8.5

#19152 update the description of variable "tidb_scatter_region"
  best-practices/high-concurrency-best-practices.md
  sql-statements/sql-statement-show-variables.md
  sql-statements/sql-statement-split-region.md
  system-variables.md
Labels: contribution, translation/done, size/S, approved, lgtm, needs-cherry-pick-release-8.4

#19119 fix incorrect message for set_var()
  system-variables.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.4

#19022 Updated TiDB Roadmap
  tidb-roadmap.md
Labels: contribution, translation/done, size/XL, approved, lgtm

#19031 br: remove experimental feature notice for encryption to GA in v8.5
  br/br-pitr-manual.md
  br/br-snapshot-manual.md
Labels: translation/from-docs, size/S, approved, lgtm, v8.5

#19114 Update docs for deprecate-integer-display-length=true
  data-type-numeric.md
  data-type-overview.md
  tidb-configuration-file.md
Labels: translation/from-docs, size/S, for-release, approved, needs-1-more-lgtm, lgtm, v8.5

#19071 tidb: add description for var `tidb_ddl_reorg_max_write_speed`
  system-variables.md
Labels: translation/doing, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.5

#18894 cdc: update debezium protocol
  ticdc/ticdc-debezium.md
Labels: translation/doing, size/M, area/ticdc, for-release, approved, lgtm, v8.5

#18524 *: make the expressions of GlobalStats consistent
  optimizer-fix-controls.md
  partitioned-table.md
  releases/release-6.3.0.md
  releases/release-6.5.10.md
  releases/release-7.3.0.md
  releases/release-7.5.0.md
  releases/release-8.1.1.md
  releases/release-8.2.0.md
  sql-statements/sql-statement-drop-stats.md
  statistics.md
  system-variables.md
Labels: type/enhancement, translation/done, size/M, area/develop, approved, needs-1-more-lgtm, lgtm

#19169 add the removal reason for `tidb_enable_change_multi_schema`
  releases/release-6.2.0.md
Labels: ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.4

#19175 br-pitr-manual: remove an unnecessary quotation mark
  br/br-pitr-manual.md
Labels: size/S, ONCALL, area/br, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.4
