Repository pingcap/docs-cn, pull requests merged in 2024-07, with the labels that each got.

#17773 resource_contorl: add privilege requirement for dashboard resouce control page
  dashboard/dashboard-resource-manager.md
  sql-statements/sql-statement-calibrate-resource.md
Labels: translation/doing, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17315 planner: update the doc about Plan Cache
  optimizer-hints.md
  sql-prepared-plan-cache.md
  statement-summary-tables.md
Labels: translation/done, size/L, approved, lgtm, v8.2

#17834 TiFlash: update LLVM requirements
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v8.2

#17465 Add tiup microservices section
  TOC.md
  command-line-flags-for-scheduling-configuration.md
  command-line-flags-for-tso-configuration.md
  pd-microservices-deployment-topology.md
  pd-microservices.md
  scale-microservices-using-tiup.md
  scheduling-configuration-file.md
  tiup/tiup-cluster-topology-reference.md
  tiup/tiup-playground.md
  tso-configuration-file.md
Labels: translation/done, size/XXL, area/scheduling, approved, lgtm, v8.2

#17648 update lightning conflict detection recording view
  dm/task-configuration-file-full.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-error-resolution.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: translation/from-docs, size/M, area/tidb-lightning, for-release, approved, needs-1-more-lgtm, lgtm, v8.2

#17687 *: adaptive analyze scan concurrency
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.2

#17837 Fix several typos and update wording for perf tuning
  grafana-tikv-dashboard.md
  performance-tuning-methods.md
Labels: translation/done, type/bug-fix, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17842 cdnfresh.txt: add v8.2 PDF
  resources/cdnfresh.txt
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#17845 tikv-grafana: add compaction job size(files) metric
  grafana-tikv-dashboard.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, v8.2, needs-cherry-pick-release-8.2

#17839 ticdc: add more description about how cdc split update kv entries
  ticdc/ticdc-behavior-change.md
Labels: translation/doing, size/S, for-release, approved, lgtm, v8.2, needs-cherry-pick-release-8.2

#17843 Update EBNF for password options
  sql-statements/sql-statement-create-user.md
Labels: translation/from-docs, size/S, for-release, approved, needs-1-more-lgtm, lgtm, v8.2, needs-cherry-pick-release-8.2

#17847 Update descriptions for tidb_schema_cache_size
  releases/release-8.0.0.md
  releases/release-8.1.0.md
  system-variables.md
Labels: translation/done, requires-version-specific-changes, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17694 Update system-variables.md
  system-variables.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17863 Update outdated https://en.pingcap.com/ links
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-proxysql-integration.md
Labels: translation/from-docs, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17747 tiup: add a ref to limitation on users operation during upgrade using tiup
  upgrade-tidb-using-tiup.md
Labels: translation/from-docs, area/tiup, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17772 br: link to BR monitoring and alert
  br/br-pitr-guide.md
Labels: type/enhancement, translation/done, size/XS, ONCALL, area/br, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17881 toc: update wording for collation
  TOC.md
Labels: translation/no-need, type/bug-fix, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17894 Update builtins output
  sql-statements/sql-statement-show-builtins.md
Labels: type/enhancement, translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm

#17650 *: improve INL_HASH_JOIN document about collation incompatibility
  optimizer-hints.md
Labels: translation/from-docs, size/XS, area/planner, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17879 Update EBNF for admin statements and add checksum details
  sql-statements/sql-statement-admin-cancel-ddl.md
  sql-statements/sql-statement-admin-check-table-index.md
  sql-statements/sql-statement-admin-checksum-table.md
  sql-statements/sql-statement-admin-pause-ddl.md
  sql-statements/sql-statement-admin-recover.md
  sql-statements/sql-statement-admin-resume-ddl.md
  sql-statements/sql-statement-admin-show-ddl.md
  sql-statements/sql-statement-admin.md
  sql-statements/sql-statement-import-into.md
Labels: translation/from-docs, size/L, area/sql-infra, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17892 fix 8025 solution
  tidb-lightning/troubleshoot-tidb-lightning.md
Labels: contribution, translation/done, size/XS, approved, lgtm, needs-ok-to-test

#17784 Extend JSON function docs
  TOC.md
  data-type-default-values.md
  data-type-json.md
  functions-and-operators/aggregate-group-by-functions.md
  functions-and-operators/json-functions.md
  functions-and-operators/json-functions/json-functions-aggregate.md
  functions-and-operators/json-functions/json-functions-create.md
  functions-and-operators/json-functions/json-functions-modify.md
  functions-and-operators/json-functions/json-functions-return.md
  functions-and-operators/json-functions/json-functions-search.md
  functions-and-operators/json-functions/json-functions-utility.md
  functions-and-operators/json-functions/json-functions-validate.md
Labels: translation/from-docs, requires-version-specific-changes, size/XXL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17514 add v8.2.0 release notes
  TOC.md
  releases/release-8.2.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, do-not-merge/hold, size/XL, for-release, approved, lgtm, v8.2, needs-cherry-pick-release-8.2

#17783 basic-features.md: add a column for v8.2.0
  basic-features.md
Labels: translation/doing, size/XL, for-release, approved, needs-1-more-lgtm, lgtm, v8.2, needs-cherry-pick-release-8.2

#17915 *: fix a typo in toc
  TOC.md
Labels: translation/done, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17836 v8.2: bump the latest TiDB version to v8.2
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  performance-schema/performance-schema-session-connect-attrs.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  releases/release-8.2.0.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, for-release, approved, needs-1-more-lgtm, lgtm, v8.2, needs-cherry-pick-release-8.2

#17914 ticdc: adjust pulsar sink doc
  ticdc/ticdc-sink-to-pulsar.md
Labels: translation/done, size/XS, area/ticdc, for-release, approved, lgtm, v8.2, needs-cherry-pick-release-8.2

#17933 sql: fix a synopsis error
  sql-statements/sql-statement-analyze-table.md
Labels: translation/done, size/XS, area/sql-infra, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17940 fix error
  releases/release-8.2.0.md
Labels: contribution, translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-ok-to-test, needs-cherry-pick-release-8.2

#17934 expressions-pushed-down: Update JSON links
  functions-and-operators/expressions-pushed-down.md
Labels: translation/from-docs, size/S, do-not-merge/hold, approved, lgtm, needs-cherry-pick-release-8.2

#17943 remove coma in expressions-pushed-down.md
  functions-and-operators/expressions-pushed-down.md
Labels: translation/no-need, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.2

#17908 update auto-random.md
  auto-random.md
Labels: translation/doing, size/S, area/sql-infra, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17787 Update production-deployment-using-tiup.md
  production-deployment-using-tiup.md
Labels: contribution, translation/done, size/XS, approved, lgtm, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17911 best-practice: support extra strategy for fine-tuning the performance in massive regions
  best-practices/massive-regions-best-practices.md
  media/best-practices/commit-log-duration.png
  tikv-configuration-file.md
Labels: contribution, translation/done, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17964 clinic: extend free expiration
  clinic/clinic-introduction.md
Labels: type/enhancement, translation/done, size/XS, area/clinic, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17974 Update pull_request_template.md
  .github/pull_request_template.md
Labels: translation/from-docs, size/XS, approved, lgtm

#17973 expression-pushed-down: Link to internal string/misc/cast functions
  functions-and-operators/expressions-pushed-down.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.2

#17733 Update tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17896 admin show ddl: Fix EBNF
  sql-statements/sql-statement-admin-show-ddl.md
Labels: translation/from-docs, type/bug-fix, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17975 update the MySQL version to 8.0 for `server-version`
  develop/dev-guide-sample-application-nodejs-prisma.md
Labels: translation/from-docs, size/XS, area/develop, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17988 Update encryption and compression functions
  functions-and-operators/encryption-and-compression-functions.md
  functions-and-operators/expressions-pushed-down.md
  password-management.md
  system-variables.md
Labels: type/enhancement, translation/from-docs, size/XL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17995 Clinic: Various fixes
  clinic/clinic-data-instruction-for-tiup.md
Labels: translation/from-docs, size/XS, area/clinic, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17996 Update function and operator overview
  functions-and-operators/functions-and-operators-overview.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18004 removed an English sentence in partitioned-table.md
  partitioned-table.md
Labels: needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17979 Update tispark-overview.md version matrix
  tispark-overview.md
Labels: type/enhancement, translation/done, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17991 Update window function docs
  functions-and-operators/expressions-pushed-down.md
  functions-and-operators/window-functions.md
  keywords.md
  system-variables.md
Labels: translation/from-docs, size/XL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18031 Add missing release note for issue tidb#53540
  releases/release-8.2.0.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.2

#18038 add aliases for migrate-full-data-from-mysql
  migration-overview.md
Labels: translation/done, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm

#18039 remove tidb_enable_async_merge_global_stats from v6.5.10 release notes
  releases/release-6.5.10.md
Labels: translation/done, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18046 fix incorrect column name in Index Join
  explain-joins.md
Labels: translation/done, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18052 release (contributors): fix a broken GitHub link
  releases/release-7.4.0.md
Labels: translation/done, type/bug-fix, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18056 Fix an outdated DM table routing link
  dm/task-configuration-file-full.md
Labels: translation/no-need, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18063 dm: fix SQL statement syntax
  dm/dm-worker-intro.md
Labels: translation/doing, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18072 Improve step description for installing tools using TiUP
  migration-tools.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17989 Document that txn-total-size-limit won't affect pipelined dml
  system-variables.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17880 Document pre/post upgrade and reload scripts
  tiup/tiup-component-cluster-reload.md
  tiup/tiup-component-cluster-upgrade.md
Labels: translation/from-docs, size/M, area/tiup, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17833 bump up the prometheus and grafana versions
  deploy-monitoring-services.md
  releases/release-8.0.0.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17990 doc: add more details to grpc-compression configs
  tidb-configuration-file.md
  tikv-configuration-file.md
Labels: translation/doing, size/XS, approved, lgtm, needs-cherry-pick-release-8.2

#17987 string-functions: Use MySQL 8.0 url instead of 8.3
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18083 Add more links and corrections to user account management
  privilege-management.md
  sql-statements/sql-statement-alter-user.md
  user-account-management.md
Labels: type/enhancement, translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm

#18096 Add metricsfilter option
  clinic/clinic-user-guide-for-tiup.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#17827 Rehash and update statistics and SQL docs
  TOC.md
  extended-statistics.md
  optimizer-fix-controls.md
  partitioned-table.md
  releases/release-5.4.0.md
  releases/release-6.3.0.md
  releases/release-7.4.0.md
  sql-statements/sql-statement-drop-stats.md
  sql-statements/sql-statement-show-analyze-status.md
  sql-statements/sql-statement-show-column-stats-usage.md
  sql-statements/sql-statement-show-stats-buckets.md
  sql-statements/sql-statement-show-stats-healthy.md
  sql-statements/sql-statement-show-stats-histograms.md
  sql-statements/sql-statement-show-stats-locked.md
  sql-statements/sql-statement-show-stats-topn.md
  statistics.md
  system-variables.md
  tidb-resource-control.md
Labels: type/enhancement, translation/from-docs, size/XXL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18099 tiflash: Refine the config doc of tiflash
  tiflash/tiflash-configuration.md
Labels: translation/doing, size/M, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17956 update tidb-distributed-execution-framework.md
  tidb-distributed-execution-framework.md
Labels: translation/done, size/XS, area/sql-infra, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17992 Replace sqlgram links
  TOC.md
  basic-sql-operations.md
  develop/dev-guide-create-table.md
  develop/dev-guide-tidb-crud-sql.md
  expression-syntax.md
  mysql-compatibility.md
  sql-statements/sql-statement-overview.md
Labels: type/enhancement, translation/from-docs, size/L, area/develop, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18076 Improve upgrade limitations
  smooth-upgrade-tidb.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/S, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18094 partitioned-table: create strictly increasing range columns partition
  partitioned-table.md
Labels: translation/done, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#18119 fix the release date of v7.5.2
  releases/release-notes.md
Labels: translation/no-need, type/bug-fix, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18138 tiflash: update TiKV to TiFlash Proxy in config
  tiflash/tiflash-configuration.md
Labels: translation/no-need, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#18140 Add a note to ticdc-sink-to-mysql.md
  ticdc/ticdc-sink-to-mysql.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18125 Update sync-diff-inspector-overview.md
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18163 ticdc-faq: fix typo for commitTS
  ticdc/ticdc-faq.md
Labels: size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18030 cdc: remove maxwell protocol, add simple protocol
  releases/release-4.0.10.md
  releases/release-4.0.6.md
  releases/release-4.0.8.md
  releases/release-5.0.6.md
  releases/release-5.1.4.md
  releases/release-5.2.4.md
  releases/release-5.3.1.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-open-api.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, requires-version-specific-changes, size/S, ONCALL, area/ticdc, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18162 ticdc: move the mysql downstream user permission info to the mysql sink doc
  ticdc/ticdc-faq.md
  ticdc/ticdc-sink-to-mysql.md
Labels: type/enhancement, translation/done, size/M, ONCALL, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18187 fix the recommended range for region-split-size
  tune-region-performance.md
Labels: translation/done, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18126 tidb: Remove description about "Control+C" for `compactible-kill-query`
  tidb-configuration-file.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18118 tidb: add explanation for the fields in mysql.user
  TOC.md
  faq/manage-cluster-faq.md
  mysql-schema/mysql-schema-user.md
  mysql-schema/mysql-schema.md
  privilege-management.md
  releases/release-7.6.0.md
  statistics.md
  tidb-resource-control.md
  user-account-management.md
Labels: type/enhancement, translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#18200 fix: remove backticks from front matter
  mysql-schema/mysql-schema-user.md
Labels: translation/from-docs, type/bug-fix, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17980 Update TiDB specific function docs
  as-of-timestamp.md
  functions-and-operators/tidb-functions.md
  identify-slow-queries.md
  statement-summary-tables.md
  system-variables.md
Labels: translation/from-docs, size/XL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18181 doc: add `session_alias` to `information_schema.processlist` and expensive queries
  identify-expensive-queries.md
  information-schema/information-schema-processlist.md
  releases/release-8.2.0.md
Labels: translation/done, size/M, approved, needs-1-more-lgtm, lgtm

#18205 tidb lightning: remove the addr for the importer backend
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/no-need, size/XS, ONCALL, area/tidb-lightning, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18206 Functions: Add examples for bit functions and operators
  functions-and-operators/bit-functions-and-operators.md
  tso.md
Labels: type/enhancement, translation/from-docs, size/XL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2
