Repository pingcap/docs-cn, pull requests merged in 2024-01, with the labels that each got.

#15955 upgrade-monitoring-services: fix path errors
  upgrade-monitoring-services.md
Labels: type/bug-fix, ONCALL, area/diagnosis, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15961 tidb-lightning: replace `NO_ENGINE_SUBSTITUTION` with `NO_AUTO_CREATE_USER`
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, size/XS, area/tidb-lightning, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15976 system-variable: indicate that max_allowed_packet is ready only in the session scope
  system-variables.md
Labels: translation/done, size/XS, area/sql-infra, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#14373 补充说明同一事务内的调度策略
  follower-read.md
Labels: type/enhancement, translation/welcome, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#15946 chore: add a doc about how to generate doc PDF locally
  README.md
  resources/tidb-pdf-generation-tutorial.md
Labels: translation/doing, translation/welcome, size/L, approved, needs-1-more-lgtm, lgtm, 2024-tidb-docs-dash

#9117 Add introduction of High Available
  TOC.md
  dm/dm-arch.md
  dm/dm-glossary.md
  dm/dm-high-availability.md
  media/dm/dm-high-availability-1.png
  media/dm/dm-high-availability-2.png
Labels: type/enhancement, status/LGT1, translation/welcome, size/L, area/dm, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#15481 string-functions: add instructions for using ASCII() and BIN()
  functions-and-operators/string-functions.md
Labels: type/enhancement, translation/done, size/M, approved, needs-1-more-lgtm, lgtm

#15991 Change the default log level of tiflash
  tiflash/tiflash-configuration.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#15989 update tidb_opt_fix_control for v6.5.7
  control-execution-plan.md
  optimizer-fix-controls.md
  releases/release-7.1.0.md
  releases/release-7.2.0.md
  sql-non-prepared-plan-cache.md
  system-variables.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#15988 update force-init-stats for v6.5.7
  releases/release-7.1.0.md
  releases/release-7.2.0.md
  statistics.md
  tidb-configuration-file.md
Labels: translation/done, size/S, area/planner, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#15934 releases: add 6.5.7 release notes
  releases/release-6.5.7.md
Labels: translation/doing, size/L, do-not-merge/hold, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#16025 update 6.5.7 release notes
  TOC.md
  releases/release-6.5.7.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/no-need, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#16008 bump version for v6.5.7
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#16031 Update year to 2024 in copyright.tex
  templates/copyright.tex
Labels: translation/from-docs, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#16032 remove tidb_opt_fix_control from 6.5.7 release notes
  releases/release-6.5.7.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15742 Update sql-statement-import-into.md
  sql-statements/sql-statement-import-into.md
Labels: contribution, translation/welcome, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16011 dm: add a note about DM to `sql_require_primary_key`
  dm/task-configuration-file-full.md
  system-variables.md
Labels: contribution, translation/done, size/XS, area/dm, approved, lgtm, needs-cherry-pick-release-7.5

#16059 vaunt: add achievements for docs dash event
  .vaunt/1st_place.png
  .vaunt/2nd_place.png
  .vaunt/3rd_place.png
  .vaunt/4th_place.png
  .vaunt/5th_place.png
  .vaunt/config.yaml
  .vaunt/contributor.png
Labels: contribution, translation/no-need, first-time-contributor, size/L, approved, lgtm

#15751 doc: move condition from where clause to on condition in nt-dml
  non-transactional-dml.md
Labels: type/enhancement, translation/doing, translation/welcome, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16072 ticdc-alert-rules: update the description of ticdc_memory_abnormal to match English doc
  ticdc/ticdc-alert-rules.md
Labels: contribution, translation/from-docs, type/bug-fix, first-time-contributor, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16073 Update tikv-ctl bad-ssts output
  tikv-control.md
Labels: contribution, translation/from-docs, first-time-contributor, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16009 tiup: add instructions for the --local option
  tiup/tiup-component-cluster-template.md
Labels: contribution, translation/doing, translation/welcome, first-time-contributor, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16092 Update system-variables.md
  system-variables.md
Labels: translation/welcome, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#15783 Add doc for new json function support in tiflash
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: translation/done, size/XS, approved, lgtm, v7.6

#15695 add doc for `tidb_txn_entry_size_limit`
  system-variables.md
  tidb-configuration-file.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v7.6

#15657 doc: transactional load data stmt
  sql-statements/sql-statement-load-data.md
Labels: translation/done, size/XS, area/sql-infra, approved, lgtm, v7.6

#15749 tikv: document periodic full compaction
  dynamic-config.md
  tikv-configuration-file.md
Labels: translation/from-docs, size/S, type/compatibility-or-feature-change, approved, needs-1-more-lgtm, lgtm, v7.6

#15601 *: add doc for system variable tidb_idle_transaction_timeout
  develop/dev-guide-connection-parameters.md
  develop/dev-guide-timeouts-in-tidb.md
  faq/manage-cluster-faq.md
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, area/develop, approved, lgtm, v7.6

#15834 Add docs for the I_S keyword table
  TOC.md
  information-schema/information-schema-keywords.md
  information-schema/information-schema.md
  keywords.md
Labels: translation/from-docs, size/M, area/sql-infra, for-release, approved, needs-1-more-lgtm, lgtm, v7.6

#16050 fix: tidb_opt_fix_control is introduced in v6.5.3
  control-execution-plan.md
  optimizer-fix-controls.md
  releases/release-7.1.0.md
  releases/release-7.2.0.md
  sql-non-prepared-plan-cache.md
  system-variables.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#16017 update tidb_opt_fix_control for v6.5
  TOC.md
  control-execution-plan.md
  optimizer-fix-controls.md
  system-variables.md
Labels: translation/done, size/M, approved, lgtm

#16102 move tikv configure item `pd.enable-forwarding` to correct place
  tikv-configuration-file.md
Labels: translation/done, size/S, approved, lgtm, needs-cherry-pick-release-7.5

#16130 ticdc: fix typo tokne -> token
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/no-need, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#15885 Global sort documents update
  sql-statements/sql-statement-import-into.md
  system-variables.md
  tidb-global-sort.md
Labels: translation/done, size/S, approved, lgtm, v7.6

#15945 create-index: remove the description that no stats are collected for mv index
  sql-statements/sql-statement-create-index.md
Labels: translation/done, size/XS, approved, lgtm, v7.6

#15943 doc-cn: add multi value index case from cnf and dnf combination
  choose-index.md
Labels: translation/done, size/M, approved, needs-1-more-lgtm, lgtm, v7.6

#16127 Update tiup-component-cluster-template.md
  tiup/tiup-component-cluster-template.md
Labels: type/enhancement, contribution, translation/doing, size/XS, area/tiup, approved, lgtm, needs-cherry-pick-release-7.5

#15960 Add explanation for auto_random ID allocation
  auto-random.md
  system-variables.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#16117 Update information-schema-ddl-jobs.md
  information-schema/information-schema-ddl-jobs.md
Labels: contribution, translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#15571 tikv: add new dynamic config item "readpool.unified.max-tasks-per-worker"
  dynamic-config.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v7.6

#15866 add tikv lower/upper functions
  functions-and-operators/expressions-pushed-down.md
Labels: translation/done, size/XS, approved, lgtm, v7.6

#15766 Add docs for `TiCDC support checking if data is entirely replicated to Downstream`
  ticdc/ticdc-open-api-v2.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm, v7.6

#15835 tiproxy: add tiproxy overview, troubleshooting, and performance test
  TOC.md
  binary-package.md
  media/tiproxy/tiproxy-architecture.png
  media/tiproxy/tiproxy-session-migration.png
  tidb-architecture.md
  tidb-monitoring-framework.md
  tiproxy/tiproxy-command-line-flags.md
  tiproxy/tiproxy-configuration.md
  tiproxy/tiproxy-deployment-topology.md
  tiproxy/tiproxy-grafana.md
  tiproxy/tiproxy-overview.md
  tiproxy/tiproxy-performance-test.md
  tiproxy/troubleshoot-tiproxy.md
  tiup/tiup-cluster-topology-reference.md
  tiup/tiup-cluster.md
  tiup/tiup-playground.md
Labels: translation/from-docs, size/XXL, approved, lgtm, v7.6

#16177 tikv: fix dead code link
  tikv-control.md
Labels: contribution, translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm

#16162 Fix the example of tidb's equivalent function for oracle's nvl2
  oracle-functions-to-tidb.md
Labels: contribution, translation/done, first-time-contributor, size/XS, approved, lgtm, needs-cherry-pick-release-7.5

#16123 resources: refine format for tidb-terms.md
  resources/tidb-terms.md
Labels: contribution, translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#16125 develop: refine format in dev-guide-choose-driver-or-orm.md
  develop/dev-guide-choose-driver-or-orm.md
Labels: contribution, missing-translation-status, size/XS, area/develop, approved, needs-1-more-lgtm, lgtm

#16163 stats: clarify configuration persistence of analyze statement
  statistics.md
Labels: contribution, translation/from-docs, first-time-contributor, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16183 tidb: fix config value for tiproxy
  tidb-configuration-file.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, v7.6

#16201 Update config.yaml for TiDB Docs Dash
  .vaunt/config.yaml
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#16168 Update the introduction of UCASE() and UNHEX()
  functions-and-operators/string-functions.md
Labels: contribution, translation/doing, first-time-contributor, size/M, approved, needs-1-more-lgtm, lgtm, 2024-tidb-docs-dash

#16161 Update the introduction of UPPER and WEIGHT_STRING
  functions-and-operators/string-functions.md
Labels: contribution, translation/doing, first-time-contributor, size/L, approved, needs-1-more-lgtm, lgtm, 2024-tidb-docs-dash

#16185 tidb-lightning: tidb.pd-addr supports multiple addresses
  get-started-with-tidb-lightning.md
  tidb-lightning/tidb-lightning-command-line-full.md
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v7.6

#16089 Update dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
Labels: contribution, translation/doing, size/M, area/develop, approved, lgtm, 2024-tidb-docs-dash

#16091 Update dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
Labels: contribution, translation/doing, size/M, area/develop, approved, lgtm, 2024-tidb-docs-dash

#15918 system-variable: add `tidb_analyze_distsql_scan_concurrency `
  system-variables.md
Labels: translation/from-docs, size/S, type/compatibility-or-feature-change, for-release, approved, needs-1-more-lgtm, lgtm, v7.6

#15905 ticdc: add explanation for csv delimiter config
  ticdc/ticdc-csv.md
Labels: translation/done, size/XS, approved, lgtm, v7.6

#15626 *: add a new system variable `tidb_enable_global_index`
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v7.6

#15999 ddl: add description tidb ddl v2
  TOC.md
  ddl-v2.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, needs-1-more-lgtm, lgtm, v7.6

#15935 resource_control: enhance observability
  identify-slow-queries.md
  information-schema/information-schema-slow-query.md
  mysql-schema.md
  statement-summary-tables.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v7.6

#16007 resource_control: add more info about sql ru consumption
  tidb-resource-control.md
Labels: translation/done, size/L, type/compatibility-or-feature-change, approved, lgtm, v7.6

#15985 DM: support for MySQL 8.0 GA
  dm/dm-compatibility-catalog.md
  dm/dm-overview.md
Labels: translation/done, size/XS, approved, lgtm, v7.6

#16202 fix 2 issues
  br/backup-and-restore-overview.md
  br/br-pitr-guide.md
  dr-solution-introduction.md
  ticdc/ticdc-open-protocol.md
Labels: translation/done, size/S, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#16000 system var: Active PD follower for handling region request
  system-variables.md
  tune-region-performance.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v7.6

#15932 system-variables: set default tidb_auto_analyze_partition_batch_size as 128
  system-variables.md
Labels: translation/from-docs, size/XS, type/compatibility-or-feature-change, for-release, approved, needs-1-more-lgtm, lgtm, v7.6

#16010 txn: add deprecation description of system variable tidb_disable_txn_…
  system-variables.md
Labels: contribution, translation/done, size/XS, for-release, approved, lgtm, v7.6

#15944 br: add description for --granularity
  br/br-snapshot-guide.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, area/br, approved, lgtm, v7.6

#15551 Add two json function which supports push down to tiflash now
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: translation/done, size/XS, approved, lgtm, v7.6

#16181 data migration: add an example Parquet file name
  migrate-from-parquet-files-to-tidb.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16120 string-functions: update ASCII() and BIN()
  functions-and-operators/string-functions.md
Labels: contribution, translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm

#15815 planner: update the SPM doc
  sql-plan-management.md
  system-variables.md
Labels: translation/done, size/L, type/compatibility-or-feature-change, approved, lgtm, v7.6

#16179 ticdc: v7.6.0 supports compatibility with the data format of the official Canal
  ticdc/ticdc-canal-json.md
Labels: translation/done, size/XS, area/ticdc, for-release, approved, needs-1-more-lgtm, lgtm, v7.6

#16226 Revert "Global sort documents update"
  sql-statements/sql-statement-import-into.md
  system-variables.md
  tidb-global-sort.md
Labels: translation/no-need, size/S, approved, needs-1-more-lgtm, lgtm, v7.6

#16172 Add/clarify SQL length limits
  dashboard/dashboard-slow-query.md
  information-schema/information-schema-slow-query.md
  system-variables.md
Labels: contribution, translation/from-docs, first-time-contributor, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16136 tidb-functions: add info about special start_key/end_key values
  functions-and-operators/tidb-functions.md
Labels: contribution, translation/from-docs, size/M, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16203 upgrade the default minimum tls version
  enable-tls-between-clients-and-servers.md
  tidb-configuration-file.md
Labels: translation/from-docs, size/XS, for-release, approved, lgtm, v7.6

#15814 *: remove the restriction for building range scan for `LIKE` on new collation columns
  character-set-and-collation.md
  character-set-gbk.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v7.6

#16174 br: add description of cross version restoration for mysql system table
  br/backup-and-restore-overview.md
Labels: contribution, translation/done, size/XS, approved, lgtm, v7.6

#16232 Add MDL for DDL troubleshooting
  tidb-troubleshooting-map.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#15871 tiup: add more fields and links from customized-montior-in-tiup-environment.md
  tiup/tiup-cluster-topology-reference.md
Labels: translation/done, size/XS, area/tiup, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16176 support: fix url, enterprise
  support.md
Labels: contribution, translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16178 Update quick-start-with-htap.md to add `USE test` command
  quick-start-with-htap.md
Labels: contribution, translation/doing, first-time-contributor, size/XS, approved, needs-1-more-lgtm, lgtm, 2024-tidb-docs-dash

#16103 Documented resuming changefeed from Failed state
  media/ticdc/ticdc-changefeed-state-transfer.png
  ticdc/ticdc-changefeed-overview.md
Labels: contribution, translation/from-docs, requires-version-specific-changes, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16090 update os support page
  hardware-and-software-requirements.md
Labels: contribution, translation/from-docs, size/S, approved, lgtm, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16242 lightning: refine description for `block-size`
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, v7.6, needs-cherry-pick-release-7.6

#16159 增加kill语句取消ddl作业的描述
  sql-statements/sql-statement-admin-cancel-ddl.md
  sql-statements/sql-statement-kill.md
Labels: contribution, translation/from-docs, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16093 Remove duplicate docs for SHOW INDEX, SHOW KEYS infavor of SHOW INDEXES
  TOC.md
  sql-statements/sql-statement-drop-index.md
  sql-statements/sql-statement-rename-index.md
  sql-statements/sql-statement-show-index.md
  sql-statements/sql-statement-show-indexes.md
  sql-statements/sql-statement-show-keys.md
Labels: contribution, translation/from-docs, size/S, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16074 develop: update the third party support table
  develop/dev-guide-third-party-support.md
Labels: contribution, translation/from-docs, first-time-contributor, size/S, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16150 Add bit reverse example to dev-guide-unique-serial-number-generation
  develop/dev-guide-unique-serial-number-generation.md
Labels: contribution, translation/from-docs, first-time-contributor, size/XS, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16297 Br add experimental description for acceleration restore speed
  br/br-snapshot-guide.md
Labels: contribution, translation/done, size/XS, approved, lgtm, v7.6, needs-cherry-pick-release-7.6

#16169 update dev-java-mybatis
  develop/dev-guide-sample-application-java-mybatis.md
Labels: contribution, translation/doing, first-time-contributor, size/M, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16160 Update dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-pymysql.md
Labels: contribution, translation/doing, first-time-contributor, size/S, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16075 update dev-guide-sample-application-python-mysqlclient
  develop/dev-guide-sample-application-python-mysqlclient.md
Labels: contribution, translation/doing, size/M, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16088 update dev-guide-sample-application-python-mysql-connector
  develop/dev-guide-sample-application-python-mysql-connector.md
Labels: contribution, translation/doing, size/M, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16170 develop: update dev-guide-sample-application-python-peewee
  develop/dev-guide-sample-application-python-peewee.md
Labels: contribution, translation/doing, size/M, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#15954 titan doc update for 7.6 release
  storage-engine/titan-configuration.md
  storage-engine/titan-overview.md
  tikv-configuration-file.md
Labels: translation/done, size/L, type/compatibility-or-feature-change, approved, lgtm, v7.6, needs-cherry-pick-release-7.6

#16135 Update dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-prisma.md
Labels: contribution, translation/doing, size/XS, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16249 bump the example TiDB version to v7.6.0
  br/backup-and-restore-use-cases.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiproxy/tiproxy-performance-test.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm, v7.6, needs-cherry-pick-release-7.6

#15667 releases: add release note for v7.6.0
  TOC.md
  releases/release-7.6.0.md
  releases/release-notes.md
  releases/release-timeline.md
  system-variables.md
  upgrade-tidb-using-tiup.md
Labels: translation/doing, size/XXL, approved, lgtm, v7.6, needs-cherry-pick-release-7.6

#16060 basic-features.md: add the column for v7.6.0
  basic-features.md
Labels: translation/doing, size/XL, for-release, approved, lgtm, v7.6, needs-cherry-pick-release-7.6

#16175 fix link, parser.y
  expression-syntax.md
Labels: contribution, translation/doing, requires-version-specific-changes, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16348 br: update new download method description
  br/br-snapshot-guide.md
Labels: translation/done, size/XS, approved, lgtm, v7.6, needs-cherry-pick-release-7.6

#16149 Explain tidb_max_tiflash_threads default value -1 means
  system-variables.md
Labels: contribution, translation/from-docs, first-time-contributor, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#15890 docs(tidb) add a reasonable example for INL_JOIN
  optimizer-hints.md
Labels: type/enhancement, translation/done, size/S, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5

#16361 br: remove --tikv-max-restore-concurrency
  releases/release-7.6.0.md
Labels: translation/done, size/XS, area/br, approved, needs-1-more-lgtm, lgtm, v7.6, needs-cherry-pick-release-7.6

#16371 README.md: add info about v7.6
  README.md
Labels: translation/doing, size/S, approved, needs-1-more-lgtm, lgtm

#16377 tidb-roadmap.md: add a link to the v7.6 release notes
  tidb-roadmap.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#16344 update titan doc to provide guidline on min-blob-size
  storage-engine/titan-configuration.md
  storage-engine/titan-overview.md
Labels: translation/done, size/S, approved, lgtm, v7.6, needs-cherry-pick-release-7.6

#16345 Update config.yaml for the PR submission time stamp
  .vaunt/config.yaml
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#16298 log_backup: fix initial scan rate limit description
  tikv-configuration-file.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16246 update description of multi-valued index
  sql-statements/sql-statement-create-index.md
Labels: translation/no-need, size/XS, approved, lgtm, v7.6, needs-cherry-pick-release-7.6

#16173 Modify table layout of pdf tex template
  templates/template.tex
Labels: contribution, translation/doing, first-time-contributor, size/S, approved, needs-1-more-lgtm, lgtm, tidb-docs-dash-bonus, 2024-tidb-docs-dash

#16393 ticdc: add example of how to show bdr role
  ticdc/ticdc-bidirectional-replication.md
  ticdc/ticdc-changefeed-config.md
Labels: translation/doing, size/S, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6

#16389 pdf: implement automatic underscore wrapping table cells
  templates/template.tex
Labels: translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6

#16113 Add missing explain formats
  sql-statements/sql-statement-explain.md
Labels: contribution, translation/from-docs, first-time-contributor, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash

#16086 string-functions: add instructions for using CONCAT() and CONCAT_WS()
  functions-and-operators/string-functions.md
Labels: contribution, translation/done, first-time-contributor, size/L, approved, needs-1-more-lgtm, lgtm, 2024-tidb-docs-dash

#16397 sysvar: add a note about `tidb_service_scope`
  system-variables.md
  tidb-distributed-execution-framework.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16121 Add info about compatibility issues with Connector/J 8.0 with TiDB v7.5
  develop/dev-guide-choose-driver-or-orm.md
Labels: contribution, translation/from-docs, first-time-contributor, size/XS, area/develop, approved, lgtm, 2024-tidb-docs-dash

#16166 tiup: Update tiup-overview.md
  tiup/tiup-overview.md
Labels: contribution, translation/done, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16112 add detail desc for String Function SUBSTRING_INDEX () and TO_BASE64
  functions-and-operators/string-functions.md
Labels: contribution, translation/doing, first-time-contributor, size/L, approved, needs-1-more-lgtm, lgtm, 2024-tidb-docs-dash, ok-to-test

#16171 Update SHOW STATUS docs
  TOC.md
  sql-statements/sql-statement-flush-status.md
  sql-statements/sql-statement-show-status.md
  status-variables.md
Labels: contribution, translation/from-docs, size/L, approved, lgtm, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16111 tiflash: Clean deprecated configs; align style of flash.proxy
  tiflash/tiflash-configuration.md
Labels: translation/done, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6

#16182 Update dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
Labels: contribution, translation/doing, first-time-contributor, size/S, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16167 Debug TiDB Documentation: 使用 Django 连接到 TiDB
  develop/dev-guide-sample-application-python-django.md
Labels: contribution, translation/doing, size/M, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16128 update guide-java-spring-boot
  develop/dev-guide-sample-application-java-spring-boot.md
Labels: contribution, translation/doing, first-time-contributor, size/S, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16164 feat: Developer Guide - GUI - MySQL Workbench
  TOC.md
  develop/dev-guide-gui-mysql-workbench.md
  media/develop/mysql-workbench-add-new-connection.png
  media/develop/mysql-workbench-connection-config-dedicated-parameters.png
  media/develop/mysql-workbench-connection-config-self-hosted-parameters.png
  media/develop/mysql-workbench-connection-config-serverless-parameters.png
  media/develop/mysql-workbench-store-dedicated-password-in-keychain.png
  media/develop/mysql-workbench-store-password-in-keychain.png
  media/develop/mysql-workbench-store-self-hosted-password-in-keychain.png
Labels: contribution, translation/from-docs, size/L, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3, needs-cherry-pick-release-7.4, needs-cherry-pick-release-7.5, tidb-docs-dash-bonus, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16165 feat: Developer Guide - GUI - Navicat
  TOC.md
  develop/dev-guide-gui-navicat.md
  media/develop/navicat-add-new-connection.jpg
  media/develop/navicat-connection-config-dedicated-general.png
  media/develop/navicat-connection-config-dedicated-ssl.jpg
  media/develop/navicat-connection-config-self-hosted-general.png
  media/develop/navicat-connection-config-serverless-general.png
  media/develop/navicat-connection-config-serverless-ssl.png
Labels: contribution, translation/from-docs, size/L, area/develop, approved, lgtm, tidb-docs-dash-bonus, 2024-tidb-docs-dash

#16461 develop: adjust the sequence of two GUI Database Tool connection docs
  TOC.md
Labels: translation/no-need, size/XS, area/develop, approved, needs-1-more-lgtm, lgtm

#16119 Enrich instructions for string functions FORMAT() and FROM_BASE64()
  functions-and-operators/string-functions.md
Labels: contribution, translation/done, first-time-contributor, size/L, approved, lgtm, needs-cherry-pick-release-7.5, 2024-tidb-docs-dash, needs-cherry-pick-release-7.6

#16390 MariaDB Migration
  TOC.md
  migrate-from-mariadb.md
Labels: contribution, translation/from-docs, size/XL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-ok-to-test
