Repository pingcap/docs-cn, pull requests merged in 2024-10, with the labels that each got.

#18727 sql-statement-explain: add explanation related to scalar subquery
  sql-statements/sql-statement-explain.md
Labels: translation/done, size/XS, area/planner, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18698 tidb-lightning: refine the PITR support info
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: translation/doing, size/XS, ONCALL, area/tidb-lightning, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18746 non-transactional-dml: update t3. to t3.id
  non-transactional-dml.md
Labels: translation/done, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18745 system tables: remove table `schema_index_usage`
  br/br-snapshot-guide.md
  mysql-schema/mysql-schema.md
Labels: translation/done, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18757 character-set-and-collation: fix an error
  character-set-and-collation.md
Labels: translation/done, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18764 fix transaction_atomicity in release notes
  releases/release-6.1.4.md
  releases/release-6.5.1.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18598 statistics: set the right range for tidb_analyze_partition_concurrency
  system-variables.md
Labels: translation/from-docs, size/XS, type/compatibility-or-feature-change, for-release, approved, needs-1-more-lgtm, lgtm, v8.4

#18758 cfg: fix wrong pd-ctl cmd
  configure-placement-rules.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18784 fix a typo in subquery-optimization.md
  subquery-optimization.md
Labels: translation/no-need, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18756 ticdc: add description for pulsar topic config
  ticdc/ticdc-sink-to-pulsar.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18775 tikv: customized Region size is an experimental feature before TiDB v6.5.0
  best-practices/massive-regions-best-practices.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18805 txn: fix the maximum value of a transaction from 10GB to 1 TiB
  basic-features.md
  develop/dev-guide-transaction-restraints.md
  tidb-configuration-file.md
Labels: translation/done, size/S, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18794 cdc: fix open protocol example data
  ticdc/ticdc-open-protocol.md
Labels: translation/done, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18818 toc: add TiDB release support policy
  TOC.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#18821 string-functions: Explain binary-as-hex behavior
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18616 add doc for hash_join_v2
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18717 add-doc-fix52592
  optimizer-fix-controls.md
Labels: contribution, translation/from-docs, size/S, for-release, approved, lgtm, ok-to-test, v8.4

#18609 planner: change default of tidb_opt_prefer_range_scan
  system-variables.md
Labels: translation/from-docs, size/XS, type/compatibility-or-feature-change, for-release, approved, needs-1-more-lgtm, lgtm, v8.4

#18613 config: update doc of tidb tikv-client.grpc-keepalive-timeout config
  tidb-configuration-file.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.4

#18626 sys-var: change `tidb_scatter_region` usage definition
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18642 resource_control: support config background tasks resource limit
  dynamic-config.md
  sql-statements/sql-statement-alter-resource-group.md
  tidb-resource-control.md
  tikv-configuration-file.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18649 sysvars: add `tidb_shard_row_id_bits` and `tidb_pre_split_regions`
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.4

#18629 add tikv date_add/date_sub/adddate/subdate functions
  functions-and-operators/expressions-pushed-down.md
Labels: translation/from-docs, size/XS, approved, lgtm, v8.4

#18774 add description about limitation
  sql-statements/sql-statement-change-column.md
  sql-statements/sql-statement-modify-column.md
  tidb-limitations.md
Labels: translation/done, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18184 cdc: add description about claim-check-raw-value
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18273 cdc: add description about checksum v2
  ticdc/ticdc-integrity-check.md
Labels: translation/done, size/S, approved, lgtm, v8.4

#18592 optimizer-fix-controls: Add optimizer fix control 47400 for controlling zero estRows
  optimizer-fix-controls.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, v8.4

#18658 TiDB supports `MID(str, pos[, len])`
  functions-and-operators/string-functions.md
Labels: translation/from-docs, size/S, for-release, approved, needs-1-more-lgtm, lgtm, v8.4

#18659 partition: global index GA & deprecated `tidb_enable_table_partition`, `tidb_enable_list_partition` and `tidb_enable_global_index`
  choose-index.md
  partitioned-table.md
  placement-rules-in-sql.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, needs-1-more-lgtm, lgtm, v8.4

#18557 planner: add variables for instance plan cache
  system-variables.md
Labels: translation/done, size/M, area/planner, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18651 *: add tidb_auto_analyze_concurrency
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18706 system variables: update the default value of tidb_enable_inl_join_inner_multi_pattern
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18772 update Go to v1.23
  hardware-and-software-requirements.md
  pd-control.md
  pd-recover.md
  tidb-control.md
Labels: translation/done, size/XS, for-release, approved, needs-1-more-lgtm, lgtm, v8.4

#18336 region: update region-size from 96MB to 256MB.
  best-practices/massive-regions-best-practices.md
  best-practices/pd-scheduling-best-practices.md
  glossary.md
  information-schema/information-schema-cluster-config.md
  pd-configuration-file.md
  pd-control.md
  tidb-storage.md
  tikv-configuration-file.md
  tikv-overview.md
  tune-region-performance.md
  tune-tikv-memory-performance.md
Labels: contribution, translation/done, size/L, type/compatibility-or-feature-change, approved, lgtm, ok-to-test, v8.4

#18646 add doc for schema cache
  TOC.md
  schema-cache.md
Labels: translation/done, size/M, approved, needs-1-more-lgtm, lgtm, v8.4

#18690 raft-engine: add the `spill-dir` config parameter
  tikv-configuration-file.md
Labels: contribution, translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, needs-cherry-pick-release-7.5, needs-ok-to-test, v8.4

#18716 sys-variables: update `tidb_schema_cache_size` default value
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18501 Add new resource control action SWITCH_GROUP
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-query-watch.md
  tidb-resource-control.md
Labels: translation/done, size/M, approved, lgtm, v8.4

#18457 update TTL doc to allow split tasks for utf8 column
  time-to-live.md
Labels: translation/done, size/S, for-release, approved, lgtm, v8.4

#18527 Update two informtion_schema tables desc
  information-schema/information-schema-processlist.md
  information-schema/information-schema-slow-query.md
Labels: translation/done, size/S, approved, lgtm, v8.4

#18849 performance-tuning-practices: fix wrong number
  performance-tuning-practices.md
Labels: translation/from-docs, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18650 br: add doc for log backup encryption
  br/br-pitr-manual.md
Labels: translation/from-docs, first-time-contributor, size/L, approved, lgtm, v8.4

#18522 tiproxy: add traffic replay doc
  TOC.md
  media/tiproxy/tiproxy-traffic-replay.png
  tiproxy/tiproxy-command-line-flags.md
  tiproxy/tiproxy-traffic-replay.md
Labels: translation/done, size/XL, approved, lgtm, v8.4

#18664 topsql: add aggregate by table or db
  dashboard/top-sql.md
  media/dashboard/top-sql-usage-agg-by-db-detail.png
  media/dashboard/top-sql-usage-select-agg-by.png
Labels: translation/done, size/M, approved, lgtm, v8.4

#18627 add logical-import-prep-stmt
  tidb-lightning/tidb-lightning-configuration.md
Labels: contribution, translation/from-docs, size/XS, approved, lgtm, ok-to-test, v8.4

#18575 resource_control: add processed_keys and ru to runaway
  information-schema/information-schema-runaway-watches.md
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-create-resource-group.md
  tidb-resource-control.md
Labels: translation/done, size/L, approved, lgtm, v8.4

#18611 resource_control: add repeats to `tidb_runaway_queries`
  tidb-resource-control.md
Labels: translation/done, size/S, approved, lgtm, v8.4

#18248 Added EXTRACT(<time unit> FROM <date/datetime/time col) as partition pruning function
  partition-pruning.md
  partitioned-table.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, v8.3, needs-cherry-pick-release-8.3

#18648 tikv config: Add in-memory lock tikv config
  dynamic-config.md
  pessimistic-transaction.md
  tikv-configuration-file.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18540 tikv: add new dynamic configure for flow-control
  dynamic-config.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v8.4

#18861 Add a section to explian the PBAC support for certs
  certificate-authentication.md
Labels: translation/from-docs, area/security, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18755 pd: support multi cn after 8.4
  enable-tls-between-components.md
Labels: translation/done, size/S, approved, lgtm, v8.4

#18726 Add system variable tidb_tso_client_rpc_mode
  system-variables.md
Labels: translation/done, size/M, area/transaction, type/compatibility-or-feature-change, approved, lgtm, v8.4

#18623 br: update restore checkpoint information
  br/backup-and-restore-storages.md
  br/backup-and-restore-use-cases.md
  br/br-checkpoint-restore.md
Labels: translation/done, size/S, approved, lgtm, v8.4

#18866 pd: add note for member `leader_priority`
  dr-multi-replica.md
  pd-control.md
  placement-rules-in-sql.md
  three-data-centers-in-two-cities-deployment.md
Labels: type/enhancement, translation/doing, size/S, area/scheduling, approved, needs-1-more-lgtm, lgtm

#18869 Update dm-stop-task.md
  dm/dm-stop-task.md
Labels: translation/done, size/XS, area/dm, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18879 Fix a JSON function typo
  functions-and-operators/json-functions.md
Labels: translation/no-need, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18871 fix: typo of jdbc v8.0.32
  develop/dev-guide-choose-driver-or-orm.md
Labels: translation/from-docs, size/XS, ONCALL, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18820 v8.4: add APPLY, RECOMMEND, TIDB_CURRENT_TSO keywords
  keywords.md
Labels: translation/done, size/XS, for-release, approved, needs-1-more-lgtm, lgtm, v8.4

#18891 glossary: link TSO to the TSO doc
  glossary.md
Labels: type/enhancement, translation/from-docs, size/XS, ONCALL, approved, lgtm

#18502 TiDB vector search doc
  TOC.md
  br/backup-and-restore-overview.md
  dm/dm-overview.md
  media/vector-search/embedding-search.png
  ticdc/ticdc-compatibility.md
  tiflash-upgrade-guide.md
  tiflash/tiflash-configuration.md
  vector-search-data-types.md
  vector-search-functions-and-operators.md
  vector-search-get-started-using-python.md
  vector-search-get-started-using-sql.md
  vector-search-improve-performance.md
  vector-search-index.md
  vector-search-integrate-with-django-orm.md
  vector-search-integrate-with-jinaai-embedding.md
  vector-search-integrate-with-langchain.md
  vector-search-integrate-with-llamaindex.md
  vector-search-integrate-with-peewee.md
  vector-search-integrate-with-sqlalchemy.md
  vector-search-integration-overview.md
  vector-search-limitations.md
  vector-search-overview.md
Labels: translation/done, first-time-contributor, size/XXL, approved, lgtm, v8.4

#18898 Update system-variables.md
  system-variables.md
Labels: contribution, translation/doing, size/XS, approved, lgtm, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18897 update the links in the index page to v8.4
  _index.md
Labels: translation/done, size/M, for-release, approved, needs-1-more-lgtm, lgtm, v8.4

#18895 Update docs around slow_query tables
  information-schema/information-schema-slow-query.md
  system-variables.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm

#18902 ddl-introduction: switch the tab of pre-v6.2 info and post-v6.2 info
  ddl-introduction.md
Labels: translation/from-docs, size/M, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18878 *: remove most of Telemetry related contents
  TOC.md
  keywords.md
  pd-configuration-file.md
  releases/release-6.1.5.md
  releases/release-6.5.1.md
  releases/release-6.6.0.md
  releases/release-8.1.0.md
  sql-statements/sql-statement-admin-show-telemetry.md
  sql-statements/sql-statement-admin.md
  sql-statements/sql-statement-overview.md
  system-variables.md
  telemetry.md
  tidb-configuration-file.md
Labels: translation/from-docs, size/XXL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18901 Add tiflash supported pushdown for vector functions
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: translation/done, size/XS, approved, lgtm, v8.4, needs-cherry-pick-release-8.4

#18904 dm-best-practices: Update for MySQL Compatible AUTO_INCREMENT
  dm/dm-best-practices.md
Labels: translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.4

#18920 Add TiCDC config "changefeed-error-stuck-duration" to v6.5.6 release notes
  releases/release-6.5.6.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18919 tikv-configuration: mark raft-engine.bytes-per-sync as deprecated
  releases/release-6.5.0.md
  tikv-configuration-file.md
Labels: translation/done, size/XS, area/engine, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18935 Improve migration from from CSV files
  migrate-from-csv-files-to-tidb.md
Labels: type/enhancement, translation/done, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18817 *: add tidb_enable_stats_owner
  system-variables.md
  tidb-configuration-file.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.4, needs-cherry-pick-release-8.4

#18936 cdc: remove mention about force-replicate
  ticdc/ticdc-overview.md
Labels: translation/done, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, approved, lgtm

#18865 cdc: add warn for event filter
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4

#18541 remove by name for alert of TiKV_raftstore_thread_cpu_seconds_total
  alert-rules.md
Labels: translation/done, first-time-contributor, size/XS, area/engine, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.4
