Repository pingcap/docs-cn, pull requests merged in 2024-09, with the labels that each got.

#17854 faq: update character set description
  character-set-and-collation.md
  faq/sql-faq.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18425 *: add a limitation about not supporting `NULLIF()` and supporting `CASE`
  generated-columns.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18499 system-variables: change the default value of `tidb_schema_cache_size`
  releases/release-8.3.0.md
  system-variables.md
Labels: contribution, translation/done, size/XS, approved, lgtm, v8.3, needs-cherry-pick-release-8.3

#18514 sql: change the thread value from 16 to 8
  sql-statements/sql-statement-import-into.md
Labels: translation/done, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18523 sql_plan_management: use `idx_a` for index name
  sql-plan-management.md
Labels: translation/done, size/M, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18536 glossary: fix descrption about isolation
  glossary.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18544 tidb: add a note for `cross-join`
  tidb-configuration-file.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#18545 ticdc: add a note about schema
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18378 pd: remove shuffle schedulers
  pd-control.md
Labels: translation/done, size/XS, area/scheduling, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18568 dashboard: add SSO for dashboard access
  dashboard/dashboard-access.md
Labels: translation/from-docs, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18555 Update tiflash-configuration.md
  tiflash/tiflash-configuration.md
Labels: translation/done, first-time-contributor, size/XS, approved, lgtm, needs-ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18577 fix typo in information-schema-inspection-result.md
  information-schema/information-schema-inspection-result.md
Labels: translation/done, type/bug-fix, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18526 PD: optimize the description of label-property
  pd-configuration-file.md
Labels: translation/doing, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18528 develop: update TiDB Cloud Import page and Connect page
  develop/dev-guide-bookshop-schema-design.md
  develop/dev-guide-gui-mysql-workbench.md
  develop/dev-guide-gui-navicat.md
  develop/dev-guide-sample-application-aws-lambda.md
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
  develop/dev-guide-sample-application-nextjs.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-sequelize.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-mysqlclient.md
  develop/dev-guide-sample-application-python-peewee.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
Labels: translation/from-docs, size/L, area/develop, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18520 *: update TiDB product names
  TOC.md
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-create-database.md
  develop/dev-guide-create-secondary-indexes.md
  develop/dev-guide-create-table.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-gui-mysql-workbench.md
  develop/dev-guide-gui-navicat.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-sample-application-aws-lambda.md
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
  develop/dev-guide-sample-application-nextjs.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-sequelize.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-mysqlclient.md
  develop/dev-guide-sample-application-python-peewee.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  develop/dev-guide-tidb-crud-sql.md
  develop/dev-guide-update-data.md
  releases/release-7.0.0.md
  releases/release-7.1.0.md
  releases/release-7.5.0.md
  releases/release-8.1.0.md
  tidb-resource-control.md
Labels: translation/from-docs, size/XL, area/develop, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#18602 develop: unify product names
  develop/dev-guide-gui-mysql-workbench.md
  develop/dev-guide-gui-navicat.md
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-sequelize.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-mysqlclient.md
  develop/dev-guide-sample-application-python-peewee.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
Labels: translation/no-need, area/develop, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#18603 add limit to import into
  sql-statements/sql-statement-import-into.md
Labels: translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#18606 Update homepage titles
  _docHome.md
Labels: translation/done, first-time-contributor, size/XS, approved, needs-1-more-lgtm, lgtm

#18615 refactor(doc): redesign the global home doc
  _docHome.md
Labels: translation/no-need, size/M, approved, needs-1-more-lgtm, lgtm

#18624 Remove an extra bracket in PR template
  .github/pull_request_template.md
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#18619 Add security configuration documentation and migrate security docs directory
  TOC.md
  best-practices-for-security-configuration.md
  media/grafana-password-reset1.png
  media/grafana-password-reset2.png
Labels: type/enhancement, contribution, translation/doing, area/security, first-time-contributor, size/L, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18641 change lightning conflict resolution `ignore`
  tidb-lightning/tidb-lightning-logical-import-mode-usage.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#18643 Add security configuration documentation and migrate security docs directory
  TOC.md
  best-practices-for-security-configuration.md
  media/grafana-password-reset1.png
  media/grafana-password-reset2.png
Labels: translation/no-need, size/L, approved, needs-1-more-lgtm, lgtm

#18652 Update a link in TiDB Lightning data sources
  tidb-lightning/tidb-lightning-data-source.md
Labels: translation/from-docs, requires-version-specific-changes, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18660 faq: update the description of "Information schema is out of date"
  faq/sql-faq.md
Labels: translation/done, type/bugfix, size/XS, area/sql-infra, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18663 Remove All Binlog References from CDC Documentation
  dr-secondary-cluster.md
Labels: translation/from-docs, first-time-contributor, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18677 *: fix the default value of cdc.min-ts-interval
  releases/release-6.5.0.md
  releases/release-6.5.1.md
  tikv-configuration-file.md
Labels: translation/from-docs, type/bugfix, size/S, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18599 add v6.5.11 release notes
  TOC.md
  releases/release-6.5.11.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18647 v6.5: bump up the latest version to v6.5.11
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm

#18612 tidb: add description about `TIDB_CHECK_CONSTRAINTS`
  TOC.md
  information-schema/information-schema-check-constraints.md
  information-schema/information-schema-tidb-check-constraints.md
Labels: translation/from-docs, size/M, for-release, approved, lgtm, needs-cherry-pick-release-8.1

#18693 system-variables: optimize the persist info
  system-variables.md
Labels: translation/done, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18543 auto-increment.md: add invalidate cache descriptions
  auto-increment.md
Labels: translation/doing, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#12674 Add a notice for pd configuration
  pd-configuration-file.md
Labels: type/enhancement, size/XS, area/scheduling, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18625 *: add aliases for 21 deleted TiDB Binlog docs from dev
  sql-statements/sql-statement-change-drainer.md
  sql-statements/sql-statement-change-pump.md
  sql-statements/sql-statement-show-drainer-status.md
  sql-statements/sql-statement-show-pump-status.md
  tidb-binlog-deployment-topology.md
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
  tidb-binlog/binlog-consumer-client.md
  tidb-binlog/binlog-control.md
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-binlog/handle-tidb-binlog-errors.md
  tidb-binlog/maintain-tidb-binlog-cluster.md
  tidb-binlog/monitor-tidb-binlog-cluster.md
  tidb-binlog/tidb-binlog-configuration-file.md
  tidb-binlog/tidb-binlog-faq.md
  tidb-binlog/tidb-binlog-glossary.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-binlog/tidb-binlog-relay-log.md
  tidb-binlog/tidb-binlog-reparo.md
  tidb-binlog/troubleshoot-tidb-binlog.md
  tidb-binlog/upgrade-tidb-binlog.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, v8.4
