Repository pingcap/docs-cn, pull requests merged in 2024-12, with the labels that each got.

#19023 Add service-middleware config for pd-ctl
  pd-control.md
Labels: translation/done, size/L, area/scheduling, approved, lgtm, v8.5

#19121 Bulk update integer display width
  auto-increment.md
  auto-random.md
  basic-sql-operations.md
  cached-tables.md
  clustered-indexes.md
  constraints.md
  cost-model.md
  develop/dev-guide-bookshop-schema-design.md
  develop/dev-guide-create-secondary-indexes.md
  develop/dev-guide-index-best-practice.md
  develop/dev-guide-transaction-restraints.md
  develop/dev-guide-unique-serial-number-generation.md
  dm/dm-manage-schema.md
  dm/dm-open-api.md
  dm/dm-performance-test.md
  dm/dm-table-routing.md
  dm/feature-online-ddl.md
  dm/handle-failed-ddl-statements.md
  dm/manually-handling-sharding-ddl-locks.md
  dm/shard-merge-best-practices.md
  dumpling-overview.md
  explain-walkthrough.md
  foreign-key.md
  functions-and-operators/tidb-functions.md
  migrate-large-mysql-shards-to-tidb.md
  migrate-small-mysql-shards-to-tidb.md
  migrate-with-more-columns-downstream.md
  mysql-schema/mysql-schema-user.md
  partitioned-table.md
  performance-schema/performance-schema-session-connect-attrs.md
  placement-rules-in-sql.md
  post-installation-check.md
  sql-plan-replayer.md
  sql-statements/sql-statement-alter-index.md
  sql-statements/sql-statement-create-table.md
  sql-statements/sql-statement-modify-column.md
  sql-statements/sql-statement-rename-index.md
  sql-statements/sql-statement-show-columns-from.md
  sql-statements/sql-statement-show-create-table.md
  sql-statements/sql-statement-show-placement-for.md
  system-variables.md
  ticdc/integrate-confluent-using-ticdc.md
  ticdc/ticdc-faq.md
  tidb-lightning/tidb-lightning-error-resolution.md
  tidb-lightning/tidb-lightning-physical-import-mode-usage.md
  tiflash/use-tiflash-mpp-mode.md
Labels: translation/from-docs, size/XL, area/develop, for-release, approved, needs-1-more-lgtm, lgtm, v8.5

#19085 docs: add documentation for ADMIN ALTER DDL JOBS command
  TOC.md
  sql-statements/sql-statement-admin-alter-ddl.md
  sql-statements/sql-statement-admin-show-ddl.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.5, v8.5

#19189 release-8.1: add a note for Red Hat Enterprise Linux 7
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#19188 Update hardware-and-software-requirements.md
  hardware-and-software-requirements.md
  releases/release-8.4.0.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19191 add aliases for Binlog docs
  sql-statements/sql-statement-change-drainer.md
  sql-statements/sql-statement-change-pump.md
  sql-statements/sql-statement-show-drainer-status.md
  sql-statements/sql-statement-show-pump-status.md
  tidb-binlog-deployment-topology.md
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
  tidb-binlog/binlog-consumer-client.md
  tidb-binlog/binlog-control.md
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/handle-tidb-binlog-errors.md
  tidb-binlog/maintain-tidb-binlog-cluster.md
  tidb-binlog/monitor-tidb-binlog-cluster.md
  tidb-binlog/tidb-binlog-configuration-file.md
  tidb-binlog/tidb-binlog-faq.md
  tidb-binlog/tidb-binlog-glossary.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-binlog/tidb-binlog-relay-log.md
  tidb-binlog/tidb-binlog-reparo.md
  tidb-binlog/troubleshoot-tidb-binlog.md
  tidb-binlog/upgrade-tidb-binlog.md
Labels: translation/done, size/M, approved, needs-1-more-lgtm, lgtm

#19183 update cdnfresh.txt for v8.1 and v8.5
  resources/cdnfresh.txt
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#19195 privilege: change privilege for `SHOW PROCESSLIST` from `SUPER` to `PROCESS`
  privilege-management.md
Labels: translation/done, type/bugfix, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19184 update hardware-and-software-requirements.md for v8.5
  hardware-and-software-requirements.md
Labels: translation/done, size/M, for-release, approved, needs-1-more-lgtm, lgtm, v8.5

#19203 remove https://github.com/apps/renovate from release notes
  releases/release-8.3.0.md
Labels: size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19187 store limit v2: remove experimental description
  pd-configuration-file.md
  pd-control.md
  releases/release-7.1.0.md
Labels: translation/done, size/S, for-release, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, v8.5

#19131 store limit v2: add more experimental description
  configure-store-limit.md
  pd-control.md
  releases/release-7.1.0.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#19215 Update optimizer-fix-controls.md
  optimizer-fix-controls.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19221 ticdc: fix alert doc
  ticdc/ticdc-alert-rules.md
Labels: translation/done, size/M, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#18628 Emphasis the importance of input of unsafe recovery
  online-unsafe-recovery.md
Labels: contribution, translation/done, size/S, approved, lgtm, ok-to-test, needs-cherry-pick-release-8.5

#19224 update OWNERS
  OWNERS
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm

#19228 sync_diff_inspector: add the check-data-only configuration item
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: translation/done, first-time-contributor, size/XS, area/sync-diff-inspector, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19196 release-8.5: add release-8.5 to dispatch.yml
  .github/workflows/dispatch.yml
Labels: translation/from-docs, size/XS, for-release, approved, needs-1-more-lgtm, lgtm, v8.5

#19226 Announce GA of memory control on stats cache
  releases/release-7.4.0.md
  system-variables.md
Labels: translation/done, size/S, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19227 Recommend RC instead of SQL Priority
  faq/sql-faq.md
  sql-statements/sql-statement-insert.md
  sql-statements/sql-statement-replace.md
  sql-statements/sql-statement-select.md
  sql-statements/sql-statement-update.md
Labels: type/enhancement, translation/done, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19118 Add IME document
  TOC.md
  analyze-slow-queries.md
  media/tikv-ime-data-organization.png
  tikv-configuration-file.md
  tikv-in-memory-engine.md
  troubleshoot-hot-spot-issues.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.5, v8.5

#18870 tiup: restriction about DXF
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19194 pd: add patrol-region-worker-count
  dynamic-config.md
  pd-configuration-file.md
  pd-control.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, needs-cherry-pick-release-8.5, v8.5

#19254 br: change the default value of table-level checksum to false
  br/br-snapshot-manual.md
Labels: translation/done, size/XS, area/br, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, v8.5

#19248 cdc: add release version for the simple protocol
  ticdc/ticdc-simple-protocol.md
Labels: type/enhancement, translation/doing, size/XS, area/ticdc, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19270 sql: fix the synopsis of `REVOKE <privileges>`
  sql-statements/sql-statement-revoke-privileges.md
Labels: translation/done, type/bugfix, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19229 Update explain and execution summary related docs
  explain-overview.md
  sql-statements/sql-statement-explain-analyze.md
  sql-statements/sql-statement-explain.md
Labels: translation/done, size/M, approved, lgtm

#19279 deploy: add glibc 2.28 requirements
  hardware-and-software-requirements.md
Labels: type/enhancement, translation/done, requires-version-specific-changes, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19283 tiup: refine description about `tiup playground --tag`
  quick-start-with-tidb.md
  tiup/tiup-playground.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19300 planner: update the default value of 46177
  optimizer-fix-controls.md
Labels: translation/done, size/XS, area/planner, approved, lgtm, needs-cherry-pick-release-8.5

#19301 planner: fix the default value of 46177 to OFF for versions earlier than 8.5
  optimizer-fix-controls.md
Labels: translation/done, size/XS, area/planner, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#18903 flashback: add limitation with stale read/snapshot
  sql-statements/sql-statement-flashback-cluster.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19315 fix version-mark format for shared-blob-cache
  releases/release-8.0.0.md
  storage-engine/titan-configuration.md
  tikv-configuration-file.md
Labels: translation/done, type/bugfix, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19317 *: improve deployment doc and toc
  dr-secondary-cluster.md
  explore-htap.md
  faq/deploy-and-maintain-faq.md
  hardware-and-software-requirements.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  releases/release-8.4.0.md
  ticdc/deploy-ticdc.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19297 wrong-index-solution: update
  wrong-index-solution.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19140 update basic-features.md for v8.5
  basic-features.md
Labels: translation/done, size/XL, approved, lgtm, needs-cherry-pick-release-8.5, v8.5

#19033 add v8.5.0 release notes
  TOC.md
  releases/release-8.5.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/from-docs, size/XL, approved, lgtm, needs-cherry-pick-release-8.5, v8.5

#19181 bump the latest version of TiDB to v8.5
  br/backup-and-restore-use-cases.md
  certificate-authentication.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  functions-and-operators/tidb-functions.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  performance-schema/performance-schema-session-connect-attrs.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-microservices-using-tiup.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-integrity-check.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/from-docs, size/L, area/develop, for-release, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, v8.5

#19328 check-before-deployment: add selinux
  check-before-deployment.md
  dm/quick-start-with-dm.md
Labels: translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19166 cdc: reformat Changefeed config and Server config
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-server-config.md
Labels: type/enhancement, translation/done, size/XXL, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19332 add warnings for CentOS 7 usage
  hardware-and-software-requirements.md
  releases/release-8.4.0.md
  releases/release-8.5.0.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, needs-cherry-pick-master, size/M, approved, needs-1-more-lgtm, lgtm

#19346 fix typos
  releases/release-8.5.0.md
  schema-cache.md
Labels: translation/no-need, approved, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19349 dm: update the example version to 8.5.0
  dm/quick-start-with-dm.md
Labels: type/enhancement, translation/from-docs, requires-version-specific-changes, size/XS, area/dm, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.5

#19356 add v9.0 in pull_request_template.md
  .github/pull_request_template.md
Labels: translation/from-docs, size/XS, approved, lgtm

#19357 tiup-playground: add info about TiProxy
  tiup/tiup-playground.md
Labels: translation/done, size/S, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19261 Improve usage of `IMPORT FROM SELECT`
  sql-statements/sql-statement-import-into.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19342 release-8.5.0.md: add the performance test section
  releases/release-8.5.0.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.5

#18388 sql: Update sql-statement-flashback-cluster.md
  sql-statements/sql-statement-flashback-cluster.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19371 README.md: add release-8.5
  README.md
Labels: translation/done, size/XS, approved, lgtm

#18525 fix the table schema for cluster_tidb_index_usage
  information-schema/information-schema-tidb-index-usage.md
Labels: translation/done, size/M, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19362 Update output of SHOW BUILTINS
  sql-statements/sql-statement-show-builtins.md
Labels: translation/from-docs, size/S, approved, lgtm

#19345 Update how to connect TiDB by MySQL Client and the limitations of the global indexes
  develop/dev-guide-connect-to-tidb.md
  partitioned-table.md
Labels: contribution, translation/done, size/S, area/develop, approved, lgtm, needs-cherry-pick-release-8.5

#19262 br: add compatibility notes to the Before you use section
  br/backup-and-restore-overview.md
Labels: type/enhancement, translation/doing, size/XS, ONCALL, area/br, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19318 v8.1.2: dynamic config add `import.num-threads`
  dynamic-config.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19298 add release notes for v8.1.2
  TOC.md
  releases/release-8.1.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19320 v8.1.2: bump version
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  dm/quick-start-with-dm.md
  functions-and-operators/json-functions.md
  functions-and-operators/tidb-functions.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  performance-schema/performance-schema-session-connect-attrs.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#18970 restore: update full restore speed
  br/backup-and-restore-overview.md
  br/br-pitr-guide.md
Labels: translation/done, size/S, area/br, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19399 add `json_schema_valid` into `tidb_allow_function_for_expression_index`
  sql-statements/sql-statement-create-index.md
  system-variables.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19404 Update the limitations of schema-cache
  schema-cache.md
Labels: contribution, translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19407 pd-control: update the section level of service-middleware configurations
  pd-control.md
Labels: area/scheduling, ONCALL, approved, lgtm, needs-cherry-pick-release-8.5

#19409 configuration-file: correct the initial capitalization of certain configuration items
  pd-configuration-file.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#15412 Add lightning import support for parquet format files exported by Snowflake
  ecosystem-tool-user-guide.md
  migration-tools.md
  tidb-lightning/tidb-lightning-data-source.md
  tidb-lightning/tidb-lightning-faq.md
  tidb-lightning/tidb-lightning-overview.md
Labels: translation/from-docs, size/S, area/tidb-lightning, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19414 chore: remove v5.3/v8.2 from PR template
  .github/pull_request_template.md
  README.md
  resources/cdnfresh.txt
Labels: missing-translation-status, size/S, approved, lgtm

#19423 Update the limitation of the Global index
  partitioned-table.md
Labels: contribution, translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19282 v7.5.5: introduce tidb_ddl_reorg_max_write_speed
  sql-statements/sql-statement-admin-alter-ddl.md
  system-variables.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19299 add release notes for v7.5.5
  TOC.md
  releases/release-7.5.5.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19321 v7.5.5: bump version
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  dm/quick-start-with-dm.md
  external-storage-uri.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#19432 update clinic free period
  clinic/clinic-introduction.md
Labels: translation/done, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4, needs-cherry-pick-release-8.2

#19445 v7.5.5: support Kylin SP3 (master branch)
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#19444 v7.5.5: support Kylin SP3
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5
