Repository pingcap/docs-cn, pull requests merged in 2024-08, with the labels that each got.

#18215 dumpling: update the gc info
  develop/dev-guide-timeouts-in-tidb.md
  dumpling-overview.md
  migrate-from-tidb-to-mysql.md
Labels: size/XS, ONCALL, area/dumpling, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18227 alert: remove keep_alive_total metric
  alert-rules.md
Labels: translation/done, size/S, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18232 bit-functions-and-operators: fix PDF build issue
  functions-and-operators/bit-functions-and-operators.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18242 sql-logical-optimization: add an entry for derive topN and limit
  sql-logical-optimization.md
Labels: type/enhancement, translation/done, size/XS, area/planner, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#17907 Add I_S.keywords for v7.5
  TOC.md
  develop/dev-guide-choose-driver-or-orm.md
  information-schema/information-schema-keywords.md
  information-schema/information-schema.md
  keywords.md
Labels: translation/from-docs, size/M, type/compatibility-or-feature-change, area/develop, approved, needs-1-more-lgtm, lgtm

#18239 Update DDL descriptions in cluster upgrade
  upgrade-tidb-using-tiup.md
Labels: type/enhancement, translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18216 Fix typo in predicate-push-down.md
  predicate-push-down.md
Labels: contribution, translation/no-need, type/bug-fix, first-time-contributor, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-ok-to-test, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18257 v7.5.3: add information_schema.keywords
  information-schema/information-schema-keywords.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18078 add release notes for 7.5.3
  TOC.md
  releases/release-7.5.3.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18161 br: add "tiup br debug" command
  br/use-br-command-line-tool.md
Labels: translation/done, size/S, ONCALL, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18228 pd: add an example for pd-recover
  pd-recover.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18279 tidb: add a bugfix about issue https://github.com/pingcap/tidb/issues/54652
  releases/release-7.5.3.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18285 sql: delete PLACEMENT(S) in keywords
  keywords.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18293 update the maximum region size for TiFlash
  tune-region-performance.md
Labels: translation/doing, area/engine, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18290 partitioned tables: add some restrictions
  partitioned-table.md
  sql-statements/sql-statement-create-table.md
Labels: type/enhancement, translation/from-docs, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18283 Update keywords.md
  keywords.md
Labels: contribution, translation/done, size/XS, approved, lgtm, ok-to-test, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18292 add ticdc pulsar sink related release note
  releases/release-8.2.0.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.2

#18308 cdc: update output-raw-change-event comment link
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, requires-version-specific-changes, size/XS, area/ticdc, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18323 sys var: add more contents to `tidb_remove_orderby_in_subquery`
  system-variables.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18326 cdc: deprecate the enable-old-value to the previous v7.4 release-note
  releases/release-7.4.0.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18341 fix: use `""` to represent empty string
  tiproxy/tiproxy-configuration.md
Labels: translation/done, type/bug-fix, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18339 add an example of using AUTO_RANDOM with PRE_SPLIT_REGIONS
  auto-random.md
Labels: type/enhancement, translation/done, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18340 update pre_split_regions usage scenario
  sql-statements/sql-statement-split-region.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18230 sys var: add global scope for `tidb_low_resolution_tso`
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, approved, lgtm, v8.3

#18345 make bdr ddl replicate GA
  sql-statements/sql-statement-admin-bdr-role.md
  ticdc/ticdc-bidirectional-replication.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, v8.3

#18214 update doc related to fast-create
  accelerated-table-creation.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/S, for-release, approved, lgtm, v8.3

#18359 sys-var: add SESSION scope for `ddl_reorg_batch_size` and `ddl_reorg_worker_cnt`
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, needs-1-more-lgtm, lgtm, v8.3

#17835 Update the log redaction documentation
  log-redaction.md
  pd-configuration-file.md
  tiflash/tiflash-configuration.md
  tikv-configuration-file.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v8.3

#18360 cdc: canal-json dml event commit-ts should be tso
  ticdc/ticdc-canal-json.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, type/bug-fix, size/S, needs-cherry-pick-release-5.4, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18361 remove ambiguous TTL from glossary
  glossary.md
Labels: translation/done, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18229 sys var: add `tidb_enable_shared_lock_promotion` related doc change
  pessimistic-transaction.md
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.3

#17893 br: make inc + log restore compatible
  br/br-incremental-guide.md
  br/br-pitr-manual.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.3

#18097 Add tidb_analyze_column_options on statistics for predicate columns
  benchmark/benchmark-tidb-using-ch.md
  statistics.md
  system-variables.md
  tiup/tiup-bench.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, v8.3

#18073 variable: add document about lazy cursor fetch and its variable
  best-practices/java-app-best-practices.md
  develop/dev-guide-connection-parameters.md
  system-variables.md
Labels: translation/from-docs, size/M, area/develop, approved, lgtm, v8.3

#18335 *: add batch operation for creating/dropping binding by specifying digests
  sql-plan-management.md
  sql-statements/sql-statement-create-binding.md
  sql-statements/sql-statement-drop-binding.md
Labels: translation/done, size/XL, approved, lgtm, v8.3

#18376 bdr ga
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, v8.3

#18377 move issue #36004 to v6.5.7 release notes
  releases/release-6.5.7.md
  releases/release-6.5.8.md
  releases/release-6.5.9.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18217 partition: add doc for global index
  partitioned-table.md
  placement-rules-in-sql.md
  sql-statements/sql-statement-add-column.md
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-create-table.md
  system-variables.md
Labels: translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm, v8.3

#18079 tiproxy: add vip configurations
  tiproxy/tiproxy-configuration.md
  tiproxy/tiproxy-deployment-topology.md
  tiproxy/tiproxy-grafana.md
  tiproxy/tiproxy-load-balance.md
  tiproxy/tiproxy-overview.md
Labels: translation/done, size/M, approved, lgtm, v8.3

#18098 Add doc for TopN spill
  configure-memory-usage.md
Labels: translation/done, size/XS, approved, lgtm, v8.3

#18226 system-variables: add tiflash_hashagg_preaggregation_mode
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.3

#18238 add the root type expand impl for rollup syntax.
  explain-aggregation.md
  functions-and-operators/group-by-modifier.md
Labels: translation/done, size/M, approved, lgtm, v8.3

#18164 doc: session_alias and rows_affected in information_schema.processlist
  identify-expensive-queries.md
  information-schema/information-schema-processlist.md
  releases/release-8.2.0.md
Labels: translation/done, size/L, approved, lgtm, v8.3

#18202 br: add issue for pitr usage
  br/br-pitr-manual.md
Labels: translation/done, size/XS, area/br, approved, lgtm, v8.3

#18346 Deprecate TiDB Binlog
  TOC.md
  basic-features.md
  ecosystem-tool-user-guide.md
  faq/deploy-and-maintain-faq.md
  production-deployment-using-tiup.md
  sql-statements/sql-statement-flashback-database.md
  sql-statements/sql-statement-flashback-table.md
  sql-statements/sql-statement-recover-table.md
  system-variables.md
  ticdc-deployment-topology.md
  tidb-binlog-deployment-topology.md
  tidb-binlog/bidirectional-replication-between-tidb-clusters.md
  tidb-binlog/binlog-control.md
  tidb-binlog/deploy-tidb-binlog.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-binlog/upgrade-tidb-binlog.md
  tidb-troubleshooting-map.md
  transaction-overview.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/M, for-release, approved, needs-1-more-lgtm, lgtm, v8.3

#18231 tidb: add doc for `batch-policy` config
  tidb-configuration-file.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.3

#17891 Change tidb_opt_projection_push_down default value to ON
  system-variables.md
Labels: translation/done, first-time-contributor, size/S, type/compatibility-or-feature-change, approved, lgtm, v8.3

#18225 br: docs on restore disk protection
  br/br-snapshot-guide.md
Labels: translation/done, size/XS, approved, lgtm, v8.3, needs-cherry-pick-release-8.3

#18387 PD: add description of batch in evict-leader-scheduler config
  pd-control.md
Labels: translation/doing, size/XS, for-release, approved, lgtm, v8.3, needs-cherry-pick-release-8.3

#18394 v8.3.0: update learning path
  _index.md
Labels: contribution, translation/done, size/M, approved, needs-1-more-lgtm, lgtm

#18313 Add TiDB best practices on public cloud
  TOC.md
  best-practices-on-public-cloud.md
  media/performance/public-cloud-best-practice/after_tuning_cpu.png
  media/performance/public-cloud-best-practice/after_tuning_metrics.png
  media/performance/public-cloud-best-practice/baseline_cpu.png
  media/performance/public-cloud-best-practice/baseline_metrics.png
Labels: translation/from-docs, area/best-practices, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2

#18117 doc: concurrency of gc delete-range
  system-variables.md
Labels: translation/done, size/XS, approved, lgtm, v8.3, needs-cherry-pick-release-8.3

#18402 pd: Fix the default name of the configuration
  command-line-flags-for-pd-configuration.md
Labels: translation/done, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18095 add v8.3.0 release notes
  TOC.md
  releases/release-8.3.0.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/XL, approved, lgtm, v8.3, needs-cherry-pick-release-8.3

#18375 basic-features.md: add a column for v8.3.0
  basic-features.md
Labels: contribution, translation/done, size/XL, approved, lgtm, v8.3, needs-cherry-pick-release-8.3

#18391 PD: Add the name field to the startup parameters
  command-line-flags-for-scheduling-configuration.md
  command-line-flags-for-tso-configuration.md
Labels: translation/done, size/S, for-release, approved, lgtm, v8.3, needs-cherry-pick-release-8.3

#18403 Update cdnfresh.txt for v8.3
  resources/cdnfresh.txt
Labels: translation/no-need, size/XS, approved, needs-1-more-lgtm, lgtm

#18390 v8.3: bump the latest TiDB version to v8.3
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  functions-and-operators/tidb-functions.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  performance-schema/performance-schema-session-connect-attrs.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-microservices-using-tiup.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3

#18421 pull_request_template: add v8.4
  .github/pull_request_template.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#18423 TOC: add v8.3 release notes
  TOC.md
Labels: size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3

#18422 Make the introduced version clear for "txn-entry-size-limit"
  data-type-string.md
  develop/dev-guide-transaction-restraints.md
  error-codes.md
  faq/backup-and-restore-faq.md
  faq/migration-tidb-faq.md
  releases/release-6.1.1.md
  releases/release-6.1.2.md
  releases/release-6.1.4.md
  releases/release-6.1.7.md
  releases/release-6.3.0.md
  releases/release-6.4.0.md
  releases/release-6.5.1.md
  releases/release-6.5.10.md
  releases/release-6.5.2.md
  releases/release-6.5.3.md
  releases/release-6.5.4.md
  releases/release-6.5.6.md
  releases/release-6.6.0.md
  releases/release-7.0.0.md
  releases/release-7.1.0.md
  releases/release-7.1.1.md
  releases/release-7.1.3.md
  releases/release-7.1.4.md
  releases/release-7.1.5.md
  releases/release-7.2.0.md
  releases/release-7.4.0.md
  releases/release-7.5.0.md
  releases/release-7.5.1.md
  releases/release-7.5.2.md
  releases/release-7.5.3.md
  releases/release-7.6.0.md
  releases/release-8.0.0.md
  releases/release-8.1.0.md
  releases/release-8.2.0.md
  releases/release-8.3.0.md
  system-variables.md
  tidb-configuration-file.md
  tidb-limitations.md
Labels: type/enhancement, translation/done, requires-version-specific-changes, size/L, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18362 *: Rename snap-max-write-bytes-per-sec (tiflash)
  tiflash/create-tiflash-replicas.md
Labels: translation/done, type/bug-fix, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18444 *: add 8.2 and 8.3 to README.md
  README.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18447 Add keywords for 8.3.0
  keywords.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3

#18385 Update system-variable ‘tidb_ddl_reorg_batch_size’
  system-variables.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18333 dev, v8.2, and v8.3: add v8.1.1 to ticdc split behavior for update events
  ticdc/ticdc-split-update-behavior.md
Labels: translation/done, size/XS, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18338 v8.1.1: Turn off hash agg spill by default
  system-variables.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#18332 v8.1.1: update ticdc split behavior for update events
  ticdc/ticdc-split-update-behavior.md
Labels: translation/done, size/S, area/ticdc, approved, needs-1-more-lgtm, lgtm

#18420 remove arbiter from v8.1.1
  binary-package.md
  tidb-configuration-file.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#18278 add v8.1.1 release notes
  TOC.md
  releases/release-8.1.1.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18461 release-8.3.0.md: refine the description of #54565
  releases/release-8.3.0.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3

#16873 Add debezium disable schema doc for ticdc
  releases/release-8.0.0.md
  ticdc/ticdc-changefeed-config.md
Labels: translation/doing, size/XS, approved, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#17689 ticdc: Update migrate from tidb to tidb doc
  migrate-from-tidb-to-tidb.md
Labels: translation/done, size/XS, area/ticdc, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18463 Revise TSO related Grafana monitoring metrics description
  dashboard/dashboard-monitoring.md
  grafana-overview-dashboard.md
  grafana-performance-overview-dashboard.md
  grafana-tidb-dashboard.md
Labels: translation/done, size/S, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18465 Make "right-derive-when-split" description more clear
  tikv-configuration-file.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.2, needs-cherry-pick-release-8.3

#18464 SELECT: Update EBNF for partitioning
  sql-statements/sql-statement-select.md
Labels: type/enhancement, translation/from-docs, size/M, area/sql-infra, approved, needs-1-more-lgtm, lgtm

#18497 chore: remove v5.2/v8.0 from PR template
  .github/pull_request_template.md
  README.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm
