Repository pingcap/docs-cn, pull requests merged in 2024-06, with the labels that each got.

#17512 system-variables: fix a typo for `hostname` description
  system-variables.md
Labels: translation/no-need, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17490 information-schema: update the description for the tikv-region-status table
  information-schema/information-schema-tikv-region-status.md
Labels: translation/doing, size/S, area/engine, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17492 TiCDC: modify Kafka sink uri format
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/from-docs, size/S, ONCALL, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-ok-to-test, needs-cherry-pick-release-8.1

#17513 br: adjust br related statement
  br/br-snapshot-guide.md
  releases/release-7.6.0.md
Labels: translation/doing, requires-version-specific-changes, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17464 Fix ticdc alert rules
  ticdc/ticdc-alert-rules.md
Labels: translation/done, size/XS, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17535 Remove fast analyze from the list of basic features
  basic-features.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17495 ticdc: Fix sql case error
  ticdc/ticdc-overview.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17467 statistics: update the note for sampling rate
  statistics.md
Labels: size/XS, area/planner, ONCALL, approved, lgtm, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17536 statistics: update the note for sampling rate
  statistics.md
Labels: translation/done, area/planner, needs-cherry-pick-release-5.3, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#17552 tiproxy: fix tiproxy api addr
  tiproxy/tiproxy-configuration.md
Labels: translation/done, type/bug-fix, size/XS, approved, lgtm, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17321 tikv: deprecate rocksdb's log configs
  tikv-configuration-file.md
Labels: translation/done, size/M, area/engine, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17520 cloud: TiDB Serverless supports TTL
  time-to-live.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17581 track-and-verify-wals-in-manifest: add v7.5.2 as a supported version
  tikv-configuration-file.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17582 Update IMPORT INTO `SPLIT_FILE`
  sql-statements/sql-statement-import-into.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17579 br: add restriction for incremental restore
  br/br-incremental-guide.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17475 lightning: add description about terminator for strict-format CSV files
  migrate-from-csv-files-to-tidb.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, approved, lgtm, needs-cherry-pick-release-7.5

#17606 Add type info for tidb_adaptive_closest_read_threshold
  system-variables.md
Labels: translation/doing, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17481 tidb-lightning: add a new doc about compatibility and scenarios
  TOC.md
  sql-statements/sql-statement-import-into.md
  tidb-lightning/tidb-lightning-compatibility-and-scenarios.md
Labels: translation/done, size/L, area/tidb-lightning, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17484 remove redundant lightning command line flags doc
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-prechecks.md
Labels: translation/from-docs, size/M, area/tidb-lightning, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17604 Group ALTER TABLE related things together
  TOC.md
Labels: type/enhancement, translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm

#17601 troubleshoot-tidb-oom：update the incorrect command, add double quotes
  troubleshoot-tidb-oom.md
Labels: contribution, first-time-contributor, missing-translation-status, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-ok-to-test, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17628 faq: Describe in what condition TiDB and RawKV can be used together
  faq/manage-cluster-faq.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17626 DM: add a step about encrypting the database password
  dm/deploy-a-dm-cluster-using-tiup.md
Labels: type/enhancement, translation/done, size/S, area/dm, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17636 br: refine description for snapshot backup
  br/backup-and-restore-overview.md
  tidb-troubleshooting-map.md
Labels: translation/done, size/XS, area/br, approved, lgtm, needs-cherry-pick-release-8.1

#17645 Fix EBNF for SHOW CREATE DATABASE
  sql-statements/sql-statement-show-create-database.md
Labels: type/enhancement, translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17605 dxf: link to data type
  tidb-distributed-execution-framework.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17603 tidb lightning: expose [tidb.session-vars] in lightning config
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, size/XS, area/tidb-lightning, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17466 add release notes for 7.5.2
  TOC.md
  releases/release-7.5.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17564 bump version for v7.5.2
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  external-storage-uri.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#17432 ticdc: fix index config of kafka dispatcher
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/from-docs, type/bug-fix, size/XS, area/ticdc, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17674 ticdc: remove duplicated words
  ticdc/ticdc-overview.md
Labels: translation/no-need, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17673 sql: Update EBNF related to indexing
  sql-statements/sql-statement-alter-table.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-create-table.md
Labels: contribution, translation/from-docs, size/XS, approved, lgtm

#17663 sql: add a note about `FULLTEXT`
  sql-statements/sql-statement-add-index.md
  sql-statements/sql-statement-create-index.md
  sql-statements/sql-statement-create-table.md
  sql-statements/sql-statement-show-indexes.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17685 ticdc: clarify description about compression
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, size/S, ONCALL, area/ticdc, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17644 Update sequence functions docs
  functions-and-operators/sequence-functions.md
Labels: type/enhancement, translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17698 tiproxy: change instance count from 3 to 1
  tiproxy/tiproxy-deployment-topology.md
Labels: translation/done, type/bug-fix, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17700 Rename `tidb_enable_concurrent_hashagg_spill` to `tidb_enable_parallel_hashagg_spill`
  configure-memory-usage.md
  releases/release-8.0.0.md
  system-variables.md
Labels: translation/done, type/bug-fix, size/M, approved, lgtm, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17695 modify the count of TiFlash replicas
  tiflash/tiflash-results-materialization.md
Labels: translation/from-docs, needs-cherry-pick-master, size/XS, area/bigdata, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17713 *: fix several typos
  br/br-monitoring-and-alert.md
  pd-configuration-file.md
  releases/release-rc.1.md
  scripts/verify-links.sh
Labels: translation/doing, type/bug-fix, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17714 remove JSON_REPLACE from supported expressions for pushdown to TiKV
  functions-and-operators/expressions-pushed-down.md
Labels: translation/done, type/bug-fix, size/XS, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0

#17732 tikv: fix default port from 20181 to 20180
  best-practices/grafana-monitor-best-practices.md
Labels: translation/done, type/bug-fix, size/XS, area/engine, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#16856 ticdc: add event filter example
  ticdc/ticdc-ddl.md
Labels: type/enhancement, translation/doing, requires-version-specific-changes, size/M, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17748 fix typo: change 'PLAN PLAYER CAPTURE' to 'PLAN REPLAYER CAPTURE'
  sql-plan-replayer.md
Labels: translation/done, type/bug-fix, size/XS, area/planner, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17756 fix error message of 8028 in metadata lock
  metadata-lock.md
Labels: translation/done, type/bug-fix, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17657 add release notes for 6.5.10
  TOC.md
  releases/release-6.5.10.md
  releases/release-7.5.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17705 backup: add time zone in examples
  br/backup-and-restore-use-cases.md
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
Labels: type/enhancement, translation/done, size/S, area/br, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17774 dm: fix the command for querying migration status
  migrate-with-more-columns-downstream.md
Labels: translation/doing, type/bug-fix, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17789 feat: updated suggest jdbc to 8.x
  develop/dev-guide-choose-driver-or-orm.md
Labels: missing-translation-status, size/S, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17794 Update docs for tidb_allow_function_for_expression_index
  sql-statements/sql-statement-create-index.md
  system-variables.md
Labels: translation/from-docs, type/bug-fix, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17796 v8.1: fix the link to roadmap
  _index.md
Labels: translation/doing, size/XS, area/develop, approved, needs-1-more-lgtm, lgtm

#17788 deprecate tidb config enable-replica-selector-v2
  tidb-configuration-file.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v8.2

#17710 ticdc: add new rules and information for syncpoint
  ticdc/ticdc-upstream-downstream-check.md
Labels: translation/done, size/XS, area/ticdc, approved, lgtm, v8.2

#17681 resource_control: add new privilege `RESOURCE_GROUP_USER`
  optimizer-hints.md
  privilege-management.md
  sql-statements/sql-statement-set-resource-group.md
  sql-statements/sql-statement-show-privileges.md
  system-variables.md
  tidb-resource-control.md
Labels: translation/done, size/M, area/engine, approved, lgtm, v8.2

#17697 Modify parallel hashagg spill doc
  configure-memory-usage.md
  system-variables.md
Labels: translation/done, size/XS, approved, lgtm, v8.2

#17731 Modify doc for parallel sort
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, approved, lgtm, v8.2

#17485 tiproxy: add doc for load balance
  TOC.md
  placement-rules-in-sql.md
  tiproxy/tiproxy-command-line-flags.md
  tiproxy/tiproxy-configuration.md
  tiproxy/tiproxy-grafana.md
  tiproxy/tiproxy-load-balance.md
  tiproxy/tiproxy-overview.md
  tiproxy/troubleshoot-tiproxy.md
Labels: translation/done, size/L, approved, lgtm, v8.2

#17440 add two json pushdown info
  functions-and-operators/expressions-pushed-down.md
Labels: contribution, translation/done, size/XS, approved, lgtm, ok-to-test, v8.2

#17627 tiflash: Add "marker" for `security.redact_info_log` in tiflash.toml
  system-variables.md
  tiflash/tiflash-configuration.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, area/bigdata, approved, lgtm, v8.2

#17755 pd-control: add description for `scheduler config evict-leader-scheduler`
  pd-control.md
Labels: type/enhancement, translation/done, size/S, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17664 br: add more parameters to SQL BR
  sql-statements/sql-statement-backup.md
  sql-statements/sql-statement-restore.md
Labels: translation/done, size/M, area/br, approved, lgtm, v8.2

#17365 config: update token-limit max value
  tidb-configuration-file.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.2

#17797 feat: adjust description of hibernate
  develop/dev-guide-choose-driver-or-orm.md
  develop/dev-guide-transaction-restraints.md
Labels: translation/done, size/S, ONCALL, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#17704 br: deprecate br restore parameter granularity
  br/br-pitr-guide.md
  br/br-snapshot-guide.md
  br/use-br-command-line-tool.md
  faq/backup-and-restore-faq.md
Labels: translation/done, size/S, area/br, approved, lgtm, v8.2

#17706 docs: Update BR and TiCDC compatibility information
  br/backup-and-restore-overview.md
  ticdc/ticdc-overview.md
Labels: translation/done, size/XS, area/br, approved, lgtm, v8.2

#17813 cached table: add links
  cached-tables.md
Labels: type/enhancement, translation/from-docs, size/S, area/sql-infra, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1

#17044 tikv: add doc for new config `max-apply-unpersisted-log-limit`
  dynamic-config.md
  tikv-configuration-file.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, needs-cherry-pick-release-8.1, v8.2

#17395 cdc: add kafka supported version table.
  ticdc/ticdc-sink-to-kafka.md
Labels: type/enhancement, translation/done, size/S, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-7.6, needs-cherry-pick-release-8.0, needs-cherry-pick-release-8.1

#17785 Add CentOS 7 EOL to OS descriptions
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5

#17686 change the default value of `tidb_enable_historical_stats` to `OFF`
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, approved, lgtm, v8.2

#17688 *: increase the performance of loading stats
  system-variables.md
  tidb-configuration-file.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, approved, lgtm, v8.2
