Repository pingcap/docs-cn, pull requests merged in 2025-02, with the labels that each got.

#19701 ddl: refine descriptions about online DDL
  ddl-introduction.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#16380 fix the default value of `periodic-full-compact-start-max-cpu`
  releases/release-7.6.0.md
Labels: contribution, translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#14439 TiCDC: Add 3 kafka addresses and correct the names of parameters
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, needs-rebase, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19715 Fix keywords orders
  sql-plan-replayer.md
Labels: contribution, translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-ok-to-test, needs-cherry-pick-release-8.5

#19721 pd: update the default value of read-base-cost
  pd-configuration-file.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19703 system-variables: add the experimental info for tidb_evolve_plan_baselines
  system-variables.md
Labels: type/enhancement, translation/from-docs, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19720 ticdc: update doc about event filter of renaming table
  ticdc/ticdc-ddl.md
Labels: translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19448 *: Add resource management topic and split docs
  TOC.md
  basic-features.md
  dashboard/dashboard-intro.md
  dashboard/dashboard-resource-manager.md
  error-codes.md
  faq/sql-faq.md
  functions-and-operators/tidb-functions.md
  glossary.md
  grafana-resource-control-dashboard.md
  information-schema/information-schema-resource-groups.md
  information-schema/information-schema-runaway-watches.md
  optimizer-hints.md
  pd-configuration-file.md
  pd-control.md
  releases/release-6.6.0.md
  releases/release-7.0.0.md
  releases/release-7.1.0.md
  releases/release-7.2.0.md
  releases/release-7.3.0.md
  releases/release-7.4.0.md
  releases/release-7.5.1.md
  releases/release-7.6.0.md
  releases/release-8.1.0.md
  releases/release-8.2.0.md
  releases/release-8.4.0.md
  sql-statements/sql-statement-alter-resource-group.md
  sql-statements/sql-statement-calibrate-resource.md
  sql-statements/sql-statement-create-resource-group.md
  sql-statements/sql-statement-drop-resource-group.md
  sql-statements/sql-statement-explain-analyze.md
  sql-statements/sql-statement-insert.md
  sql-statements/sql-statement-overview.md
  sql-statements/sql-statement-query-watch.md
  sql-statements/sql-statement-replace.md
  sql-statements/sql-statement-select.md
  sql-statements/sql-statement-set-resource-group.md
  sql-statements/sql-statement-show-create-resource-group.md
  sql-statements/sql-statement-update.md
  statement-summary-tables.md
  system-variable-reference.md
  system-variables.md
  tidb-configuration-file.md
  tidb-resource-control-background-tasks.md
  tidb-resource-control-ru-groups.md
  tidb-resource-control-runaway-queries.md
  tiflash/tiflash-pipeline-model.md
  tikv-configuration-file.md
  tiproxy/tiproxy-load-balance.md
  tiproxy/tiproxy-traffic-replay.md
  user-account-management.md
Labels: translation/done, size/XXL, approved, lgtm, needs-cherry-pick-release-8.5

#19730 lighting: reorder tidb.session-vars
  tidb-lightning/tidb-lightning-configuration.md
Labels: translation/done, type/bugfix, size/XS, ONCALL, area/tidb-lightning, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19733 tidb: Add ENGINE_ATTRIBUTE table option
  sql-statements/sql-statement-create-table.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#19742 fix: add doc aliases to prevent 404 errors on tidb-resource-control page
  tidb-resource-control-ru-groups.md
Labels: translation/done, type/bugfix, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm

#19743 v8.5: add doc aliases to prevent 404 errors on tidb-resource-control page
  tidb-resource-control-ru-groups.md
Labels: translation/done, type/bugfix, ONCALL, approved, needs-1-more-lgtm, lgtm

#19745 fix the default value of tidb_enable_plan_replayer_capture in release notes
  releases/release-6.5.0.md
  releases/release-6.6.0.md
Labels: translation/done, type/bugfix, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19754 tiup: update sysctl settings
  check-before-deployment.md
Labels: translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19686 tiproxy: add tiproxy topology definition to the usage section
  tiproxy/tiproxy-overview.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19741 variable: tidb_slow_txn_log_threshold
  releases/release-7.0.0.md
  system-variables.md
Labels: translation/done, size/S, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19687 pd: store limit updates
  configure-store-limit.md
Labels: translation/from-docs, size/M, approved, lgtm, needs-cherry-pick-release-8.5

#11227 glossary: add some terms to glossary
  glossary.md
Labels: type/enhancement, translation/doing, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#19732 Add doc for `APPROX_DISTINCT_COUNT` aggregate function
  functions-and-operators/aggregate-group-by-functions.md
Labels: translation/from-docs, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19785 ticdc: update "safe-mode" description
  ticdc/ticdc-faq.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19786 ci: sync media to cos
  .github/workflows/media.yml
Labels: translation/no-need, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19806 ref: update storage wording
  tidb-storage.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19814 Revert "ref: update storage wording (#19806)"
  tidb-storage.md
Labels: translation/no-need, missing-translation-status, size/XS, approved, lgtm

#19803 v5.4-v6.1: update video resource links to point to new locations
  command-line-flags-for-tidb-configuration.md
  dm/dm-overview.md
  dumpling-overview.md
  explore-htap.md
  faq/manage-cluster-faq.md
  overview.md
  quick-start-with-tidb.md
  ticdc/ticdc-overview.md
  tidb-architecture.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-monitoring-framework.md
  user-account-management.md
Labels: translation/no-need, size/M, needs-cherry-pick-release-5.4, approved, needs-1-more-lgtm, lgtm

#19804 v6.5-v8.3: update video resource links to point to new locations
  command-line-flags-for-tidb-configuration.md
  dm/dm-overview.md
  dumpling-overview.md
  explore-htap.md
  faq/manage-cluster-faq.md
  overview.md
  quick-start-with-tidb.md
  tidb-architecture.md
  tidb-binlog/tidb-binlog-overview.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-monitoring-framework.md
  user-account-management.md
Labels: translation/no-need, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#19805 v8.4-dev: update video resource links to point to new locations
  command-line-flags-for-tidb-configuration.md
  dm/dm-overview.md
  dumpling-overview.md
  explore-htap.md
  faq/manage-cluster-faq.md
  overview.md
  quick-start-with-tidb.md
  tidb-architecture.md
  tidb-lightning/tidb-lightning-overview.md
  tidb-monitoring-framework.md
  user-account-management.md
Labels: translation/no-need, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19825 doc: correct subquery optimization examples for clarity
  subquery-optimization.md
Labels: translation/from-docs, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19835 support: replace internals.tidb.io with discussions on GitHub
  support.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19850 CI: Update LinkChecker URL excludes
  .github/workflows/link-fail-fast.yaml
  .lycheeignore
  develop/dev-guide-third-party-support.md
  vector-search/vector-search-integration-overview.md
Labels: translation/from-docs, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#19816 tiup: give a more clear recommendation about SELinux
  check-before-deployment.md
  tiup/tiup-component-cluster-check.md
Labels: type/enhancement, translation/from-docs, size/S, area/tiup, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19854 Document bug: API command for changefeed (/api/v2/changefeed/test1/synced)
  ticdc/ticdc-open-api-v2.md
Labels: translation/from-docs, size/XS, area/ticdc, approved, lgtm, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19753 add tiup no-sudo doc
  TOC.md
  tiup/tiup-cluster-no-sudo-mode.md
  tiup/tiup-cluster-topology-reference.md
Labels: contribution, translation/from-docs, first-time-contributor, size/L, approved, lgtm, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19848 Fix incorrect slow query table desc row count
  information-schema/information-schema-slow-query.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.4

#19849 ticdc: add description about safe-mode arguments
  ticdc/ticdc-sink-to-mysql.md
Labels: type/enhancement, translation/doing, size/XS, area/ticdc, needs-cherry-pick-release-6.5, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19862 pd: add note for tombstone store gc
  tidb-scheduling.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19405 *: upgrade tidb_auto_analyze_partition_batch_size default value
  releases/release-8.2.0.md
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v8.2, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19882 tidb-configuration-file: Add like to Coprocessor Cache docs
  tidb-configuration-file.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19868 mysql-compatibility.md: Add note about JOIN on subquery
  mysql-compatibility.md
Labels: contribution, translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19891 refine admin related docs
  sql-statements/sql-statement-admin-pause-ddl.md
  sql-statements/sql-statement-admin-resume-ddl.md
  sql-statements/sql-statement-admin-show-ddl.md
Labels: type/enhancement, translation/doing, size/S, approved, lgtm, needs-cherry-pick-release-8.5

#19880 br: 在线升级到v7.2.0以上的集群可能会遇到兼容性错误
  br/backup-and-restore-overview.md
Labels: translation/done, size/XS, area/br, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19893 generated columns: list disallowed functions
  generated-columns.md
Labels: type/enhancement, translation/from-docs, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19901 fix: vague order by description
  develop/dev-guide-unstable-result-set.md
Labels: translation/no-need, size/XS, area/develop, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19879 dm: reformat DM config
  dm/dm-master-configuration-file.md
  dm/dm-source-configuration-file.md
  dm/dm-worker-configuration-file.md
  dm/task-configuration-file-full.md
Labels: type/enhancement, translation/done, size/XL, area/dm, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19910 docs: update description and default value for `concurrently-init-stats` in configuration file
  releases/release-8.2.0.md
  tidb-configuration-file.md
Labels: translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19167 lightning: reformat TiDB Lightning config
  tidb-lightning/tidb-lightning-configuration.md
  tidb-lightning/tidb-lightning-logical-import-mode-usage.md
Labels: type/enhancement, translation/done, size/XXL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19914 Update notes for scaling PD nodes
  scale-tidb-using-tiup.md
Labels: translation/done, size/S, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19168 tiflash: reformat TiFlash config file
  tiflash/tiflash-configuration.md
Labels: type/enhancement, translation/done, size/XXL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19926 sql-statement-overview.md: add four SQL statements
  sql-statements/sql-statement-overview.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, lgtm, needs-cherry-pick-release-8.5

#19929 tiflash: update config max_threads and task_scheduler_active_set_soft_limit
  tiflash/tiflash-configuration.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19928 v6.5.12: support openEuler 22.03 LTS SP4
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#19853 add v6.5.12 release notes
  TOC.md
  releases/release-6.5.12.md
  releases/release-7.5.5.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19897 tidb_ddl_reorg_max_write_speed: add the support info of v6.5.12
  releases/release-8.5.0.md
  sql-statements/sql-statement-admin-alter-ddl.md
  system-variable-reference.md
  system-variables.md
Labels: translation/done, requires-version-specific-changes, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.5

#19881 v6.5: bump the example TiDB version to v6.5.12
  br/backup-and-restore-use-cases.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  dm/quick-start-with-dm.md
  pd-control.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-ddl.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-sink-to-cloud-storage.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
Labels: translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm
