Repository pingcap/docs-cn, pull requests merged in 2025-04, with the labels that each got.

#20140 doc-review: support specifying a custom prompt file
  .github/workflows/doc_review.yml
  doc-review-prompt.txt
Labels: translation/no-need, size/M, approved, needs-1-more-lgtm, lgtm, area/docs-efficiency

#20136 add tidb-upgrade-migration-guide
  TOC.md
  tidb-upgrade-migration-guide.md
Labels: type/enhancement, translation/doing, size/XL, area/deploy-upgrade-maintain, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20012 Describe TiCDC support in TiFlash
  ticdc/ticdc-compatibility.md
  tiflash/create-tiflash-replicas.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20152 doc-review-prompt: add two new guidelines
  doc-review-prompt.txt
Labels: missing-translation-status, size/XS, approved, needs-1-more-lgtm, lgtm

#20155 v6.1: update the BR compatibility info
  br/backup-and-restore-overview.md
Labels: type/enhancement, translation/done, size/XS, ONCALL, area/br, approved, lgtm

#20153 fix typo
  sql-statements/sql-statement-savepoint.md
Labels: translation/no-need, size/XS, approved, lgtm, type/bug, needs-cherry-pick-release-8.5

#20156 v5.4: update the BR compatibility info
  br/backup-and-restore-tool.md
Labels: type/enhancement, translation/done, size/XS, ONCALL, area/br, approved, lgtm

#19852 remove `txn_scope` from docs
  system-variable-reference.md
  system-variables.md
  tidb-configuration-file.md
  tidb-resource-control-ru-groups.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, for-release, approved, lgtm, v9.0-beta.1

#20154 Extend DDL/MDL info
  TOC.md
  ddl-introduction.md
  metadata-lock.md
  mysql-schema/mysql-schema-tidb-mdl-view.md
  mysql-schema/mysql-schema.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20160 sql: refine term for AUTO_INCREMENT
  auto-increment.md
  basic-features.md
  dm/dm-best-practices.md
  functions-and-operators/information-functions.md
  mysql-compatibility.md
  releases/release-6.4.0.md
  releases/release-6.5.0.md
  releases/release-8.1.0.md
Labels: translation/no-need, size/M, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19878 system-variables: add doc for `tidb_max_dist_task_nodes`
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v9.0-beta.1

#20137 add system variable tidb_enable_point_get_cache back
  system-variables.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.5

#20134 stale read: update the description of tidb_external_ts
  stale-read.md
Labels: type/enhancement, translation/from-docs, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20002 br: add compatibility between log backup and PITR
  br/br-pitr-manual.md
Labels: translation/done, size/S, approved, lgtm, v9.0-beta.1

#19907 br: provide a storage target option for BR restore checkpoint data
  br/br-checkpoint-restore.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, for-release, approved, lgtm, v9.0-beta.1

#20166 tidb: enhance clarity and ensure consistency for the system variable tidb_auto_analyze_concurrency
  releases/release-8.4.0.md
  system-variables.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20167 statistics: Add more variables that control auto analyze
  statistics.md
  system-variables.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20175 information_schema: Update IS_VISIBLE description
  information-schema/information-schema-statistics.md
Labels: translation/from-docs, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20163 ticdc: add detailed notes for table version
  ticdc/ticdc-sink-to-cloud-storage.md
Labels: type/enhancement, translation/done, size/XS, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19847 statements: add network traffic related stats in statments summary table
  statement-summary-tables.md
Labels: translation/done, size/S, approved, lgtm, v9.0-beta.1

#20011 Add new Index advisor user doc
  TOC.md
  index-advisor.md
  sql-tuning-overview.md
Labels: translation/from-docs, size/L, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, v9.0-beta.1

#20185 update release for fix control 54337 to 8.3
  optimizer-fix-controls.md
Labels: translation/from-docs, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19994 variable: tidb_pipelined_dml_resource_policy
  pipelined-dml.md
  system-variables.md
Labels: translation/done, size/S, approved, needs-1-more-lgtm, lgtm, v9.0-beta.1

#20191 ticdc: use `cdc cli changefeed list` to check `checkpoint-ts`
  ticdc/ticdc-manage-changefeed.md
Labels: translation/done, ONCALL, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20165 best practices: refine java connection pools
  best-practices/java-app-best-practices.md
Labels: translation/done, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20208 v6.0.0 release notes: update the description of "setting incorrect values for system variables"
  releases/release-6.0.0-dmr.md
Labels: translation/done, type/bugfix, size/XS, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20127 *: add TiDB workload repository
  TOC.md
  sql-statements/sql-statement-admin.md
  system-variable-reference.md
  system-variables.md
  workload-repository.md
Labels: translation/from-docs, size/L, type/compatibility-or-feature-change, approved, needs-1-more-lgtm, lgtm, v9.0-beta.1

#20207 tidb-monitoring-framework: add TiDB Dashboard
  TOC.md
  _index.md
  deploy-monitoring-services.md
  tidb-monitoring-framework.md
Labels: type/enhancement, translation/done, size/M, ONCALL, area/diagnosis, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20225 Update vector-search-index.md
  vector-search/vector-search-index.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20226 v6.5: update keywords according to parser.y
  keywords.md
Labels: translation/done, type/bugfix, size/L, ONCALL, approved, needs-1-more-lgtm, lgtm

#20229 docs: add attribution for KNN vector search description
  vector-search/vector-search-index.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20096 add saas scenario best practices
  TOC.md
  best-practices/saas-best-practices.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#20141 tiproxy: add a guide to enable tiproxy using tiup
  tiproxy/tiproxy-overview.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#20234 update the default collation of GBK from gbk_bin to gbk_chinese_ci
  character-set-and-collation.md
  character-set-gbk.md
  sql-statements/sql-statement-show-character-set.md
Labels: translation/done, type/bugfix, size/M, ONCALL, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20250 修改错别字"更据"为"根据"
  develop/dev-guide-optimize-sql.md
Labels: contribution, translation/no-need, first-time-contributor, size/XS, area/develop, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20260 pd configuration: add dashboard.disable-custom-prom-addr
  pd-configuration-file.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20268 releases: add one br entry to v8.1.2
  releases/release-8.1.2.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20255 add FAQs about collation for JDBC connections
  develop/dev-guide-sample-application-java-jdbc.md
  faq/sql-faq.md
  faq/upgrade-faq.md
Labels: size/M, area/sql-infra, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20279 hardware-and-software-requirements: update "麒麟欧拉版" to "银河麒麟"
  hardware-and-software-requirements.md
Labels: missing-translation-status, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20288 JDBC URL: update the letter case for defaultFetchSize
  faq/sql-faq.md
Labels: missing-translation-status, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20259 fix(pd): add missing configuration items for PD
  pd-configuration-file.md
  releases/release-8.0.0.md
Labels: translation/done, size/S, area/scheduling, ONCALL, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20267 planner: add doc for `tidb_ignore_inlist_plan_digest`.
  releases/release-7.6.0.md
  system-variables.md
Labels: translation/done, size/S, area/planner, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20261 tikv: recorrect the settings of some configs and supplement missing annotations for several configs.
  releases/release-7.6.0.md
  releases/release-8.0.0.md
  releases/release-8.1.0.md
  releases/release-8.1.2.md
  tikv-configuration-file.md
Labels: contribution, translation/done, size/M, area/engine, ONCALL, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4
