Repository pingcap/docs-cn, pull requests merged in 2025-03, with the labels that each got.

#19946 update "DB2" to "Db2"
  faq/migration-tidb-faq.md
  optimizer-fix-controls.md
  releases/release-8.4.0.md
Labels: translation/from-docs, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19943 Add a TiUP note to production deployment
  production-deployment-using-tiup.md
Labels: translation/done, size/S, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19952 update media resource links to point to new locations
  tidb-monitoring-api.md
  tiproxy/tiproxy-load-balance.md
  tiproxy/tiproxy-overview.md
  tiproxy/tiproxy-traffic-replay.md
Labels: translation/done, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19861 TiDB auto increment MySQL-compatible behavior clarification
  auto-increment.md
Labels: type/enhancement, translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19945 migration-tools: update the descriptions for Dumpling
  migration-tools.md
Labels: type/enhancement, translation/from-docs, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19944 mysql-schema: add information about several missing system tables
  mysql-schema/mysql-schema.md
Labels: translation/done, size/S, ONCALL, approved, lgtm

#19824 br: add more info about the br log structure
  br/br-log-architecture.md
Labels: type/enhancement, translation/done, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19900 hardware-and-software-requirements: Update for EOLs
  hardware-and-software-requirements.md
Labels: translation/from-docs, size/S, approved, lgtm

#20003 sql-statements: expand DefaultValueExpr defination
  sql-statements/sql-statement-create-table.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19982 system-variables: remove the default value descriptions for last_xxx variables
  system-variables.md
Labels: type/enhancement, translation/doing, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19988 statistics.md: correct the default value of stats-load-concurrency
  statistics.md
Labels: translation/done, size/XS, area/planner, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20006 v6.5.0 release notes: add descriptions about tidb_store_batch_size
  releases/release-6.5.0.md
Labels: size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19993 remove the benchmark files for earlier releases
  benchmark/benchmark-sysbench-v2.md
  benchmark/benchmark-sysbench-v3.md
  benchmark/benchmark-sysbench-v4-vs-v3.md
  benchmark/benchmark-sysbench-v5-vs-v4.md
  benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md
  benchmark/benchmark-sysbench-v5.2.0-vs-v5.1.1.md
  benchmark/benchmark-sysbench-v5.3.0-vs-v5.2.2.md
  benchmark/benchmark-sysbench-v5.4.0-vs-v5.3.0.md
  benchmark/benchmark-sysbench-v6.0.0-vs-v5.4.0.md
  benchmark/benchmark-sysbench-v6.1.0-vs-v6.0.0.md
  benchmark/benchmark-sysbench-v6.2.0-vs-v6.1.0.md
  benchmark/benchmark-tpch.md
  benchmark/v3.0-performance-benchmarking-with-sysbench.md
  benchmark/v3.0-performance-benchmarking-with-tpcc.md
  benchmark/v4.0-performance-benchmarking-with-tpcc.md
  benchmark/v4.0-performance-benchmarking-with-tpch.md
  benchmark/v5.0-performance-benchmarking-with-tpcc.md
  benchmark/v5.1-performance-benchmarking-with-tpcc.md
  benchmark/v5.2-performance-benchmarking-with-tpcc.md
  benchmark/v5.3-performance-benchmarking-with-tpcc.md
  benchmark/v5.4-performance-benchmarking-with-tpcc.md
  benchmark/v5.4-performance-benchmarking-with-tpch.md
  benchmark/v6.0-performance-benchmarking-with-tpcc.md
  benchmark/v6.0-performance-benchmarking-with-tpch.md
  benchmark/v6.1-performance-benchmarking-with-tpcc.md
  benchmark/v6.1-performance-benchmarking-with-tpch.md
  benchmark/v6.2-performance-benchmarking-with-tpcc.md
  benchmark/v6.2-performance-benchmarking-with-tpch.md
  faq/manage-cluster-faq.md
  information-schema/information-schema-inspection-result.md
  tidb-troubleshooting-map.md
  tikv-control.md
Labels: translation/from-docs, size/XXL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#19997 v6.1: add aliases for stale benchmark docs
  benchmark/benchmark-sysbench-v6.0.0-vs-v5.4.0.md
  benchmark/benchmark-sysbench-v6.1.0-vs-v6.0.0.md
  benchmark/v6.0-performance-benchmarking-with-tpcc.md
  benchmark/v6.0-performance-benchmarking-with-tpch.md
  benchmark/v6.1-performance-benchmarking-with-tpcc.md
  benchmark/v6.1-performance-benchmarking-with-tpch.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#19998 v5.4: add aliases for stale benchmark docs
  benchmark/benchmark-sysbench-v2.md
  benchmark/benchmark-sysbench-v3.md
  benchmark/benchmark-sysbench-v4-vs-v3.md
  benchmark/benchmark-sysbench-v5-vs-v4.md
  benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md
  benchmark/benchmark-sysbench-v5.2.0-vs-v5.1.1.md
  benchmark/benchmark-sysbench-v5.3.0-vs-v5.2.2.md
  benchmark/benchmark-sysbench-v5.4.0-vs-v5.3.0.md
  benchmark/benchmark-tpch.md
  benchmark/v3.0-performance-benchmarking-with-sysbench.md
  benchmark/v3.0-performance-benchmarking-with-tpcc.md
  benchmark/v4.0-performance-benchmarking-with-tpcc.md
  benchmark/v4.0-performance-benchmarking-with-tpch.md
  benchmark/v5.0-performance-benchmarking-with-tpcc.md
  benchmark/v5.1-performance-benchmarking-with-tpcc.md
  benchmark/v5.2-performance-benchmarking-with-tpcc.md
  benchmark/v5.3-performance-benchmarking-with-tpcc.md
  benchmark/v5.4-performance-benchmarking-with-tpcc.md
  benchmark/v5.4-performance-benchmarking-with-tpch.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm

#19996 v6.5: add aliases for stale benchmark docs
  benchmark/benchmark-sysbench-v6.2.0-vs-v6.1.0.md
  benchmark/v6.2-performance-benchmarking-with-tpcc.md
  benchmark/v6.2-performance-benchmarking-with-tpch.md
Labels: translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm

#19989 tiup: Update/fix no sudo mode docs
  tiup/tiup-cluster-no-sudo-mode.md
Labels: translation/from-docs, size/L, area/tiup, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20021 add openEuler 22.03 LTS SP3/SP4
  hardware-and-software-requirements.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#19967 br: fix description about case-sensitive and insensitive
  br/backup-and-restore-overview.md
Labels: translation/from-docs, size/S, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19971 tidb-lightning: update wording about parallel import
  tidb-lightning/tidb-lightning-distributed-import.md
  tidb-lightning/tidb-lightning-physical-import-mode.md
Labels: translation/from-docs, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19832 br: add compact log backup
  TOC.md
  br/br-compact-log-backup.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v9.0

#19704 ticdc: update the TiCDC Debezium protocol
  ticdc/ticdc-debezium.md
Labels: translation/from-docs, size/XXL, approved, needs-1-more-lgtm, lgtm, v9.0

#19962 add release notes 7.5.6
  TOC.md
  releases/release-7.5.6.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20024 bump tidb to 7.5.6
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  dm/quick-start-with-dm.md
  external-storage-uri.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-monitoring-services.md
  upgrade-tidb-using-tiup.md
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#20048 Add a section to change isolation level in transaction-isolation-levels.md
  transaction-isolation-levels.md
Labels: translation/done, size/S, ONCALL, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19941 add tidb_enable_window_function can control the keyword list
  keywords.md
Labels: contribution, translation/done, first-time-contributor, size/XS, approved, lgtm, ok-to-test, needs-cherry-pick-release-8.5

#20042 sys var: clarify the description of tidb_ddl_reorg_max_write_speed
  system-variables.md
Labels: translation/done, size/S, needs-cherry-pick-release-6.5, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.5

#20025 br: improve visualization of BR
  br/backup-and-restore-use-cases.md
  br/br-pitr-guide.md
  br/br-pitr-manual.md
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
Labels: translation/done, size/M, approved, lgtm, v9.0

#19898 update doc for max_user_connections.
  mysql-schema/mysql-schema-user.md
  security-compatibility-with-mysql.md
  sql-statements/sql-statement-alter-user.md
  sql-statements/sql-statement-create-user.md
  system-variables.md
Labels: translation/done, size/M, type/compatibility-or-feature-change, approved, lgtm, v9.0

#20056 Fix the desciption about cluster index and pre split region on auto random column
  clustered-indexes.md
Labels: translation/done, type/bugfix, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19831 Add docs about `cluster_id` row in `mysql.tidb`
  mysql-schema/mysql-schema.md
Labels: translation/done, size/XS, approved, lgtm, v9.0

#19845 Support pushdown to tiflash for some aggregation functions
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: translation/done, size/XS, approved, lgtm, v9.0

#20067 Remove deleted tiflash param "raftstore.store-batch-retry-recv-timeout"
  tiflash/tiflash-configuration.md
Labels: translation/done, type/bugfix, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#20068 Small updates to TiKV config docs
  tikv-configuration-file.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19507 partitioned-table: global index supports non-unique index
  partitioned-table.md
Labels: translation/done, size/M, approved, lgtm, v9.0

#20082 tiup: extend the firewall docs
  check-before-deployment.md
  quick-start-with-tidb.md
Labels: type/enhancement, translation/from-docs, size/L, area/tiup, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20069 Improve the description of TLS configuration parameters between components
  tidb-configuration-file.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19625 br: add unrecoverable system tables list
  br/br-snapshot-guide.md
  faq/backup-and-restore-faq.md
Labels: translation/done, size/M, for-release, approved, lgtm, v9.0

#20028 ticdc: refine faq doc
  ticdc/ticdc-faq.md
Labels: translation/done, size/S, ONCALL, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19999 tikv: add missing tikv configs
  tikv-configuration-file.md
Labels: translation/done, requires-version-specific-changes, size/M, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20034 ticdc: add duplicate entry faq
  ticdc/ticdc-faq.md
Labels: type/enhancement, translation/done, size/M, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#19538 update mpp_version
  system-variables.md
  tiflash/tiflash-configuration.md
Labels: translation/done, size/S, approved, lgtm, v9.0

#20105 Update tidb-limitations of index
  tidb-limitations.md
Labels: contribution, translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#19889 import into: remove restriction thread >= 8 for import into with global-sort
  sql-statements/sql-statement-import-into.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v9.0

#19834 system-variables: add @@global.tidb_accelerate_user_creation_update
  system-variables.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v9.0

#19815 support more function pushdown
  functions-and-operators/expressions-pushed-down.md
  tiflash/tiflash-supported-pushdown-calculations.md
Labels: translation/done, size/XS, approved, lgtm, v9.0

#19846 Add network traffic related stats in slow query table
  information-schema/information-schema-slow-query.md
Labels: translation/done, size/XL, approved, lgtm, v9.0

#19380 doc: configs of max-ts checker
  tikv-configuration-file.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v9.0

#19869 add new config hashagg_use_magic_hash for tiflash
  tiflash/tiflash-configuration.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, for-release, approved, lgtm, v9.0

#19942 Modify hash join explain analyze description
  sql-statements/sql-statement-explain-analyze.md
Labels: translation/done, size/M, approved, lgtm, v9.0

#20000 Update the default value of `pd_enable_follower_handle_region` to ON
  system-variables.md
Labels: translation/done, size/XS, approved, lgtm, v9.0

#20120 tiup-cluster-no-sudo-mode: Correct the order of operations to ensure t…
  check-before-deployment.md
  tiup/tiup-cluster-no-sudo-mode.md
Labels: type/enhancement, translation/from-docs, size/M, area/tiup, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20121 system-variables: Update/extend tidb_general_log docs
  system-variables.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20126 Clarify TiKV SM4 encryption descriptions
  encryption-at-rest.md
Labels: translation/done, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20001 docs: update sync-diff-inspector docs for move to tiflow repo
  download-ecosystem-tools.md
  sync-diff-inspector/sync-diff-inspector-overview.md
Labels: translation/from-docs, size/M, type/compatibility-or-feature-change, area/sync-diff-inspector, approved, needs-1-more-lgtm, lgtm, v9.0-beta.1

#19744 pd-microservices GA
  pd-microservices.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, v9.0-beta.1

#19202 ttl: updated ttl `TTL_JOB_INTERVAL` description
  time-to-live.md
Labels: translation/from-docs, size/S, for-release, approved, lgtm, v9.0-beta.1

#20049 log-backup: added an explaination to the log status
  br/br-pitr-guide.md
Labels: translation/done, requires-version-specific-changes, size/M, approved, lgtm, needs-cherry-pick-release-8.5
