Repository pingcap/docs-cn, pull requests merged in 2025-05, with the labels that each got.

#20305 Add restriction for IMPORT INTO regarding empty
  sql-statements/sql-statement-import-into.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20139 include compatibility notice for tidb_remove_orderby_in_subquery
  releases/release-7.2.0.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20249 Add tidb index usage limitation for valid stats
  information-schema/information-schema-tidb-index-usage.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20314 Update pad attribute where needed
  character-set-and-collation.md
  information-schema/information-schema-collations.md
  sql-statements/sql-statement-show-collation.md
Labels: translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20319 ticdc: add [[filter.event-filters]] to the toml example
  ticdc/ticdc-ddl.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20324 dev guide: fix broken link
  develop/dev-guide-timeouts-in-tidb.md
Labels: translation/no-need, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20133 dm: add log redaction configuration item in dm worker log file
  dm/dm-worker-configuration-file.md
  log-redaction.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, approved, lgtm, v9.0-beta.1

#20337 basic-features: fix table formatting issue
  basic-features.md
Labels: translation/done, type/bugfix, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20348 Correct the description of "Total RU of user resource groups"
  dashboard/dashboard-resource-manager.md
Labels: translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20333 docs: clarify AUTO_RANDOM_BASE usage and explicit insert behavior
  auto-random.md
Labels: translation/from-docs, size/M, approved, lgtm, needs-cherry-pick-release-8.5

#20351 tiproxy: rephrase TiProxy performance to make it comfortable
  tiproxy/tiproxy-overview.md
  tiproxy/tiproxy-performance-test.md
Labels: translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm

#20035 add release notes v9.0.0 - features part
  releases/release-9.0.0.md
Labels: translation/done, size/XL, area/develop, approved, lgtm, v9.0-beta.1

#20358 add release notes v9.0.0 - features part (#20035)
  auto-random.md
  basic-features.md
  br/br-snapshot-guide.md
  br/br-snapshot-manual.md
  br/use-br-command-line-tool.md
  dashboard/dashboard-resource-manager.md
  dm/dm-worker-configuration-file.md
  log-redaction.md
  tiproxy/tiproxy-overview.md
  tiproxy/tiproxy-performance-test.md
Labels: contribution, translation/no-need, size/M, approved, needs-1-more-lgtm, lgtm

#20359 sql: remove confusing description
  sql-statements/sql-statement-alter-table.md
Labels: translation/done, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20369 quick-start: add a note about minimum resource requirement
  quick-start-with-tidb.md
Labels: translation/done, size/XS, ONCALL, approved, lgtm, needs-cherry-pick-release-8.5

#20345 ticdc: add new doc for TiCDC data replication capabilities
  TOC.md
  ticdc/ticdc-data-replication-capabilities.md
  ticdc/ticdc-overview.md
Labels: type/enhancement, translation/done, size/M, ONCALL, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20364 dev-guide-bookshop-schema-design: update a step for data import
  develop/dev-guide-bookshop-schema-design.md
Labels: translation/from-docs, size/XS, area/develop, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20381 replay haproxy 2.6.2 with 2.6.21
  best-practices/haproxy-best-practices.md
Labels: translation/doing, size/S, approved, lgtm, needs-cherry-pick-release-8.5

#20394 system-variable: update default value of tidb_stats_cache_mem_quota
  releases/release-8.5.1.md
  system-variables.md
Labels: translation/from-docs, size/S, approved, lgtm, needs-cherry-pick-release-8.5

#20400 add `in-memory-engine` config items
  releases/release-8.5.0.md
  tikv-configuration-file.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.5

#20366 glossary: add vector search
  glossary.md
  vector-search/vector-search-get-started-using-sql.md
  vector-search/vector-search-overview.md
Labels: translation/done, size/S, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20397 br: sys table pitr id map
  mysql-schema/mysql-schema.md
Labels: type/enhancement, translation/done, missing-translation-status, size/XS, area/br, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20422 ticdc: minor adjust the description of `foreign_key_checks`
  ticdc/ticdc-data-replication-capabilities.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5
