Repository pingcap/docs-cn, pull requests merged in 2025-09, with the labels that each got.

#20832 pitr: add more description for performance parameters
  best-practices/saas-best-practices.md
  br/br-pitr-guide.md
  br/br-pitr-manual.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20557 best practices: multi-column index optimization
  TOC.md
  best-practices/multi-column-index-best-practices.md
  media/best-practices/multi-column-index-table-access-path-selection.png
Labels: translation/from-docs, area/best-practices, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#20867 troubleshooting: remove outdated `max-txn-time-use`
  tidb-troubleshooting-map.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20877 Fix typo in FAQ: '事物' to '事务'
  faq/migration-tidb-faq.md
  faq/sql-faq.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20742 v7.5.7: change the default value of tidb_enable_historical_stats
  system-variables.md
Labels: translation/done, size/XS, type/compatibility-or-feature-change, approved, needs-1-more-lgtm, lgtm

#20708 tikv: update auto compaction config
  dynamic-config.md
  garbage-collection-configuration.md
  tikv-configuration-file.md
Labels: contribution, translation/done, requires-version-specific-changes, size/M, type/compatibility-or-feature-change, for-release, approved, lgtm, needs-cherry-pick-release-7.5, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5, v9.0-beta.2

#20924 tiflash: add the default value of `enable_resource_control`
  tiflash/tiflash-configuration.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20928 Update TiProxy version to v1.3.2
  tiproxy/tiproxy-deployment-topology.md
  tiproxy/tiproxy-overview.md
Labels: translation/from-docs, needs-cherry-pick-master, size/XS, approved, lgtm

#20932 sql-statement-load-data: add DuplicateOpt
  sql-statements/sql-statement-load-data.md
Labels: translation/from-docs, size/S, approved, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20922 DM MariaDB and foreign key compatibility clarification
  dm/dm-compatibility-catalog.md
Labels: type/enhancement, translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20918 Add details to the `--initialize-secure` option
  best-practices-for-security-configuration.md
  command-line-flags-for-tidb-configuration.md
Labels: type/enhancement, translation/from-docs, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20609 Update follower read and learner read descriptions
  follower-read.md
Labels: translation/done, size/S, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5, type/outdated

#20923 tikv: clarify the description of config 'in-memory-engine.capacity'
  tikv-configuration-file.md
Labels: type/enhancement, translation/done, size/XS, area/engine, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20958 develop: remove client connection parameters doc
  develop/dev-guide-client-connection-parameters.md
Labels: translation/no-need, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20959 develop: remove client connection parameters doc
  develop/dev-guide-client-connection-parameters.md
Labels: translation/no-need, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#20960 develop: remove client connection parameters doc
  develop/dev-guide-client-connection-parameters.md
Labels: translation/no-need, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#20278 tidb: mark the concurrently-init-stats config as deprecated
  tidb-configuration-file.md
Labels: translation/from-docs, size/XS, type/compatibility-or-feature-change, approved, needs-1-more-lgtm, lgtm, v9.0-beta.2

#20676 include storage engines in slow query logs and statements summary
  identify-slow-queries.md
  statement-summary-tables.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, v9.0-beta.2

#20961 develop: remove client connection parameters doc
  develop/dev-guide-client-connection-parameters.md
Labels: translation/no-need, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#20151 add tiflash config storage.temp
  tiflash/tiflash-configuration.md
Labels: translation/done, size/S, type/compatibility-or-feature-change, for-release, approved, lgtm, v9.0-beta.2

#20968 update MariaDB documentation links from `kb/` to `docs/`
  best-practices/java-app-best-practices.md
  develop/dev-guide-connection-parameters.md
  dm/dm-glossary.md
  migrate-from-mariadb.md
Labels: translation/done, size/S, area/develop, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5
