Repository pingcap/docs-cn, pull requests merged in 2025-07, with the labels that each got.

#20597 ticdc: fix wrong config value of `region-threshold`
  ticdc/ticdc-changefeed-config.md
Labels: translation/done, type/bugfix, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20603 clinic: list audit logs as included in diag
  clinic/clinic-data-instruction-for-tiup.md
Labels: translation/from-docs, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20252 Refine tiflash FAQ and configuration docs
  tiflash/create-tiflash-replicas.md
  tiflash/tiflash-configuration.md
  tiflash/troubleshoot-tiflash.md
Labels: translation/done, size/L, area/develop, approved, lgtm, needs-cherry-pick-release-8.5

#20620 TiFlash: small fixes and added links
  tiflash/tiflash-compatibility.md
  tiflash/use-fastscan.md
Labels: translation/from-docs, size/S, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20593 v8.5: use a variable to refer to TiDB Cloud Serverless
  TOC.md
  _docHome.md
  develop/dev-guide-bookshop-schema-design.md
  develop/dev-guide-build-cluster-in-cloud.md
  develop/dev-guide-create-database.md
  develop/dev-guide-create-secondary-indexes.md
  develop/dev-guide-create-table.md
  develop/dev-guide-delete-data.md
  develop/dev-guide-gui-mysql-workbench.md
  develop/dev-guide-gui-navicat.md
  develop/dev-guide-insert-data.md
  develop/dev-guide-proxysql-integration.md
  develop/dev-guide-sample-application-aws-lambda.md
  develop/dev-guide-sample-application-golang-gorm.md
  develop/dev-guide-sample-application-golang-sql-driver.md
  develop/dev-guide-sample-application-java-hibernate.md
  develop/dev-guide-sample-application-java-jdbc.md
  develop/dev-guide-sample-application-java-mybatis.md
  develop/dev-guide-sample-application-java-spring-boot.md
  develop/dev-guide-sample-application-nextjs.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-sequelize.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-python-django.md
  develop/dev-guide-sample-application-python-mysql-connector.md
  develop/dev-guide-sample-application-python-mysqlclient.md
  develop/dev-guide-sample-application-python-peewee.md
  develop/dev-guide-sample-application-python-pymysql.md
  develop/dev-guide-sample-application-python-sqlalchemy.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  develop/dev-guide-tidb-crud-sql.md
  develop/dev-guide-update-data.md
  quick-start-with-tidb.md
  releases/release-7.0.0.md
  tidb-resource-control-ru-groups.md
  vector-search/vector-search-get-started-using-python.md
  vector-search/vector-search-get-started-using-sql.md
  vector-search/vector-search-integrate-with-django-orm.md
  vector-search/vector-search-integrate-with-jinaai-embedding.md
  vector-search/vector-search-integrate-with-langchain.md
  vector-search/vector-search-integrate-with-llamaindex.md
  vector-search/vector-search-integrate-with-peewee.md
  vector-search/vector-search-integrate-with-sqlalchemy.md
Labels: translation/no-need, size/XL, area/develop, approved, needs-1-more-lgtm, lgtm, area/tidb-cloud, rename-serverless

#20642 pd-ctl: add notice for `member delete`
  pd-control.md
Labels: type/enhancement, translation/done, size/XS, ONCALL, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20644 chore: remove v8.3 and v8.4 from PR template
  .github/pull_request_template.md
  README.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#20647 tidb-lightning: add checking PITR and active changefeed task
  tidb-lightning/tidb-lightning-prechecks.md
Labels: contribution, translation/done, size/XS, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20653 hardware-and-software-requirements: Add note about supported filesystems
  .lycheeignore
  hardware-and-software-requirements.md
Labels: type/enhancement, translation/from-docs, size/XS, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20663 release-8.5: bump version for v8.5.2 and update variables.json
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-prisma.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  dm/quick-start-with-dm.md
  functions-and-operators/tidb-functions.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-microservices-using-tiup.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-tidb-using-tiup.md
  variables.json
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#20645 toc: move up and reorganize best practices
  TOC.md
  best-practices/uuid.md
  glossary.md
Labels: type/enhancement, translation/from-docs, size/M, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20671 v6.1-br: add tip linking to v7.5 BR doc
  br/backup-storage-S3.md
Labels: type/enhancement, translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#20665 release-7.5: replace TiDB version hardcoding `v7.5.6` with variable `{{{ .tidb-version }}}`
  br/backup-and-restore-use-cases.md
  develop/dev-guide-sample-application-nodejs-mysql2.md
  develop/dev-guide-sample-application-nodejs-mysqljs.md
  develop/dev-guide-sample-application-nodejs-typeorm.md
  develop/dev-guide-sample-application-ruby-mysql2.md
  develop/dev-guide-sample-application-ruby-rails.md
  dm/maintain-dm-using-tiup.md
  dm/quick-start-create-task.md
  external-storage-uri.md
  information-schema/information-schema-tidb-servers-info.md
  pd-control.md
  post-installation-check.md
  production-deployment-using-tiup.md
  quick-start-with-tidb.md
  scale-tidb-using-tiup.md
  system-variables.md
  ticdc/deploy-ticdc.md
  ticdc/ticdc-changefeed-config.md
  ticdc/ticdc-changefeed-overview.md
  ticdc/ticdc-manage-changefeed.md
  ticdc/ticdc-open-api-v2.md
  ticdc/ticdc-sink-to-cloud-storage.md
  ticdc/ticdc-sink-to-pulsar.md
  tidb-binlog/get-started-with-tidb-binlog.md
  tidb-monitoring-api.md
  tiflash/create-tiflash-replicas.md
  tiup/tiup-cluster.md
  tiup/tiup-component-cluster-deploy.md
  tiup/tiup-component-cluster-patch.md
  tiup/tiup-component-cluster-upgrade.md
  tiup/tiup-component-dm-upgrade.md
  tiup/tiup-component-management.md
  tiup/tiup-mirror.md
  tiup/tiup-playground.md
  upgrade-monitoring-services.md
  upgrade-tidb-using-tiup.md
  variables.json
Labels: translation/done, size/L, area/develop, approved, needs-1-more-lgtm, lgtm

#20674 Revert "v6.5 br: add an v6.1 alias to br use cases"
  br/backup-and-restore-use-cases.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm

#20689 overload-threshold: update the description of its effective scope
  tidb-configuration-file.md
Labels: size/XS, area/engine, ONCALL, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20690 Move tiflow/issues/9855 from v7.1.6 release notes to v7.1.2 release notes
  releases/release-7.1.2.md
  releases/release-7.1.6.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5
