Repository pingcap/docs-cn, pull requests merged in 2025-06, with the labels that each got.

#20423 dm-best-practices: update the example for the auto random column
  dm/dm-best-practices.md
Labels: translation/done, size/XS, ONCALL, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20449 dev doc: update the example of paginate results
  develop/dev-guide-paginate-results.md
Labels: translation/done, size/S, ONCALL, area/develop, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20251 Add TiDB 8.5.2 Release Notes
  TOC.md
  releases/release-8.5.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#20453 Add avg_tidb_cpu_time avg_tikv_cpu_time for statements summary doc
  statement-summary-tables.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20458 delete description about special non-reserved keywords that might still require special treatment
  keywords.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20335 Add VictoriaMetrics switch guide for TiUP cluster
  maintain-tidb-using-tiup.md
Labels: translation/done, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#20474 tiflash: correct the default value of `task_scheduler_active_set_soft_limit`
  releases/release-7.4.0.md
  tiflash/tiflash-configuration.md
Labels: translation/done, requires-version-specific-changes, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20479 Fix a typo about data source
  maintain-tidb-using-tiup.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20476 Update doc_review.yml
  .github/workflows/doc_review.yml
Labels: translation/no-need, size/S, approved, lgtm

#20475 cdc: fix kafka version table
  ticdc/ticdc-sink-to-kafka.md
Labels: translation/done, type/bugfix, size/XS, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20498 Revert "Revert "Add TiDB 8.5.2 Release Notes" (#20464)"
  TOC.md
  releases/release-8.5.2.md
  releases/release-notes.md
  releases/release-timeline.md
Labels: contribution, translation/from-docs, needs-cherry-pick-master, size/L, approved, needs-1-more-lgtm, lgtm

#20502 pd: change the default lease
  pd-configuration-file.md
  releases/release-8.5.2.md
Labels: translation/done, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20522 remove loong64 arch in release notes v8.5.2
  releases/release-8.5.2.md
Labels: translation/done, size/XS, approved, lgtm, needs-cherry-pick-release-8.5

#20524 tiproxy: update vip description about CIDR
  tiproxy/tiproxy-configuration.md
Labels: translation/done, size/XS, for-release, approved, lgtm, v9.0-beta.1

#20530 tiproxy: fix image link in tiproxy-load-balance.md
  tiproxy/tiproxy-load-balance.md
Labels: translation/done, size/XS, approved, lgtm

#20532 Revert "tiproxy: fix image link in tiproxy-load-balance.md"
  tiproxy/tiproxy-load-balance.md
Labels: contribution, missing-translation-status, size/XS, approved, needs-1-more-lgtm, lgtm

#20533 tiproxy: update architecture diagram
  media/tiproxy/tiproxy-balance-label-v2.png
  media/tiproxy/tiproxy-balance-label.png
  tiproxy/tiproxy-load-balance.md
Labels: translation/done, size/XS, approved, lgtm

#20526 titan-configuration: remove the unrecommended steps of updating TiKV configuration
  storage-engine/titan-configuration.md
  tikv-configuration-file.md
Labels: translation/doing, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#20546 feat: jdbc set query timeout
  develop/dev-guide-timeouts-in-tidb.md
Labels: translation/from-docs, size/XS, area/develop, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#20568 add notice about upgrading tiproxy
  tiproxy/tiproxy-overview.md
Labels: translation/doing, size/XS, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-8.5

#20525 tiproxy: update the recommended graceful-wait-before-shutdown
  tiproxy/tiproxy-deployment-topology.md
  tiproxy/tiproxy-load-balance.md
  tiproxy/tiproxy-overview.md
Labels: translation/done, size/S, approved, lgtm, needs-cherry-pick-release-8.5

#20534 Fix wording to reflect poor performance of initial query before optimization
  explain-walkthrough.md
Labels: translation/from-docs, size/XS, approved, lgtm, ok-to-test, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#20577 br: `{checkpoint_ts}-{uuid}.meta` should be `{resolved_ts}-{uuid}.meta`
  br/br-log-architecture.md
Labels: translation/done, size/XS, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, needs-1-more-lgtm, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5
